Fix #968 : Reenable all landscape tests in app module
oppia/oppia-android pull request #1016
Opened 2020-04-24 09:41 UTC by SayantanBanerjee16

## Explanation

Fixes #968 :

There are four files where Landscape tests are still ignored:- 
```
- AudioFragmentTest
- StateFragmentTest
- InputInteractionViewTestActivityTest
- ConceptCardFragmentTest
```

The first 3 still don't have any landscape mode so far and so I had kept them un-affected. The last one landscape mode enabled and tests passed.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-04-24 10:08 UTC, rt4914 requested changes
LGTM, one nit suggested.

2020-04-24 10:08 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/topic/conceptcard/ConceptCardFragmentTest.kt
> -  @Ignore("Landscape not properly supported") // TODO(#56): Reenable once landscape is supported.
There are some unused imports. Please remove them

2020-04-24 12:00 UTC, SayantanBanerjee16 commented on app/src/sharedTest/java/org/oppia/app/topic/conceptcard/ConceptCardFragmentTest.kt
> -  @Ignore("Landscape not properly supported") // TODO(#56): Reenable once landscape is supported.
Done.

2020-04-24 12:01 UTC, SayantanBanerjee16 commented
@rt4914 Done with the nit update. Do merge. Thanks :)

2020-04-27 06:16 UTC, rt4914 approved these changes
LGTM

2020-04-27 06:16 UTC, merged