Fix 1031: Onboarding Flow landscape
oppia/oppia-android pull request #1032
Opened 2020-04-29 09:41 UTC by nikitamarysolomanpvt

## Explanation
Onboarding Flow landscape
## Mocks
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/1f86ca4e-795e-4a75-8784-fea53864b94b/RG-OB-Onboarding-1-
The following is a list of opportunities to improve the accessibility of Oppia. Each item corresponds to an outlined area on the attached screenshot.

##GIF 
![mobizen_20200429_150210 (1)](https://user-images.githubusercontent.com/54615666/80582005-a2561a00-8a2b-11ea-830e-fee8fa580cdc.gif)

## Accessibility Scanner Results:
Item label
org.oppia.app:id/onboarding_fragment_next_image_view
This item may not have a label readable by screen readers.

Item descriptions
org.oppia.app:id/slide_image_view
This non-clickable item's speakable text: "Welcome to Oppia!" is identical to that of 1 other item(s).
![screenshot_Oppia_2020-04-29-15_08_10](https://user-images.githubusercontent.com/54615666/80581857-733fa880-8a2b-11ea-9e3c-e00b0b524721.png)

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-04-29 10:20 UTC, rt4914 requested changes
Suggested changes. PTAL

2020-04-29 10:20 UTC, rt4914 commented on app/src/main/res/layout-land/onboarding_fragment.xml
> +      android:layout_marginBottom="4dp"
This is `0dp` in mocks.

2020-04-29 10:20 UTC, rt4914 commented on app/src/main/res/layout-land/onboarding_slide.xml
> +      app:layout_constraintDimensionRatio="4:4"
The ratio for the image is 10:9
`app:layout_constraintDimensionRatio="H, 10:9"` once this change is done, checkout the circle of smiley face, they look more rounded and works well with mocks.

2020-04-29 10:20 UTC, rt4914 commented on app/src/main/res/layout-land/onboarding_slide.xml
> +      android:layout_marginTop="80dp"
Add marginStart as `8dp`

2020-04-29 10:20 UTC, rt4914 commented on app/src/main/res/layout-land/onboarding_slide.xml
>        android:layout_marginStart="10dp"
This is mentioned as `18dp` in mocks and the end margin is `38dp` so I guess as you have made `38dp` to `40dp`,  18dp can be made as `20dp`

2020-04-29 10:20 UTC, rt4914 commented on app/src/main/res/layout-land/onboarding_slide_final.xml
> +  <androidx.constraintlayout.widget.ConstraintLayout
All the changes from `onboarding_slide` should be done in this too.

2020-04-29 10:20 UTC, rt4914 commented on app/src/main/res/layout-land/onboarding_slide_final.xml
> +      android:layout_width="240dp"
This should be `match_parent` as you already have margin to take of all the things.

2020-04-29 10:20 UTC, rt4914 commented on app/src/main/res/layout-land/onboarding_slide_final.xml
> +      android:layout_marginTop="24dp"
This is `28dp` in mocks.

2020-04-29 10:22 UTC, rt4914 commented
@nikitamarysolomanpvt PTAL non_flaky_tests I think merge with latest develop will fix this.

Also, naming convention for branches does not use `_`, instead it uses `-`, like `onboarding-flow-landscape`. Follow this convention in your other branches. 

Reference: https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change

2020-04-29 10:55 UTC, veena14cs commented
> @nikitamarysolomanpvt PTAL non_flaky_tests I think merge with latest develop will fix this.
> 
> Also, naming convention for branches does not use `_`, instead it uses `-`, like `onboarding-flow-landscape`. Follow this convention in your other branches.
> 
> Reference: https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change

+1

2020-04-29 11:01 UTC, veena14cs commented on app/src/main/res/layout-land/onboarding_fragment.xml
> +      android:layout_marginEnd="20dp"
marginEnd is 28dp in the mock and top margin is 24dp.

2020-04-29 11:04 UTC, veena14cs commented on app/src/main/res/layout-land/onboarding_fragment.xml
> +      android:layout_marginBottom="4dp"
+1

2020-04-29 11:09 UTC, veena14cs requested changes
Please address the changes.

2020-04-29 12:02 UTC, nikitamarysolomanpvt reviewed
> @nikitamarysolomanpvt PTAL non_flaky_tests I think merge with latest develop will fix this.
> 
> Also, naming convention for branches does not use _, instead it uses -, like onboarding-flow-
>landscape. Follow this convention in your other branches.

In https://github.com/oppia/oppia-android/pull/1033 renamed branch to onboarding-flow-landscape

2020-04-29 12:02 UTC, nikitamarysolomanpvt commented on app/src/main/res/layout-land/onboarding_fragment.xml
> +      android:layout_marginBottom="4dp"
Done.

2020-04-29 12:02 UTC, nikitamarysolomanpvt commented on app/src/main/res/layout-land/onboarding_slide.xml
> +      app:layout_constraintDimensionRatio="4:4"
updated to app:layout_constraintDimensionRatio="H, 10:9"

2020-04-29 12:02 UTC, nikitamarysolomanpvt commented on app/src/main/res/layout-land/onboarding_slide.xml
> +      android:layout_marginTop="80dp"
Done

2020-04-29 12:02 UTC, nikitamarysolomanpvt commented on app/src/main/res/layout-land/onboarding_slide.xml
>        android:layout_marginStart="10dp"
Added margin start 18dp.

2020-04-29 12:02 UTC, nikitamarysolomanpvt commented on app/src/main/res/layout-land/onboarding_slide_final.xml
> +      android:layout_marginTop="24dp"
I found them as 24 dp in mock.

2020-04-29 12:02 UTC, nikitamarysolomanpvt commented on app/src/main/res/layout-land/onboarding_slide_final.xml
> +      android:layout_width="240dp"
Done

2020-04-29 12:02 UTC, nikitamarysolomanpvt commented on app/src/main/res/layout-land/onboarding_slide_final.xml
> +  <androidx.constraintlayout.widget.ConstraintLayout
Done

2020-04-29 12:02 UTC, nikitamarysolomanpvt commented on app/src/main/res/layout-land/onboarding_fragment.xml
> +      android:layout_marginEnd="20dp"
It adjusted as per padding.

2020-04-30 04:53 UTC, nikitamarysolomanpvt commented
duplicate of #1033

2020-04-30 04:53 UTC, closed without merging