Fixes #1079 : GSoC Support Tablet: Lowfi Onboarding Flow
oppia/oppia-android pull request #1080
Opened 2020-05-16 21:18 UTC by MohamedMedhat1998

## Explanation
Fixes #1079  
Created landscape-tablet layouts for onboarding flow (low-fi). These layouts have the qualifier "sw600dp" for tablets, combined with the qualifier "land" for landscape mode

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-05-17 17:04 UTC, rt4914 requested changes
In low-fi always check the test cases. `testOnboardingFragment_checkSlide3Image_isCorrect` test case is failing because some of the xml files does not have a content description.

If you are aware of this test failure, in such cases please make sure that you mention this in description of PR so that the reviewer knows it.

2020-05-17 17:04 UTC, rt4914 commented on app/src/main/res/layout-sw600dp-land/onboarding_slide_final.xml
> +</layout>
EOF is missing, add one blank line at the end.

2020-05-17 17:04 UTC, rt4914 commented on app/src/main/res/layout-sw600dp-land/onboarding_slide.xml
> +</layout>
EOF is missing, add one blank line at the end.

2020-05-17 17:04 UTC, rt4914 commented on app/src/main/res/layout-sw600dp-land/onboarding_fragment.xml
> +</layout>
EOF is missing, add one blank line at the end.

2020-05-18 09:33 UTC, rt4914 commented
@MohamedMedhat1998 Please fix the test case issue and also, reply to all conversations.

2020-05-18 09:57 UTC, MohamedMedhat1998 commented on app/src/main/res/layout-sw600dp-land/onboarding_slide_final.xml
> +</layout>
Done

2020-05-18 09:57 UTC, MohamedMedhat1998 commented on app/src/main/res/layout-sw600dp-land/onboarding_slide.xml
> +</layout>
Updated

2020-05-18 09:57 UTC, MohamedMedhat1998 commented on app/src/main/res/layout-sw600dp-land/onboarding_fragment.xml
> +</layout>
Done

2020-05-18 09:59 UTC, MohamedMedhat1998 commented
> 
> 
> In low-fi always check the test cases. `testOnboardingFragment_checkSlide3Image_isCorrect` test case is failing because some of the xml files does not have a content description.
> 
> If you are aware of this test failure, in such cases please make sure that you mention this in description of PR so that the reviewer knows it.

Done

2020-05-18 09:59 UTC, MohamedMedhat1998 commented
> 
> 
> @MohamedMedhat1998 Please fix the test case issue and also, reply to all conversations.

Completed!  
Can you review it again please?

2020-05-18 10:48 UTC, rt4914 commented
> > @MohamedMedhat1998 Please fix the test case issue and also, reply to all conversations.
> 
> Completed!
> Can you review it again please?

@MohamedMedhat1998 Just add `android:contentDescription="@string/onboarding_slide_3_title"` to `layout_land/onboarding_slide_final.xml` `ImageView`. 
Checkout its portrait mode code fort comparision.

2020-05-18 11:20 UTC, MohamedMedhat1998 commented
> 
> 
> > > @MohamedMedhat1998 Please fix the test case issue and also, reply to all conversations.
> > 
> > 
> > Completed!
> > Can you review it again please?
> 
> @MohamedMedhat1998 Just add `android:contentDescription="@string/onboarding_slide_3_title"` to `layout_land/onboarding_slide_final.xml` `ImageView`.
> Checkout its portrait mode code fort comparision.

Done!  
Added `contentDescription` in normal devices and in tablet devices

2020-05-18 11:26 UTC, rt4914 approved these changes
LGTM. Thanks.

2020-05-18 12:04 UTC, rt4914 commented
@vinitamurthi @veena14cs Can you have a look at this. The test cases are failing for `SplashActivityTest` (non_flaky_tests).
When I run this file on espresso, I am getting this error:
`java.lang.RuntimeException: Delegate runner 'org.robolectric.RobolectricTestRunner' for AndroidJUnit4 could not be loaded.`

I tried to solve this error using [this link](https://stackoverflow.com/questions/53619024/attempted-to-use-androidjunit4-with-standard-junit-runner-and-delegate-runner-o), but everything is correct as per the link.

2020-05-19 08:25 UTC, vinitamurthi commented
As veena mentioned in the chat, it looks like it is working on develop. Does this PR affect the splash activity in any way?

2020-05-19 08:42 UTC, rt4914 commented
> As veena mentioned in the chat, it looks like it is working on develop. Does this PR affect the splash activity in any way?

@veena14cs @vinitamurthi 
Solved the issue. Actually it was quite weird issue. On develop they were passing but on this PR branch they were failing. Actually on PR branch I tried running other test cases also on espresso and all test cases were failing. So I did gradle sync again and it worked. Somehow the library was working for develop but not for this branch.

After gradle sync everything worked.

There is still on issue, why does is fail on CircleCI? So for that I have restarted the CircleCI job now and lets see what the result is.

2020-05-19 11:44 UTC, MohamedMedhat1998 commented
Can I merge now?

2020-05-19 13:39 UTC, rt4914 commented
> > As veena mentioned in the chat, it looks like it is working on develop. Does this PR affect the splash activity in any way?
> 
> @veena14cs @vinitamurthi
> Solved the issue. Actually it was quite weird issue. On develop they were passing but on this PR branch they were failing. Actually on PR branch I tried running other test cases also on espresso and all test cases were failing. So I did gradle sync again and it worked. Somehow the library was working for develop but not for this branch.
> 
> After gradle sync everything worked.
> 
> There is still on issue, why does is fail on CircleCI? So for that I have restarted the CircleCI job now and lets see what the result is.

@veena14cs @vinitamurthi The test cases are passing now.

2020-05-19 13:39 UTC, merged