Fix #1129: Backflow code optimised
oppia/oppia-android pull request #1130
Opened 2020-05-27 07:28 UTC by rt4914

## Explanation

Fixes #1129

This PR optimises the code written in #1036.

The main points of optimisations:
1. Pass enum values instead of numbers from parent activities when opening the exploration.
2. Remove null support from `backflowScreen` variable.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-05-27 11:43 UTC, Sarthak2601 requested changes
Nice implementation. Just a few things here.
Also, when I ran the tests on my system it showed `no tests were found`. It can be a device error as well. Are they passing in yours ? 
Please also take care of the `non-flaky tests`

2020-05-27 11:43 UTC, Sarthak2601 commented on app/src/main/java/org/oppia/app/player/exploration/BackflowScreenEnum.kt
> +  BACKFLOW_SCREEN_DEFAULT(2);
I think default should have 0 value here.

2020-05-27 11:43 UTC, Sarthak2601 commented on app/src/main/java/org/oppia/app/player/exploration/ExplorationActivityPresenter.kt
> +      else -> activity.startActivity(
Is there a need to have an else statement here when we are already handling everything through the default value ?

2020-07-09 21:44 UTC, rt4914 commented
Earlier this PR was blocked because of test cases issue. Now as this PR needs a lot of changes including suggestions and new changes in current develop, I am closing this PR and this will be created correctly in future.

2020-07-09 21:44 UTC, closed without merging