Fix part of #1287: Fix lint issues in app module in the kotlin files (conceptcard, info, questionplayer)
oppia/oppia-android pull request #1312
Opened 2020-06-11 11:21 UTC by anandwana001

## Explanation

Fixes part of #1287
`conceptcard, info, questionplayer` folder `ktlint` check

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-06-11 13:19 UTC, vinitamurthi approved these changes

2020-06-12 07:16 UTC, nikitamarysolomanpvt requested changes
PTAL on the nit changes

2020-06-12 07:16 UTC, nikitamarysolomanpvt commented on app/src/main/java/org/oppia/app/topic/conceptcard/ConceptCardFragment.kt
> +  @Inject
Please revert this change to
 `@Inject lateinit var conceptCardFragmentPresenter: ConceptCardFragmentPresenter`

2020-06-12 07:16 UTC, nikitamarysolomanpvt commented on app/src/main/java/org/oppia/app/topic/info/TopicInfoFragment.kt
> +  @Inject
ditto.

2020-06-12 07:16 UTC, nikitamarysolomanpvt commented on app/src/main/java/org/oppia/app/topic/questionplayer/QuestionPlayerActivity.kt
> +  @Inject
ditto.

2020-06-12 07:16 UTC, nikitamarysolomanpvt commented on app/src/main/java/org/oppia/app/topic/questionplayer/QuestionPlayerFragment.kt
> +  @Inject
ditto.

2020-06-12 07:36 UTC, nikitamarysolomanpvt approved these changes
LGTM. I resolved all `@Inject` alignment related comments as it is advised to do so.

2020-06-12 07:39 UTC, anandwana001 commented
> LGTM. I resolved all `@Inject` alignment related comments as it is advised to do so.

Thank You :)

2020-06-12 09:52 UTC, merged