Fix #1629 : replace story_text_size to reading_text_size
oppia/oppia-android pull request #1691
Opened 2020-08-21 22:31 UTC by prayutsu

## Explanation

Fixes #1629 : Replace all the occurrences of storyTextSize with readingTextSize

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

Reviewers - @anandwana001 @rt4914

2020-08-21 23:29 UTC, prayutsu commented
@rt4914 Replaced all the occurrences of 'StoryTextSIze' with 'ReadingTextSize'

2020-08-22 13:12 UTC, prayutsu commented
@rt4914 PTAL

2020-08-24 04:06 UTC, rt4914 requested changes
Just few changes. Thanks.

There is one issue with branch name, the branch name should have all `small characters` separated by `underscore`. Refernece: https://github.com/oppia/oppia-android/pull/1685#pullrequestreview-472435495

2020-08-24 04:06 UTC, rt4914 commented on app/src/main/java/org/oppia/app/options/OptionsReadingTextSizeViewModel.kt
> +/** StoryText size settings view model for the recycler view in [OptionsFragment]. */
Update this comment too.

2020-08-24 04:06 UTC, rt4914 commented on app/src/main/java/org/oppia/app/options/ReadingTextSizeActivity.kt
> +/** The activity to change the Text size of the Story content in the app. */
Update to `/** The activity to change the text size of the reading content in the app. */`

2020-08-24 04:06 UTC, rt4914 commented on app/src/main/java/org/oppia/app/options/ReadingTextSizeFragment.kt
>  /** The fragment to change the text size of the story content in the app. */
Update this comment too.

2020-08-24 04:06 UTC, rt4914 commented on app/src/main/java/org/oppia/app/player/exploration/ExplorationFragment.kt
> +    checkNotNull(readingTextSize) { "ExplorationFragment must be created with a story text size" }
Update the message:

`ExplorationFragment must be created with a reading text size`

2020-08-24 04:06 UTC, rt4914 commented on model/src/main/proto/profile.proto
>  // Supported Story text sizes for user preference.
Update this to:
`// Supported reading text sizes for user preference.`

2020-08-24 04:06 UTC, rt4914 commented on model/src/main/proto/profile.proto
>    // Represents user selected story-text-size.
Update this to:
`Represents user selected reading-text-size.`

2020-08-24 04:38 UTC, prayutsu commented
> Just few changes. Thanks.
> 
> There is one issue with branch name, the branch name should have all `small characters` separated by `underscore`. Refernece: [#1685 (review)](https://github.com/oppia/oppia-android/pull/1685#pullrequestreview-472435495)

Sure I will fix those up. Thanks @rt4914

2020-08-24 05:22 UTC, prayutsu commented
@rt4914 Do I need to change my branch name? Actually I changed it locally but it didn't change on my fork.

2020-08-24 05:34 UTC, aggarwalpulkit596 commented
You will most likely have to create another PR for that once you change your branch name it won't be reflected to this branch/PR

2020-08-24 05:35 UTC, prayutsu commented
hey @rt4914, I just changed the branch name, actually, a new branch has been created. So, do I need to create another PR?

2020-08-24 05:35 UTC, prayutsu commented
> You will most likely have to create another PR for that once you change your branch name it won't be reflected to this branch/PR

Oh, I already got the answer. Thanks to @aggarwalpulkit596

2020-08-24 05:53 UTC, rt4914 commented
> hey @rt4914, I just changed the branch name, actually, a new branch has been created. So, do I need to create another PR?

Yes, please create a PR. Once new PR is created, close this PR with appropriate message.

2020-08-24 06:52 UTC, prayutsu commented
Created New PR https://github.com/oppia/oppia-android/pull/1696

2020-08-24 06:52 UTC, closed without merging

2020-08-24 07:11 UTC, rt4914 commented
> Created New PR #1696

Thanks for mentioning this comment.