fixes #1589 : Naming consistency for DataProviderIds in doma…
oppia/oppia-android pull request #1716
Opened 2020-08-26 14:49 UTC by The-Fuse

…in layer

## Explanation

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-08-27 02:43 UTC, The-Fuse commented
@rt4914  Please review this.

2020-08-27 14:13 UTC, rt4914 requested changes
Thanks for submitting PR.
The convention for the renaming is `<function_name>_<optional_context>_PROVIDER_ID` which means the id should start with a function name where it is getting used.

Also, you have missed some files like `StoryProgressController`, so make sure you check the entire domain module.

2020-08-27 14:13 UTC, rt4914 commented on domain/src/main/java/org/oppia/domain/exploration/ExplorationDataController.kt
> +private const val EXPLORATION_DATA_PROVIDER_ID = "exploration_data_provider_id"
This does not following the convention mentioned in the issue.
`<function_name>_<optional_context>_PROVIDER_ID`
means that the rename should be 
`GET_EXPLORATION_BY_ID_PROVIDER_ID ="get_exploration_by_id_provider_id"`

2020-09-04 10:13 UTC, anandwana001 commented
@The-Fuse any update on this?

2020-09-05 04:51 UTC, The-Fuse commented
Yes , working on it .

2020-09-14 07:06 UTC, anandwana001 commented
@The-Fuse Let me know if you need any assistance on this or if you are finding any difficulty in the codebase.

2020-09-16 04:21 UTC, closed without merging