Fix #1802 : Reading text size not scrollable or flexible
oppia/oppia-android pull request #1819
Opened 2020-09-07 19:02 UTC by prayutsu

## Explanation

Fixes #1802 
Preview Text now displays the correct and real size of the text in stories.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

Screenshots for the same - 

<img src="https://user-images.githubusercontent.com/54636525/92412313-19818480-f169-11ea-9b03-14dcd19fc261.jpg" width="280">    <img src="https://user-images.githubusercontent.com/54636525/92412315-1a1a1b00-f169-11ea-8431-0aee1907ce4e.jpg" width="280">
<img src="https://user-images.githubusercontent.com/54636525/92412316-1b4b4800-f169-11ea-9328-8aab64d00db0.jpg" width="280">    <img src="https://user-images.githubusercontent.com/54636525/92412318-1be3de80-f169-11ea-8bfe-fb7e20cd3a91.jpg" width="280">

2020-09-07 19:02 UTC, prayutsu commented
@anandwana001 PTAL

2020-09-07 22:01 UTC, anandwana001 requested changes
Check few comments @prayutsu 

At the very first time when you open the reading text size screen and you change from medium to small the text size doesn't change. Also, isn't this the text size looking too small?

2020-09-07 22:01 UTC, anandwana001 commented on app/src/main/java/org/oppia/app/options/ReadingTextSizeFragmentPresenter.kt
> +      getReadingTextSize(ReadingTextSize.MEDIUM_TEXT_SIZE) -> {
this is mistaken here, I guess. It should not be changed

2020-09-07 22:01 UTC, anandwana001 commented on app/src/main/java/org/oppia/app/options/ReadingTextSizeFragmentPresenter.kt
> +          TypedValue.COMPLEX_UNIT_PX,
we are using the normal sp values than why we need to mention pixel value here?
Could you explain this and also add why we can't fix this from UI side?

2020-09-08 05:01 UTC, prayutsu commented on app/src/main/java/org/oppia/app/options/ReadingTextSizeFragmentPresenter.kt
> +          TypedValue.COMPLEX_UNIT_PX,
Please have a look [here](https://stackoverflow.com/questions/20364993/setting-textsize-programmatically/20365110).

2020-09-08 05:03 UTC, prayutsu commented on app/src/main/java/org/oppia/app/options/ReadingTextSizeFragmentPresenter.kt
> +      getReadingTextSize(ReadingTextSize.MEDIUM_TEXT_SIZE) -> {
yes, this is mistaken, I'll correct it.

2020-09-08 05:15 UTC, rt4914 commented on app/src/main/java/org/oppia/app/options/ReadingTextSizeFragmentPresenter.kt
> +          TypedValue.COMPLEX_UNIT_PX,
<img width="684" alt="Screenshot 2020-09-08 at 10 44 37 AM" src="https://user-images.githubusercontent.com/9396084/92435572-5167e680-f1c0-11ea-9b36-72f13d3b99ee.png">

Based on the documentation of this function, it does make sense.

2020-09-08 05:17 UTC, prayutsu commented on app/src/main/java/org/oppia/app/options/ReadingTextSizeFragmentPresenter.kt
> +          TypedValue.COMPLEX_UNIT_PX,
Actually, I logged out the value of defaultReadingTextSizeInFloat (in getReadingTextSIzeInFloat function), it is set to 18sp in dimens.xml but when I logged its value, it was showing 51.875, so, it was inferred in pixels, so when I am setting textSize, I am actually explicitly mentioning that the textSize passed as the parameter is actually in pixels.

2020-09-08 05:18 UTC, prayutsu commented
> Check few comments @prayutsu
> 
> At the very first time when you open the reading text size screen and you change from medium to small the text size doesn't change. Also, isn't this the text size looking too small?

I think this will get fixed when I correct that mistaken "MEDIUM_TEXT_SIZE" mentioned by you.

2020-09-08 05:20 UTC, anandwana001 commented on app/src/main/java/org/oppia/app/options/ReadingTextSizeFragmentPresenter.kt
> +          TypedValue.COMPLEX_UNIT_PX,
Thanks for looking into deep. This is good to go now.

2020-09-10 07:22 UTC, anandwana001 commented on app/src/main/java/org/oppia/app/options/ReadingTextSizeFragmentPresenter.kt
> +      getReadingTextSize(ReadingTextSize.MEDIUM_TEXT_SIZE) -> {
we are good to merge after this update

2020-09-10 07:35 UTC, anandwana001 approved these changes
LGTM, Thanks @prayutsu

2020-09-10 14:25 UTC, merged