Introduce data provider extension functions
oppia/oppia-android pull request #1836
Opened 2020-09-11 09:40 UTC by BenHenning

This PR is a proof-of-concept I thought of earlier today: it replaces most DataProviders methods with DataProvider extension functions to improve readability. In general, the readability aspects of this change seem nice, but it comes with a few costs:
- The extension functions don't have access to the Dagger graph, so an application component injector needed to be added to retrieve access to application dependencies
- Accessing the injector required making DataProvider an abstract class and passing around a context object (which is a bit gross)
- The new injector needs to be a separate interface from the existing application injector since it's defined in a different module
- Introducing new injectors requires many tests to be updated to properly support injector overriding
- Subsequently, many non-app module tests needed to be updated to use a test application (which is probably preferred, anyway, since it's more correct)

Note that I also fixed a bunch of cases when comments or KDocs were exceeding 100 characters.

Note also that some tests are initially failing for reasons I'm not sure of--more investigation is needed.

Please let me know what your initial thoughts are on the approach given the caveats mentioned above.

2020-09-15 08:31 UTC, rt4914 requested changes
Two points:
1. I personally like this change to converting the `DataProvider` in app layer because I think it looks much cleaner now.

2. For reviewers: This PR might look big but actually its not, these are just small changes.

Will wait for the CI fixes before approving.

Following domain test files are failing:
<img width="728" alt="Screenshot 2020-09-15 at 1 56 10 PM" src="https://user-images.githubusercontent.com/9396084/93186111-dec8af00-f75b-11ea-982e-68514c630835.png">

2020-09-22 04:01 UTC, BenHenning commented
Thanks @rt4914. All tests are fixed. PTAL (also for @aggarwalpulkit596 and @anandwana001).

@vinitamurthi I'm assuming you're not interested in reviewing this PR, so I'm removing you as a reviewer. Feel free to re-add yourself if you'd like to take a pass on it.

2020-09-22 04:23 UTC, vinitamurthi commented
Oh sorry about that, I had approved and then deassigned but it looks like my review didn't go

2020-09-22 04:25 UTC, anandwana001 approved these changes
This is amazing PR 
Thanks @BenHenning

2020-09-22 12:22 UTC, rt4914 approved these changes
LGTM, thanks.

2020-09-23 16:10 UTC, BenHenning commented
Thanks all. Going ahead and merging this since it's pretty large and will likely cause other large, in-flight PRs to have conflicts.

2020-09-23 16:10 UTC, merged