Fix #2080: Remove injected TestCoroutineDispatchers if not in use
oppia/oppia-android pull request #2083
Opened 2020-11-05 05:25 UTC by ShridharGoel

## Explanation
Fixes #2080 

Removed injected `TestCoroutineDispatchers` from the following test since it was not being used:
1. FAQListFragmentTest
2. FAQSingleActivityTest
3. HelpFragmentTest
4. HtmlParserTest
5. MyDownloadsFragmentTest

## Checklist
- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

Screenshots:

![FAQListFragmentTest](https://user-images.githubusercontent.com/35566748/98201041-db2ff800-1f54-11eb-8900-812a6bc15adc.png)
![FAQSingleActivityTest](https://user-images.githubusercontent.com/35566748/98201056-dff4ac00-1f54-11eb-9708-361503a1417a.png)
![HelpFragmentTest](https://user-images.githubusercontent.com/35566748/98201063-e1be6f80-1f54-11eb-8b3b-dced8f74d588.png)
![HtmlParserTest](https://user-images.githubusercontent.com/35566748/98201068-e3883300-1f54-11eb-9a8d-3990941b8002.png)
![MyDownloadsFragmentTest](https://user-images.githubusercontent.com/35566748/98201073-e551f680-1f54-11eb-94f1-d0402039aae1.png)

2020-11-05 05:28 UTC, anandwana001 commented
@ShridharGoel You had to complete the onboarding instructions first, else PR will be closed by bot.

2020-11-05 05:50 UTC, ShridharGoel commented
@anandwana001 I have done it now. Can you reopen the PR? I don't have the option to reopen it.

2020-11-05 06:04 UTC, anandwana001 commented
@ShridharGoel Please fix the ktlint failure. Check wiki guide here - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide

2020-11-05 06:15 UTC, ShridharGoel commented
@anandwana001 I have removed the unused imports. That has fixed it.

2020-11-05 06:17 UTC, anandwana001 commented
> @anandwana001 I have removed the unused imports. That has fixed it.

Could you also put Espresso tests result of these classes!!

2020-11-05 06:20 UTC, anandwana001 requested changes
Thanks @ShridharGoel 
nit changes suggested

2020-11-05 06:20 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsFragmentTest.kt
>    @Before
leave a line above.

2020-11-05 06:20 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsFragmentTest.kt
> +  fun tearDown() {}
no need for this function now.

2020-11-05 06:21 UTC, ShridharGoel commented on app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsFragmentTest.kt
>    @Before
Updated.

2020-11-05 06:22 UTC, ShridharGoel commented on app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsFragmentTest.kt
> +  fun tearDown() {}
Updated.

2020-11-05 06:26 UTC, anandwana001 commented
@ShridharGoel Suggestion for further contribution:
Always use the branch name more descriptive. Check our wiki guide here - https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change

2020-11-05 07:29 UTC, ShridharGoel commented
@anandwana001 Can you tell which other screenshots need to be added?

2020-11-05 07:56 UTC, anandwana001 commented
@ShridharGoel the current screenshots in the pr description are of robolectric, you need to add the same for Espresso as well. Need to check all tests are passing in espresso as well.

2020-11-05 14:41 UTC, ShridharGoel commented
@anandwana001 Can you tell how to run the tests separately for Espresso? Currently the tests run only for Roboelectric.

2020-11-05 17:14 UTC, ShridharGoel commented
@anandwana001 I keep getting this error on running the Espresso tests.

`Test running failed: Instrumentation run failed due to 'Process crashed.'`

2020-11-06 01:15 UTC, anandwana001 commented
@ShridharGoel 
1. Could you mention which device you are running tests on?
2. Are tests passing when not removing the `testCoroutineDispatchers`?

2020-11-06 01:17 UTC, ShridharGoel commented
@anandwana001 

1. I'm using Redmi Note 8.
2. Tests running is failing even in tests in which `testCoroutineDispatchers` hasn't been removed.

2020-11-06 01:18 UTC, ShridharGoel commented
Closed by mistake.

2020-11-06 01:20 UTC, anandwana001 commented
Did you try on an emulator?

2020-11-06 01:24 UTC, ShridharGoel commented
No, will try and update.

2020-11-06 02:31 UTC, ShridharGoel commented
@anandwana001 Worked fine using emulator. I have updated the screenshots to include screenshots of Espresso tests.

2020-11-06 02:43 UTC, anandwana001 approved these changes
LGTM, Thanks @ShridharGoel for your first PR at Oppia. 
deferring to @rt4914 for further merge.

2020-11-06 03:25 UTC, ShridharGoel commented
@anandwana001 Thank you.

2020-11-06 07:26 UTC, rt4914 approved these changes
LGTM, thanks.

2020-11-06 07:27 UTC, merged