Fix #2090 removed bang bang operator in NetworkInterceptor.kt and used let for instead
oppia/oppia-android pull request #2091
Opened 2020-11-06 03:23 UTC by prudhvir3ddy

## Explanation
removed bang bang operator which may null pointer exception though current code got null check but this is just a better way of coding and making use of kotlin higher order function . fixes #2090

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-11-06 03:49 UTC, anandwana001 commented
@prudhvir3ddy 
We recommend to follow few points:
1. PR title `Fix #bugnum: short description`
2. Branch naming, please check our wiki here - https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change
3. As per the last point in the above checklist, you can also mention me or @rt4914 for review in the PR description, until you get the Reviewer/Assignee section access.

2020-11-06 06:16 UTC, prudhvir3ddy commented
@anandwana001 anyhow my branch will be deleted after this merge right ?

2020-11-06 06:23 UTC, anandwana001 commented
@prudhvir3ddy The branch is from your fork, so it's up to you to delete or not. As per the naming, you can choose a descriptive naming with all small caps with `-` to separate, from your next PR's.

2020-11-06 06:28 UTC, aggarwalpulkit596 requested changes

2020-11-06 06:28 UTC, aggarwalpulkit596 commented on data/src/main/java/org/oppia/android/data/backends/gae/NetworkInterceptor.kt
> +        var rawJson = it.string()
Instead of using `it` could you something more descriptive maybe
`resBody` or simply  `body`

2020-11-06 07:51 UTC, aggarwalpulkit596 approved these changes

2020-11-06 07:51 UTC, aggarwalpulkit596 commented
LGTM @anandwana001 do you have anything else or should i go ahead and merge this one.

2020-11-06 16:47 UTC, anandwana001 commented
@rt4914 I will defer to Rajat. 
Also, checks are failing.

2020-11-08 07:25 UTC, rt4914 approved these changes
LGTM, thanks. @anandwana001 You can make a note of this as you are the onboarding mentor.

2020-11-08 07:25 UTC, merged

2020-11-08 07:26 UTC, anandwana001 commented
@rt4914  Thanks