Fix Part of #1968: Fixed 4 tests from NavigationDrawerTestActivityTest for roboelectric
oppia/oppia-android pull request #2122
Opened 2020-11-16 23:59 UTC by FareesHussain

## Explanation

Fix part of #1968 
Fixed 4 test cases
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.

 ### Before
![image](https://user-images.githubusercontent.com/54740946/99322345-bfeab400-2895-11eb-9544-42fe59d83583.png)
 ### After
![image](https://user-images.githubusercontent.com/54740946/99322379-d42eb100-2895-11eb-9e1e-75b992791ce3.png)

2020-11-17 04:56 UTC, FareesHussain commented
Currently, this pr fixes two tests 
robolectric dependencies need to be [upgraded](https://github.com/robolectric/robolectric/issues/5454) for the other 2 tests as they are associated with firebase
upgrading dependencies is causing CI check errors

2020-11-17 06:14 UTC, anandwana001 commented
> upgraded

@FareesHussain To upgrade the dependencies, you also need to upgrade the version at bazel files too. 
Please check files like `BUILD` and `WORKSPACE` and check if `robolectric` dependencies are mentioned there!!

2020-11-17 06:25 UTC, anandwana001 requested changes
Thanks @FareesHussain for your first successful pull request

No need of before screenshot, but it's good. Also, add a screenshot showing test are passing on espresso as well as on robolectric. So, it will be two screenshots, 1 will be for espresso and other is for robolectric. 

Update PR title accordingly.

2020-11-17 06:25 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt
>    // TODO(#973): Fix NavigationDrawerTestActivityTest
remove todo, as this test cases is passing

2020-11-17 06:25 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt
> +      onView(withId(R.id.home_activity_drawer_layout)).check(matches(isDisplayed()))
Both `isOpen` and `isDisplayed` are used for different purpose. 

**[`isOpen`](https://developer.android.com/reference/androidx/test/espresso/contrib/DrawerMatchers#isOpen())**
```
Returns a matcher that verifies that the drawer (with gravity START) is open.
``` 

**[`isDisplayed`](https://developer.android.com/reference/androidx/test/espresso/matcher/ViewMatchers#isdisplayed)**
```
Returns a matcher that matches Views that are currently displayed on the screen to the user.
```

2020-11-17 06:25 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt
>    // TODO(#973): Fix NavigationDrawerTestActivityTest
remove todo

2020-11-17 06:25 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt
> +    launch(NavigationDrawerTestActivity::class.java).use {
Could you describe a bit about this change here!!

as per the earlier test, we are launching `NavigationDrawerTestActivity` using `createNavigationDrawerActivityIntent` where we are passing `0` as to mention the Admin profile, but how this new change is different from the previous one?

2020-11-17 06:25 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt
> +          withText(R.string.administrator_controls)
Can we confirm here that if we launch the intent with the non-admin profile, this test must fail?

2020-11-17 06:38 UTC, FareesHussain commented
> @FareesHussain To upgrade the dependencies, you also need to upgrade the version at bazel files too.
> Please check files like `BUILD` and `WORKSPACE` and check if `robolectric` dependencies are mentioned there!!

so I'll have to change for all other source sets in build.gradle too right?

2020-11-17 06:43 UTC, anandwana001 commented
> > @FareesHussain To upgrade the dependencies, you also need to upgrade the version at bazel files too.
> > Please check files like `BUILD` and `WORKSPACE` and check if `robolectric` dependencies are mentioned there!!
> 
> so I'll have to change for all other source sets in build.gradle too right?

1. Anywhere we are mentioning the robolectric should need to update, as all the modules should have the same version of the library to run on. 
2. Before updating the version, I think it will be more helpful to provide a concrete reason and make sure nothing else will be breaking. As per you had mention regarding the firebase thing, we already had this firebase initialisation at multiple places and it's breaking for any other file, so is there anything different in this file which really needs a version update?

2020-11-17 06:55 UTC, FareesHussain commented
we need to update robolectric dependencies as it was mentioned [here](https://github.com/robolectric/robolectric/issues/5454) 
I'm not sure for other dependencies

2020-11-17 06:56 UTC, anandwana001 commented
> we need to update robolectric dependencies as it was mentioned [here](https://github.com/robolectric/robolectric/issues/5454)
> I'm not sure for other dependencies

If you see other test files, we do have Firebase initialization there but they are not failing. I will take look into it, and also check the changelog for this new version.

2020-11-17 07:18 UTC, anandwana001 commented
@FareesHussain I run the test cases with/without updating the version and didn't find any changes in the test cases result. Could you mention which tests result is changed after updating the version?

For `testNavigationDrawerTestActivity_withUserProfile_openNavigationDrawer_checkAdministratorControlsNotDisplayed`, it is passing already for robolectric, required no changes for this particular test case.

2020-11-17 07:55 UTC, FareesHussain commented
For `testNavigationDrawerTestActivity_clickNavigationDrawerHamburger_checkProfileProgress_displayProfileProgressSuccessfully`
the test passed after changing the version  

it failed without updating version here
![image](https://user-images.githubusercontent.com/54740946/99322345-bfeab400-2895-11eb-9544-42fe59d83583.png)

2020-11-17 07:59 UTC, anandwana001 commented
> For `testNavigationDrawerTestActivity_clickNavigationDrawerHamburger_checkProfileProgress_displayProfileProgressSuccessfully`
> the test passed after changing the version
> 
> it failed without updating version here
> ![image](https://user-images.githubusercontent.com/54740946/99322345-bfeab400-2895-11eb-9544-42fe59d83583.png)

Thanks for the update, I will check this.

2020-11-17 09:28 UTC, FareesHussain commented
> @FareesHussain To upgrade the dependencies, you also need to upgrade the version at bazel files too.
> Please check files like `BUILD` and `WORKSPACE` and check if `robolectric` dependencies are mentioned there!!

@anandwana001 I've updated in all file bazel and gradle but there's some error in CI check

2020-11-17 10:16 UTC, anandwana001 commented
> > @FareesHussain To upgrade the dependencies, you also need to upgrade the version at bazel files too.
> > Please check files like `BUILD` and `WORKSPACE` and check if `robolectric` dependencies are mentioned there!!
> 
> @anandwana001 I've updated in all file bazel and gradle but there's some error in CI check

@FareesHussain It looks like updating the version cause the failure for test cases of other files. 
Here, tests in `AudioFragmentTest` are failing because of updating the version. Please check on local by running these failed test cases. 
`testAudioFragment_openFragment_showsFragment`
`testAudioFragment_invokePrepared_changeDifferentLanguage_checkResetSeekBarAndPaused `
`testAudioFragment_openFragment_showsEnglishAudioLanguageWhenDefaultAudioLanguageNotAvailable `
`testAudioFragment_invokePrepared_touchSeekBar_checkStillPaused `
`testAudioFragment_openFragment_profileWithEnglishAudioLanguage_showsEnglishAudioLanguage `

2020-11-18 05:34 UTC, closed without merging

2020-11-18 05:36 UTC, FareesHussain commented
Closed as the among the 4 solved tests 2 were not correct and 
2 of them require updating dependencies which causes problem in other tests and CI check errors