Fix #2120: Highfi PinPasswordActivity
oppia/oppia-android pull request #2128
Opened 2020-11-19 20:13 UTC by prayutsu

## Explanation

Fixes #2120
 Dedicated layouts for tablets are added according to the mocks.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

Device tested - Nexus C - 
![Screenshot_1605816537](https://user-images.githubusercontent.com/54636525/99718945-acc42800-2ad1-11eb-9c4d-db939b636bcc.png)
![Screenshot_1605816547](https://user-images.githubusercontent.com/54636525/99718957-af268200-2ad1-11eb-973b-a47457a41736.png)

2020-11-19 20:15 UTC, prayutsu commented
@rt4914 Do we also need to enlarge the keyboard size?

2020-11-20 04:23 UTC, rt4914 commented
> @rt4914 Do we also need to enlarge the keyboard size?

No that is not needed.

2020-11-20 11:14 UTC, MohamedMedhat1998 requested changes
Nice work but there are some nit changes, PTAL and update the PR accordingly.  
Also some other changes:  
1. Add the mocks link to the PR description as we tend to do that with `high-fi` PRs.
2. Use the defined styles in `styles.xml` for the `TextViews`. For example, `hello_text_view` style should be `Heading1`

2020-11-20 11:14 UTC, MohamedMedhat1998 commented on app/src/main/res/layout-sw600dp-land/pin_password_activity.xml
> +      android:layout_marginTop="128dp"/>
`android:layout_marginTop` should be `104dp`, not `128dp` because the `128dp` includes the system bar which is `24dp` in height.

2020-11-20 11:14 UTC, MohamedMedhat1998 commented on app/src/main/res/layout-sw600dp-land/pin_password_activity.xml
> +      app:itemHeight="48dp"
`44dp`

2020-11-20 11:14 UTC, MohamedMedhat1998 commented on app/src/main/res/layout-sw600dp-land/pin_password_activity.xml
> +      app:itemWidth="28dp"
`24dp`

2020-11-20 11:14 UTC, MohamedMedhat1998 commented on app/src/main/res/layout-sw600dp-land/pin_password_activity.xml
> +      android:paddingTop="12dp"
`18dp`

2020-11-20 11:14 UTC, MohamedMedhat1998 commented on app/src/main/res/layout-sw600dp-land/pin_password_activity.xml
> +      android:layout_marginStart="12dp"
`16dp`

2020-11-20 11:14 UTC, MohamedMedhat1998 commented on app/src/main/res/layout-sw600dp-land/pin_password_activity.xml
> +        android:layout_marginTop="4dp"
`8dp`

2020-11-20 11:14 UTC, MohamedMedhat1998 commented on app/src/main/res/layout-sw600dp-port/pin_password_activity.xml
> +      android:layout_marginTop="240dp"/>
`216dp`

2020-11-20 11:14 UTC, MohamedMedhat1998 commented on app/src/main/res/layout-sw600dp-port/pin_password_activity.xml
> +      android:paddingTop="12dp"
`18dp`

2020-11-20 11:14 UTC, MohamedMedhat1998 commented on app/src/main/res/layout-sw600dp-port/pin_password_activity.xml
> +      android:layout_marginStart="12dp"
`16dp`

2020-11-20 11:14 UTC, MohamedMedhat1998 commented on app/src/main/res/layout-sw600dp-port/pin_password_activity.xml
> +        android:layout_marginTop="4dp"
`8dp`

2020-11-21 07:23 UTC, prayutsu commented on app/src/main/res/layout-sw600dp-port/pin_password_activity.xml
> +        android:layout_marginTop="4dp"
done

2020-11-21 07:23 UTC, prayutsu commented on app/src/main/res/layout-sw600dp-port/pin_password_activity.xml
> +      android:layout_marginStart="12dp"
done

2020-11-21 07:23 UTC, prayutsu commented on app/src/main/res/layout-sw600dp-port/pin_password_activity.xml
> +      android:paddingTop="12dp"
done

2020-11-21 07:24 UTC, prayutsu commented on app/src/main/res/layout-sw600dp-port/pin_password_activity.xml
> +      android:layout_marginTop="240dp"/>
done

2020-11-21 07:24 UTC, prayutsu commented on app/src/main/res/layout-sw600dp-land/pin_password_activity.xml
> +        android:layout_marginTop="4dp"
done

2020-11-21 07:24 UTC, prayutsu commented on app/src/main/res/layout-sw600dp-land/pin_password_activity.xml
> +      android:paddingTop="12dp"
done

2020-11-21 07:24 UTC, prayutsu commented on app/src/main/res/layout-sw600dp-land/pin_password_activity.xml
> +      app:itemWidth="28dp"
done

2020-11-21 07:24 UTC, prayutsu commented on app/src/main/res/layout-sw600dp-land/pin_password_activity.xml
> +      app:itemHeight="48dp"
done

2020-11-21 07:24 UTC, prayutsu commented on app/src/main/res/layout-sw600dp-land/pin_password_activity.xml
> +      android:layout_marginTop="128dp"/>
done

2020-11-21 07:25 UTC, prayutsu commented
@MohamedMedhat1998 FIxed suggested changes, PTAL
P.S - Also updated the screenshots in the PR description

2020-11-21 10:35 UTC, MohamedMedhat1998 approved these changes
LGTM, Thanks!

2020-11-21 11:03 UTC, MohamedMedhat1998 commented
Approving this PR on behalf of Rajat because he may not be available during the weekend.

2020-11-21 11:04 UTC, merged

2020-11-21 11:04 UTC, MohamedMedhat1998 commented
give @prayutsu 75 points