Fix #1891: Throughly add tests for NumberWithUnitsInputIsEqualToRuleClassifier
oppia/oppia-android pull request #2152
Opened 2020-11-22 17:34 UTC by peculiaruc

## Explanation
 Fix #1891, Throughly added tests for NumberWithUnitsInputIsEqualToRuleClassifier

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-11-22 21:50 UTC, peculiaruc commented
![Screenshot from 2020-11-22 18-13-48](https://user-images.githubusercontent.com/35475543/99918114-12ecbd00-2d15-11eb-85c9-e6885177f07e.png)

2020-11-24 00:29 UTC, anandwana001 requested changes
Thanks @peculiaruc 
Left a few comments.

2020-11-24 00:29 UTC, anandwana001 commented on domain/src/test/java/org/oppia/android/domain/classify/rules/numberwithunits/NumberWithUnitsIsEqualToRuleClassifierProviderTest.kt
> +/** Tests for [NumberWithUnitsIsEqualToRuleClassifierProviderTest]. */
It will be NumberWithUnitsIsEqualToRuleClassifierProvider

2020-11-24 00:29 UTC, anandwana001 commented on domain/src/test/java/org/oppia/android/domain/classify/rules/numberwithunits/NumberWithUnitsIsEqualToRuleClassifierProviderTest.kt
> +class NumberWithUnitsIsEqualToRuleClassifierProviderTest {
Remove TODO from its respective provider class. 
`// TODO(#210): Add tests for this classifier.`

2020-11-24 00:29 UTC, anandwana001 commented on domain/src/test/java/org/oppia/android/domain/classify/rules/numberwithunits/NumberWithUnitsIsEqualToRuleClassifierProviderTest.kt
> +  private val TEST_WHOLE_NUMBER_VALUE_9 =
Please check `NumberWithUnitsIsEquivalentToRuleClassifierProviderTest` for variable naming.

2020-11-24 00:29 UTC, anandwana001 commented on domain/src/test/java/org/oppia/android/domain/classify/rules/numberwithunits/NumberWithUnitsIsEqualToRuleClassifierProviderTest.kt
> +  fun testEquals_fractionInputNumberWithUnits_withFractionAnswerWithUnits_bothValuesMatches() {
Take reference from `NumberWithUnitsIsEquivalentToRuleClassifierProviderTest` for function naming.

2020-11-24 00:29 UTC, anandwana001 commented on domain/src/test/java/org/oppia/android/domain/classify/rules/numberwithunits/NumberWithUnitsIsEqualToRuleClassifierProviderTest.kt
> +  fun testEquals_differentFractionWithUnits_withRealAnswerNumberWithUnits_bothDoNotMatch() {
`testDifferentFractionWithUnits_withRealAnswerNumberWithUnits_bothDoNotMatch` this sounds short and similar too.

2020-11-26 11:40 UTC, rt4914 commented
@peculiaruc PTAL at Akshay's comments.

2020-11-30 10:43 UTC, anandwana001 approved these changes
LGTM, Thanks @peculiaruc 

I am resolving my comments as of now, later, please try to mention done or any comment so that the reviewer can understand the requested suggestion has been done.

2020-11-30 12:09 UTC, rt4914 approved these changes
LGTM, thanks.

2020-11-30 12:09 UTC, merged

2020-11-30 18:05 UTC, peculiaruc commented
> Thanks @peculiaruc
> Left a few comments.

Done

2020-11-30 18:06 UTC, peculiaruc commented
> LGTM, Thanks @peculiaruc
> 
> I am resolving my comments as of now, later, please try to mention done or any comment so that the reviewer can understand the requested suggestion has been done.

Done. so sorry it is coming late