Fix #2146: [RTL] Highfi CompletedStoryList #2146
oppia/oppia-android pull request #2169
Opened 2020-11-25 15:47 UTC by FareesHussain

## Explanation

Fixes #2146 

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

Mobile Portrait | Mobile Landscape 
--- | --- 
<img src="https://user-images.githubusercontent.com/54740946/100248870-fabdad80-2f61-11eb-987a-0f9c7e3d42ba.png" align="center" width="100%"/> | <img src="https://user-images.githubusercontent.com/54740946/100248895-ff826180-2f61-11eb-93d1-2a4e78a394d4.png" align="center" width="100%"/>

Tablet Portrait | Tablet Landscape 
--- | --- 
<img src="https://user-images.githubusercontent.com/54740946/100249719-e4642180-2f62-11eb-9343-d0c14ba458d1.png" align="center" width="100%"/> | <img src="https://user-images.githubusercontent.com/54740946/100249725-e62de500-2f62-11eb-8869-6d87b6b8f244.png" align="center" width="100%"/>

2020-11-25 15:48 UTC, FareesHussain commented
@rt4914 please check

This is what is could do so far as the only changes needed for RTL were in TextView remaining were automatically managed

2020-11-25 16:48 UTC, anandwana001 commented
@FareesHussain It looks like tests in `CompletedStoryListActivityTest ` are failing.

2020-11-25 17:55 UTC, rt4914 commented
> @FareesHussain It looks like tests in `CompletedStoryListActivityTest ` are failing, as this pr involves modifying landscape layout files.

Actually thats an ongoing issue https://github.com/oppia/oppia-android/issues/1658 .
For now we will have to run this and check.

2020-11-25 19:41 UTC, rt4914 requested changes
This PR looks good but one change is suggested.

Also I am adding screenshots that I recorded during testing for future reference.
![Screenshot_1606333046](https://user-images.githubusercontent.com/9396084/100274280-26518f80-2f84-11eb-970e-45d90b682502.png)
![Screenshot_1606333063](https://user-images.githubusercontent.com/9396084/100274289-294c8000-2f84-11eb-9d8b-54f36817867d.png)
![Screenshot_1606333107](https://user-images.githubusercontent.com/9396084/100274291-2a7dad00-2f84-11eb-913b-8a01b2b7a558.png)
![Screenshot_1606333118](https://user-images.githubusercontent.com/9396084/100274292-2b164380-2f84-11eb-940c-37a2e414d8f1.png)

2020-11-25 19:41 UTC, rt4914 commented on app/src/main/res/layout/completed_story_item.xml
> -    android:onClick="@{(v) -> viewModel.onCompletedStoryItemClicked()}"
Please add this click item back.

2020-11-26 00:58 UTC, FareesHussain commented on app/src/main/res/layout/completed_story_item.xml
> -    android:onClick="@{(v) -> viewModel.onCompletedStoryItemClicked()}"
Done

2020-11-26 01:28 UTC, FareesHussain commented
May be the previous checks failed cause I removed the onClick attribute

2020-11-26 11:43 UTC, rt4914 commented
> May be the previous checks failed cause I removed the onClick attribute

Yes, exactly.

2020-11-26 11:44 UTC, rt4914 approved these changes
LGTM, thanks.

2020-11-26 11:44 UTC, merged