Fix #2147: Rtl support layouts
oppia/oppia-android pull request #2181
Opened 2020-11-26 12:10 UTC by FareesHussain

## Explanation

Fixes #2147 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

Mobile Portrait | Mobile Landscape 
--- | --- 
<img src="https://user-images.githubusercontent.com/54740946/100348987-c30c3f80-300d-11eb-9906-accd564be452.png" align="center" width="100%"/> | <img src="https://user-images.githubusercontent.com/54740946/100348982-c0114f00-300d-11eb-81dd-55705f130b1e.png" align="center" width="60%"/>

Tablet Portrait | Tablet Landscape 
--- | --- 
<img src="https://user-images.githubusercontent.com/54740946/100348983-c0114f00-300d-11eb-9c20-bcaf220b12ee.png" align="center" width="60%"/> | <img src="https://user-images.githubusercontent.com/54740946/100348992-c4d60300-300d-11eb-8050-b79e9ef5253b.png" align="center" width="200%"/>

2020-11-26 12:41 UTC, FareesHussain commented
@rt4914 please check

2020-11-26 12:57 UTC, rt4914 commented
> @rt4914 please check

Hello @FareesHussain PTAL https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section

2020-11-30 07:54 UTC, rt4914 requested changes
@FareesHussain 
Why is `tools:ignore="RtlCompat"` needed? Because if I am removing this, it does not affect UI. Am I missing something?

2020-11-30 08:00 UTC, FareesHussain commented
> @FareesHussain
> Why is `tools:ignore="RtlCompat"` needed? Because if I am removing this, it does not affect UI. Am I missing something?

i added this cause it shows a error with a suggestion to add it when I  add `android:textAlignment="viewStart"` in a checkbox
but it works even without it

2020-11-30 08:19 UTC, rt4914 commented
> > @FareesHussain
> > Why is `tools:ignore="RtlCompat"` needed? Because if I am removing this, it does not affect UI. Am I missing something?
> 
> i added this cause it shows a error with a suggestion to add it when I add `android:textAlignment="viewStart"` in a checkbox
> but it works even without it

@FareesHussain Okay, in that case you can fix this by using `android:gravity="start"`

2020-11-30 08:30 UTC, FareesHussain commented
@rt4914 `android:gravity="start"` is not working for check box

2020-11-30 09:27 UTC, rt4914 commented
> @rt4914 `android:gravity="start"` is not working for check box

@FareesHussain Actually i did check that code and it was working. Can you please mention what error you are getting?

2020-11-30 09:31 UTC, FareesHussain commented
I'm sorry I was little confused i'll push those changes

2020-11-30 19:02 UTC, rt4914 requested changes
@FareesHussain Just one nit change suggested, rest all looks good. Thanks.

2020-11-30 19:02 UTC, rt4914 commented on app/src/main/res/layout-sw600dp-land/topic_practice_subtopic.xml
> +        app:layout_constraintTop_toTopOf="parent"/>
Please add space before closing tag.
`app:layout_constraintTop_toTopOf="parent" />`

2020-12-01 01:11 UTC, FareesHussain commented on app/src/main/res/layout-sw600dp-land/topic_practice_subtopic.xml
> +        app:layout_constraintTop_toTopOf="parent"/>
Done please check

2020-12-01 05:37 UTC, rt4914 approved these changes
LGTM, thanks.

2020-12-01 05:37 UTC, merged