Fix #2093: [Mobile-Landscape] High-fi StoryActivity Updated UI
oppia/oppia-android pull request #2201
Opened 2020-12-01 10:54 UTC by ReCodee

## Explanation

 Fixes #2093 

### Screenshots
![Screenshot_2020-12-01-16-13-31-391_org oppia android](https://user-images.githubusercontent.com/59660380/100731257-283aa900-33f1-11eb-959c-d30ab1b9295f.jpg)

![Screenshot_2020-12-01-16-12-36-344_org oppia android](https://user-images.githubusercontent.com/59660380/100731540-88c9e600-33f1-11eb-83bf-78f1c5142d5f.jpg)

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-12-01 11:02 UTC, anandwana001 commented
You can check and setup ktlint on your local machine, this will prevent the GitHub check failures. 
https://github.com/oppia/oppia-android/wiki/Ktlint-Guide

2020-12-02 04:25 UTC, anandwana001 commented
@ReCodee I suggest to setup Macros, this is fix all issue in just one shortcut. 
Please check here - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros

2020-12-02 04:30 UTC, anandwana001 requested changes
Formating suggestion, @ReCodee

2020-12-02 04:30 UTC, anandwana001 commented on app/src/main/java/org/oppia/android/app/story/StoryFragmentPresenter.kt
> +          binding.storyChapterCard.strokeWidth = when (
```kotlin
 binding.storyChapterCard.strokeWidth =
            when (storyItemViewModel.chapterSummary.chapterPlayState) {
              ChapterPlayState.NOT_PLAYABLE_MISSING_PREREQUISITES ->
                view.context.resources.getDimension(R.dimen.space_0dp).toInt()
              else ->
                view.context.resources.getDimension(R.dimen.story_chapter_stroke_width).toInt()
            }
```

2020-12-02 04:30 UTC, anandwana001 commented on app/src/main/java/org/oppia/android/app/story/StoryFragmentPresenter.kt
> +            ).parseOppiaHtml(
```kotlin
).parseOppiaHtml(
    str,
    binding.chapterTitle
)
```

2020-12-02 04:50 UTC, anandwana001 commented on app/src/main/java/org/oppia/android/app/story/StoryFragmentPresenter.kt
> +          binding.storyChapterCard.strokeWidth = when (
You are getting the indentation issue. Please use the Reformat Code or Macros as per the suggestion to fix the issue. 

```kotlin
binding.storyChapterCard.strokeWidth =
  when (storyItemViewModel.chapterSummary.chapterPlayState) {
    ChapterPlayState.NOT_PLAYABLE_MISSING_PREREQUISITES ->
      view.context.resources.getDimension(R.dimen.space_0dp).toInt()
    else ->
      view.context.resources.getDimension(R.dimen.story_chapter_stroke_width).toInt()
  }
```

2020-12-08 04:47 UTC, anandwana001 commented
@ReCodee Any update on this?

2020-12-08 05:38 UTC, ReCodee commented
Will reopen this when ci check fails are resolved.

2020-12-08 05:38 UTC, closed without merging