Fix #2263: Fixes App crashes in Lessons Tab and Espresso tests in TopicLessonFragmentTest
oppia/oppia-android pull request #2264
Opened 2020-12-15 08:55 UTC by FareesHussain

## Explanation

Fixes #2263 

 - Fixes app crash in lessons Tab (landscape)
 - Fixes Espresso lagging test case in TopicLessonFragmentTest (testLessonsPlayFragment_loadRatiosTopic_configurationChange_storyName_isCorrect)
- Fixes app crash in lesson Tab (Tablet portrait and Tablet landscape)
 - Fixes 12 failed test in TopicLessonFragmentTest when run in TopicLessonFragmentTest (run in tablet)

**NOTE**:  above mentioned tests passes in robolectric

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

##ScreenShots
testLessonsPlayFragment_loadRatiosTopic_configurationChange_storyName_isCorrect before changes 
![image](https://user-images.githubusercontent.com/54740946/102191168-0d7f2e80-3edf-11eb-87f8-0234f8e5f05b.png)
Espresso test failing in tablet
![image](https://user-images.githubusercontent.com/54740946/102192083-48ce2d00-3ee0-11eb-81bb-d13e7d548a18.png)

2020-12-15 10:47 UTC, FareesHussain commented
Workflow needs to be re-run as it works when I run it in my [forked workflow](https://github.com/FareesHussain/oppia-android/runs/1556276174?check_suite_focus=true)

2020-12-15 11:31 UTC, anandwana001 commented
@FareesHussain can we investigate why this crash is occurring? As I know earlier it is not crashing.

2020-12-15 11:33 UTC, FareesHussain commented
may be bindable adapter was implemented in story summary recently 
the person who implemented it might have forgot to make changes in other layouts

2020-12-15 11:42 UTC, anandwana001 commented
> may be bindable adapter was implemented in story summary recently
> the person who implemented it might have forgot to make changes in other layouts

Could you link the PR which cause the crash? We can fix but need to check why things working correctly before.

2020-12-15 11:47 UTC, FareesHussain commented
> > may be bindable adapter was implemented in story summary recently
> > the person who implemented it might have forgot to make changes in other layouts
> 
> Could you link the PR which cause the crash? We can fix but need to check why things working correctly before.

It was working correctly because robolectric tests are passing and it was tested in mobile portrait 

and this is the pr #2104

2020-12-15 11:59 UTC, anandwana001 commented
> #2104

Looking into this, Thanks for mentioning.

2020-12-15 12:21 UTC, anandwana001 approved these changes
LGTM, Thanks @FareesHussain

2020-12-15 12:46 UTC, rt4914 approved these changes
Thanks a lot @FareesHussain

2020-12-15 12:47 UTC, rt4914 commented
This will need @BenHenning approval as he is the code owner.

2020-12-15 12:48 UTC, FareesHussain commented
@anandwana001 I tried to run the Bazel test you mentioned 

for the first command
```bazel build //oppia --android_databinding_use_v3_4_args --experimental_android_databinding_v2 --java_header_compilation=false --noincremental_dexing --define=android_standalone_dexing_tool=d8_compat_dx```

I get the output
```
DEBUG: Rule 'io_bazel_stardoc' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "4378e9b6bb2831de7143580594782f538f461180", shallow_since = "157082916
6 -0400" and dropping ["tag"]
DEBUG: Repository io_bazel_stardoc instantiated at:
  E:/android/oppia-android-two/WORKSPACE:45:35: in <toplevel>
  C:/users/syed farees hussain/_bazel_syed farees hussain/zcnrcatv/external/io_bazel_rules_kotlin/kotlin/internal/repositories/download.bzl:115:10: in kt_download_local_dev_dependencies
  C:/users/syed farees hussain/_bazel_syed farees hussain/zcnrcatv/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  C:/users/syed farees hussain/_bazel_syed farees hussain/zcnrcatv/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
DEBUG: Rule 'robolectric' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "a7eac9418cc0b6d2527699986d5937efcebae927c3917c8bd3cb7663ee65ab63"
DEBUG: Repository robolectric instantiated at:
  E:/android/oppia-android-two/WORKSPACE:91:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/syed farees hussain/_bazel_syed farees hussain/zcnrcatv/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'tools_android' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1594238320 -0400"
DEBUG: Repository tools_android instantiated at:
  E:/android/oppia-android-two/WORKSPACE:102:15: in <toplevel>
Repository rule git_repository defined at:
  C:/users/syed farees hussain/_bazel_syed farees hussain/zcnrcatv/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: Skipping '//oppia': no such package 'oppia': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - E:/android/oppia-android-two/oppia
WARNING: Target pattern parsing failed.
ERROR: no such package 'oppia': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - E:/android/oppia-android-two/oppia
INFO: Elapsed time: 212.216s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Could you please check

2020-12-15 13:10 UTC, FareesHussain commented
For the second command
```
bazel test //app:TopicLessonsFragmentTest --android_databinding_use_v3_4_args --experimental_android_databinding_v2 --java_header_compilation=false --noincremental_dexing --define=android_standalone_dexing_tool=d8_compat_dx
```
The output is

```
DEBUG: Rule 'io_bazel_stardoc' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "4378e9b6bb2831de7143580594782f538f461180", shallow_since = "1570829166 -0400" and dropping ["tag"]
DEBUG: Repository io_bazel_stardoc instantiated at:
  E:/android/oppia-android-two/WORKSPACE:45:35: in <toplevel>
  C:/users/syed farees hussain/_bazel_syed farees hussain/zcnrcatv/external/io_bazel_rules_kotlin/kotlin/internal/repositories/download.bzl:115:10: in kt_download_local_dev_dependencies
  C:/users/syed farees hussain/_bazel_syed farees hussain/zcnrcatv/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  C:/users/syed farees hussain/_bazel_syed farees hussain/zcnrcatv/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
DEBUG: Rule 'robolectric' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "a7eac9418cc0b6d2527699986d5937efcebae927c3917c8bd3cb7663ee65ab63"
DEBUG: Repository robolectric instantiated at:
  E:/android/oppia-android-two/WORKSPACE:91:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/syed farees hussain/_bazel_syed farees hussain/zcnrcatv/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'tools_android' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1594238320 -0400"
DEBUG: Repository tools_android instantiated at:
  E:/android/oppia-android-two/WORKSPACE:102:15: in <toplevel>
Repository rule git_repository defined at:
  C:/users/syed farees hussain/_bazel_syed farees hussain/zcnrcatv/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Repository maven instantiated at:
  E:/android/oppia-android-two/WORKSPACE:125:14: in <toplevel>
  C:/users/syed farees hussain/_bazel_syed farees hussain/zcnrcatv/external/rules_jvm_external/defs.bzl:89:19: in maven_install
Repository rule coursier_fetch defined at:
  C:/users/syed farees hussain/_bazel_syed farees hussain/zcnrcatv/external/rules_jvm_external/coursier.bzl:620:33: in <toplevel>
INFO: Repository 'maven' used the following cache hits instead of downloading the corresponding file.
 * Hash '8f35f92fb8e021f96b3aa8145c66c3b2e29295baabb28ff50569e613438afcbd' for https://github.com/coursier/coursier/releases/download/v2.0.0-RC3-4/coursier.jar
If the definition of 'maven' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
        File "C:/users/syed farees hussain/_bazel_syed farees hussain/zcnrcatv/external/rules_jvm_external/coursier.bzl", line 364, column 13, in _coursier_fetch_impl
                fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:androidx_annotation_annotation in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact w
ith coursier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:androidx_databinding_databinding_adapters in repository @maven which failed to fetch. no such package '@maven//': Error while fetching
 artifact with coursier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:androidx_databinding_databinding_common in repository @maven which failed to fetch. no such package '@maven//': Error while fetching a
rtifact with coursier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:androidx_databinding_databinding_compiler in repository @maven which failed to fetch. no such package '@maven//': Error while fetching
 artifact with coursier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:androidx_databinding_databinding_runtime in repository @maven which failed to fetch. no such package '@maven//': Error while fetching
artifact with coursier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:androidx_navigation_navigation_fragment in repository @maven which failed to fetch. no such package '@maven//': Error while fetching a
rtifact with coursier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:androidx_navigation_navigation_ui in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifac
t with coursier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:androidx_test_espresso_espresso_contrib in repository @maven which failed to fetch. no such package '@maven//': Error while fetching a
rtifact with coursier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:androidx_test_espresso_espresso_core in repository @maven which failed to fetch. no such package '@maven//': Error while fetching arti
fact with coursier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:androidx_test_espresso_espresso_intents in repository @maven which failed to fetch. no such package '@maven//': Error while fetching a
rtifact with coursier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:androidx_test_ext_junit in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with cou
rsier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:androidx_test_runner in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursi
er: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:com_github_bumptech_glide_mocks in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact
with coursier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:com_google_truth_truth in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with cour
sier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:org_jetbrains_kotlin_kotlin_test_junit in repository @maven which failed to fetch. no such package '@maven//': Error while fetching ar
tifact with coursier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:org_jetbrains_kotlin_kotlin_reflect in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artif
act with coursier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:org_jetbrains_kotlinx_kotlinx_coroutines_test in repository @maven which failed to fetch. no such package '@maven//': Error while fetc
hing artifact with coursier: Timed out
ERROR: E:/android/oppia-android-two/app/BUILD.bazel:1092:9: //app:TopicLessonsFragmentTest depends on @maven//:or [...]

2020-12-15 15:07 UTC, anandwana001 commented
@FareesHussain It involves cloning of oppia's bazel version. I will do it for now. 
Please add the screenshot of espresso and robolectric result for future reference.

2020-12-15 15:20 UTC, FareesHussain commented
Espresso 
![image](https://user-images.githubusercontent.com/54740946/102233622-79c95480-3f16-11eb-91b4-40e08153f72b.png)
Robolectric
![image](https://user-images.githubusercontent.com/54740946/102234239-18ee4c00-3f17-11eb-8890-fe032e6efdb6.png)

2020-12-16 01:56 UTC, BenHenning commented
I'm fine with approving this, but can we please update #2263 with the root cause (e.g. which PR introduced the original crash)? In general, cases like this should lead to a reversion, not a fix (see https://github.com/oppia/oppia-android/wiki/Revert-&-regression-policy).

2020-12-16 01:58 UTC, BenHenning commented
Also, before approving: @FareesHussain please add tests in the fragment holding these views that hit each of these scenarios (e.g. landscape, tablet portrait, tablet landscape). Please add a screenshot showing these tests fail without your fix in place (to ensure they prevent this from happening again).

2020-12-16 01:58 UTC, BenHenning requested changes
Requesting changes until there's a test to guard against this regressing in the future.

2020-12-16 03:26 UTC, FareesHussain commented
> Requesting changes until there's a test to guard against this regressing in the future.

@BenHenning I've already added them in this pr description please check

2020-12-16 03:33 UTC, FareesHussain commented
> Please add a screenshot showing these tests fail without your fix in place (to ensure they prevent this from happening again).

I've already added screenshots in this pr description please check

2020-12-16 07:32 UTC, FareesHussain commented
@BenHenning  please check
## Before changes

For mobile landscape the following tests does'nt run to the completions in espresso (however they pass in robolectric)

*testLessonsPlayFragment_loadRatiosTopic_clickExpandListIconIndex1_configurationChange_chapterListIsVisible*
![image](https://user-images.githubusercontent.com/54740946/102313922-880b8500-3f97-11eb-96eb-2e4cdb5e90be.png)

*testLessonsPlayFragment_loadRatiosTopic_configurationChange_storyName_isCorrect*
![image](https://user-images.githubusercontent.com/54740946/102314060-cacd5d00-3f97-11eb-9c48-a021fdcd9e47.png)


*Running all tests of TopicLessonsFragmentTest 12 out of 13 Tests fail*
![image](https://user-images.githubusercontent.com/54740946/102192083-48ce2d00-3ee0-11eb-81bb-d13e7d548a18.png)

## After Changes
*Mobile espresso*
![image](https://user-images.githubusercontent.com/54740946/102233622-79c95480-3f16-11eb-91b4-40e08153f72b.png)

*Tablet Espresso* (NEXUS 7 API 27)
![image](https://user-images.githubusercontent.com/54740946/102317977-8beed580-3f9e-11eb-80cc-077982a70301.png)

2020-12-18 03:46 UTC, BenHenning commented
Thanks @FareesHussain. Sorry to be a bit clearer, what we actually need here is a test that results in the same crash that you're fixing. Are those Espresso tests actually resulting in the same bindable adapter issue that #2263 is describing? It's also odd that Robolectric isn't failing--it should be. @FareesHussain can you make sure that we have a test that specifically fails on Robolectric without the suggest fix in place? @anandwana001 might this be because Robolectric doesn't do rotation correctly? If so, @FareesHussain you may be able to write an explicit test for this that starts the device in landscape mode (e.g. using ``@Config`` per http://robolectric.org/javadoc/3.3/org/robolectric/annotation/Config.html#qualifiers--).

2020-12-18 04:11 UTC, FareesHussain commented
> Thanks @FareesHussain. Sorry to be a bit clearer, what we actually need here is a test that results in the same crash that you're fixing. Are those Espresso tests actually resulting in the same bindable adapter issue that #2263 is describing? It's also odd that Robolectric isn't failing--it should be. @FareesHussain can you make sure that we have a test that specifically fails on Robolectric without the suggest fix in place? @anandwana001 might this be because Robolectric doesn't do rotation correctly? If so, @FareesHussain you may be able to write an explicit test for this that starts the device in landscape mode (e.g. using `@Config` per http://robolectric.org/javadoc/3.3/org/robolectric/annotation/Config.html#qualifiers--).

@BenHenning  There is no crash when I run this on Espresso(it crashes when the Item in the recyclerview is expanded) The test stop as below. I will try adding tests corresponding test that fail in robolectric.

![Screenshot_1608264360](https://user-images.githubusercontent.com/54740946/102573465-84513d00-4114-11eb-9ef9-7804599c6591.png)

2020-12-19 02:01 UTC, anandwana001 commented
> Thanks @FareesHussain. Sorry to be a bit clearer, what we actually need here is a test that results in the same crash that you're fixing. Are those Espresso tests actually resulting in the same bindable adapter issue that #2263 is describing? It's also odd that Robolectric isn't failing--it should be. @FareesHussain can you make sure that we have a test that specifically fails on Robolectric without the suggest fix in place? @anandwana001 might this be because Robolectric doesn't do rotation correctly? If so, @FareesHussain you may be able to write an explicit test for this that starts the device in landscape mode (e.g. using `@Config` per http://robolectric.org/javadoc/3.3/org/robolectric/annotation/Config.html#qualifiers--).

Sounds like that. Robolectric is not performing rotation correctly.

2020-12-19 19:29 UTC, FareesHussain commented
@BenHenning please check

*Before changes robolectric*
![image](https://user-images.githubusercontent.com/54740946/102697611-2d0ab400-425d-11eb-83f9-e41d89b1362e.png)

*After changes robolectric*
![image](https://user-images.githubusercontent.com/54740946/102697706-dce02180-425d-11eb-9122-4f2f878c0184.png)

2020-12-20 05:34 UTC, FareesHussain commented
Workflow needs to be re-run as the checks pass on my forked workflow

https://github.com/FareesHussain/oppia-android/actions/runs/433429817

2020-12-20 17:59 UTC, FareesHussain commented on app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt
> +      onView(isRoot()).perform(orientationLandscape())
I added these again cause orientation does'nt change in Espresso
even if using `@config`

2020-12-22 03:25 UTC, BenHenning commented
Thanks @FareesHussain. Can you actually change the test such that:
- We have a test for doing X (in portrait by default)
- We have another test for doing X after a configuration change
- We have another test for doing X (in landscape by default)

The third test is technically a new, duplicate test of the first one (but starting in landscape). This is preferred over changing existing tests to only be landsdcape + configuration change, and should improve our behavioral coverage a bit.

It looks like two tests were changed before--in that case I'd expect those two to be reverted, and duplicated to be the third class of test above (starting in landscape but performing a configuration change).

2020-12-23 09:31 UTC, BenHenning approved these changes
Thanks @FareesHussain! LGTM.

2020-12-23 09:31 UTC, merged