Fix #2038: File formatting under numericinput package
oppia/oppia-android pull request #2334
Opened 2020-12-29 07:50 UTC by Victor-Titan

## Explanation

Fixes #2038 Formatted the files under the numericinput package as specified in issue #2038

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

PTAL @anandwana001

2020-12-29 09:22 UTC, Victor-Titan commented
@anandwana001 I can't understand the error it's showing in the checks. Can you please help?

2020-12-29 23:54 UTC, anandwana001 requested changes
Thanks @Victor-Titan 
one change else LGTM

2020-12-29 23:54 UTC, anandwana001 commented on domain/src/test/java/org/oppia/android/domain/classify/rules/numericinput/NumericInputIsGreaterThanRuleClassifierProviderTest.kt
>    @Inject
leave an empty line above

2020-12-30 10:15 UTC, Victor-Titan commented
> Thanks @Victor-Titan
> one change else LGTM

@anandwana001 Please check now, I've made the changes.

2020-12-31 09:06 UTC, anandwana001 approved these changes
LGTM, Thanks @Victor-Titan

2020-12-31 09:55 UTC, rt4914 approved these changes
LGTM, thanks.

2020-12-31 09:55 UTC, merged