Fixes #2266 RTL Support in Admin Pin Verification
oppia/oppia-android pull request #2336
Opened 2020-12-29 09:46 UTC by RaghavAwasthi

## Explanation

  The PR fixes #2266  by adding `locale ` based RTL Support for users.
  The PR  also adds the .idea folder to `.gitignore` so that android studio files get auto ignored by default  for all the contributors 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-12-29 10:04 UTC, FareesHussain requested changes
@RaghavAwasthi Need reformatting. I suggest to set up a macro so it will be handy all the time, and it also works with XML files.
Check out wiki here - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros

please check - https://github.com/oppia/oppia-android/wiki/RTL-Guidelines
Add screenshots in description
Also, I've added few comments please check

2020-12-29 10:04 UTC, FareesHussain commented on .gitignore
> +/.idea
This has a seperate issue for this #1734 and it is blocked on  `XML linter` so please revert this

2020-12-29 10:04 UTC, FareesHussain commented on app/src/main/res/layout-sw600dp-land/pin_password_activity.xml
> +
Remove this extra line

2020-12-29 10:26 UTC, FareesHussain commented
@RaghavAwasthi Add screenshots in the description too

2020-12-29 10:33 UTC, RaghavAwasthi commented
> @RaghavAwasthi Add screenshots in the description too

Done

2020-12-29 10:49 UTC, FareesHussain requested changes
@RaghavAwasthi Screenshot should look like this add the same for all the layouts
![image](https://user-images.githubusercontent.com/54740946/103278426-768f9780-49f1-11eb-9f42-8ba757964f7b.png)

2020-12-29 11:09 UTC, FareesHussain commented
@RaghavAwasthi In RTL the input must be from **Right to Left** but for the `PinView` it is **Left to Right** please fix that too

2020-12-29 17:06 UTC, FareesHussain commented
Sorry I forgot to mention it please update the title to :
`Fix #2266: RTL Support in Admin Pin Verification`

2021-01-06 09:15 UTC, anandwana001 commented
@RaghavAwasthi any update on this?

2021-01-07 08:37 UTC, RaghavAwasthi commented
@anandwana001  I was quite ill, hence was not able to complete it. Will update in a day or so. Thanks

2021-01-10 18:28 UTC, Luffy18346 commented
@RaghavAwasthi any update on this?

2021-01-19 14:02 UTC, rt4914 commented
Closing this PR because of no activity.

2021-01-19 14:02 UTC, closed without merging