Fix #2270 Added RTL mode for Audio and Language Activity
oppia/oppia-android pull request #2338
Opened 2020-12-29 10:39 UTC by imraghav20

Fixes #2270

## Explanation

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-12-29 10:44 UTC, FareesHussain commented on .idea/codeStyles/Project.xml
> +      </option>
Please don't make changes in `.idea` files.
Have a look at the checklist

2020-12-29 10:45 UTC, FareesHussain requested changes
@imraghav20 Add screenshots in the description
Have a look at RTL guidelines for the screenshots
https://github.com/oppia/oppia-android/wiki/RTL-Guidelines

2020-12-29 10:45 UTC, FareesHussain commented on .idea/codeStyles/Project.xml
> +      </option>
Please don't make changes in `.idea` files.
Have a look at the checklist

2020-12-29 10:52 UTC, imraghav20 commented
> @imraghav20 Add screenshots in the description
> Have a look at RTL guidelines for the screenshots
> https://github.com/oppia/oppia-android/wiki/RTL-Guidelines

Added screenshots in both portrait and layout mode.

![WhatsApp Image 2020-12-29 at 4 16 29 PM (1)](https://user-images.githubusercontent.com/59257038/103278543-bd7d8d00-49f1-11eb-80d2-1ab1fd2aa013.jpeg)
![WhatsApp Image 2020-12-29 at 4 16 29 PM (2)](https://user-images.githubusercontent.com/59257038/103278545-beaeba00-49f1-11eb-904f-29a68720b1a0.jpeg)
![WhatsApp Image 2020-12-29 at 4 16 29 PM (3)](https://user-images.githubusercontent.com/59257038/103278546-bf475080-49f1-11eb-97f4-bd3f477bf78e.jpeg)
![WhatsApp Image 2020-12-29 at 4 16 29 PM](https://user-images.githubusercontent.com/59257038/103278551-c1111400-49f1-11eb-88ad-c937a15926d7.jpeg)

2020-12-29 11:03 UTC, FareesHussain commented
@imraghav20 please revert the changes in  `Project.xml`

2020-12-29 11:12 UTC, imraghav20 commented
> @imraghav20 please revert the changes in `Project.xml`

Yes I am trying to do so, but whenever after changes I check out `git status` it shows there are no changes to commit. And when I go back to Android Studio, I see the code has been auto generated.

Any suggestions?

2020-12-29 11:17 UTC, FareesHussain commented
> > @imraghav20 please revert the changes in `Project.xml`
> 
> Yes I am trying to do so, but whenever after changes I check out `git status` it shows there are no changes to commit. And when I go back to Android Studio, I see the code has been auto generated.
> 
> Any suggestions?

@imraghav20 You can change it directly from github and paste the code from the following file
https://github.com/oppia/oppia-android/blob/develop/.idea/codeStyles/Project.xml

2020-12-29 11:19 UTC, imraghav20 commented
> > > @imraghav20 please revert the changes in `Project.xml`
> > 
> > 
> > Yes I am trying to do so, but whenever after changes I check out `git status` it shows there are no changes to commit. And when I go back to Android Studio, I see the code has been auto generated.
> > Any suggestions?
> 
> @imraghav20 You can change it directly from github and paste the code from the following file
> https://github.com/oppia/oppia-android/blob/develop/.idea/codeStyles/Project.xml

Thanks @FareesHussain

2020-12-29 11:23 UTC, FareesHussain approved these changes
LGTM, thanks

2020-12-30 05:25 UTC, rt4914 approved these changes
LGTM, thanks.

2020-12-30 05:26 UTC, merged