Remove unnecessary Initialisation of Firebase app in Testing
oppia/oppia-android pull request #2360
Opened 2021-01-04 10:52 UTC by etigoel

## Explanation

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-01-04 11:15 UTC, FareesHussain commented
@etigoel please check the checklist in the PR description

2021-01-04 13:11 UTC, etigoel commented
> @etigoel please check the checklist in the PR description

Locally the tests are getting passed. Can we check if the tests are flaky.

2021-01-04 13:13 UTC, FareesHussain commented
> > @etigoel please check the checklist in the PR description
> 
> Locally the tests are getting passed. Can we check if the tests are flaky.
> 
> 

Add screenshots for the passing tests

2021-01-04 13:35 UTC, anandwana001 requested changes
Thanks to @etigoel  for your first successful pull request. 

1. Please follow the checklist given in the Pull request description
      - PR title
      - PR description

2. Could you please confirm that after removing all the test cases are passing on Espresso? 
For Robolectric the test cases are passing on GitHub action so no need to check locally.

2021-01-04 13:35 UTC, anandwana001 commented on .idea/misc.xml
> +  ?xml version="1.0" encoding="UTF-8"?>
there should be no modification in this file.

2021-01-04 15:40 UTC, rt4914 requested changes
Suggested nit change.
Also, please follow the instructions mentioned in point 4. https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change

2021-01-04 15:40 UTC, rt4914 commented on .idea/misc.xml
> +  ?xml version="1.0" encoding="UTF-8"?>
Remove this line.

2021-01-04 15:53 UTC, etigoel commented on .idea/misc.xml
> +  ?xml version="1.0" encoding="UTF-8"?>
Done

2021-01-04 16:15 UTC, etigoel commented
> Thanks to @etigoel for your first successful pull request.
> 
> 1. Please follow the checklist given in the Pull request description
>    
>    * PR title
>    * PR description
> 2. Could you please confirm that after removing all the test cases are passing on Espresso?
>    For Robolectric the test cases are passing on GitHub action so no need to check locally.

To run tests on espresso, I have created Android-instrumented-tests run configuration and its passing. Do we need to perform any other action.

2021-01-04 16:22 UTC, etigoel commented
> > > @etigoel please check the checklist in the PR description
> > 
> > 
> > Locally the tests are getting passed. Can we check if the tests are flaky.
> 
> Add screenshots for the passing tests

All the tests are passing currently.

2021-01-04 17:02 UTC, etigoel commented
The test is getting passed locally. 
![image](https://user-images.githubusercontent.com/66623641/103559739-a13f8b80-4edc-11eb-900f-aead8ccbc31d.png)

2021-01-04 17:54 UTC, rt4914 approved these changes
LGTM, thanks.

2021-01-04 17:54 UTC, rt4914 commented
Will wait for @anandwana001 approval.

2021-01-04 17:55 UTC, rt4914 commented
@etigoel Please update title and description as per this comment: https://github.com/oppia/oppia-android/pull/2360#pullrequestreview-561023186

2021-01-05 08:42 UTC, anandwana001 approved these changes
LGTM, Thanks @etigoel

2021-01-05 08:44 UTC, rt4914 requested changes
Blocking because of title and description. 

As per mine and @anandwana001 previous comments please update the title and description of this PR so that you mention the issue number correctly.
Read this wiki and follow the 4th step to fix the PR. https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change

2021-01-05 11:15 UTC, ShridharGoel commented
@etigoel You also need to update the PR description to include the issue number.

2021-01-05 18:03 UTC, etigoel commented
> @etigoel You also need to update the PR description to include the issue number.

For this I am using git commit -m "message" -m "message". Do we need to something else.

2021-01-05 18:05 UTC, FareesHussain commented
> > @etigoel You also need to update the PR description to include the issue number.
> 
> For this I am using git commit -m "message" -m "message". Do we need to something else.

@etigoel You need to do this in github go to this PR description and edit
![image](https://user-images.githubusercontent.com/54740946/103682302-b684ea80-4fae-11eb-87bb-08a8f6cb1412.png)

2021-01-05 20:03 UTC, Luffy18346 commented
Hi @etigoel, as @FareesHussain suggested above, you have to edit the PR and update the explanation.
For example, write "Fixes #(bug number): " (or "Fixes part of #(bug number)" if the PR only partially fixes an issue) below the explanation when you edit the PR. If you want, you can add further description about what issue this PR solves.

For the reference, you can take a look at 4th point in https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change

2021-01-06 06:04 UTC, etigoel commented
> Hi @etigoel, as @FareesHussain suggested above, you have to edit the PR and update the explanation.
> For example, write "Fixes #(bug number): " (or "Fixes part of #(bug number)" if the PR only partially fixes an issue) below the explanation when you edit the PR. If you want, you can add further description about what issue this PR solves.
> 
> For the reference, you can take a look at 4th point in https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change

Done.. Thank you

2021-01-06 06:04 UTC, etigoel commented
> > > @etigoel You also need to update the PR description to include the issue number.
> > 
> > 
> > For this I am using git commit -m "message" -m "message". Do we need to something else.
> 
> @etigoel You need to do this in github go to this PR description and edit
> ![image](https://user-images.githubusercontent.com/54740946/103682302-b684ea80-4fae-11eb-87bb-08a8f6cb1412.png)

Done.. Thanks

2021-01-06 08:35 UTC, rt4914 approved these changes
LGTM, thanks.

2021-01-06 08:35 UTC, merged