Fix #150: Lowfi text input interaction view part 1
oppia/oppia-android pull request #240
Opened 2019-10-16 11:47 UTC by nikitamarysolomanpvt

Replicated from #190

## Explanation
Part 1: This PR contains Text input view and it Fix  #150  .

## Reference Mock
https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/4d4e4bd8-3755-41fc-bf83-3dcff5d5eee1/Lesson-1-a-ii-Exploration-Player-Text-Input-No-Ans
https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/eeed0f6c-54ca-4371-ab23-5199abd87f28/Lesson-1-a-ii-Exploration-Player-Text-Input-Keyboa

## Reference Design Doc
https://docs.google.com/document/d/1QigNdZeMBy-JjHW26QH4qT0UtCyzfvW0xEaStSdY9gM/edit?usp=sharing
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is **assigned** to an appropriate reviewer.

2019-10-17 17:28 UTC, rt4914 requested changes
PTAL @nikitamarysolomanpvt

2019-10-17 17:28 UTC, rt4914 commented on app/src/main/java/org/oppia/app/activity/InputInteractionViewTestActivity.kt
> + * it contains [NumericInputInteractionView] and [TextInputInteractionView].
Nit: First character capital. `It contains ...`

2019-10-17 17:28 UTC, rt4914 commented on app/src/main/java/org/oppia/app/activity/InputInteractionViewTestActivity.kt
> +package org.oppia.app.activity
Should we keep this file in this package? I suggest shifting it to `customview` or `state`.
Basically, wherever the implementation is these test-activities should be in that only.

2019-10-17 17:28 UTC, rt4914 commented on app/src/main/java/org/oppia/app/activity/InputInteractionViewTestActivity.kt
> +    contentNumericComponent = findViewById(R.id.test_number_input_interaction_view) as NumericInputInteractionView
Prefer writing it this way:

`contentNumericComponent = findViewById(R.id.test_number_input_interaction_view)`

Ditto for next line

2019-10-17 17:28 UTC, rt4914 commented on app/src/main/java/org/oppia/app/activity/InputInteractionViewTestActivity.kt
> +      textInput = savedInstanceState.getString(KEY_TEXT_INPUT_ID)
Either make the `textInput` support null by changing line 18 to 

`private var textInput: String? = ""`

or else check that the `savedInstanceState.getString(KEY_TEXT_INPUT_ID)`  is not null.

2019-10-17 17:28 UTC, rt4914 commented on app/src/main/java/org/oppia/app/activity/InputInteractionViewTestActivity.kt
> +      textInput = savedInstanceState.getString(KEY_TEXT_INPUT_ID)
Ditto for numericInput

2019-10-17 17:28 UTC, rt4914 commented on app/src/main/java/org/oppia/app/customview/inputInteractionView/TextInputInteractionView.kt
> +    setLongClickable(false)
Update this to `isLongClickable = false`

2019-10-17 17:28 UTC, rt4914 commented on app/src/main/java/org/oppia/app/customview/inputInteractionView/TextInputInteractionView.kt
> +    if (text.isEmpty()) {
Simplify this to:

`return if (text.isEmpty()) {
      InteractionObject.newBuilder().build()
    } else {
      InteractionObject.newBuilder().setReal(text.toString().toDouble()).build()
    }`


As suggested earlier, prefer solving as many warnings as possible in Android Studio itself.

2019-10-17 17:28 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/activity/InputInteractionViewTestActivityTest.kt
> +class InputInteractionViewTestActivityTest {
Can only check these test-cases once @jamesxu0 PR on #241 is merged in develop.

2019-10-25 09:07 UTC, nikitamarysolomanpvt commented
Duplicate of this is #246 created due to change in approach

2019-10-25 09:07 UTC, closed without merging