Fix #2408 : Resolved ktlint max line in topic test package
oppia/oppia-android pull request #2428
Opened 2021-01-07 11:55 UTC by varunvjha

## Explanation

Fixes #2408 : Removed ' // ktlint-disable max-line-length ' and fixed the functions name under 100 char length.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-01-07 14:26 UTC, rt4914 requested changes
Great work. Suggested few changes.

2021-01-07 14:26 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt
> +  fun testCCFragment_openDialogFragment0_checkSkillAndExplanationDisplayedWithoutRichText() {
Alternate suggestion which works just by removing `Fragment`

`fun testConceptCard_openDialog0_checkSkillAndExplanationAreDisplayedWithoutRichText() {`

2021-01-07 14:26 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt
> +  fun testCCFragment_openDialogFragment0_checkSkillAndExplanationDisplayedWithoutRichText() {
Same things applies for this entire file?

2021-01-07 14:26 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt
> +  fun testLessonsPlayFragment_clickExpandListIconIndex1then2_chapterListForIndex1NotDisplayed() {
Its nice but the `T` should be capital in `1then2`.

`testLessonsPlayFragment_clickExpandListIconIndex1Then2_chapterListForIndex1NotDisplayed `

2021-01-07 14:26 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt
> +  fun testLessonsPlayFragment_clickExpandListIconIndex1then2_chapterListForIndex1NotDisplayed() {
Ditto at other places.

2021-01-07 14:26 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt
> +import org.oppia.android.app.topic.revisioncard.RevisionCardActivity.Companion.createRevisionCardActivityIntent
This change won't work. You can fix this by removing the import and using
`RevisionCardActivity.createRevisionCardActivityIntent(` everywhere to fix the error.

2021-01-07 14:26 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt
> +  fun testRevCardTestActivity_fractionSubtopicId1_checkReturnToTopicButtonDispSuccessfully() {
Instead of `testRevisionCardTestActivity` use `testRevisionCard` to fix this.

2021-01-07 14:43 UTC, varunvjha commented
@rt4914 Made the requested changes. PTAL.

2021-01-08 10:03 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt
> +  fun testRevCardTestActivity_fractionSubtopicId1_checkReturnToTopicButtonDispSuccessfully() {
@varunvjha Always reply to these comments.

2021-01-08 10:03 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt
> +import org.oppia.android.app.topic.revisioncard.RevisionCardActivity.Companion.createRevisionCardActivityIntent
@varunvjha Always reply to these comments.

2021-01-08 10:03 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt
> +  fun testLessonsPlayFragment_clickExpandListIconIndex1then2_chapterListForIndex1NotDisplayed() {
@varunvjha Always reply to these comments.

2021-01-08 10:03 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt
> +  fun testCCFragment_openDialogFragment0_checkSkillAndExplanationDisplayedWithoutRichText() {
@varunvjha Always reply to these comments.

2021-01-08 10:04 UTC, rt4914 approved these changes
LGTM, thanks.

2021-01-08 10:05 UTC, merged

2021-01-14 16:22 UTC, anandwana001 commented
There are some issues with this PR. @MaskedCarrot will be solving them in his pr https://github.com/oppia/oppia-android/pull/2411

2021-01-15 00:39 UTC, anandwana001 commented
@rt4914 could you please revert this pr as there many changes which need to reopen these issues.