Fix #2405 : Ktlint maxline profileprogresstest
oppia/oppia-android pull request #2444
Opened 2021-01-08 17:15 UTC by varunvjha

## Explanation

Fixes #2405  : Removed ' // ktlint-disable max-line-length ' and fixed the functions name under 100 char length.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-01-09 05:07 UTC, anandwana001 requested changes
Thanks @varunvjha 
Please apply the similar approach to other test as well and keep a consistency in naming all the fucntion names. 

Also, please update the test name in file `ProfilePictureActivityTest`

```kotlin
fun testProfilePictureActivity_userImageIsDisplayed()
```

2021-01-09 05:07 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt
> +  fun testProfileProg_openProfilePictureEditDialog_configChange_dialogIsStillOpen() {
please keep the prefix unchanged `testProfileProgressFragment`

2021-01-09 05:07 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt
> +  fun testProfileProg_openProfilePictureEditDialog_configChange_dialogIsStillOpen() {
```kotlin
fun testProfileProgressFragment_openProfilePictureEditDialog_configChange_dialogIsStillOpen()
```

2021-01-09 05:07 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt
> +  fun testProfileProgNoProg_rVItem0_checkOngoingTopicsCount_countIsZero() {
```kotlin
fun testProfileProgressFragment_noProgress_ongoingTopicCountIsZero()
```

2021-01-09 05:07 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt
> +  fun testProfileProgWithProg_rVItem0_checkOngoingTopicsCount_countIsTwo() {
```kotlin
fun testProfileProgressFragment_twoPartialStoryProgress_ongoingTopicCountIsTwo()
```

2021-01-09 05:07 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt
> +  fun testProfileProgWithProg_change_config_rVItem0_checkOngoingTopicsCount_countIsTwo() {
```kotlin
fun testProfileProgressFragment_configChange_twoPartialStoryProgress_ongoingTopicCountIsTwo()
```

2021-01-09 05:07 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt
> +  fun testProfileProgNoProg_rVItem0_checkOngoingTopicsString_descriptionIsCorrect() {
```kotlin
fun testProfileProgressFragment_noProgress_ongoingTopicDescriptionIsCorrect()
```

2021-01-10 04:18 UTC, anandwana001 commented
@varunvjha please reply to all the comment above with done or if anything needs to discuss regarding that comment.

2021-01-10 04:58 UTC, varunvjha commented
> Thanks @varunvjha 
> Please apply the similar approach to other test as well and keep a consistency in naming all the fucntion names. 
> 
> Also, please update the test name in file `ProfilePictureActivityTest`
> 
> ```kotlin
> fun testProfilePictureActivity_userImageIsDisplayed()
> ```

Done

2021-01-10 04:58 UTC, varunvjha commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt
> +  fun testProfileProg_openProfilePictureEditDialog_configChange_dialogIsStillOpen() {
> please keep the prefix unchanged `testProfileProgressFragment`

Done

2021-01-10 04:59 UTC, varunvjha commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt
> +  fun testProfileProgNoProg_rVItem0_checkOngoingTopicsCount_countIsZero() {
Done

2021-01-10 04:59 UTC, varunvjha commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt
> +  fun testProfileProgWithProg_rVItem0_checkOngoingTopicsCount_countIsTwo() {
Done

2021-01-10 04:59 UTC, varunvjha commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt
> +  fun testProfileProgWithProg_change_config_rVItem0_checkOngoingTopicsCount_countIsTwo() {
Done

2021-01-10 04:59 UTC, varunvjha commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt
> +  fun testProfileProgNoProg_rVItem0_checkOngoingTopicsString_descriptionIsCorrect() {
Done

2021-01-10 05:16 UTC, varunvjha commented
> @varunvjha please reply to all the comment above with done or if anything needs to discuss regarding that comment.

Done. PTAL.

2021-01-11 07:02 UTC, anandwana001 requested changes
Keep consistency with the `testProfileProgressFragment`

at line 186 - testProfileProgressFragment_profilePictureEditDialogIsDisplayed

at line - 251 - testProfileProgressFragment_imageSelectAvatar_configChange_checkGalleryIntent

at line 498 - testProfileProgressFragment_configChange_firstStory_storyNameIsCorrect

at line 515 - testProfileProgressFragment_firstStory_storyNameIsCorrect

at line 536 - testProfileProgressFragment_firstStory_topicNameIsCorrect

at line 557 - testProfileProgressFragment_clickFirstStory_opensTopicActivity

at line 581 - testProfileProgressFragment_clickViewAll_opensRecentlyPlayedActivity

at line 602 - testProfileProgressFragment_noProgress_topicCountIsNotClickable

at line 618 - testProfileProgressFragment_noProgress_storyCountIsNotClickable

at line 634 - testProfileProgressFragment_configChange_noProgress_storyCountIsNotClickable

at line 652 - testProfileProgressFragment_clickTopicCount_opensOngoingTopicListActivity

at line 684 - testProfileProgressFragment_clickStoryCount_opensCompletedStoryListActivity

2021-01-12 00:05 UTC, anandwana001 requested changes
testProfileProgressFragment_configurationChange_checkProfileName_profileNameIsCorrect
use -> `configChange`

testProfileProgressFragment_changeConfig_checkOngoingTopicDescriptionIsCorrect
use -> `configChange`

testProfileProgress_twoPartialStoryProgress_checkCompletedStoriesDescriptionIsCorrect
use -> `testProfileProgressFragment` 
is it doesn't comes in 100 char let me know

2021-01-12 07:24 UTC, varunvjha commented
Made requested changes. PTAL @anandwana001

2021-01-12 07:51 UTC, anandwana001 commented
```diff
- testProfileProgressFragment_twoPartialStoryProgress_checkCompletedStoriesDescriptionIsCorrect
+ testProfileProgressFragment_twoPartialStoryProgress_completedStoriesDescriptionIsCorrect

- testProfileProgressFragment_twoPartialStoryProgress_checkOngoingTopicDescriptionIsCorrect
+ testProfileProgressFragment_twoPartialStoryProgress_ongoingTopicDescriptionIsCorrect

- testProfileProgressFragment_configChange_checkOngoingTopicDescriptionIsCorrect
+ testProfileProgressFragment_configChange_ongoingTopicDescriptionIsCorrect

- testProfileProgressFragment_noProgress_checkCompletedStoriesCountIsZero
+ testProfileProgressFragment_noProgress_completedStoriesCountIsZero

- testProfileProgressFragment_twoPartialStoryProgress_checkCompletedStoriesCountIsTwo
+ testProfileProgressFragment_twoPartialStoryProgress_completedStoriesCountIsTwo

- testProfileProgressFragment_noProgress_completedStoriesDescriptionIsCorrect
+ testProfileProgressFragment_noProgress_completedStoriesDescriptionIsCorrect
```

2021-01-12 07:52 UTC, anandwana001 requested changes

2021-01-12 07:52 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt
> +  fun testProfileProgressFragment_twoPartialStoryProgress_checkCompletedStoriesDescriptionIsCorrect() {
```diff
- testProfileProgressFragment_twoPartialStoryProgress_checkCompletedStoriesDescriptionIsCorrect
+ testProfileProgressFragment_twoPartialStoryProgress_completedStoriesDescriptionIsCorrect

- testProfileProgressFragment_twoPartialStoryProgress_checkOngoingTopicDescriptionIsCorrect
+ testProfileProgressFragment_twoPartialStoryProgress_ongoingTopicDescriptionIsCorrect

- testProfileProgressFragment_configChange_checkOngoingTopicDescriptionIsCorrect
+ testProfileProgressFragment_configChange_ongoingTopicDescriptionIsCorrect

- testProfileProgressFragment_noProgress_checkCompletedStoriesCountIsZero
+ testProfileProgressFragment_noProgress_completedStoriesCountIsZero

- testProfileProgressFragment_twoPartialStoryProgress_checkCompletedStoriesCountIsTwo
+ testProfileProgressFragment_twoPartialStoryProgress_completedStoriesCountIsTwo

- testProfileProgressFragment_noProgress_completedStoriesDescriptionIsCorrect
+ testProfileProgressFragment_noProgress_completedStoriesDescriptionIsCorrect
```

2021-01-12 08:13 UTC, anandwana001 approved these changes
LGTM

2021-01-12 08:25 UTC, rt4914 approved these changes
LGTM, thanks.

2021-01-12 08:25 UTC, merged