Added RTL support in Reading Display Size
oppia/oppia-android pull request #2448
Opened 2021-01-10 17:01 UTC by harsh-hash

## Explanation

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-01-10 17:20 UTC, FareesHussain commented
@harsh-hash please add screenshots in the description

2021-01-10 17:37 UTC, harsh-hash commented
![Screenshot_1610300116](https://user-images.githubusercontent.com/60041954/104130769-a26b2f80-5398-11eb-8d36-a8707602a232.png)
![Screenshot_1610300163](https://user-images.githubusercontent.com/60041954/104130772-a4cd8980-5398-11eb-9f7a-800d3540fa11.png)

2021-01-10 17:48 UTC, FareesHussain requested changes
@harsh-hash looks good but i recommend to add `layoutDirection="locale"`
only for the contraintLayout with seek bar

2021-01-10 17:48 UTC, FareesHussain commented on app/src/main/res/layout-land/reading_text_size_fragment.xml
> +    android:layoutDirection="locale">
Revert this and add in the `line :72`

2021-01-10 17:48 UTC, FareesHussain commented on app/src/main/res/layout-sw600dp/reading_text_size_fragment.xml
> +    android:layoutDirection="locale">
Revert this and add in the `line :42`

2021-01-10 17:48 UTC, FareesHussain commented on app/src/main/res/layout/reading_text_size_fragment.xml
> +    android:layoutDirection="locale">
Revert this and add in the `line :66`

2021-01-10 17:50 UTC, FareesHussain commented
Also update PR title to `Fix #2269: Added....`
and Add `Fixes #2269` in the Explanation

2021-01-10 18:20 UTC, FareesHussain requested changes
@harsh-hash NIT changes requied this needs reformatting, I recommend you to use [macros](https://github.com/oppia/oppia-android/wiki/Ktlint-Guide#macros) for reformatting

2021-01-10 18:33 UTC, FareesHussain approved these changes
LGTM, thanks

2021-01-10 18:53 UTC, FareesHussain commented
Tests need to be re-run

2021-01-11 15:31 UTC, rt4914 approved these changes
LGTM, thanks.

2021-01-11 15:41 UTC, rt4914 requested changes
Have you tried following these steps? https://github.com/oppia/oppia-android/wiki/RTL-Guidelines

For me on develop it does work correctly without any change.

![Screenshot_1610379642](https://user-images.githubusercontent.com/9396084/104202949-92635680-5451-11eb-8701-fdf3db8e61b7.png)

2021-01-11 16:06 UTC, FareesHussain commented
@rt4914 Yes this works correctly in develop

2021-01-11 16:10 UTC, harsh-hash commented
I have not sure about this issue, tried various things , and the first thing that worked, I thought that was the solution.

2021-01-11 18:06 UTC, FareesHussain commented
> I have not sure about this issue, tried various things , and the first thing that worked, I thought that was the solution.

@harsh-hash thats great, We generally use layoutDirection="locale" to solve RTL related issues but as this was already fixed, it needs to be closed 

@rt4914 This can be closed

2021-01-11 18:09 UTC, closed without merging