Fix Issue #2463: remove textdirection property from textInputLayout
oppia/oppia-android pull request #2470
Opened 2021-01-13 17:27 UTC by alwin48

## Explanation

Fixes #2463: Removed android:textDirection='locale' in TextInputLayout from layout/profile_reset_pin_activity and layout-land/profile_reset_pin_activity

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-01-13 18:24 UTC, FareesHussain requested changes
PTAL

2021-01-13 18:24 UTC, FareesHussain commented on .idea/gradle.xml
> +        <option name="useQualifiedModuleNames" value="true" />
Please revert this

2021-01-14 08:16 UTC, alwin48 commented on .idea/gradle.xml
> +        <option name="useQualifiedModuleNames" value="true" />
Okay, I will do that.

2021-01-14 08:24 UTC, FareesHussain approved these changes
LGTM, thanks

2021-01-15 00:41 UTC, anandwana001 commented
@alwin48 please correct the pr title as per the first point in the checklist.

2021-01-15 03:55 UTC, alwin48 commented
> @alwin48 please correct the pr title as per the first point in the checklist.

Done.

2021-01-15 07:56 UTC, rt4914 approved these changes
LGTM, thanks.

2021-01-15 07:56 UTC, merged