Remove textDirection property from reset_pin_dialog
oppia/oppia-android pull request #2475
Opened 2021-01-14 14:55 UTC by arhamathar

## Explanation

Fixes #2464:  Remove android:textDirection="locale" from textInputLayout from the following files
        layout/reset_pin_dialog
        layout-land/reset_pin_dialog

## Checklist

- [x ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [  ] The PR is made from a branch that is up-to-date with "develop".
- [x ] The PR's branch is based on "develop" and not on any other branch.
- [x ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-01-14 15:12 UTC, FareesHussain requested changes
@arhamathar LGTM, please update the title to 
`Fix #2464: Remove textDirection property from reset_pin_dialog`
and in the check list remove the space after `x` in the brackets

2021-01-14 15:19 UTC, arhamathar commented
> @arhamathar LGTM, please update the title to
> `Fix #2464: Remove textDirection property from reset_pin_dialog`
> and in the check list remove the space after `x` in the brackets

Done !

2021-01-14 15:20 UTC, FareesHussain commented
The tests need to be re-run

2021-01-14 15:21 UTC, FareesHussain approved these changes
LGTM, thanks

2021-01-15 07:53 UTC, rt4914 approved these changes
LGTM, thanks.

2021-01-15 07:53 UTC, merged