Fix #2326: Changes in Views inside Practice Tab [A11y]
oppia/oppia-android pull request #2525
Opened 2021-01-20 14:01 UTC by Mehul-Bisht

## Explanation

Fixes #2326: Changes in Views inside Practice Tab [A11y]
Fixed issue with checkbox accessibility for all layouts

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-01-20 14:03 UTC, Mehul-Bisht commented
@rt4914 @FareesHussain please review my PR and notify about any improvements related to checkboxes

2021-01-20 14:25 UTC, ARJUPTA commented
@Mehul-Bisht the topic_practice_header_view.xml does not need to be changed as the START button resides in topic_practice_footer_view.xml

2021-01-20 14:29 UTC, Mehul-Bisht commented
> @Mehul-Bisht the topic_practice_header_view.xml does not need to be changed as the START button resides in topic_practice_footer_view.xml

Yes I know, but the reason why I reduced padding at the bottom for the header was that I made changes to padding of the topic_practice_subtopic. So now the subtopic items have more padding at the top so the header doesn't need as much padding on the bottom as it had before. May I attach a screenshot to show the changes?

2021-01-20 14:31 UTC, ARJUPTA commented
> > @Mehul-Bisht the topic_practice_header_view.xml does not need to be changed as the START button resides in topic_practice_footer_view.xml
> 
> Yes I know, but the reason why I reduced padding at the bottom for the header was that I made changes to padding of the topic_practice_subtopic. So now the subtopic items have more padding at the top so the header doesn't need as much padding on the bottom as it had before. May I attach a screenshot to show the changes?

Yes, also attach the screenshots for before the changes and of passing scans

2021-01-20 14:41 UTC, Mehul-Bisht commented
**Before** changes screenshots are already shown here: https://github.com/oppia/oppia-android/issues/2326

**After** changes the scans for:

**Portrait Mode:** 

![portrait](https://user-images.githubusercontent.com/65572088/105189813-5ae46080-5b5b-11eb-98f8-07ec7ce67796.png)

**Landscape Mode:** 

![land_bottom](https://user-images.githubusercontent.com/65572088/105190005-93843a00-5b5b-11eb-9b34-714adf472335.png)
![land_top](https://user-images.githubusercontent.com/65572088/105190012-954dfd80-5b5b-11eb-85d2-d0164722f03c.png)

2021-01-20 15:21 UTC, ARJUPTA commented
@Mehul-Bisht you have done a good work . Even if we have solved the issue this way, but we don't want the UI to change drastically.
|Before|After|
|:-:|:-:|
|![Screenshot_1611155272](https://user-images.githubusercontent.com/64064110/105195629-d268be80-5b60-11eb-8e35-c209751868df.png)|![Screenshot_1611155350](https://user-images.githubusercontent.com/64064110/105195633-d399eb80-5b60-11eb-8a6f-849ee471032c.png)|

You must try keeping the `topic_practice_header_view` to be unchanged along with aligning the checkboxes to be `start|top `instead of `start|bottom`

2021-01-20 15:28 UTC, Mehul-Bisht commented
Ok I will update it soon.

2021-01-20 16:00 UTC, Mehul-Bisht commented
@ARJUPTA I have now made the specified changes in all practice tab layout files. Kindly review.

2021-01-21 05:09 UTC, ARJUPTA commented
> @ARJUPTA I have now made the specified changes in all practice tab layout files. Kindly review.

Thanks @Mehul-Bisht , nit changes 
- Edit the title to be `Fixes Part of #2326` as you have not worked on complete Issue 
- Attach some Screenshots in the PR description like below 

@rt4914 Rest everything LGTM. 

| Before | After | Scan |
|:-:|:-:|:-:|
|![Screenshot_1611155272](https://user-images.githubusercontent.com/64064110/105282203-d255d680-5bd3-11eb-859b-5265b296cbf6.png) |  ![Screenshot_1611205113](https://user-images.githubusercontent.com/64064110/105282208-d4b83080-5bd3-11eb-80d2-41853158c476.png) | ![Screenshot_1611205191](https://user-images.githubusercontent.com/64064110/105282212-d681f400-5bd3-11eb-9a19-a12e5688398c.png) |

2021-01-21 05:44 UTC, ARJUPTA commented
@rt4914 while testing this for landscape mode, I encountered another issue

|||
|:-:|:-:|
|![Screenshot_1611207456](https://user-images.githubusercontent.com/64064110/105284920-64141280-5bd9-11eb-903c-5540f06d72e5.png)|![Screenshot_1611207443](https://user-images.githubusercontent.com/64064110/105285026-958cde00-5bd9-11eb-91b5-7bd9b5060367.png)|

I think this is because of the drop-shadow view, I tried to set it not important for accessibility but still the checks failed at this giving wrong indication about contrast issue in checkbox.

2021-01-21 10:00 UTC, rt4914 commented
> @rt4914 while testing this for landscape mode, I encountered another issue
> 
> ![Screenshot_1611207456](https://user-images.githubusercontent.com/64064110/105284920-64141280-5bd9-11eb-903c-5540f06d72e5.png)	![Screenshot_1611207443](https://user-images.githubusercontent.com/64064110/105285026-958cde00-5bd9-11eb-91b5-7bd9b5060367.png)
> I think this is because of the drop-shadow view, I tried to set it not important for accessibility but still the checks failed at this giving wrong indication about contrast issue in checkbox.

@ARJUPTA File an issue mentioning how to reproduce this and we will have a look. Thanks.

2021-01-21 10:05 UTC, rt4914 commented
@Mehul-Bisht Update your PR description to
`Fixes part of #2326: Changes in Views inside Practice Tab [A11y]`
Otherwise the entire issue will get closed.

2021-01-21 10:14 UTC, rt4914 requested changes
Really nice work @Mehul-Bisht . Suggested one nit change.

2021-01-21 10:14 UTC, rt4914 commented on app/src/main/res/layout/topic_practice_subtopic.xml
>        android:minHeight="22dp"
You can remove `minHeight` from all files fo this view because as we are adding padding bottom the minHeight attribute is of no use now.

2021-01-21 12:09 UTC, Mehul-Bisht commented
@rt4914 @ARJUPTA I have made the changes to the PR title, description and minHeight attribute now, please review again.

2021-01-21 15:59 UTC, rt4914 approved these changes
LGTM, thanks.

2021-01-21 15:59 UTC, merged

2021-01-24 16:41 UTC, ARJUPTA commented
@Mehul-Bisht and @rt4914 are you facing this issue on a Tablet ?
|||
|:-:|:-:|
|![Screenshot_1611506427](https://user-images.githubusercontent.com/64064110/105636989-03aefa80-5e91-11eb-8bf4-fb7d073672c0.png) | ![Screenshot_1611506115](https://user-images.githubusercontent.com/64064110/105636913-969b6500-5e90-11eb-9d6d-8ef765439660.png) |

2021-01-24 19:28 UTC, Mehul-Bisht commented
@ARJUPTA I could not test it with a tablet since my device doesn't run emulators that well. I tried to select an appropriate value for the tablet layout.

2021-01-25 04:37 UTC, ARJUPTA commented
> @ARJUPTA I could not test it with a tablet since my device doesn't run emulators that well. I tried to select an appropriate value for the tablet layout.

It's okay . For future PR mention the tests you have done on your side.