Fixes part of #2314: Changes in Numeric Input Interaction Item[a11y]
oppia/oppia-android pull request #2548
Opened 2021-01-23 17:39 UTC by ARJUPTA

## Explanation

Fixes part of #2314 
Tried setting 1dp stroke of blue color instead of blue shadow. This solved the contrast issue but deformed the Text Input Layout.
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-01-23 17:52 UTC, ARJUPTA commented
@rt4914 I think it is because of the change in the space occupied by background drawable. I tried setting the `android:gravity="center_vertical"` for numeric_input_interaction view but it still no effect

2021-01-23 19:04 UTC, rt4914 commented
Will check this on Monday. Thanks.

2021-01-25 15:40 UTC, rt4914 commented
The `XX_interaction_item` contains `paddingBottom` just remove that and it should work.
Note: XX means `fraction`, `numeric_input`, `text_input`, or anything in general which uses this file.

Also, because of these changes the `shadow` effect is almost completely gone and looks like a simple border so will need to improve on that part. Thanks.

2021-01-26 12:06 UTC, ARJUPTA commented
> The `XX_interaction_item` contains `paddingBottom` just remove that and it should work.
> Note: XX means `fraction`, `numeric_input`, `text_input`, or anything in general which uses this file.
> 
> Also, because of these changes the `shadow` effect is almost completely gone and looks like a simple border so will need to improve on that part. Thanks.

Yes it did worked out. This is the new UI after removing bottom padding and blue shadow. Scans are also passed for it. 

|After Changes|Tests|
|:-:|:-:|
|![Screenshot_1611662464](https://user-images.githubusercontent.com/64064110/105842789-c2d3f480-5ffc-11eb-91ce-a94cc99ce55a.png)|![Screenshot_1611662494](https://user-images.githubusercontent.com/64064110/105842790-c4052180-5ffc-11eb-9bd0-0a679c28c704.png)|

@rt4914 PTAL

2021-01-27 15:52 UTC, rt4914 commented
@mschanteltc Will this new UI work where the input box does not have a shadow but just a border?

2021-01-27 19:16 UTC, mschanteltc commented
> @mschanteltc Will this new UI work where the input box does not have a shadow but just a border?

I would still prefer it to have the shadow when the user taps on the input. According to this "Text input focus style" [example](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html), even if the shadow does not provide sufficient contrast, the cursor's contrast with the white background should be enough of an indicator to show that the text input is in focus. 

Would it be possible to ignore the contrast rules for this case?

2021-01-28 16:27 UTC, rt4914 requested changes
@ARJUPTA Try this: https://gist.github.com/rt4914/19e8f5005c8ee26933aa0e17cc44c248

2021-01-28 16:47 UTC, ARJUPTA commented
|After Suggested change| Tests |
|:-:|:-:|
|![Screenshot_1611852226](https://user-images.githubusercontent.com/64064110/106170367-5f8dc200-61b6-11eb-86b2-53f8d406b1ac.png)|![Screenshot_1611852235](https://user-images.githubusercontent.com/64064110/106170358-5e5c9500-61b6-11eb-981c-1e50377ddf3f.png)

@mschanteltc after what @rt4914 suggested the scans pass for this too and also the UI isn't much changed. Can we go with this?

2021-01-28 17:23 UTC, rt4914 commented
@ARJUPTA Can you please update the code as per https://github.com/oppia/oppia-android/pull/2548#pullrequestreview-578514487

2021-01-28 17:32 UTC, ARJUPTA commented
> @ARJUPTA Can you please update the code as per [#2548 (review)](https://github.com/oppia/oppia-android/pull/2548#pullrequestreview-578514487)

Done

2021-01-28 18:14 UTC, mschanteltc commented
> @mschanteltc this is after what @rt4914 suggested, the scans pass for this too and also the UI isn't much changed. Can we go with this?

Yes this looks great! Let's go with this.

2021-01-28 20:34 UTC, rt4914 requested changes
@ARJUPTA One nit change.

2021-01-28 20:34 UTC, rt4914 commented on app/src/main/res/drawable/edit_text_background_shadow.xml
> +</layer-list>
EOF is missing.

2021-01-29 04:32 UTC, ARJUPTA commented on app/src/main/res/drawable/edit_text_background_shadow.xml
> +</layer-list>
done

2021-01-29 15:55 UTC, rt4914 approved these changes
LGTM, thanks.

2021-01-29 15:55 UTC, merged