Fix 2282 added RTL Support to topic lessons tab
oppia/oppia-android pull request #2549
Opened 2021-01-23 18:10 UTC by priyanka0906

## Explanation
fixes #2282 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

Mobile Portrait | Mobile Landscape
------------ | -------------
![Screenshot_1611394972](https://user-images.githubusercontent.com/56197993/105597298-f115c200-5db9-11eb-9180-e74c58541d3b.png)|![Screenshot_1611413644](https://user-images.githubusercontent.com/56197993/105597410-f8d56680-5db9-11eb-856d-a4ec8768a2d2.png)

2021-01-23 18:28 UTC, FareesHussain requested changes
@priyanka0906 Added few suggestions also add screenshots before this implementation for better review

2021-01-23 18:28 UTC, FareesHussain commented on app/src/main/java/org/oppia/android/app/customview/SegmentedCircularProgressView.kt
> +import java.util.*
Wildcard import ktlint error
```suggestion
import java.util.Locale
```

2021-01-23 18:28 UTC, FareesHussain commented on app/src/main/java/org/oppia/android/app/customview/SegmentedCircularProgressView.kt
> +      rotationY=180f
```suggestion
    if (isRTL)
      rotationY = 180f
```

2021-01-23 19:03 UTC, rt4914 commented
Apart from what @FareesHussain has suggestion update your title to
`Fix #2282: Added RTL Support to topic lessons tab`

2021-01-24 03:21 UTC, priyanka0906 commented
> @priyanka0906 Added few suggestions also add screenshots before this implementation for better review

screenshots of the code??

2021-01-24 07:26 UTC, FareesHussain commented
> > @priyanka0906 Added few suggestions also add screenshots before this implementation for better review
> 
> screenshots of the code??

No. Screenshot of the layout without your implementation and screenshot of the layout with your implementation to compare the changes

2021-01-24 07:33 UTC, priyanka0906 commented
> > > @priyanka0906 Added few suggestions also add screenshots before this implementation for better review
> > 
> > 
> > screenshots of the code??
> 
> No. Screenshot of the layout without your implementation and screenshot of the layout with your implementation to compare the changes

okay

2021-01-24 13:51 UTC, priyanka0906 commented
> > > > @priyanka0906 Added few suggestions also add screenshots before this implementation for better review
> > > 
> > > 
> > > screenshots of the code??
> > 
> > 
> > No. Screenshot of the layout without your implementation and screenshot of the layout with your implementation to compare the changes
> 
> okay

is it fine now?

2021-01-24 13:51 UTC, priyanka0906 commented
> Apart from what @FareesHussain has suggestion update your title to
> `Fix #2282: Added RTL Support to topic lessons tab`

done

2021-01-24 13:54 UTC, priyanka0906 commented on app/src/main/java/org/oppia/android/app/customview/SegmentedCircularProgressView.kt
> +      rotationY=180f
done

2021-01-24 13:54 UTC, priyanka0906 commented on app/src/main/java/org/oppia/android/app/customview/SegmentedCircularProgressView.kt
> +import java.util.*
@FareesHussain  done

2021-01-24 15:36 UTC, FareesHussain approved these changes
LGTM, thanks

2021-01-25 15:31 UTC, rt4914 approved these changes
LGTM, thanks.

2021-01-25 15:31 UTC, merged