Fix #2602 Using String from strings.xml
oppia/oppia-android pull request #2605
Opened 2021-02-03 13:05 UTC by kartikeysaran

## Explanation
Fixes #2602 
Previously hard-coded string was used .

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-02-03 13:15 UTC, rt4914 commented
@kartikeysaran Update title to:
`Fix #2602: Using String from strings.xml`

2021-02-03 13:20 UTC, kartikeysaran commented
> @kartikeysaran Update title to:
> `Fix #2602: Using String from strings.xml`

Okay

2021-02-03 13:21 UTC, kartikeysaran commented
@rt4914  Why does it fails Robolectric Tests (Non-App Module) ?

2021-02-03 13:36 UTC, FareesHussain requested changes
@kartikeysaran This is the reason behind the failing test case. 

As this is a single file change please make sure you don't include the automatic changes made by android studio (in files `misc.xml` or `Project.xml`) in the commit.

2021-02-03 13:36 UTC, FareesHussain commented on app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsFragmentTest.kt
> +          withText("R.string.my_downloads")
```suggestion
          withText(R.string.my_downloads)
```

2021-02-03 14:21 UTC, kartikeysaran commented
> @kartikeysaran This is the reason behind the failing test case.
> 
> As this is a single file change please make sure you don't include the automatic changes made by android studio (in files `misc.xml` or `Project.xml`) in the commit.

Thankyou @FareesHussain . From next time I would make sure I don't commit this error

2021-02-03 15:06 UTC, rt4914 approved these changes
LGTM, thanks.

2021-02-03 15:06 UTC, rt4914 commented
> @kartikeysaran Update title to:
> `Fix #2602: Using String from strings.xml`

@kartikeysaran This change is still pending. You can edit the PR title to fix this.

2021-02-04 01:18 UTC, FareesHussain approved these changes
LGTM.

2021-02-04 09:03 UTC, kartikeysaran commented
> > @kartikeysaran Update title to:
> > `Fix #2602: Using String from strings.xml`
> 
> @kartikeysaran This change is still pending. You can edit the PR title to fix this.

Sorry For Delay , Changed the title

2021-02-05 21:06 UTC, rt4914 approved these changes
LGTM, thanks.

2021-02-05 21:06 UTC, merged