#2403 fixed ktlint max length in player package
oppia/oppia-android pull request #2640
Opened 2021-02-05 19:48 UTC by som23ya

## Explanation

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-02-05 19:52 UTC, prayutsu commented on app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
>    @Test
You also need to remove these TODOs.

2021-02-05 19:55 UTC, prayutsu requested changes
@som23ya Please fix the title of the PR to follow our PR guidelines, it should match the format `Fix #issueNumber: Title of the PR`.
Also please add the `Fixes #issueNumber` keyword in the PR explanation to link the corresponding issue.

2021-02-05 20:06 UTC, som23ya commented
> @som23ya Please fix the title of the PR to follow our PR guidelines, it should match the format `Fix #issueNumber: Title of the PR`.
> Also please add the `Fixes #issueNumber` keyword in the PR explanation to link the corresponding issue.

Thanks for helping on that, it had slipped my mind. :D

2021-02-06 03:37 UTC, anandwana001 requested changes
Thanks @som23ya 
left a comment

2021-02-06 03:37 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
> +  fun testAudWithCell_openRatioExp_clickAudIcon_changeConfig_checkOpensCellAudDialog() {
this is doesn't sounds good `testAudWithCell`

`testAudioWithCellular_ratioExp_audioIcon_configChange_opensCellAudioDialog`
Let me know if this works, and also keep consistency with `configChange` everywhere.

2021-02-06 03:37 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
> +  fun testAudWithCell_openRatioExp_clickAudIcon_changeConfig_checkOpensCellAudDialog() {
follow a similar pattern with others as well.

2021-02-06 03:39 UTC, anandwana001 commented
please complete all the installations steps:
https://github.com/oppia/oppia-android/wiki#installation

ktlint Guide for any reference - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide

2021-02-13 00:42 UTC, anandwana001 commented
any update on this @som23ya ?

2021-02-14 04:37 UTC, anandwana001 commented
Closing this PR as no further update.

2021-02-14 04:37 UTC, closed without merging