Fix #1839: Fixed overlapping progressbar and hint bulb
oppia/oppia-android pull request #2688
Opened 2021-02-11 14:04 UTC by aishapervin

## Explanation
Fixes #1839
i am adding a constraint from `progressbar` to` hints_and_solution_fragments_container` to solve this issue.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-02-11 14:14 UTC, aishapervin commented
@rt4914 please check.

2021-02-11 14:17 UTC, FareesHussain approved these changes
LGTM, thanks.

2021-02-11 14:20 UTC, anandwana001 commented
Can we try one thing here: 
Write a test case with `isCompletlyDisplayed()` and see if it passes with current fix and fail without fix. 
Just a suggestion if it works out.

2021-02-11 15:42 UTC, rt4914 requested changes
@aishapervin Nice work. Just one nit change suggested.

2021-02-11 15:42 UTC, rt4914 commented on app/src/main/res/layout/question_player_fragment.xml
> +      <FrameLayout
Add one blank line above this.

2021-02-11 16:26 UTC, aishapervin commented on app/src/main/res/layout/question_player_fragment.xml
> +      <FrameLayout
done.

2021-02-12 09:26 UTC, rt4914 approved these changes
LGTM, thanks.

2021-02-12 09:26 UTC, merged