Fix #2681: Remove onboarding_java_proto_lite export
oppia/oppia-android pull request #2701
Opened 2021-02-12 10:55 UTC by Sparsh1212

## Explanation

Fixes #2681: Remove onboarding_java_proto_lite export from the model library.
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-02-12 10:56 UTC, Sparsh1212 commented
@fsharpasharp PTAL.

2021-02-13 11:37 UTC, Sparsh1212 commented
@BenHenning Can you please update the branch here also so as to retrigger the build just like in the case of [#2673 ](https://github.com/oppia/oppia-android/pull/2699)

2021-02-14 01:25 UTC, anandwana001 requested changes
Bazel lint fix.

2021-02-14 01:25 UTC, anandwana001 commented on model/BUILD.bazel
> +    visibility = ["//visibility:public"],
Bazel lint error, Fix like this.  

```
java_lite_proto_library(
    name = "onboarding_java_proto_lite",
    visibility = ["//visibility:public"],
    deps = [":onboarding_proto"],
)
```

2021-02-14 04:23 UTC, anandwana001 requested changes

2021-02-14 04:23 UTC, anandwana001 commented on model/BUILD.bazel
> +    deps = [":onboarding_proto"],
there is whitespace at the end of this failing with causing the failure

<img width="435" alt="Screenshot 2021-02-14 at 09 52 46" src="https://user-images.githubusercontent.com/25057618/107868441-69980c00-6eaa-11eb-9f8a-ec082c312a2f.png">

2021-02-14 11:58 UTC, Sparsh1212 commented
@anandwana001 I have made the lint fixes and the build checks have also passed successfully. PTAL

2021-02-14 12:33 UTC, fsharpasharp approved these changes

2021-02-14 23:21 UTC, anandwana001 approved these changes
Bazel Lint fix LGTM

2021-02-24 06:55 UTC, BenHenning approved these changes
Thanks @Sparsh1212! LGTM.

2021-02-24 07:57 UTC, merged