Fix part of #2684: Update CODE_OF_CONDUCT.md
oppia/oppia-android pull request #2770
Opened 2021-02-23 17:03 UTC by BenHenning

Fix part of #2684.

This is updating the code of conduct to exactly match the template GitHub expects so that it shows up as completed on the community profile. See https://github.community/t/code-of-conduct-is-present-in-repo-but-insights-community-tab-doesnt-detect-it/1534/7 for context.

2021-02-23 17:04 UTC, BenHenning commented
@seanlip sending this your way to get your thoughts since it seems you were the one that customized the code of conduct in the first place.

Please do not consider this urgent.

2021-02-24 04:23 UTC, seanlip requested changes
Not worth fixing in this way, IMO. I suggest sending an email to GitHub support to let them know, similar to what was suggested in the linked thread.

For what it's worth, the oppia/oppia repo used to have all the boxes ticked, but I just checked and the ones for README, CODE_OF_CONDUCT and CONTRIBUTING are now unticked. I'm not sure what disqualifies our README from being a README. I think this is more just an issue on GitHub's end, and we shouldn't be changing our docs just to fix that.

2021-02-24 04:25 UTC, seanlip commented
Actually, scratch the first paragraph, I misread the thread and only looked at the last few comments.

That said, my thoughts in the second paragraph remain unchanged. How do you feel about it?

2021-02-24 04:30 UTC, seanlip commented
OK, successive visits to the oppia/oppia community profile show the following (without me changing anything):

![Screenshot from 2021-02-23 20-27-32](https://user-images.githubusercontent.com/10575562/108947669-c5cefe80-7615-11eb-99f0-6b32e54633f3.png)

![Screenshot from 2021-02-23 20-27-43](https://user-images.githubusercontent.com/10575562/108947672-c798c200-7615-11eb-86c5-df13bcf1dbf8.png)

An earlier visit also only showed the README, code of conduct and contributing being empty, with "pull request template" being ticked. I haven't changed anything between successive visits.

So my opinion is that their community profile page is seriously buggy and we shouldn't put too much stock into it. (For the record, oppia/oppia _does_ have a pull request template.)

2021-02-24 05:33 UTC, BenHenning commented
@seanlip this is a known issue: https://github.community/t/community-profile-items-not-recognized/160414 for most of the items, but per https://github.community/t/code-of-conduct-is-present-in-repo-but-insights-community-tab-doesnt-detect-it/1534/2 it seems like GitHub is specifically designed to do an exact match on the code of conduct. Did Oppia web have all the boxes checked after December 2018 (the date of that post)? If so then I'm inclined to believe this is the first issue & am happy to close this, otherwise if we're unsure then I'd expect it to be happy after updating the code of conduct to match.

Also happy with waiting until the first issue is fixed before revisiting this. Any preference?

2021-02-24 05:38 UTC, seanlip commented
Pretty sure we did have all the boxes checked the last time I looked at it, but I think that was around end-2018 so it might have been before Dec 2018.

But it's more the principle of the thing, tbh. I don't want to change our docs to satisfy an arbitrary checklist, especially one that is kind of buggy. That seems like gamification working in a negative way. Unless that checklist has actual impact somewhere?

2021-02-24 06:36 UTC, BenHenning commented
Hmm, I am unsure how important fulfilling that list is. I couldn't find a satisfactory answer when I was digging into it, so I'm trying it more as a "project health" measure. Unfortunately, the way it appears is it almost seems like we don't have a code of conduct at all which seems wrong to me. I agree with the principle you're mentioning here. I'll close this for now & revisit once the other issue is fixed. If this is still not showing up correctly, I'll raise it with GitHub staff.

2021-02-24 06:36 UTC, closed without merging