draft #2532: refactor and annotate tests in app module
oppia/oppia-android pull request #2793
Opened 2021-02-27 14:52 UTC by dipu989

Fixes #2532 (Draft): This PR aims to move the tests from `test` folder to `sharedTest` folder in their respective counterpart's folders.

Checklist for this draft - 
1) Moved all the tests to the intended folders.
2) Annotated the test's class with RunOn(TestPlatform.ROBOELECTRIC)
3) Ran all the tests locally and all of them passed.

Yet to do - 
1) Removing the Gradle/Bazel code around the app module test folder

2021-02-27 14:59 UTC, anandwana001 requested changes

2021-02-27 14:59 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/testing/administratorcontrols/AdministratorControlsFragmentTest.kt
> +
Empty line not required

2021-02-27 14:59 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/testing/administratorcontrols/AdministratorControlsFragmentTest.kt
> +
Ditto for all

2021-02-27 14:59 UTC, dipu989 commented
PTAL if the changes are the intended ones.

2021-02-27 15:00 UTC, dipu989 commented on app/src/sharedTest/java/org/oppia/android/app/testing/administratorcontrols/AdministratorControlsFragmentTest.kt
> +
Sure, will remove them.

2021-02-27 15:00 UTC, anandwana001 commented
For draft pr, use draft option of GitHub in the right side.

2021-03-03 05:01 UTC, anandwana001 requested changes
LGTM, Thanks @dipu989 

We ca move forward with the last part `Removing the Gradle/Bazel code around the app module test folder`

2021-03-03 05:39 UTC, dipu989 commented
@anandwana001 Sure, I will update the PR accordingly. Thanks!

2021-03-12 03:40 UTC, anandwana001 commented
@dipu989 please resolve the conflicts.

2021-03-13 15:02 UTC, dipu989 commented
@anandwana001 Resolved the conflicts, PTAL!
Roboelectric checks are failing.
Do I need to remove the block of `Unit Test`  [this](https://github.com/oppia/oppia-android/blob/2d8930664b86a98b16ec1d0d98c6f2742ce13baa/app/BUILD.bazel#L715) from Bazel file as they have been moved to `sharedTest` folder now?

2021-03-15 04:49 UTC, anandwana001 commented
> @anandwana001 Resolved the conflicts, PTAL!
> Roboelectric checks are failing.
> Do I need to remove the block of `Unit Test` [this](https://github.com/oppia/oppia-android/blob/2d8930664b86a98b16ec1d0d98c6f2742ce13baa/app/BUILD.bazel#L715) from Bazel file as they have been moved to `sharedTest` folder now?

I guess, yes. we need to remove this one as nothing will exist there now. Let's commit and see.

2021-03-16 16:22 UTC, dipu989 commented
@anandwana001 Committed the changes.
I have moved the file `DataBinderMapperImpl.java` from the `test` folder to `sharedTest` folder too in the recent commit.
PTAL!

2021-03-22 08:26 UTC, anandwana001 commented
@dipu989 looks like we do have checks failing. Could you check on these?

2021-03-22 08:26 UTC, anandwana001 commented
Closing this PR due to force push

2021-03-22 08:26 UTC, closed without merging

2021-03-25 08:21 UTC, dipu989 commented
@anandwana001 After updating my fork with the latest upstream, I checked out with a new branch and am cherry-picking the commits from this PR's branch. But merge conflicts are coming, which are resolved too in this same PR but with different commits.
So is there any way around so that I can cherry-pick all the commits without fixing merge conflicts again that has already been fixed?

2021-03-25 09:04 UTC, anandwana001 commented
> which are resolved too in this same PR

But, I think you cannot use the same pr or this branch as we have a force push in this branch.

2021-03-25 10:11 UTC, dipu989 commented
@anandwana001 Yes, I got this, So I was trying to create a new branch itself and cherry-pick the commis and am facing issues mentioned above. Is there any way I can cherry-pick the commits without fixing the merge commits all over again (as they are already fixed in the subsequent commits)?

2021-04-08 10:55 UTC, anandwana001 commented
@dipu989  Is it fixed now?

2021-04-09 08:31 UTC, dipu989 commented
@anandwana001 No, the issue that I stated above still persists.

2021-04-12 02:53 UTC, anandwana001 commented
Let me know if you still want to continue on this or you can take other issues to work on.

2021-04-12 19:16 UTC, dipu989 commented
> 
> 
> Let me know if you still want to continue on this or you can take other issues to work on.

I will try creating a fresh PR will all the changes. If issue still persists, will let you know.