Fix part of #2834 Add correct lambda function argument name.
oppia/oppia-android pull request #2841
Opened 2021-03-05 22:44 UTC by nskirkey

## Explanation
Describe the bug:
In most of the places we are using it for the lambda function argument. it is not readable and not helps to understand what it represents.

Expected behavior:
Look for the below-mentioned test files and Replace it with the correct names

Fixes part of #2834 (TopicSummaryViewModelTest )

## Checklist

- [X] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [X] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [X] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [X] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [X] The PR is made from a branch that's **not** called "develop".
- [X] The PR is made from a branch that is up-to-date with "develop".
- [X] The PR's branch is based on "develop" and not on any other branch.
- [] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-03-06 02:09 UTC, anandwana001 commented
`Fix part of #2834: Add correct lambda function argument name for TopicSummaryViewModelTest`

2021-03-06 02:11 UTC, anandwana001 requested changes
Thanks @nskirkey 
Left a nit change

2021-03-06 02:11 UTC, anandwana001 commented on app/src/sharedTest/java/org/oppia/android/app/home/TopicSummaryViewModelTest.kt
> +      it.onActivity { homeFragmentTestActivity ->
Could we have a name for these lambdas too?
`it.onActivity`

2021-03-07 01:46 UTC, anandwana001 approved these changes
LGTM, Thanks @nskirkey

2021-03-08 09:16 UTC, rt4914 approved these changes
LGTM, thanks.

2021-03-08 09:16 UTC, merged