Fix #2893: Prevent audio from playing when play button is hit twice
oppia/oppia-android pull request #2895
Opened 2021-03-12 15:30 UTC by ArpitShukIa

## Explanation

Fixes #2893 : When user double taps the play icon, second tap calls the `pauseAudio` function in `AudioFragmentPresenter` but the function simply returns because at that moment `playStatus` is `UiAudioPlayStatus.LOADING` and `prepared = false`.

I simply added a check when the audio is loaded to check if there is a pauseAudioRequest pending and if so, called pauseAudio again.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-03-12 15:33 UTC, ArpitShukIa commented
@BenHenning PTAL.

2021-03-15 03:45 UTC, anandwana001 commented
@ArpitShukIa Could you please confirm is issue #2893 is the same as #1801 
For context - https://github.com/oppia/oppia-android/issues/2893#issuecomment-797854785

2021-03-15 04:06 UTC, ArpitShukIa commented
I am not able to reproduce that issue.
https://user-images.githubusercontent.com/51705072/111102182-7c693380-8571-11eb-92ce-a3ca9bb0db7a.mp4

2021-03-16 10:33 UTC, ArpitShukIa commented
@anandwana001 It seems like both issues are the same. I am no longer able to reproduce #1801. This PR fixes both of them.

2021-03-18 08:36 UTC, prayutsu commented
@ArpitShukla Did you test the behavior when the play button is hit more than twice? And after the audio playback is completed and the user tries to listen the audio again, we should get the same behavior.

2021-03-18 09:26 UTC, ArpitShukIa commented
### On hitting multiple times:
When user hits second time, audio playback gets paused and the fragment starts navigating up (animation). If we press again while the animation is in progress, audio is still paused and animation restarts.
Only when the animation finishes, audio can be played again.
This looked ok to me.

### When audio playback completes:
We are getting the desired behavior here as well, user can click the play button and the audio restarts playing.

I can send the screen recordings, if required.

2021-03-19 14:45 UTC, prayutsu reviewed
I tested this locally, and it looks good to me. Not sure if we also need a test case for this.

2021-03-20 02:58 UTC, BenHenning requested changes
Thanks @ArpitShukIa! Sorry about this, but I actually think we might need to close this. See my comment at the bottom of #2893. This issue is actually quite a bit harder than it seems. While your fix may mitigate the immediate issue, it doesn't address the core problem of audio synchronization issues across threads. In order to properly fix this, we'll need to reimplement much of the audio player itself.

I suggest taking a look at other open issues to see if you'd like to work on something else. If you're really interested in this problem, it will probably still be available after you gain more familiarity with the codebase.

2021-03-20 02:59 UTC, closed without merging