Fixes Part of #2833: Add missing named argument
oppia/oppia-android pull request #2925
Opened 2021-03-16 05:52 UTC by arjunrkaushik

## Explanation
Adds named arguments to AppVersionActivityTest

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-03-16 06:17 UTC, arjunrkaushik commented
@rt4914 Could you please help me figure out why the 3 checks are failing...

2021-03-17 12:05 UTC, rt4914 requested changes
Thanks. Suggested changes.


Also, in future name your branch something which is more descriptive, it should not contain your name or the issue number.

Suggestion: `named-arguments-app-version-activity-test`

2021-03-17 12:05 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AppVersionActivityTest.kt
>    private fun launchAdministratorControlsActivityIntent(profileId: Int): Intent {
Rename `profileId ` to `internalProfileId` and also whereever you are using it as named argument.

2021-03-17 12:05 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AppVersionActivityTest.kt
>          scrollToPosition<RecyclerView.ViewHolder>(
This should not be changed. This is the reason why the tests are failing.
`scrollToPosition<RecyclerView.ViewHolder>(3)`

2021-03-17 12:05 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AppVersionActivityTest.kt
> +      context = ApplicationProvider.getApplicationContext()
This is no needed as the value which is `ApplicationProvider.getApplicationContext()` is  self-explanatory.

2021-03-18 18:21 UTC, arjunrkaushik commented
@rt4914 Thank you so much!!

2021-03-18 18:21 UTC, closed without merging