Fixes #2427: added configChanges flag to AdministratorControlsActivity in AndroidManifest
oppia/oppia-android pull request #2932
Opened 2021-03-17 10:35 UTC by sakshampruthi

…anifest.xml

## Explanation
Fixes #2427 
Since the Administrator Controls Activity doesn't need to update resources during a specific configuration change so I have used configChnages flag for the activity in android manifest. So putting that in the configuration file avoids the system to destroy the AdministratorControlsActivity. Instead, it invokes the onConfigurationChanged(Configuration) method

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-03-18 00:35 UTC, FareesHussain requested changes

2021-03-18 00:35 UTC, FareesHussain commented on app/src/main/AndroidManifest.xml
> +      android:configChanges="orientation|screenSize"/>
Nit fix
```suggestion
      android:configChanges="orientation|screenSize" />
```

2021-03-18 06:22 UTC, BenHenning requested changes
Thanks @sakshampruthi! I don't think this is how we want to solve this problem. The change effectively disables configuration changes for AdministratorControlsActivity by indicating to the system that it will handle configuration changes directly. While that does mitigate the issue for orientation changes & screen size changes, it doesn't solve other cases when a configuration change or activity reconstruction will happen (such as low memory).

The correct way to solve this issue is to use Android's saved instance state bundles. One approach may be to store a value in the bundle to indicate that the dialog should be open, and upon the activity being created automatically open the dialog if that value is present in the bundle. See https://developer.android.com/topic/libraries/architecture/saving-states for more information.

2021-03-18 06:49 UTC, sakshampruthi commented
@BenHenning That was initially my approach. But the dialog is being called directly from `administrator_controls_account_actions_view.xml` and the dialog is in `AdministratorControlsAccountActionsViewModel.kt`. So my approach was to save the state in activity using the state bundle and then calling the logout method after checking the state bundle. The problem I am facing is how should I connect  `AdministratorControlsAccountActionsViewModel.kt` and  `AdministratorControlsFragment.kt`. `AdministratorControlsAccountActionsViewModel.kt` requires 2 arguments to be passed to create its reference and both  `AdministratorControlsActivity` do not have those variables.

2021-03-18 10:04 UTC, ArpitShukIa commented
@sakshampruthi As I mentioned [here](https://github.com/oppia/oppia-android/issues/2427#issuecomment-800043536), you need to go down the chain.
- `AdministratorControlsActivity` has a reference to `AdministratorControlsActivityPresenter`.
- `AdministratorControlsActivityPresenter` has a function `getAdministratorControlsFragment()` which gives u a reference to `AdministratorControlsFragment`.
- `AdministratorControlsFragment` has a reference to `AdministratorControlsFragmentPresenter`.
- `AdministratorControlsFragmentPresenter` has a reference to `AdministratorControlsViewModel`.
- `AdministratorControlsViewModel` is creating an object of `AdministratorControlsAccountActionsViewModel` [here](https://github.com/oppia/oppia-android/blob/63a754ebfaccc5f65d12a50d9a8041dd30a9b05a/app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsViewModel.kt#L86).
- `AdministratorControlsAccountActionsViewModel` is responsible for creating the alert dialog.

This is definitely a long chain, but with the current app architecture, this seems like the only possible way to me.

2021-03-18 10:30 UTC, sakshampruthi commented
@ArpitShukIa I know how to communicate between activities using startActivitiesdforresult() but I am not sure how to proceed with these classes. Maybe you can help me out with this?

2021-03-18 11:20 UTC, ArpitShukIa commented
@sakshampruthi 
- AdministratorControlsAccountActionsViewModel: Create a public boolean `isDialogVisible`. Set this to `true` in `onLogOutClicked()`. Add an onDismissListener to alert dialog and set this boolean to `false` there.
- AdministratorControlsViewModel: Create a global reference to `AdministratorControlsAccountActionsViewModel` using `AdministratorControlsAccountActionsViewModel(fragment, IntentFactoryShim)` and add this to `itemViewModelList`
<br>[Alternative to this can be to create that boolean here and pass an additional lambda to AdministratorControlsAccountActionsViewModel to change this boolean]
<br>Create two functions here, one which returns the value of `isDialogVisible` to the caller and another function which calls `onLogOutClicked()`. Use the global reference for both these functions.

Now continue creating such functions for every member in the chain.
Then finally in `AdministratorControlsActivity's` `onSaveInstanceState` fetch this boolean value from the presenter and save it in the bundle. And in `onCreate()` check for this value, if present call the corresponding function in presenter to display the dialog again.

2021-03-19 13:01 UTC, rt4914 commented
@sakshampruthi I will need to close this PR because of **force-push**.
We should not do a force push as it tampers the commit history and makes it hard to review and revisit code.

It is also mentioned in this point: https://github.com/oppia/oppia-android/wiki#address-review-comments-until-all-reviewers-give-lgtm-looks-good-to-me

2021-03-19 13:01 UTC, closed without merging

2021-03-19 13:28 UTC, sakshampruthi commented
@rt4914 Can I open a new pull request with no force-pushed code?