Fixes #2427: Saved the state in Android's saved instance state bundles and restore the dialog closed due to orientation change
oppia/oppia-android pull request #2946
Opened 2021-03-19 14:23 UTC by sakshampruthi

## Explanation
Fixes #2427: Saved the state in Android's saved instance state bundles and restore the dialog closed due to orientation change

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-03-19 15:01 UTC, prayutsu requested changes
@sakshampruthi In the current approach, there are some dependency inversions, activity and fragment should not depend upon their presenters.

I think migrating `AlertDialog` to `DialogFragment` may fix the issue and would be a better way to handle it.
@FareesHussain WDYT?

2021-03-19 15:01 UTC, prayutsu commented on app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt
> +    }
Shouldn't this be handled in the `AdministratorControlsActivityPresenter` as we are handling `onSavedInstance` there?

2021-03-19 15:47 UTC, sakshampruthi commented on app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt
> +    }
Yes, I'll rectify this

2021-03-19 20:45 UTC, FareesHussain commented
> I think migrating `AlertDialog` to `DialogFragment` may fix the issue and would be a better way to handle it.
> @FareesHussain WDYT?

@prayutsu Sounds good to me, but @rt4914 gave a explanation why not to use `DialogFragment` here https://github.com/oppia/oppia-android/pull/2095#discussion_r519289293

2021-03-20 08:49 UTC, ARJUPTA commented
> > I think migrating `AlertDialog` to `DialogFragment` may fix the issue and would be a better way to handle it.
> > @FareesHussain WDYT?
> 
> @prayutsu Sounds good to me, but @rt4914 gave a explanation why not to use `DialogFragment` here [#2095 (comment)](https://github.com/oppia/oppia-android/pull/2095#discussion_r519289293)

@FareesHussain agreed with the point @rt4914 said but the current solution looks more like a patch-work, if in future we need more flags to get stored for orientation changes then it will generate a list of parameters passed to handleOnCreate(). @prayutsu  WDYT?

2021-03-20 13:01 UTC, prayutsu commented
@ARJUPTA @FareesHussain @rt4914 @sakshampruthi I think it is better to use DialogFragment in general as it handles configuration change itself and also it will also help us in the future if we want some features related to lifecycle callbacks.

2021-03-21 16:01 UTC, FareesHussain commented
Assigning @rt4914 to add this views based on this https://github.com/oppia/oppia-android/pull/2946#issuecomment-803115671

2021-03-24 00:17 UTC, rt4914 requested changes
@sakshampruthi Can we make it a bit simpler similar to this PR: https://github.com/oppia/oppia-android/pull/2958

Also, do add test such that if your approach is removed that test should fail or else pass.

2021-03-26 14:33 UTC, sakshampruthi commented
Okay, I will try that

2021-04-06 09:43 UTC, anandwana001 commented
@sakshampruthi any update on this?

2021-04-06 09:57 UTC, sakshampruthi commented
@anandwana001 I am caught up in an event for college and I will be stuck for a while. So you may unassign me and you can go ahead and close this pull request for now. If it remains unsolved after my event is complete I'll let you know and I'll work on it then

2021-04-06 11:14 UTC, closed without merging