Fix #2919: Add bazel util networking
oppia/oppia-android pull request #2954
Opened 2021-03-20 04:40 UTC by jonathanalvares9009

This PR will add BUILD.bazel to the networking package under utility module.
FIxes #2919 .

## Explanation

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-03-20 04:47 UTC, jonathanalvares9009 commented
@anandwana001 can you assign @BenHenning this PR for him to review it?

2021-03-20 04:49 UTC, anandwana001 commented
@jonathanalvares9009 could you please correct the issue number 2919 is a pr not the issue.

2021-03-20 08:10 UTC, jonathanalvares9009 commented
@fsharpasharp can you assign @BenHenning to review this PR?

2021-03-20 08:17 UTC, fsharpasharp requested changes
Thanks! Looks good.

2021-03-20 08:17 UTC, fsharpasharp commented on utility/src/main/java/org/oppia/android/util/networking/BUILD.bazel
> +"""
Consider rephrasing this sentence, since it seems a bit tautological.

2021-03-20 09:18 UTC, jonathanalvares9009 commented
@fsharpasharp made the change you requested.

2021-03-20 09:28 UTC, fsharpasharp commented on utility/src/main/java/org/oppia/android/util/networking/BUILD.bazel
> +"""
I think something like 

"Package for networking utilities."

is enough.

2021-03-20 09:29 UTC, fsharpasharp commented
Can you check and fix the linting issue?

```
********************************
Checking Bazel file formatting
********************************
utility/src/main/java/org/oppia/android/util/networking/BUILD.bazel # reformat
********************************
Buildifier issue found.
Please fix the above issues.
```

2021-03-20 09:44 UTC, jonathanalvares9009 commented
@fsharpasharp I tried running ktlint -F **file src** but it doesn't make the changes can you help me?

2021-03-20 09:54 UTC, jonathanalvares9009 commented
@anandwana001 my commit is failing the lint test but I ran ktlint -f **file_name** but it showed no errors n there wasn't a difference when I ran git diff. COuld you help me?

2021-03-20 09:56 UTC, fsharpasharp commented
@jonathanalvares9009 the ktlinter won't work on BUILD.bazel files. Try to put the visibility field before the deps field.

2021-03-20 10:13 UTC, jonathanalvares9009 commented
@fsharpasharp thanks passed ktlint test.

2021-03-21 06:36 UTC, jonathanalvares9009 commented
@fsharpasharp can you review my PR?

2021-03-21 08:33 UTC, fsharpasharp commented
Could you amend the description with something similar to my suggestion? We want to describe package rather than the "implementation" of the library.

2021-03-21 10:15 UTC, jonathanalvares9009 commented
@fsharpasharp is it ok now?

2021-03-22 09:41 UTC, jonathanalvares9009 commented
@fsharpasharp and @BenHenning please review my PR.

2021-03-22 10:08 UTC, fsharpasharp commented
> @fsharpasharp is it ok now?

I don't see an update to the comment. Update the above thread to make this conversation easier to follow.

2021-03-22 10:24 UTC, jonathanalvares9009 commented
@fsharpasharp I'm confused what am I supposed to update now? I update the PR description to **Package for networking utilities** and the comment in the bazel file to **This file contains the dependecies needed by the files under the networking package to run**. Can you please tell me what to change?

2021-03-22 10:34 UTC, fsharpasharp commented
> @fsharpasharp I'm confused what am I supposed to update now? I update the PR description to **Package for networking utilities** and the comment in the bazel file to **This file contains the dependecies needed by the files under the networking package to run**. Can you please tell me what to change?

I was refering to the comment in the BUILD.bazel file.

2021-03-22 10:42 UTC, fsharpasharp commented
> This file contains the dependecies needed by the files under the networking package to run.

This phrase describes the configuration itself. We want the comment in the BUILD.bazel file to describe the package (the directory). I was refering to this comment when I was talking about the description of the package.

2021-03-22 10:57 UTC, jonathanalvares9009 commented
@fsharpasharp I made the change is it good now?

2021-03-22 11:09 UTC, fsharpasharp commented
> @fsharpasharp I made the change is it good now?

Yes, that looks good. I'll wait for the checks, and then I'll approve the PR.

2021-03-22 17:31 UTC, jonathanalvares9009 commented
@fsharpasharp PR has passed all checks

2021-03-22 18:20 UTC, fsharpasharp approved these changes
Nice, thanks!

2021-03-23 01:13 UTC, jonathanalvares9009 commented
@BenHenning please review my PR

2021-03-23 02:12 UTC, BenHenning approved these changes
Thanks @jonathanalvares9009! This LGTM.

2021-03-23 02:12 UTC, merged