Fix #1383: added audio based content highlighting
oppia/oppia-android pull request #2996
Opened 2021-03-24 07:20 UTC by justdvnsh

## Explanation
Fix #1383: Added audio based content highlighting - to highlight the correct recyler view item based on the audio track playing

## Checklist
- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-03-24 07:22 UTC, justdvnsh commented
@rt4914 I have created a PR as requested. 
(https://drive.google.com/file/d/1w81SKafbCgszq0f9PJRZuARkEooYbREv/view?usp=sharing) this is a POC video to cross verify.

Also, there is one problem in the code. However, rest everything seems to work just fine. Please take a look and tell me, so that I can make more improvements in this PR and also, clean up the code a little.

2021-03-30 13:20 UTC, rt4914 commented
Couple of issues with this implementation.
1. The UI/border of the content disappears which should not happen:
<img src="https://user-images.githubusercontent.com/9396084/112995278-aed97a00-9188-11eb-94b8-8816fbbd7196.png" width="250" />

2. In case of repetitive contents only the last item should get highlighted and not all
<img src="https://user-images.githubusercontent.com/9396084/112995398-ce70a280-9188-11eb-8cac-cf270db6847b.png" width="250" />

2021-03-30 13:21 UTC, rt4914 requested changes
The approach is on the right track but there are a lot of edge cases that needs to be taken care of.

2021-04-03 13:04 UTC, justdvnsh commented
@rt4914 Okay. Would be working on it.

2021-04-19 03:32 UTC, anandwana001 commented
@justdvnsh any update on this?

2021-04-19 15:33 UTC, justdvnsh commented
@anandwana001 Yes. I will be working on this from tomorrow. Sorry, got a little busy due to the GSoC and internships !!

2021-04-27 11:43 UTC, justdvnsh commented
> Couple of issues with this implementation.
> 
> 1. The UI/border of the content disappears which should not happen:
> 
> <img alt="" width="250" src="https://user-images.githubusercontent.com/9396084/112995278-aed97a00-9188-11eb-94b8-8816fbbd7196.png">
> 
> 1. In case of repetitive contents only the last item should get highlighted and not all
> 
> <img alt="" width="250" src="https://user-images.githubusercontent.com/9396084/112995398-ce70a280-9188-11eb-8cac-cf270db6847b.png">


@rt4914 Okay, so I am having a little issue here. Can you help me out a little. First part is okay (it can be solved using a binding adapter), but for the second part, there needs to be some way of highlighting only the last feedback item. Can you suggest me anything that can be done to resolve the 2nd part of this issue ?

2021-05-06 13:26 UTC, rt4914 commented
> > Couple of issues with this implementation.
> > 
> > 1. The UI/border of the content disappears which should not happen:
> > 
> > <img alt="" width="250" src="https://user-images.githubusercontent.com/9396084/112995278-aed97a00-9188-11eb-94b8-8816fbbd7196.png">
> > 
> > 1. In case of repetitive contents only the last item should get highlighted and not all
> > 
> > <img alt="" width="250" src="https://user-images.githubusercontent.com/9396084/112995398-ce70a280-9188-11eb-8cac-cf270db6847b.png">
> 
> @rt4914 Okay, so I am having a little issue here. Can you help me out a little. First part is okay (it can be solved using a binding adapter), but for the second part, there needs to be some way of highlighting only the last feedback item. Can you suggest me anything that can be done to resolve the 2nd part of this issue ?

@justdvnsh Actually even I do not have any direct solution here because that's the same step I was stuck the last time. Do you have some approaches in mind?

2021-05-13 03:40 UTC, anandwana001 commented
@justdvnsh any update on this?

2021-05-13 11:34 UTC, justdvnsh commented
@anandwana001 Yup. I am stuck too on the step mentioned above. Trying to formulate a solution for now.

2021-05-13 11:34 UTC, justdvnsh commented
@rt4914 Not

> > > Couple of issues with this implementation.
> > > 
> > > 1. The UI/border of the content disappears which should not happen:
> > > 
> > > <img alt="" width="250" src="https://user-images.githubusercontent.com/9396084/112995278-aed97a00-9188-11eb-94b8-8816fbbd7196.png">
> > > 
> > > 1. In case of repetitive contents only the last item should get highlighted and not all
> > > 
> > > <img alt="" width="250" src="https://user-images.githubusercontent.com/9396084/112995398-ce70a280-9188-11eb-8cac-cf270db6847b.png">
> > 
> > 
> > @rt4914 Okay, so I am having a little issue here. Can you help me out a little. First part is okay (it can be solved using a binding adapter), but for the second part, there needs to be some way of highlighting only the last feedback item. Can you suggest me anything that can be done to resolve the 2nd part of this issue ?
> 
> @justdvnsh Actually even I do not have any direct solution here because that's the same step I was stuck the last time. Do you have some approaches in mind?

Not really Actually !

2021-05-19 04:21 UTC, anandwana001 commented
@rt4914 PTAL

2021-06-29 18:35 UTC, anandwana001 commented
Closing this PR as no further update.

2021-06-29 18:35 UTC, closed without merging