Fix #2947: Test cases are flaking in the FakeOppiaClockTest
oppia/oppia-android pull request #3015
Opened 2021-03-25 21:43 UTC by Karanjot-singh

## Explanation
Fixes #2947: Delay between reported time and current time increased to 100m/s

## Screenshots of Tests
1. ``` testGetCurrentCalendar_wallClockMode_returnsCalendarWithCurrentTimeMillis()``` run 100 times

![image](https://user-images.githubusercontent.com/55680995/112547512-daeba880-8de0-11eb-95ed-de8f7d4ab58d.png)

2. ```testGetCurrentTimeMs_wallClockMode_returnsCurrentTimeMillis()``` run 100 times

![image](https://user-images.githubusercontent.com/55680995/112547485-d2936d80-8de0-11eb-9f71-e300b48df060.png)

3. ```FakeOppiaClockTest.kt``` run 100 times

![image](https://user-images.githubusercontent.com/55680995/112547547-e343e380-8de0-11eb-8144-1483cb76e934.png)

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-03-25 21:45 UTC, Karanjot-singh commented
PTAL @anandwana001 @BenHenning

2021-03-25 23:46 UTC, anandwana001 commented
Assigning @prayutsu as he is the Issue author to take a loot initially, before the code owners.

2021-03-26 07:52 UTC, prayutsu requested changes
Left some comments. PTAL @Karanjot-singh

2021-03-26 07:52 UTC, prayutsu commented on testing/src/test/java/org/oppia/android/testing/time/FakeOppiaClockTest.kt
>      // flakiness since this is testing real clock time).
Replace 4 ms with 100 ms.

2021-03-26 07:52 UTC, prayutsu commented on testing/src/test/java/org/oppia/android/testing/time/FakeOppiaClockTest.kt
>      assertThat(reportedTimeMs).isNotEqualTo(0)
Please add a '.' after the comment.

2021-03-26 07:52 UTC, prayutsu commented on testing/src/test/java/org/oppia/android/testing/time/FakeOppiaClockTest.kt
> -    assertThat(calendar.timeInMillis).isWithin((currentTimeMs - 2)..(currentTimeMs + 2))
Correct typo `inited` --> `initiated`.

2021-03-26 08:00 UTC, prayutsu commented
@anandwana001 @BenHenning I tested it locally and the flakes seem to be fixed now.

@Karanjot-singh Can you also add some screenshots where - 
1. The whole test file is run 100 times
2. flaky test 1 is run 1000 times in isolation.
3. flaky test 2 is run 1000 times in isolation.

2021-03-26 08:04 UTC, Karanjot-singh commented
> @anandwana001 @BenHenning I tested it locally and the flakes seem to be fixed now.
> 
> @Karanjot-singh Can you also add some screenshots where - 
> 1. The whole test file is run 100 times
> 2. flaky test 1 is run 1000 times in isolation.
> 3. flaky test 2 is run 1000 times in isolation.

Sure, I will make these changes and add the extra screenshots in a few minutes.

2021-03-26 09:32 UTC, Karanjot-singh commented
I have made the changes and added the screenshots. PTAL @prayutsu

2021-03-26 20:39 UTC, prayutsu approved these changes
LGTM, Thanks @Karanjot-singh

2021-03-26 20:43 UTC, prayutsu commented
@Karanjot-singh The reviewed comments should only be resolved by one who initiated it (or if they explicitly ask you to resolve them) and if you made the suggested changes, you can reply - "Done" to the comments rather than resolving it.
Unresolved comments help the reviewers to keep the track of the suggested changes as the reviewers don't go through the resolved conversations.

Thanks!

2021-03-26 20:45 UTC, Karanjot-singh commented
> @Karanjot-singh The reviewed comments should only be resolved by one who initiated it (or if they explicitly ask you to resolve them) and if you made the suggested changes, you can reply - "Done" to the comments rather than resolving it.
> Unresolved comments help the reviewers to keep the track of the suggested changes as the reviewers don't go through the resolved conversations.
> 
> Thanks!

Noted! Will definitely take care of that.

2021-03-30 04:52 UTC, BenHenning approved these changes
Thanks @Karanjot-singh!

2021-03-30 04:52 UTC, merged