Fix part of #134: Home fragment text fix
oppia/oppia-android pull request #311
Opened 2019-11-06 12:13 UTC by rt4914

## Explanation

"All Topics" text was missing from HomeFragment just above Topic list.

I have added that as a item now.

Mock: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/d47aa8de-a7a8-4d25-b011-5baefc7b7098/HP-Home-Page-

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2019-11-06 14:17 UTC, rt4914 commented
@veena14cs @nikitamarysolomanpvt Waiting for your review on this.

2019-11-06 15:23 UTC, nikitamarysolomanpvt requested changes
Test cases are failing in both portrait and landscape mode

2019-11-06 15:33 UTC, rt4914 commented
> Test cases are failing in both portrait and landscape mode

@nikitamarysolomanpvt I have checked once again, and they were passing. Can you please add screenshot of error, so that I can investigate the issue.

2019-11-06 15:37 UTC, veena14cs approved these changes
Looks good. All testcases are passing for me.

2019-11-06 16:46 UTC, nikitamarysolomanpvt commented
> > Test cases are failing in both portrait and landscape mode
> 
> @nikitamarysolomanpvt I have checked once again, and they were passing. Can you please add screenshot of error, so that I can investigate the issue.

<img width="1626" alt="small_" src="https://user-images.githubusercontent.com/54615666/68318237-7db76000-00e2-11ea-8fea-3fd6d243b92e.png">
<img width="1627" alt="small" src="https://user-images.githubusercontent.com/54615666/68318253-81e37d80-00e2-11ea-99f8-ce8a233b0eb8.png">

2019-11-06 17:03 UTC, rt4914 commented
> > > Test cases are failing in both portrait and landscape mode
> > 
> > 
> > @nikitamarysolomanpvt I have checked once again, and they were passing. Can you please add screenshot of error, so that I can investigate the issue.
> 
> <img alt="small_" width="1626" src="https://user-images.githubusercontent.com/54615666/68318237-7db76000-00e2-11ea-8fea-3fd6d243b92e.png">
> 
> <img alt="small" width="1627" src="https://user-images.githubusercontent.com/54615666/68318253-81e37d80-00e2-11ea-99f8-ce8a233b0eb8.png">

The errors are actually pointing to a valid code but they are not failing. Maybe its worth mentioning to @BenHenning 

@BenHenning For context: The test cases in this PR are passing in mine and @veena14cs 's laptop but some test cases are failing in @nikitamarysolomanpvt laptop. Not sure why this is happening.

2019-11-07 07:09 UTC, BenHenning commented
All 18 tests in HomeActivityTest are passing for me on my local Nexus 5X device, and on emulator locally via Espresso. They fail for me when run with Robolectric with the same error:

```
android.view.InflateException: Binary XML file line #16: Layout state should be one of 100 but it is 10

Caused by: java.lang.IllegalStateException: Layout state should be one of 100 but it is 10
	at androidx.recyclerview.widget.RecyclerView$State.assertLayoutStep(RecyclerView.java:12115)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3941)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3652)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:444)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at org.robolectric.shadows.ShadowLegacyMessageQueue.dispatchMessage(ShadowLegacyMessageQueue.java:157)
	at org.robolectric.shadows.ShadowLegacyMessageQueue.access$200(ShadowLegacyMessageQueue.java:42)
	at org.robolectric.shadows.ShadowLegacyMessageQueue$1.run(ShadowLegacyMessageQueue.java:135)
	at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:407)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:279)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:261)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:244)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:234)
	at org.robolectric.util.Scheduler.setIdleState(Scheduler.java:89)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:124)
	at org.robolectric.shadows.ShadowLegacyLooper.unPause(ShadowLegacyLooper.java:267)
	at org.robolectric.shadows.ShadowLegacyLooper.runPaused(ShadowLegacyLooper.java:324)
	at org.robolectric.shadows.ShadowViewGroup.addView(ShadowViewGroup.java:36)
	at android.view.ViewGroup.addView(ViewGroup.java)
	at android.view.ViewGroup.addView(ViewGroup.java:4837)
	at androidx.appcompat.widget.Toolbar.addSystemView(Toolbar.java:1405)
	at androidx.appcompat.widget.Toolbar.ensureMenuView(Toolbar.java:1054)
	at androidx.appcompat.widget.Toolbar.setMenu(Toolbar.java:551)
	at androidx.appcompat.widget.ToolbarWidgetWrapper.setMenu(ToolbarWidgetWrapper.java:370)
	at androidx.appcompat.widget.ActionBarOverlayLayout.setMenu(ActionBarOverlayLayout.java:721)
	at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1583)
	at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:1869)
	at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:230)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at org.robolectric.shadows.ShadowLegacyMessageQueue.dispatchMessage(ShadowLegacyMessageQueue.java:157)
	at org.robolectric.shadows.ShadowLegacyMessageQueue.access$200(ShadowLegacyMessageQueue.java:42)
	at org.robolectric.shadows.ShadowLegacyMessageQueue$1.run(ShadowLegacyMessageQueue.java:135)
	at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:407)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:279)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:261)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:244)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:234)
	at org.robolectric.util.Scheduler.setIdleState(Scheduler.java:89)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:124)
	at org.robolectric.shadows.ShadowLegacyLooper.unPause(ShadowLegacyLooper.java:267)
	at org.robolectric.shadows.ShadowLegacyLooper.runPaused(ShadowLegacyLooper.java:324)
	at org.robolectric.shadows.ShadowViewGroup.addView(ShadowViewGroup.java:36)
	at android.view.ViewGroup.addView(ViewGroup.java)
	at androidx.constraintlayout.widget.ConstraintLayout.addView(ConstraintLayout.java:634)
	at android.view.ViewGroup.addView(ViewGroup.java:4837)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
	at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java:1366)
	at org.oppia.app.databinding.WelcomeBinding.inflate(WelcomeBinding.java:53)
	at org.oppia.app.databinding.WelcomeBinding.inflate(WelcomeBinding.java:39)
	at org.oppia.app.home.topiclist.TopicListAdapter.onCreateViewHolder(TopicListAdapter.kt:30)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(View.java: [...]

2019-11-07 07:10 UTC, BenHenning commented
So @nikitamarysolomanpvt are the tests randomly flaking out on you? It seems that per the different screenshots that they are almost arbitrarily failing.

2019-11-07 07:11 UTC, rt4914 commented
> All 18 tests in HomeActivityTest are passing for me on my local Nexus 5X device, and on emulator locally via Espresso. They fail for me when run with Robolectric with the same error:
> 
> ```
> android.view.InflateException: Binary XML file line #16: Layout state should be one of 100 but it is 10
> 
> Caused by: java.lang.IllegalStateException: Layout state should be one of 100 but it is 10
> 	at androidx.recyclerview.widget.RecyclerView$State.assertLayoutStep(RecyclerView.java:12115)
> 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3941)
> 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3652)
> 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
> 	at android.view.View.layout(View.java:20672)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
> 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
> 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
> 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
> 	at android.view.View.layout(View.java:20672)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
> 	at android.view.View.layout(View.java:20672)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
> 	at android.view.View.layout(View.java:20672)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
> 	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:444)
> 	at android.view.View.layout(View.java:20672)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
> 	at android.view.View.layout(View.java:20672)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
> 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
> 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
> 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
> 	at android.view.View.layout(View.java:20672)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
> 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
> 	at android.view.View.layout(View.java:20672)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
> 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
> 	at android.os.Handler.handleCallback(Handler.java:873)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at org.robolectric.shadows.ShadowLegacyMessageQueue.dispatchMessage(ShadowLegacyMessageQueue.java:157)
> 	at org.robolectric.shadows.ShadowLegacyMessageQueue.access$200(ShadowLegacyMessageQueue.java:42)
> 	at org.robolectric.shadows.ShadowLegacyMessageQueue$1.run(ShadowLegacyMessageQueue.java:135)
> 	at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:407)
> 	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:279)
> 	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:261)
> 	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:244)
> 	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:234)
> 	at org.robolectric.util.Scheduler.setIdleState(Scheduler.java:89)
> 	at org.robolectric.util.Scheduler.unPause(Scheduler.java:124)
> 	at org.robolectric.shadows.ShadowLegacyLooper.unPause(ShadowLegacyLooper.java:267)
> 	at org.robolectric.shadows.ShadowLegacyLooper.runPaused(ShadowLegacyLooper.java:324)
> 	at org.robolectric.shadows.ShadowViewGroup.addView(ShadowViewGroup.java:36)
> 	at android.view.ViewGroup.addView(ViewGroup.java)
> 	at android.view.ViewGroup.addView(ViewGroup.java:4837)
> 	at androidx.appcompat.widget.Toolbar.addSystemView(Toolbar.java:1405)
> 	at androidx.appcompat.widget.Toolbar.ensureMenuView(Toolbar.java:1054)
> 	at androidx.appcompat.widget.Toolbar.setMenu(Toolbar.java:551)
> 	at androidx.appcompat.widget.ToolbarWidgetWrapper.setMenu(ToolbarWidgetWrapper.java:370)
> 	at androidx.appcompat.widget.ActionBarOverlayLayout.setMenu(ActionBarOverlayLayout.java:721)
> 	at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1583)
> 	at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:1869)
> 	at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:230)
> 	at android.os.Handler.handleCallback(Handler.java:873)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at org.robolectric.shadows.ShadowLegacyMessageQueue.dispatchMessage(ShadowLegacyMessageQueue.java:157)
> 	at org.robolectric.shadows.ShadowLegacyMessageQueue.access$200(ShadowLegacyMessageQueue.java:42)
> 	at org.robolectric.shadows.ShadowLegacyMessageQueue$1.run(ShadowLegacyMessageQueue.java:135)
> 	at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:407)
> 	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:279)
> 	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:261)
> 	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:244)
> 	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:234)
> 	at org.robolectric.util.Scheduler.setIdleState(Scheduler.java:89)
> 	at org.robolectric.util.Scheduler.unPause(Scheduler.java:124)
> 	at org.robolectric.shadows.ShadowLegacyLooper.unPause(ShadowLegacyLooper.java:267)
> 	at org.robolectric.shadows.ShadowLegacyLooper.runPaused(ShadowLegacyLooper.java:324)
> 	at org.robolectric.shadows.ShadowViewGroup.addView(ShadowViewGroup.java:36)
> 	at android.view.ViewGroup.addView(ViewGroup.java)
> 	at androidx.constraintlayout.widget.ConstraintLayout.addView(ConstraintLayout.java:634)
> 	at android.view.ViewGroup.addView(ViewGroup.java:4837)
> 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
> 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
> 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
> 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
> 	at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
> 	at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java:1366)
> 	at org.oppia.app.databinding.WelcomeBinding.inflate(WelcomeBinding.java:53)
> 	at org.oppia.app.databinding.WelcomeBinding.inflate(WelcomeBinding.java:39)
> 	at org.oppia.app.home.topiclist.TopicListAdapter.onCreateViewHolder(TopicListAdapter.kt:30)
> 	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
> 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
> 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
> 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
> 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
> 	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
> 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
> 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
> 	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
> 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerVie [...]

2019-11-07 07:13 UTC, BenHenning commented
I can't be sure what the failure is without being able to repro it & investigate, but I suspect it's a timing issue. We don't have a proper idling resource for Kotlin coroutines, so it's quite feasible that for @nikitamarysolomanpvt some of the coroutines aren't completing before Espresso tries to verify the UI, so the UI is actually behind.

#89 is meant to fix this, and I think that I'll need to work on that to even begin writing exploration fragment tests. I think we should proceed with the flake, and follow up with an investigation if there are still issues after #89 is resolved.

2019-11-07 07:14 UTC, BenHenning commented
(sending back because I wasn't requested as a reviewer, so I interpreted my assignment as needing to answer the question asked earlier)

2019-11-07 07:15 UTC, rt4914 commented
> I can't be sure what the failure is without being able to repro it & investigate, but I suspect it's a timing issue. We don't have a proper idling resource for Kotlin coroutines, so it's quite feasible that for @nikitamarysolomanpvt some of the coroutines aren't completing before Espresso tries to verify the UI, so the UI is actually behind.
> 
> #89 is meant to fix this, and I think that I'll need to work on that to even begin writing exploration fragment tests. I think we should proceed with the flake, and follow up with an investigation if there are still issues after #89 is resolved.

So, should we merge this for now or wait for #89 ?

2019-11-07 07:22 UTC, rt4914 commented
> > I can't be sure what the failure is without being able to repro it & investigate, but I suspect it's a timing issue. We don't have a proper idling resource for Kotlin coroutines, so it's quite feasible that for @nikitamarysolomanpvt some of the coroutines aren't completing before Espresso tries to verify the UI, so the UI is actually behind.
> > #89 is meant to fix this, and I think that I'll need to work on that to even begin writing exploration fragment tests. I think we should proceed with the flake, and follow up with an investigation if there are still issues after #89 is resolved.
> 
> So, should we merge this for now or wait for #89 ?

As per conversation with @BenHenning : we should merge this for now and once #89 is fixed we will need to check all the test cases once again.

2019-11-07 07:43 UTC, rt4914 commented
@nikitamarysolomanpvt waiting for your comments and approval on this.

2019-11-07 09:04 UTC, nikitamarysolomanpvt commented
> So @nikitamarysolomanpvt are the tests randomly flaking out on you? It seems that per the different screenshots that they are almost arbitrarily failing.

First one is portrait  and the second one id landscape mode. In Landscape mode every time random test cases are failing.

2019-11-07 09:09 UTC, nikitamarysolomanpvt approved these changes
I tested it again, the test cases are failing randomly in landscape mode. Approving this for now given that once #89 is fixed all these test cases needs to be tested again. Also, currently, the test cases seems failing because of some issue of Roboelectirc.

2019-11-07 09:17 UTC, rt4914 commented
Merging this now. In this PR comments are actually important, so if anyone is going through this PR in future, I suggest take a look at all the comments.

2019-11-07 09:18 UTC, merged