Fix #3200: Alpha Content Parsing Error
oppia/oppia-android pull request #3203
Opened 2021-05-19 06:15 UTC by anandwana001

## Explanation

Fixes #3200 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-05-20 04:26 UTC, vinitamurthi approved these changes

2021-05-20 04:48 UTC, anandwana001 commented
@rt4914 Let me know if we need to update the current data files with this JSONObject/JSONArray thing. I will do in this PR only else I think we might not able to merge the PR. Also, the app will not be able to support the current explorations due to this parsing.

2021-05-20 07:58 UTC, rt4914 requested changes
@anandwana001 Yes we will need to update it for json files. As per the test failures it looks like we need to do that for `test_exp_id_2` but you can run all `domain` layer tests locally to check if any other file needs this change or not.

2021-08-18 12:09 UTC, anandwana001 commented
Need to discuss in a team meeting, closing this PR for now.

2021-08-18 12:09 UTC, closed without merging