Fix #980: In HDPI device shadow looks odd for edit profile image thumbnail.
oppia/oppia-android pull request #3212
Opened 2021-05-20 06:32 UTC by anandwana001

## Explanation

Fixes #980 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-05-20 09:13 UTC, Sparsh1212 reviewed
LGTM for xxxhdpi.
But I am still encountering the odd shadow on the edit image thumbnail for some devices. Can you please cross-check on your local?
1. Nexus S (HDPI)

![image](https://user-images.githubusercontent.com/55937724/118952212-6153df00-b979-11eb-9bb4-fae49394c71f.png)

2. Nexus 4 (xhdpi)

![image](https://user-images.githubusercontent.com/55937724/118952376-86485200-b979-11eb-8a32-90ca006527a6.png)

2021-05-24 09:47 UTC, rt4914 approved these changes
LGTM, thanks.

2021-05-24 09:47 UTC, rt4914 commented on app/src/main/res/layout-sw600dp-port/profile_progress_header.xml
> +      android:textAlignment="viewStart"
Remove this. Though it was added but for all xml files we need to remove `textAlignment`, `textDirection` and `textLocale`. Though we are not doing it right away but whenever we see this in code we should remove it.

2021-05-24 09:47 UTC, rt4914 commented on app/src/main/res/layout-sw600dp-land/profile_progress_header.xml
> +      android:textAlignment="viewStart"
Ditto

2021-05-24 09:56 UTC, rt4914 requested changes
Blocking on @Sparsh1212 suggestions.

2021-07-26 02:51 UTC, anandwana001 commented
closing this PR as not working on this currently

2021-07-26 02:51 UTC, closed without merging