FIX #2823: Profile list activity label
oppia/oppia-android pull request #3225
Opened 2021-05-22 21:16 UTC by pravesh00

## Explanation

Fixes #2823: Profile list activity label added

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-05-22 21:17 UTC, pravesh00 commented
PTAL @Victor-Titan @rt4914

2021-05-23 09:40 UTC, pravesh00 commented
@rt4914 can you please help me with how to remove these unit test failures?

2021-05-23 19:53 UTC, rt4914 requested changes
@pravesh00 Suggestion changes.

Also if you check sample PR number mentioned in the issue that PR contains a test too. You have to create a similar test file and add test. You can create a new test file `ProfileListActivityTest`

2021-05-23 19:53 UTC, rt4914 commented on .idea/misc.xml
> +</project>
This changes from this entire file. It should not be visible under `Files changed` section on github.

2021-05-23 19:53 UTC, rt4914 commented on app/src/main/res/values/strings.xml
> +  <string name="profile_list_activity_label">Profile List</string>
Rename to `profile_list_activity_title`

2021-05-23 19:53 UTC, rt4914 commented on app/src/main/AndroidManifest.xml
> +      android:label="@string/profile_list_activity_label"/>
Add ` ` (space) before `/>`

2021-05-25 11:51 UTC, pravesh00 commented
I was facing some gradle change issues so I have closed this PR and created a new one #3244

2021-05-25 11:51 UTC, closed without merging