Fix #3242: Hi-Fi User Profile Tablet
oppia/oppia-android pull request #3264
Opened 2021-06-01 09:39 UTC by anandwana001

## Explanation

Fix #3242 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-06-03 08:22 UTC, anandwana001 commented on app/src/main/res/layout-land/profile_edit_fragment.xml
> +</layout>
add new line

2021-06-04 08:21 UTC, rt4914 requested changes
Blocking on your TODO.

2021-06-04 09:42 UTC, rt4914 commented
> Blocking on your TODO.

@anandwana001 Convert the profile deletion alert dialog to `DialogFragment` similar to `ExitProfileDialogFragment` and that should persist during config change.

2021-06-07 08:06 UTC, rt4914 commented
@anandwana001 In `ProfileEditActivityTest ` tests are failing on CI.

2021-06-07 10:08 UTC, anandwana001 commented
> @anandwana001 In `ProfileEditActivityTest ` tests are failing on CI.

missed to update the id, all are passing now. PTAL

2021-06-08 15:52 UTC, rt4914 approved these changes
LGTM

2021-06-08 16:12 UTC, merged