Fix part of #1587: Made some intent/bundle/saved/tags instance keys consistent.
oppia/oppia-android pull request #3350
Opened 2021-06-21 00:19 UTC by ayush0402

## Explanation

Made some keys consistent in various Activities and Fragments.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-06-21 00:28 UTC, ayush0402 commented
@rt4914 , PTAL

2021-06-21 04:52 UTC, prayutsu requested changes
@ayush0402 Left some comments.
Also please link the issue with this PR

2021-06-21 04:52 UTC, prayutsu commented on .idea/misc.xml
>      <output url="file://$PROJECT_DIR$/build/classes" />
Revert these changes.

2021-06-21 04:52 UTC, prayutsu commented on .idea/runConfigurations.xml
>          <option value="org.jetbrains.plugins.gradle.execution.test.runner.TestMethodGradleConfigurationProducer" />
Revert these too.

2021-06-21 04:55 UTC, prayutsu commented
@ayush0402 To fix the failing unit tests, identify the failing test file and then try to find the cause of the error. To run the tests locally, read our [wiki instructions](https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing).

2021-06-21 17:18 UTC, rt4914 commented
@prayutsu Assign it to me or Akshay once approved from your side.

2021-06-23 08:03 UTC, prayutsu commented
@ayush0402 You should not resolve conversation threads by yourself, only the person who started the thread should it, it helps in keeping track of the changes they requested. And once you make the changes as requested by the reviewer, you should reply with "Done" or "fixed" so that the reviewer is aware that you have made changes.

2021-06-23 08:42 UTC, ayush0402 commented
I will keep that in mind for next time. I made the requested changes. @prayutsu PTAL.

2021-06-23 08:57 UTC, prayutsu requested changes
@ayush0402 PTAL. It looks like you missed adding the extra blank line while undoing the changes.
All files must end with an empty new line (also called EOF).
Also please note that the issue hasn't been linked yet. You need to correct the keyword in the PR explanation -- it should be `Fixes part of #issueNumber` instead of `Fix part of #issueNumber`. 
Thanks!

2021-06-23 08:57 UTC, prayutsu commented on .idea/misc.xml
> +</project>
Revert these too.

2021-06-23 08:57 UTC, prayutsu commented on .idea/runConfigurations.xml
> +</project>
Ditto.

2021-06-23 09:29 UTC, ayush0402 commented
@prayutsu PTAL. Made requested changes.

2021-06-25 11:06 UTC, prayutsu approved these changes
LGTM, thanks @ayush0402

2021-06-25 11:13 UTC, prayutsu commented
@ayush0402 I have resolved all the conversations as of now, but you should always reply to the conversation threads with "Done" or "Fixed" when you commit the suggested changes so that the reviewer can resolve the conversation.

2021-06-25 11:24 UTC, fsharpasharp approved these changes
Approving for the changes in IntentFactoryShimImpl.kt

2021-06-25 16:08 UTC, anandwana001 commented
Please follow the first point in the PR checklist and mark it did once done. 
Assign me back once Rajat reviews the PR.

2021-06-25 21:14 UTC, ayush0402 commented
@anandwana001 Done. PTAL.

2021-06-26 20:43 UTC, rt4914 approved these changes
@ayush0402 Nice work. Thanks.

2021-06-28 06:05 UTC, anandwana001 approved these changes
LGTM

2021-06-28 06:05 UTC, merged