Added Update to Guava Library
oppia/oppia-android pull request #3493
Opened 2021-07-17 13:52 UTC by jaimehta1912

## Explanation

This PR updated the Guava library from version `28.1-android` to version `30.1-android` which was relased on December 14th, 2020.

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-07-26 13:35 UTC, rt4914 requested changes
@jaimehta1912 PTAL

2021-07-26 13:35 UTC, rt4914 commented on .idea/misc.xml
> +</project>
Revert these changes

2021-07-26 13:35 UTC, rt4914 commented on .idea/runConfigurations.xml
> +</project>
Revert these changes.

2021-07-26 13:35 UTC, rt4914 commented on app/build.gradle
> -      'com.google.guava:guava:28.1-android',
We need this change in `third_party\versions.bzl` too.

2021-07-30 05:40 UTC, BenHenning commented
Hi @jaimehta1912. Thanks for sending this PR! In general, we usually only update dependency versions when there's a clear need (either a security or privacy update is needed, or we need newer API functionality). Otherwise, updating dependencies can actually reduce the stability of the app since changes in libraries can change app behavior in ways not always covered by our tests.

If you think there's a specific reason why we should update these versions, please follow up with a comment. Otherwise, I'm closing this PR for now.

If you like to help out with open problems, I suggest heading over to our [starter issues list](https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee) for unassigned, open issues that we could use help on.

2021-07-30 05:40 UTC, closed without merging

2021-08-04 22:43 UTC, jaimehta1912 commented
The changes or the improvements introduced with this version are, to detect potential problems for users now so that can plan to use Java 8 language features in our implementation later. A warning log message when running guava-android under a Java 7 VM. This warning is not guaranteed to be logged when running under Java 7, so please don't rely on it as only warning about future problems. If the warning itself causes trouble, can eliminate it by silencing the logger for `com.google.common.base.MoreObjects$ToStringHelper`.

2021-08-08 20:41 UTC, jaimehta1912 commented
@rt4914