Added Update to CircleImageView Library
oppia/oppia-android pull request #3494
Opened 2021-07-17 14:01 UTC by jaimehta1912

## Explanation

Added update to the `CircleImageView` from version `3.0.1` to version `3.1.0` which was released on January 26th, 2020.

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-07-26 13:31 UTC, rt4914 requested changes
@jaimehta1912 PTAL Thanks.

2021-07-26 13:31 UTC, rt4914 commented on .idea/misc.xml
> +</project>
Revert changes to this file. These are unintentional changes.

2021-07-26 13:31 UTC, rt4914 commented on .idea/runConfigurations.xml
> +</project>
Revert changes to this file. These are unintentional changes.

2021-07-26 13:31 UTC, rt4914 commented on app/build.gradle
> +      'de.hdodenhof:circleimageview:3.1.0',
You will need to apply this change in `third_party/versions.bzl` file too.

2021-07-26 13:32 UTC, rt4914 commented
@jaimehta1912 Please make sure you have signed the CLA [here](https://github.com/oppia/oppia-android/wiki#onboarding-instructions).

2021-07-26 13:57 UTC, jaimehta1912 commented
@rt4914  yes  sir  ,I have signed CLA already

2021-07-28 19:08 UTC, rt4914 commented
> @rt4914 yes sir ,I have signed CLA already

@jaimehta1912 Please reply to above comments and update the PR accordingly. Thanks.

2021-07-30 05:40 UTC, BenHenning commented
Thanks @jaimehta1912. FYI I'm closing this for the same reason mentioned in https://github.com/oppia/oppia-android/pull/3493#issuecomment-889642775. Similarly, if you think there's a reason why we should update this, then please let us know in a follow-up comment.

2021-07-30 05:40 UTC, closed without merging

2021-08-04 22:47 UTC, jaimehta1912 commented
The reason to Update this particular Library is that new features such as, support for image alpha, replaced fields holding bitmap dimensions with local variables, removed pointless override of getScaleType, eestructured initialization and property updates and added support for animated drawables have been released with the Updated version of this Library.

2021-08-08 20:42 UTC, jaimehta1912 commented
@rt4914