Fix #3474: Merged faq single activity into one layout file and updated dimens.xml (land),(sw600dp-land)
oppia/oppia-android pull request #3518
Opened 2021-07-24 12:07 UTC by rishidyno

## Explanation

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-07-24 12:36 UTC, rishidyno commented
I have merged the faq_single_activity.xml file into a single file. I have deleted unnecessary values in dimens.xml.

Screenshots before merging into a single file.

![mobile-portrait](https://user-images.githubusercontent.com/78549195/126868092-654c2ecb-72e6-4043-9559-1653d94f4386.png)
![mobile-landscape](https://user-images.githubusercontent.com/78549195/126868097-4925437f-5586-401f-97d8-06fcfba2c3c2.png)
![tablet-portrait](https://user-images.githubusercontent.com/78549195/126868098-bcf6fa37-3aa4-47d3-b88b-1a1c54dffab0.png)
![tablet-landscape](https://user-images.githubusercontent.com/78549195/126868100-f981a9fe-2625-4e83-995b-95b919d80c88.png)

Screenshots after merging into a single file.
![mobile-portrait](https://user-images.githubusercontent.com/78549195/126868118-9dec668f-9941-45da-a560-78523fc9f5d2.png)
![mobile-landscape](https://user-images.githubusercontent.com/78549195/126868123-e6685e0b-62b1-419b-938c-051ef3b1f63e.png)
![tablet-landscape](https://user-images.githubusercontent.com/78549195/126868130-915098c1-767d-4379-81a1-456e70692296.png)
![tablet-portrait](https://user-images.githubusercontent.com/78549195/126868131-c2ea86e9-f42a-4f9f-88d1-d99a2eee27f1.png)

Earlier it crashed when in the tablet landscape mode but not the dimension does not match as before because of 
android:layout_width="match_parent"
which was 560dp in the original version of the landscape

2021-07-24 19:23 UTC, prayutsu requested changes
@rishidyno Please follow the PR checklist and link the related issue with the PR.
Also please revert the unwanted changes.

2021-07-24 19:23 UTC, prayutsu commented on .idea/misc.xml
> +</project>
These changes are unwanted, revert them.

2021-07-24 19:23 UTC, prayutsu commented on .idea/runConfigurations.xml
>        </set>
Ditto

2021-07-26 10:23 UTC, rishidyno commented
@prayutsu I have done some changes to the code but am still not able to resolve the issue but working on it.

2021-07-26 17:34 UTC, rishidyno commented
This PR had some issues so will close it and I have created a new PR -> https://github.com/oppia/oppia-android/pull/3526

2021-07-26 17:34 UTC, closed without merging