Merge completed activity into single file
oppia/oppia-android pull request #3689
Opened 2021-08-16 16:19 UTC by vrajdesai78

## Explanation
I have merged completed_story_item and completed_story_list_fragment into single files by giving it's dimension in dimens.xml file. 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-08-23 18:48 UTC, rt4914 commented
@vrajdesai78 I think you will need to update your branch by merging with latest develop.

2021-08-28 13:13 UTC, vrajdesai78 commented
@rt4914 Please review my pull request

2021-08-30 18:04 UTC, rt4914 requested changes
@vrajdesai78 PTAL.

Thanks.

2021-08-30 18:04 UTC, rt4914 commented on app/src/main/res/values-sw600dp-port/dimens.xml
> +  <dimen name="completed_story_item_topic_container_marginTop">36dp</dimen>
Please add bottom margin as `0dp` otherwise it will end up using value from `layout/dimens.xml` file which is `12dp`.

2021-08-30 18:04 UTC, rt4914 commented on app/src/main/res/values-sw600dp-land/dimens.xml
> +  <dimen name="completed_story_item_topic_container_marginTop">32dp</dimen>
Please add bottom margin as 0dp otherwise it will end up using value from layout/dimens.xml file which is 12dp.

2021-08-30 18:04 UTC, rt4914 commented on app/src/main/res/values/dimens.xml
> +  <dimen name="completed_story_list_fragment_recyclerview_paddingBottom">144dp</dimen>
Change the naming convention to
`completed_story_list_fragment_recyclerview_padding_bottom`

Basically keep all characters small and all words separated by `_`.

Apply this everywhere.

2021-09-01 16:51 UTC, rt4914 commented
@vrajdesai78 Please do not resolve comments. Actually you should reply to the comments mentioning whether they are done or not and based on your reply I will review it and then if needed I will resolve the comment.

2021-09-01 16:52 UTC, rt4914 approved these changes
LGTM, thanks.

2021-09-01 16:52 UTC, merged

2021-09-01 16:56 UTC, vrajdesai78 commented
> @vrajdesai78 Please do not resolve comments. Actually you should reply to the comments mentioning whether they are done or not and based on your reply I will review it and then if needed I will resolve the comment.

Ok next time I won't resolve comments. Thank you for merging my pull request.