Fix #1951: hints_summary.xml optimised
oppia/oppia-android pull request #3706
Opened 2021-08-19 04:49 UTC by arinarora18

## Explanation

Fixes #1951: This PR optimises the hints_summary.xml for mobile and tablet devices for both portrait and landscape orientation. 
 
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-08-19 04:54 UTC, arinarora18 commented
Portrait before and after:
<img width="318" alt="Portrait before" src="https://user-images.githubusercontent.com/70138233/130009755-9b6fa87d-37ad-4c0d-aa90-c1cc1e4b3d86.png">
<img width="318" alt="Portrait after" src="https://user-images.githubusercontent.com/70138233/130009752-1e33109c-bdcb-4b72-bf45-45407fc87cfe.png">

Landscape before and after:
<img width="648" alt="Landscape before" src="https://user-images.githubusercontent.com/70138233/130009746-033d5ddb-8545-4bd6-b263-32b57d50b112.png">
<img width="648" alt="Landscape after" src="https://user-images.githubusercontent.com/70138233/130009732-2ff155d9-da7f-467c-8803-952e7ed0d3d1.png">

Portrait before and after(tablet):
<img width="358" alt="Portrait before (tablet)" src="https://user-images.githubusercontent.com/70138233/130009756-27596e21-7223-4b91-9181-661c29c38e53.png">
<img width="359" alt="Portrait after(tablet)" src="https://user-images.githubusercontent.com/70138233/130009754-2e4b641a-85e8-41bc-96a6-bc6e24b53c77.png">

Landscape before and after(tablet):
<img width="642" alt="Landscape before(tablet)" src="https://user-images.githubusercontent.com/70138233/130009750-79178a55-0a8b-4e10-b8dc-aa5b9434e513.png">
<img width="644" alt="Landscape after(tablet)" src="https://user-images.githubusercontent.com/70138233/130009745-41095bf5-0f5b-495d-8102-f47a92293000.png">

2021-08-21 03:24 UTC, arinarora18 commented
@anandwana001 any updates?

2021-08-21 10:43 UTC, anandwana001 requested changes
Thanks @arinarora18 for you first PR. 

Rather than updating all the UI files in terms of views, could you follow an approach where we first can look at all the common things like margins, padding, and then you can see the view component tree in the android studio on in layout editor if views are same and their margin, padding is different then fetch the margin and padding from the respective dimension file. 

https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources

2021-08-21 10:43 UTC, anandwana001 commented on .idea/misc.xml
> +  <component name="DesignSurface">
please don't make any changes to this file.

2021-08-21 10:43 UTC, anandwana001 commented on .idea/runConfigurations.xml
> -      </set>
please don't make any changes to this file.

2021-08-23 12:36 UTC, rt4914 requested changes
@arinarora18 I suggested not doing this PR directly as it will make this really hard to review.

Instead I suggested first focus on this issue https://github.com/oppia/oppia-android/issues/3537 and solve this first. Once it gets solved, then solve this issues.

Reason behind this suggestions:
Currently develop contains 4 files for `hints_summary.xml`.
Once you solve #3537 and it gets merged you will have only 1 file in develop.
Now solve that one single file and optimising it, is much more easier.

Also please have look at [this](https://github.com/oppia/oppia-android/wiki/Working-on-UI) too. 

Thanks.

2021-09-06 14:07 UTC, closed without merging