Fix #3324: Created BUILD.bazel in oppialogger inside domain module
oppia/oppia-android pull request #3739
Opened 2021-08-26 06:53 UTC by deepanshu731

Fixed #3324 
Created a BUILD.bazel file in oppialogger package inside domain.
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2021-08-27 08:04 UTC, BenHenning commented
Hi @deepanshu731. My apologies for the delay--I'll need to take a look at this tomorrow.

2021-09-02 09:19 UTC, BenHenning commented
Hi--sorry again about the delay. I still plan to look at this later in the week; I've just had some project emergencies to deal with in the meantime. Thanks for your patience.

2021-09-03 06:09 UTC, deepanshu731 commented
> Hi--sorry again about the delay. I still plan to look at this later in the week; I've just had some project emergencies to deal with in the meantime. Thanks for your patience.

Its okay @BenHenning

2021-09-21 01:01 UTC, BenHenning requested changes
Thanks @deepanshu731! This looks really solid! Just had a few comments.

Sorry for the extended delay--I plan to prioritize this PR moving forward.

2021-09-21 01:01 UTC, BenHenning commented on domain/src/main/java/org/oppia/android/domain/oppialogger/BUILD.bazel
> +Library for providing logging to the Oppia Android app.
Perhaps instead: ``Package for providing logging support.`` (it's implied that this is for the app, and technically this package can contain multiple libraries)

Ditto for other new BUILD files.

2021-09-21 01:01 UTC, BenHenning commented on domain/src/main/java/org/oppia/android/domain/oppialogger/exceptions/BUILD.bazel
> +    visibility = ["//domain:__pkg__"],
Maybe testing visibility, instead?

2021-09-21 01:01 UTC, BenHenning commented on domain/BUILD.bazel
> +    "src/main/java/org/oppia/android/domain/oppialogger/*.kt",
```suggestion
    "src/main/java/org/oppia/android/domain/oppialogger/**/*.kt",
```

(since sub-packages are also included)

2021-09-21 01:01 UTC, BenHenning commented on app/BUILD.bazel
> +        "//domain/src/main/java/org/oppia/android/domain/oppialogger/loguploader:worker_module",
Shouldn't these be deps for "app"?

2021-09-23 15:50 UTC, deepanshu731 commented on domain/src/main/java/org/oppia/android/domain/oppialogger/BUILD.bazel
> +Library for providing logging to the Oppia Android app.
done

2021-09-23 15:50 UTC, deepanshu731 commented on app/BUILD.bazel
> +        "//domain/src/main/java/org/oppia/android/domain/oppialogger/loguploader:worker_module",
done

2021-09-23 15:50 UTC, deepanshu731 commented on domain/BUILD.bazel
> +    "src/main/java/org/oppia/android/domain/oppialogger/*.kt",
done

2021-09-23 15:51 UTC, deepanshu731 commented on domain/src/main/java/org/oppia/android/domain/oppialogger/exceptions/BUILD.bazel
> +    visibility = ["//domain:__pkg__"],
done

2021-09-24 08:49 UTC, deepanshu731 commented
@BenHenning these tests are failing after updating from develop (Did to resolve merge conflict) maybe some realted to databinding are failing where i didnt change anything  , Can you help me out with this ?

2021-09-26 04:04 UTC, BenHenning requested changes
Thanks @deepanshu731. Had just a few more comments, but this PR is looking good to me overall.

> @BenHenning these tests are failing after updating from develop (Did to resolve merge conflict) maybe some realted to databinding are failing where i didnt change anything , Can you help me out with this ?

This is a CI flake (see #3759). Restarting should fix it, but given that I requested a couple more changes you could probably just push a new commit with those fixes & CI should pass on the re-run.

2021-09-26 04:04 UTC, BenHenning commented on domain/src/main/java/org/oppia/android/domain/oppialogger/analytics/BUILD.bazel
> +Package for providing logging analytics.
```suggestion
Package for providing logging support for analytics events.
```

2021-09-26 04:04 UTC, BenHenning commented on domain/src/main/java/org/oppia/android/domain/oppialogger/exceptions/BUILD.bazel
> +Package for providing logging exception.
```suggestion
Package for providing logging support for exceptions.
```

2021-09-26 04:55 UTC, deepanshu731 commented on domain/src/main/java/org/oppia/android/domain/oppialogger/analytics/BUILD.bazel
> +Package for providing logging analytics.
done

2021-09-26 04:55 UTC, deepanshu731 commented on domain/src/main/java/org/oppia/android/domain/oppialogger/exceptions/BUILD.bazel
> +Package for providing logging exception.
done

2021-09-26 05:54 UTC, deepanshu731 commented
> Thanks @deepanshu731. Had just a few more comments, but this PR is looking good to me overall.
> 
> > @BenHenning these tests are failing after updating from develop (Did to resolve merge conflict) maybe some realted to databinding are failing where i didnt change anything , Can you help me out with this ?
> 
> This is a CI flake (see #3759). Restarting should fix it, but given that I requested a couple more changes you could probably just push a new commit with those fixes & CI should pass on the re-run.

Thanks @BenHenning PTAL.

2021-09-27 07:47 UTC, BenHenning approved these changes
Thanks @deepanshu731. PR LGTM! Thanks so much for your patience with the slow reviews.

2021-09-27 07:47 UTC, merged