Fix #3587: Merge topic revision fragments
oppia/oppia-android pull request #3816
Opened 2021-09-18 20:02 UTC by ayaazansari

Fixes #3587 
Merged the 4 topic revision-fragment xmls (landscape/portrait of phone and tablet )into one revision-fragment .

2021-09-18 21:16 UTC, ayaazansari commented
@rt4914 I'm getting this error when I try to open the fragment in the emulator please help!!
java.lang.IllegalArgumentException: The tag for topic_revision_fragment is invalid. Received: layout-sw600dp-port/topic_revision_fragment_0

2021-09-24 19:53 UTC, rt4914 requested changes
Thanks.

Please add before and after screenshot for this UI.

Also, once you remove tablet related files, make sire you install the app from tablet device, rebuild the app and then install the app again on tablet and it should work correctly.

2021-09-24 19:53 UTC, rt4914 commented on app/src/main/res/values-land/dimens.xml
> +  <dimen name="topic_revision_fragment_paddingStart">56dp</dimen>
Rename this and all other dimens name to `topic_revision_fragment_paddingStart `.
Basically all names should contain only small-characters separated by `_`.

2021-09-24 19:53 UTC, rt4914 commented on app/src/main/res/values-land/dimens.xml
> +  <!-- Topic Revision Fragment -->
Rename to ` <!-- TopicRevisionFragment -->`

2021-10-01 11:32 UTC, ayaazansari commented
@rt4914 PTAL

2021-10-03 20:00 UTC, rt4914 approved these changes
LGTM, thanks.

2021-10-03 20:00 UTC, rt4914 commented on app/src/main/res/layout/topic_revision_fragment.xml
> +      android:paddingStart ="@dimen/topic_revision_fragment_padding_start"
There is this space before `=`. Please remove it

2021-10-03 20:00 UTC, rt4914 requested changes
One nit change suggested above.

2021-10-04 10:30 UTC, ayaazansari commented on app/src/main/res/layout/topic_revision_fragment.xml
> +      android:paddingStart ="@dimen/topic_revision_fragment_padding_start"
@rt4914 done.

2021-10-05 13:30 UTC, rt4914 commented
@ayaazansari Please merge this latest develop as there are merge conflicts as I had just merged a couple of PRs.

2021-10-05 18:48 UTC, ayaazansari commented
@rt4914 done

2021-10-06 19:00 UTC, rt4914 approved these changes
LGTM, thanks.

2021-10-06 19:00 UTC, merged