Fix #3582: Merge topic lesson title
oppia/oppia-android pull request #3831
Opened 2021-09-22 17:40 UTC by ayaazansari

Fixed #3582 
Merged the 4 topic_lessons_title.xml (landscape/portrait of phone and tablet )into single xml file .

2021-09-22 17:57 UTC, ayaazansari commented
@rt4914 I'm getting this error when I try to open the fragment in the tablet portrait mode ,please help!
error: java.lang.IllegalArgumentException: The tag for topic_lessons_title is invalid. Received: layout-sw600dp-port/topic_lessons_title_0

2021-09-24 19:52 UTC, rt4914 requested changes
Thanks.

Please add before and after screenshot for this UI.

Also, once you remove tablet related files, make sire you install the app from tablet device, rebuild the app and then install the app again on tablet and it should work correctly.

2021-09-24 19:52 UTC, rt4914 commented on .idea/misc.xml
> +</project>
We don't need any change to `.idea` file, this must have been done automatically from android studio please do not add this file to your commit. 
Note: Don't delete this file, we need this file we just don't need the changes this file contains.

2021-09-24 19:52 UTC, rt4914 commented on app/src/main/res/values-land/dimens.xml
> +  <dimen name="topic_lessons_title_marginStart">100dp</dimen>
Rename this and all other dimens name to `topic_lessons_title_margin_start `.
Basically all names should contain only small-characters separated by `_`.

2021-10-02 20:07 UTC, ayaazansari commented
@rt4914 after those changes I'm getting the wrong layout , the "Stories you can play" title comes to the starting without any margin..
![Screenshot_1633183770](https://user-images.githubusercontent.com/65058484/135730493-a05d958f-75ed-4155-bdc5-ab688838441d.png)

2021-10-05 12:45 UTC, rt4914 requested changes
You are getting the wrong output because the TextView `topic_play_text_view ` width is `wrap_content` in some layouts and `528dp` fixed in some layouts.
You might beed to use `ConstraintLayout` to handle is correctly.

2021-10-05 12:45 UTC, rt4914 commented on .idea/misc.xml
> +</project>
@ayaazansari PTAL

2021-10-05 12:45 UTC, rt4914 commented on app/src/main/res/values-land/dimens.xml
> +  <dimen name="topic_lessons_title_marginStart">100dp</dimen>
@ayaazansari PTAL

2021-10-05 12:51 UTC, rt4914 commented
@ayaazansari PTAL

2021-10-05 19:23 UTC, ayaazansari commented
@rt4914 what layout width should I use for port,land of phone and port,land of tablet ?

2021-10-06 18:59 UTC, rt4914 commented
> @rt4914 what layout width should I use for port,land of phone and port,land of tablet ?

[Mobile Portrait](https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/4705f47b-9ada-4159-8b81-8db32cd3737d/)
- Width = Variable
- Margins = Fixed (as mentioned in mocks)

[Mobile Landscape](https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/f0c4284e-f2a6-4052-98e2-778932290c08/specs/)
- Width = Variable
- Margins = Fixed (as mentioned in mocks)

[Tablet Portrait](https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/a98b7a3c-46c4-49c6-af77-14a1ff5b7b03/)
- Width = 528dp (as mentioned in mocks)
- Margins = Variable

[Tablet Landscape](https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/28b4ea3f-6436-4e8f-a737-28373f56525b/)
- Width = 528dp (as mentioned in mocks)
- Margins = Variable


You might need to implement `ConstraintLayout` inside `ConstraintLayout` to achieve this.

2021-10-20 19:52 UTC, closed without merging