Changes for making the file RTL compatible
oppia/oppia-android pull request #3847
Opened 2021-09-27 07:14 UTC by bkaur-bkj

## Explanation

Fixes #3807 By removing the right constraints from the xml file 
removed the file name from exempted files list

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passin
![WhatsApp Image 2021-09-27 at 12 21 58 PM (1)](https://user-images.githubusercontent.com/64087572/134861254-903964a3-7e68-46a0-a48b-e1f90b3dd04e.jpeg)

![WhatsApp Image 2021-09-27 at 12 21 58 PM](https://user-images.githubusercontent.com/64087572/134861282-9775608a-bf7e-4c28-8513-e14be14494e0.jpeg)

Added a screenshot for the normal app view and view after selecting force RTL layout. Both were similar to as of before  the changes were made.

2021-09-27 07:48 UTC, rt4914 requested changes
@bkaur-bkj Thanks. There is one `git` file visible in `Files Changed` section. Just get rid of it and then the tests should pass. The `Files Changed` section should contain only those files to which you have made changes.

2021-09-27 08:04 UTC, bkaur-bkj commented
> @bkaur-bkj Thanks. There is one `git` file visible in `Files Changed` section. Just get rid of it and then the tests should pass. The `Files Changed` section should contain only those files to which you have made changes.

Yes sir made the changes

2021-09-27 09:02 UTC, bkaur-bkj commented
@rt4914 PTAL on this failed check https://github.com/oppia/oppia-android/pull/3847/checks?check_run_id=3717818072#step:15:1548

2021-09-28 14:23 UTC, rt4914 approved these changes
LGTM, thanks.

2021-09-29 11:56 UTC, BenHenning approved these changes
LGTM, thanks @bkaur-bkj!

2021-09-29 11:57 UTC, merged