deleted-land-and-land(sw-600)-and-added-needed-dimensions-to-dimensio…
oppia/oppia-android pull request #3878
Opened 2021-10-04 21:17 UTC by rishidyno

Fix #3585
…ns-file

## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2021-10-04 21:25 UTC, rishidyno commented
@rt4914 in this particular PR the app is not working in tablet landscape mode. The reason for this is what I could think of is we have a constraint layout in a frame layout for land tablet mode and its UI is quite different from normal mobile mode. So I think we will only be able to merge it only into 3 layout files.  

If there is a solution to this please let me know I will work accordingly.

2021-10-05 12:25 UTC, rt4914 requested changes
@rishidyno For this PR you might need to make some extra efforts.
1. We don't need FrameLayout. We only need ConstraintLayout.
2. Based on above statement create a single file such that the before/after UI in all configurations is same.

Also, considering you have already been onboarded, suggest on picking up `good-first-issues`. Also you are part of CLaM team (you might have received an email regarding the same around 4 Sep) so you should pick issues from https://github.com/oppia/oppia-android/projects/13

2021-10-05 13:27 UTC, rishidyno commented
> @rishidyno For this PR you might need to make some extra efforts.
> 
> 1. We don't need FrameLayout. We only need ConstraintLayout.
> 2. Based on above statement create a single file such that the before/after UI in all configurations is same.
> 
> Also, considering you have already been onboarded, suggest on picking up `good-first-issues`. Also you are part of CLaM team (you might have received an email regarding the same around 4 Sep) so you should pick issues from https://github.com/oppia/oppia-android/projects/13

Ok! got it. Thanks!.

2021-10-05 17:36 UTC, rishidyno commented
@rt4914  I have made the required changes PTAL.

2021-10-06 18:52 UTC, rt4914 requested changes
@rishidyno PTAL

2021-10-06 18:52 UTC, rt4914 commented on app/src/main/res/values-sw600dp-land/dimens.xml
> +  <dimen name="topic_practice_header_view_constraint_layout_layout_margin_start">460dp</dimen>
This approach will actually create problems because if the tablet device is smaller than `460dp` may end up shifting this UI towards the right-side of screen. (You can test this on Tablet Nexus 7).

From[ tablet mocks](https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/3ff75dc6-0e6a-447a-9d13-998fb58e39c4/) I can say that the width should remain fixed(360dp) in case of tablet and for mobile the margins should remain fixed (similar to what you have right now for mobile.). You might need to do this by implementing `ConstraintLayout` inside `ConstraintLayout` to achieve this.

2021-10-06 18:52 UTC, rt4914 commented on app/src/main/res/values-sw600dp-port/dimens.xml
> +
Remove this extra blank line.

2021-10-06 18:52 UTC, rt4914 commented on app/src/main/res/values-sw600dp-port/dimens.xml
> +  <!-- Topic Practice Header View-->
Always add space before/after the text
`<!-- Topic Practice Header View -->`

2021-10-06 18:52 UTC, rt4914 commented on app/src/main/res/values-sw600dp-port/dimens.xml
> +  <!-- Topic Practice Header View-->
Ditto for other files.

2021-11-02 17:10 UTC, closed without merging