Fix part of #3602: Added label for ProfilePictureActivity
oppia/oppia-android pull request #3881
Opened 2021-10-05 16:51 UTC by deepanshu731

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2021-10-06 03:24 UTC, rt4914 requested changes
@deepanshu731 PTAL. Also please add screenshot displaying test case is passing on Espresso.

2021-10-06 03:24 UTC, rt4914 commented on app/src/main/res/values/strings.xml
> +  <string name="profile_picture_activity_title">profile picture activity</string>
Update to <string name="profile_picture_activity_title">Profile Picture</string>

2021-10-07 03:05 UTC, deepanshu731 commented on app/src/main/res/values/strings.xml
> +  <string name="profile_picture_activity_title">profile picture activity</string>
done

2021-10-08 15:37 UTC, rt4914 approved these changes
LGTM, thanks.

2021-10-09 02:36 UTC, BenHenning requested changes
Thanks @deepanshu731. Just had one follow-up comment, PTAL.

2021-10-09 02:36 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +  val activityTestRule: ActivityTestRule<ProfilePictureActivity> = ActivityTestRule(
This rule is actually deprecated. Can we use ActivityScenario or ActivityScenarioRule, instead? There are a bunch of tests that use these two patterns for reference.

2021-10-12 11:24 UTC, deepanshu731 commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +  val activityTestRule: ActivityTestRule<ProfilePictureActivity> = ActivityTestRule(
done

2021-10-13 01:04 UTC, BenHenning reviewed
Thanks @deepanshu731! The new test looks good, just had one other comment. PTAL.

2021-10-13 01:04 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +    )
We should use ``use`` here, like so:

```kotlin
launch(ProfilePictureActivity::class.java).use { scenario ->
  scenario.onActrivity { activity ->
...
```

This ensures the scenario is 'closed' (which shuts down the activity in Espresso tests).

2021-10-13 06:19 UTC, deepanshu731 commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +    )
done

2021-10-14 05:23 UTC, BenHenning approved these changes
Thanks @deepanshu731! LGTM.

2021-10-14 05:24 UTC, BenHenning commented
Merging since all conversations are resolved & all approvals are presednt.

2021-10-14 05:24 UTC, merged