Fixes #3564  Merge profile progress header xml
oppia/oppia-android pull request #3885
Opened 2021-10-05 19:35 UTC by bkaur-bkj

## Explanation

Fixes #3564  
merged portrait and landscape files of tab layout, could not merge the mobile layout files as they had some constraints and other differences too.
## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2021-10-05 19:42 UTC, bkaur-bkj commented
@rt4914  PTAL, as discussed I made a PR merging the 2 tab layout files but it says some conflicts I tried viewing them but got no idea how to resolve them and not understood the issue.

2021-10-06 09:19 UTC, bkaur-bkj commented
@rt4914, I resolved the conflicts but one test is failing

2021-10-06 18:40 UTC, rt4914 commented
@bkaur-bkj As mentioned in the issue description please  add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

2021-10-06 18:41 UTC, rt4914 commented
> @rt4914, I resolved the conflicts but one test is failing

@bkaur-bkj The test which is failing is an optional one and also it mostly is failing on develop too so don't worry about it in this PR.

2021-10-07 08:06 UTC, bkaur-bkj commented
@rt4914 I have added ss for mobile portrait and landscape but I tried for tablet it crashes, as I tried merging the landscape and portrait layout of tablet I removed tablet landscape layout and tried running at app on tab, it was fine with portrait but crashed in landscape so I changed the folder of the file and placed the file profile_progress_header in the layout/swa600dp/ folder. But it not crases for portrait layout too.
pls let me know what change should I do

2021-10-08 15:39 UTC, rt4914 commented
> @rt4914 I have added ss for mobile portrait and landscape but I tried for tablet it crashes, as I tried merging the landscape and portrait layout of tablet I removed tablet landscape layout and tried running at app on tab, it was fine with portrait but crashed in landscape so I changed the folder of the file and placed the file profile_progress_header in the layout/swa600dp/ folder. But it not crases for portrait layout too. pls let me know what change should I do

@bkaur-bkj For tablet follow these steps:
1. Uninstall the app
2. `Build` -> `Rebuild` the project.
3. Now install the app.
Basically whenever we remove any xml file for tablet we need to uninstall the previous version and install the fresh build.

2021-10-08 15:39 UTC, rt4914 commented
@bkaur-bkj Also please merge with latest develop as there are conflicts currently.

2021-10-08 18:40 UTC, bkaur-bkj commented
> @bkaur-bkj Also please merge with latest develop as there are conflicts currently.

Yes sir Done

2021-10-08 18:40 UTC, bkaur-bkj commented
> > @rt4914 I have added ss for mobile portrait and landscape but I tried for tablet it crashes, as I tried merging the landscape and portrait layout of tablet I removed tablet landscape layout and tried running at app on tab, it was fine with portrait but crashed in landscape so I changed the folder of the file and placed the file profile_progress_header in the layout/swa600dp/ folder. But it not crases for portrait layout too. pls let me know what change should I do
> 
> @bkaur-bkj For tablet follow these steps:
> 
> 1. Uninstall the app
> 2. `Build` -> `Rebuild` the project.
> 3. Now install the app.
>    Basically whenever we remove any xml file for tablet we need to uninstall the previous version and install the fresh build.

yes done worked now

2021-10-08 18:47 UTC, rt4914 requested changes
@bkaur-bkj PTAL

2021-10-08 18:47 UTC, rt4914 commented on app/src/main/res/values-sw600dp-land/dimens.xml
> +  <!-- Profile Progress Header-->
Space before and after the text
`<!-- Profile Progress Header -->`

2021-10-08 18:47 UTC, rt4914 commented on app/src/main/res/values-sw600dp-port/dimens.xml
> +  <!-- Profile Progress Header-->
Ditto

2021-10-08 18:47 UTC, rt4914 commented on app/src/main/res/values/dimens.xml
> +  <!-- Profile Progress Header-->
Ditto

2021-10-08 18:47 UTC, rt4914 commented on app/src/main/res/values/dimens.xml
> +  <dimen name="view_all_textview_margin_end">24dp</dimen>
These values should be `0dp`  and also add a comment on top mentioning this:
`These values are getting used only in tablet mode and therefore mentioned as 0dp here.`

2021-10-09 06:15 UTC, bkaur-bkj commented on app/src/main/res/values/dimens.xml
> +  <dimen name="view_all_textview_margin_end">24dp</dimen>
done

2021-10-09 06:15 UTC, bkaur-bkj commented on app/src/main/res/values/dimens.xml
> +  <!-- Profile Progress Header-->
done

2021-10-09 06:15 UTC, bkaur-bkj commented on app/src/main/res/values-sw600dp-port/dimens.xml
> +  <!-- Profile Progress Header-->
done

2021-10-09 06:15 UTC, bkaur-bkj commented on app/src/main/res/values-sw600dp-land/dimens.xml
> +  <!-- Profile Progress Header-->
done

2021-10-14 06:43 UTC, rt4914 requested changes
One comment left.
@bkaur-bkj PTAL

2021-10-14 06:43 UTC, rt4914 commented on app/src/main/res/values/dimens.xml
> +  <dimen name="recently_played_stories_textView_layout_margin_start">0dp</dimen>
There is inconsistency in writing the word `TextView`. You have written it as `textView` as well as `textview`. 

Please use following `text_view`.

This change will affect almost all files.

2021-10-14 08:02 UTC, bkaur-bkj commented on app/src/main/res/values/dimens.xml
> +  <dimen name="recently_played_stories_textView_layout_margin_start">0dp</dimen>
okay sir

2021-10-14 10:03 UTC, bkaur-bkj commented
@rt4914 PTAL

2021-10-14 18:20 UTC, rt4914 approved these changes
LGTM, thanks.

2021-10-14 18:20 UTC, merged