Fix oppia#3581
oppia/oppia-android pull request #3889
Opened 2021-10-06 10:07 UTC by puranjayK

## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2021-10-06 10:44 UTC, puranjayK commented
@rt4914 PTAL

2021-10-06 18:39 UTC, rt4914 commented
@puranjayK Thanks for the PR. As mentioned in the issue description add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

2021-10-06 19:49 UTC, puranjayK commented
I have updated the comment
@rt4914 PTAL

2021-10-08 15:42 UTC, rt4914 requested changes
@puranjayK Please add tablet mobile/portrait before/after screenshots too.


**Note**:
Whenever you remove a tablet xml file you will need to perform following steps to see the fresh changes.
1. Uninstall the previous app.
2. `Build` -> `Rebuild` the app.
3. Install the app again.

2021-10-08 15:42 UTC, rt4914 commented on app/src/main/res/values-land/dimens.xml
> +  <!--  Topic Lessons Story Summary-->
Update to
`<!-- Topic Lessons Story Summary -->`

Basically one space before and after the text. Currently you have 2 space before and 0 space after.

Ditto for other files.

2021-10-08 15:42 UTC, rt4914 commented on app/src/main/res/values/dimens.xml
> +<!--  Topic Lessons Story Summary-->
The alignment of comment is incorrect. It should start from where you below line is starting.

2021-10-09 09:14 UTC, puranjayK commented
@rt4914
I'm getting the wrong layout in the tablet mode. 
The lesson story summary cardview had "layout_gravity=centre" attribute earlier in the XML file. Can you please tell what are the margins in the tablet mode.
<img src="https://user-images.githubusercontent.com/85157266/136652036-9ebee03d-5fbe-459d-92c1-60a4c8ad54af.png" width = 500/>

<img src="https://user-images.githubusercontent.com/85157266/136652210-8ce1a2bc-4650-40f5-8c82-8469cbcfd4fa.png" height = 500/>

2021-10-09 09:16 UTC, puranjayK commented on app/src/main/res/values-land/dimens.xml
> +  <!--  Topic Lessons Story Summary-->
Done

2021-10-09 09:16 UTC, puranjayK commented on app/src/main/res/values/dimens.xml
> +<!--  Topic Lessons Story Summary-->
Done

2021-10-16 10:36 UTC, rt4914 commented
@puranjayK For tablet the content width is fixed instead of margin. Have a look https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/a98b7a3c-46c4-49c6-af77-14a1ff5b7b03/

2021-10-16 15:03 UTC, puranjayK commented
@rt4914 
How should I keep the card view in centre then?

2021-10-18 19:24 UTC, rt4914 commented
> @rt4914 How should I keep the card view in centre then in tablet mode?

@puranjayK Either introduce constraints or use layout_gravity. Or else instead of merging it to single file merging it to 2/3 files which can work best for the app.

2021-10-19 21:09 UTC, puranjayK commented
> > @rt4914 How should I keep the card view in centre then in tablet mode?
> 
> @puranjayK Either introduce constraints or use layout_gravity. Or else instead of merging it to single file merging it to 2/3 files which can work best for the app.

Merged the files into 2 XML files.
Updated the comment with screenshots

2021-10-25 05:23 UTC, puranjayK commented
> > > @rt4914 How should I keep the card view in centre then in tablet mode?
> > 
> > 
> > @puranjayK Either introduce constraints or use layout_gravity. Or else instead of merging it to single file merging it to 2/3 files which can work best for the app.
> 
> Merged the files into 2 XML files. Updated the comment with screenshots

@rt4914 PTAL

2021-10-31 09:56 UTC, rt4914 requested changes
@puranjayK PTAL

The `story_name_chapter_count_container` TextView has different `layout_marginStart` for tablet landscape and portrait.

2021-10-31 10:06 UTC, puranjayK commented
> @puranjayK PTAL
> 
> The `story_name_chapter_count_container` TextView has different `layout_marginStart` for tablet landscape and portrait.
> 
> Also, please merge with latest develop too.

@rt4914 I will make the necessary changes. Till then is it possible if you could add "hacktoberfest-accepted" label to the PR?

2021-11-03 21:16 UTC, rt4914 commented
@puranjayK I am not sure about that. I will talk to @BenHenning about this.

2021-11-03 22:03 UTC, BenHenning commented
Hi @puranjayK. Sorry for not following up earlier. For Oppia Android, we only consider PRs accepted for Hacktoberfest when they've been merged since that ensures that we can maintain a consistent quality bar across all contributions to the project.

Please let me know if you have any further questions.

2021-11-03 22:03 UTC, rt4914 commented
@puranjayK This PR cannot be labelled for `Accepted`. I do understand that part of this was delayed PR review but we need multiple PRs for hacktoberfest and also that too merged before 31st Oct.
https://hacktoberfest.digitalocean.com/faq

2021-11-18 16:56 UTC, rt4914 commented
Closing this PR because of inactivity.

2021-11-18 16:56 UTC, closed without merging