Fix #3788: Break `*Required` into two parts.
oppia/oppia-android pull request #3890
Opened 2021-10-06 11:32 UTC by rishidyno

Fix #3788
## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2021-10-06 12:29 UTC, rishidyno commented
@rt4914 when i get the string resource for *Required 
`val starRequired: String = Resources.getSystem().getString(R.string.add_profile_required)`
the app keeps crashing when i open add_profie_activity but not in the case of 
val starRequired: String = "*Required"

2021-10-06 18:45 UTC, rt4914 requested changes
@rishidyno PTAL

2021-10-06 18:45 UTC, rt4914 commented on app/src/main/java/org/oppia/android/app/profile/AddProfileViewModel.kt
> +  val starRequired: String = "*Required"
Here `*` should be mentioned here by `required` should come from `strings.xml` file.

Also whatever error you are getting can you mention it here or create a [debugging doc](https://github.com/oppia/oppia/wiki/Debugging-Docs) mentioning what steps you performed and what errors you got.

2021-10-06 18:45 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/profile/AddProfileActivityTest.kt
> +    assertThat(label).isEqualTo(context.getString(R.string.add_profile_required))
This test case has been written incorrectly. Please check below test case in this file `testAddProfileActivity_inputName_opensProfileChooserActivity ` and implement a test similar to that.

2021-10-07 16:09 UTC, rishidyno commented on app/src/main/java/org/oppia/android/app/profile/AddProfileViewModel.kt
> +  val starRequired: String = "*Required"
I did not get this properly could you please make it clear to me again.

2021-10-08 19:10 UTC, rt4914 commented on app/src/main/java/org/oppia/android/app/profile/AddProfileViewModel.kt
> +  val starRequired: String = "*Required"
Part 1 of string = *
Part 2 of string = Required.

Part 2 should be mentioned in `strings.xml` file. and Part 1 should be directly inside kotlin.
@rishidyno If this does not make sense ping me and we can meet.

2021-10-14 18:18 UTC, rt4914 commented
@rishidyno Any updates?

2021-10-15 10:15 UTC, rishidyno commented
> @rishidyno Any updates?

@rt4914  Sorry! I was away because of my personal work. I will continue now.

2021-10-18 13:40 UTC, rishidyno commented
> @rishidyno Any updates?

@rt4914 I am actually out of station for work. I will continue on 20th

2021-10-22 06:01 UTC, rishidyno commented
![Screenshot from 2021-10-22 12-24-10](https://user-images.githubusercontent.com/78549195/138407300-a13b1b02-9272-44eb-b78b-1890192e9b84.png)


@rt4914 here I am getting an unresolved reference error could you please help me out with this.
 Also, please give a verdict on the test I have written.

2021-12-09 18:52 UTC, closed without merging