Fixes #3900 : Added toolbar to exit ProfilePictureActivity
oppia/oppia-android pull request #3918
Opened 2021-10-09 17:14 UTC by bkaur-bkj

## Explanation

Fixes #3900: Added toolbar to exit the ProfilePictureActivity

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

After adding the toolbar and shadow

![WhatsApp Image 2021-10-16 at 7 29 15 PM](https://user-images.githubusercontent.com/64087572/137590342-6c7a54d7-789b-4710-8578-e040996c92f7.jpeg)

2021-10-12 02:45 UTC, BenHenning requested changes
Thanks @bkaur-bkj. Left some initial thoughts--PTAL.

2021-10-12 02:45 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureActivityPresenter.kt
> +    activity.supportActionBar!!.setTitle(R.string.profile_photo)
Does this activity not already have a title? I'd expect to reuse the same one rather than defining a new string.

2021-10-12 02:45 UTC, BenHenning commented on app/src/main/res/values/strings.xml
> +  <string name="profile_photo">Profile Photo</string>
Should be: profile_photo_activity_title.

2021-10-12 02:45 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureActivityPresenter.kt
> +  private fun setUpNavigationDrawer() {
Probably should be ``setUpToolbar``; this isn't actually setting up a navigation drawer.

2021-10-12 02:45 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureActivityPresenter.kt
> +    activity.supportActionBar!!.setTitle(R.string.profile_photo)
That being said, a lot of other activities don't explicitly defined their title. Do we need to here?

2021-10-12 04:08 UTC, bkaur-bkj commented on app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureActivityPresenter.kt
> +  private fun setUpNavigationDrawer() {
Yes, sorry for that mistake I changed it.

2021-10-12 04:08 UTC, bkaur-bkj commented on app/src/main/res/values/strings.xml
> +  <string name="profile_photo">Profile Photo</string>
Done

2021-10-12 04:09 UTC, bkaur-bkj commented on app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureActivityPresenter.kt
> +    activity.supportActionBar!!.setTitle(R.string.profile_photo)
could not find any other string with the value "Profile Photo" which was to be used as a toolbar title here as mentioned in the issue so I made a new string should I change something?

2021-10-12 15:12 UTC, rt4914 commented on app/src/main/res/values/strings.xml
> +  <string name="profile_photo">Profile Photo</string>
Actually it should be `profile_picture_activity_title` as value can be different but the convention that we are following is activity name with *_title*

2021-10-12 15:27 UTC, bkaur-bkj commented on app/src/main/res/values/strings.xml
> +  <string name="profile_photo">Profile Photo</string>
okay sir

2021-10-13 01:02 UTC, BenHenning requested changes
Thanks @bkaur-bkj. I think the approach overall LGTM. The main gap yet is ensuring that we have tests to ensure that this stays working long-term.

2021-10-13 01:02 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureActivityPresenter.kt
> +    activity.supportActionBar!!.setTitle(R.string.profile_photo)
It seems this activity doesn't yet have a title set, so the new string looks like the correct approach.

2021-10-13 01:02 UTC, BenHenning commented on app/src/main/res/values/strings.xml
> +  <string name="profile_photo">Profile Photo</string>
Thanks for the correction @rt4914.

2021-10-13 01:02 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureActivityPresenter.kt
> +    setUpNavigationDrawer()
Can you also add tests to ensure that the navigation drawer is being set up with the correct configuration (e.g. back button) & title, and that clicking the back button finishes the activity?

2021-10-13 17:34 UTC, bkaur-bkj commented
@rt4914 @BenHenning Sir as said I have tried adding the test case for the above cases of checking title and back button working but as I am not aware much of writing test cases my case for action button check is getting failed, can you pls help what should I change here.

2021-10-14 05:30 UTC, BenHenning requested changes
Thanks @bkaur-bkj. Just had a few other comments. Beyond that:
- #3881 was just merged; could you sync this PR with the latest develop changes, address the conflict, and update the PR to use the activity title string introduced in that PR, instead (so that we don't need to duplicate it)?
- I see there was a lint error. Do you have your local Git repository set up with the pre-push hook to catch lint errors? If not, you should run setup.sh locally as explained [here](https://github.com/oppia/oppia-android/wiki#installation). That will ensure lint failures are caught before pushing which will help you discover & fix them more quickly (i.e. without needing to wait for CI or running them manually).

2021-10-14 05:30 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +  fun testProfilePictureActivity_hasCorrectTitle() {
```suggestion
  fun testProfilePictureActivity_toolbarHasCorrectTitle() {
```

(Otherwise it's ambiguous since the activity also has a title that's separately defined).

2021-10-14 05:30 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +  val activityTestRule = ActivityTestRule(
This is actually deprecated. We should use ActivityScenarioRule or launch the ActivityScenario directly. See other tests that do either of these for reference.

2021-10-14 05:30 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +import org.oppia.android.app.devoptions.markchapterscompleted.testing.MarkChaptersCompletedTestActivity
Is this import needed?

2021-10-14 05:30 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +  fun testProfilePictureActivity_closesOnPressingNavigateUpButton() {
Generally, it's clearer to structure the test name as: testAction_withCondition_andOtherAction_hasOutcome, e.g.:

```suggestion
  fun testProfilePictureActivity_pressNavigateUp_finishesActivity() {
```

2021-10-14 05:31 UTC, BenHenning commented
Also, @bkaur-bkj please make sure that you respond to all comments before sending a PR back for review. It's important to make it clear to reviewers that you've explicitly addressed a comment so that we know to check for it being resolved in our next review round.

2021-10-14 06:20 UTC, bkaur-bkj commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +  fun testProfilePictureActivity_hasCorrectTitle() {
Okay I will make these changes

2021-10-14 06:20 UTC, bkaur-bkj commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +  val activityTestRule = ActivityTestRule(
Okay checking it

2021-10-14 06:21 UTC, bkaur-bkj commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +import org.oppia.android.app.devoptions.markchapterscompleted.testing.MarkChaptersCompletedTestActivity
I not imported it manually it got while writing the other sections of the file, will just check that again.

2021-10-14 06:21 UTC, bkaur-bkj commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +  fun testProfilePictureActivity_closesOnPressingNavigateUpButton() {
okay got it

2021-10-14 06:22 UTC, bkaur-bkj commented
> Also, @bkaur-bkj please make sure that you respond to all comments before sending a PR back for review. It's important to make it clear to reviewers that you've explicitly addressed a comment so that we know to check for it being resolved in our next review round.

okay sorry for not replying last time

2021-10-14 06:50 UTC, rt4914 requested changes
@bkaur-bkj PTAL

2021-10-14 06:50 UTC, rt4914 commented on app/src/main/res/layout/profile_picture_activity.xml
> +      app:layout_constraintTop_toTopOf="parent" />
Lets make it a bit simple.
Instead of using `include`, write code similar to this https://github.com/oppia/oppia-android/blob/15669dc163446e9342b1bd764eea1a5b8a2b9b45/app/src/main/res/layout/app_version_activity.xml#L9

This way you can actually remove a lot of kotlin code.

Also from the same link above you will need to introduce `[View`](https://github.com/oppia/oppia-android/blob/15669dc163446e9342b1bd764eea1a5b8a2b9b45/app/src/main/res/layout/app_version_activity.xml#L32) in your xml to show the shadow below the toolbar.

2021-10-14 07:03 UTC, rt4914 commented on app/src/main/res/layout/profile_picture_activity.xml
> +      app:layout_constraintTop_toTopOf="parent" />
FYI I have suggested to remove `include` because we won't be using them in future in our code as per https://github.com/oppia/oppia-android/issues/3746

2021-10-14 08:10 UTC, bkaur-bkj commented on app/src/main/res/layout/profile_picture_activity.xml
> +      app:layout_constraintTop_toTopOf="parent" />
Okay sir done

2021-10-14 08:15 UTC, bkaur-bkj commented on app/src/main/res/layout/profile_picture_activity.xml
> +      app:layout_constraintTop_toTopOf="parent" />
@rt4914 I have made these changes and also the one asked for adding tests, but still the test fails and I have no clue how to modify them.

2021-10-15 17:56 UTC, bkaur-bkj commented
@BenHenning @rt4914 PTAL

2021-10-16 09:20 UTC, BenHenning commented
Sorry, I'll need to review this on Monday.

2021-10-16 10:49 UTC, rt4914 requested changes
@bkaur-bkj PTAL thanks.

2021-10-16 10:49 UTC, rt4914 commented on app/src/main/res/layout/profile_picture_activity.xml
> +        app:title="@string/administrator_controls_app_version"
This title is incorrect. It should be `profile_picture_activity_title`

2021-10-16 10:49 UTC, rt4914 commented on app/src/main/res/layout/profile_picture_activity.xml
> +      android:layout_height="4dp"
This should be of `6dp`. Also please update the screenshot displaying that the shadow is visible.

2021-10-16 10:49 UTC, rt4914 commented on app/src/main/res/layout/profile_picture_activity.xml
> +      app:layout_constraintTop_toBottomOf="@id/profile_picture_activity_app_bar_layout"
This is incorrect. Instead the `View` should be present on top of `ImageView` to fix this reorder the code as follows:
```
< ConstraintLayout ....
... 
>
   <AppBarLayout
      ...
      ...
      />
   
   <ImageView
      ...
      ...
      />

   <View
      ...
      ...
      />


</ConstraintLayout

```


Basically shift `View` below `ImageView` in code.

2021-10-16 10:49 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +  fun testProfilePictureActivity_toolbarHasCorrectTitle() {
Refer to this test case for 
https://github.com/oppia/oppia-android/blob/4e19d2f9f56981336b2812b5b8ed5c75411131b8/app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt#L242

2021-10-16 10:49 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +  fun testProfilePictureActivity_pressNavigateUp_finishesActivity() {
Reference: https://github.com/oppia/oppia-android/blob/4e19d2f9f56981336b2812b5b8ed5c75411131b8/app/src/sharedTest/java/org/oppia/android/app/story/StoryFragmentTest.kt#L193

2021-10-16 14:00 UTC, bkaur-bkj commented on app/src/main/res/layout/profile_picture_activity.xml
> +        app:title="@string/administrator_controls_app_version"
ok sir done

2021-10-16 14:01 UTC, bkaur-bkj commented on app/src/main/res/layout/profile_picture_activity.xml
> +      app:layout_constraintTop_toBottomOf="@id/profile_picture_activity_app_bar_layout"
done

2021-10-16 14:01 UTC, bkaur-bkj commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +  fun testProfilePictureActivity_toolbarHasCorrectTitle() {
As discussed I have not changed this part as per new way of writing tests.

2021-10-16 14:02 UTC, bkaur-bkj commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +  fun testProfilePictureActivity_pressNavigateUp_finishesActivity() {
As discussed I have not changed this part as per new way of writing tests.

2021-10-16 14:02 UTC, bkaur-bkj commented
@rt4914 PTAL I made the changes requested and have also added the updated screenshot , but with just that naming changes one check is failing and  I unable to resolve it

2021-10-18 19:10 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +  fun testProfilePictureActivity_pressNavigateUp_finishesActivity() {
Ack.

2021-10-18 19:12 UTC, rt4914 requested changes
@bkaur-bkj PTAL at one comment.

2021-10-18 19:12 UTC, rt4914 commented on app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureActivityPresenter.kt
> +    activity.supportActionBar!!.setDisplayHomeAsUpEnabled(true)
Can you check if these 4 lines are still needed. Please check each line individually
```
    activity.setSupportActionBar(toolbar)
    activity.supportActionBar!!.setTitle(R.string.profile_picture_activity_title)
    activity.supportActionBar!!.setDisplayShowHomeEnabled(true)
    activity.supportActionBar!!.setDisplayHomeAsUpEnabled(true)
```

2021-10-18 19:12 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfilePictureActivityTest.kt
> +  fun testProfilePictureActivity_toolbarHasCorrectTitle() {
Ack.

2021-10-19 03:08 UTC, BenHenning approved these changes
Thanks @bkaur-bkj. LGTM!

2021-10-19 03:09 UTC, BenHenning commented
Restarting Gradle run since it was a Java 8 flake.

2021-10-20 14:03 UTC, bkaur-bkj commented on app/src/main/java/org/oppia/android/app/profileprogress/ProfilePictureActivityPresenter.kt
> +    activity.supportActionBar!!.setDisplayHomeAsUpEnabled(true)
Yes sir these lines were not necessary so I removed them in the updated commit after successful running of app and tests.

2021-10-20 14:04 UTC, bkaur-bkj commented
@rt4914 PTAL I have removed the unnecessary part of toolbar

2021-10-21 07:29 UTC, rt4914 approved these changes
LGTM, thanks.

2021-10-21 07:29 UTC, merged