Fix #3919: Marquee for toolbar titles make  RTL compatible.
oppia/oppia-android pull request #3920
Opened 2021-10-11 22:02 UTC by veena14cs

## Explanation

This PR fixes #3919. This PR fixes Marquee direction for toolbar titles to from right-to-left in RTL devices.

https://user-images.githubusercontent.com/16301028/137023878-e0b8fda5-ed80-4182-b268-131608d74d68.mp4

https://user-images.githubusercontent.com/16301028/137025589-b0b9fae5-ed6b-4105-ad61-fbcf453176f3.mp4

**Device**
Nexus 5 Kitkat

https://user-images.githubusercontent.com/16301028/137274925-00458346-8e80-4fb7-b719-7d14cd09ddf0.mp4

https://user-images.githubusercontent.com/16301028/137276845-98120610-d07b-476f-82ae-6cf42dddde16.mp4

## Screenshots of Testcases after RTL 

<img width="384" alt="Screenshot (15)" src="https://user-images.githubusercontent.com/16301028/136861572-c2c0396c-8772-4500-9a4b-caabf27bc0ec.png">

<img width="384" alt="Screenshot (16)" src="https://user-images.githubusercontent.com/16301028/136861658-595bda99-d607-40f5-89ee-a83fcfe25574.png">

<img width="384" alt="Screenshot (17)" src="https://user-images.githubusercontent.com/16301028/136861777-e915997e-a44f-4ba5-a6a5-e62e3df5c617.png">

<img width="384" alt="Screenshot (22)" src="https://user-images.githubusercontent.com/16301028/136864275-b01e5ab9-1412-48fe-b1e1-d96090797cb1.png">

<img width="384" alt="Screenshot (27)" src="https://user-images.githubusercontent.com/16301028/137022839-8cddbf81-30d0-4b28-8e46-b0b53bb1cdb8.png">

##  Screenshots of Testcases before RTL 

<img width="384" alt="Screenshot (18)" src="https://user-images.githubusercontent.com/16301028/136862669-d9bd969a-a998-4c2d-ab60-87f0feeec712.png">

<img width="384" alt="Screenshot (19)" src="https://user-images.githubusercontent.com/16301028/136862789-bb2f5232-74fc-480c-9b0d-7646e411afb7.png">

<img width="384" alt="Screenshot (21)" src="https://user-images.githubusercontent.com/16301028/136862906-058effca-8089-4f90-8fc3-800ce795bb10.png">

<img width="192" alt="Screenshot (23)" src="https://user-images.githubusercontent.com/16301028/136864913-470d885b-daa8-4823-8b49-6963f988ca0e.png">

<img width="384" alt="Screenshot (26)" src="https://user-images.githubusercontent.com/16301028/137022755-b1cf5ac2-f9a4-4972-ba5a-f1e701be4f0b.png">

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2021-10-12 02:49 UTC, BenHenning requested changes
Thanks @veena14cs. If this doesn't work in an emulator, how have you verified that it's correct? It was my understanding that the built-in marquee in AndroidX's toolbar doesn't properly support RTL. Is that not the case?

2021-10-12 02:49 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
> -  //  thread helps to counter that.
Mis-reformatting?

2021-10-12 02:49 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivityPresenter.kt
> +      }
This seems really error-prone (it's super easy to forget this when creating or changing activities). Would it be reasonable to create our own toolbar subclass that sets up its text direction automatically?

I'm also a bit confused. Why doesn't this just automatically work in the system?

2021-10-12 09:41 UTC, veena14cs commented
> Thanks @veena14cs. If this doesn't work in an emulator, how have you verified that it's correct? It was my understanding that the built-in marquee in AndroidX's toolbar doesn't properly support RTL. Is that not the case?

By default it is not supporting. If the textview direction is set to RTL then the marquee direction goes right-to-left.

2021-10-12 09:44 UTC, veena14cs commented on app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
> -  //  thread helps to counter that.
Done.

2021-10-12 19:57 UTC, veena14cs commented on app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivityPresenter.kt
> +      }
Created custom marquee toolbar textview for setting textdirection. It is not setting the marquee direction by default when device is in RTL mode. We need to set textdirection to get correct Marquee effect.

2021-10-12 20:00 UTC, veena14cs commented
> Thanks @veena14cs. If this doesn't work in an emulator, how have you verified that it's correct? It was my understanding that the built-in marquee in AndroidX's toolbar doesn't properly support RTL. Is that not the case?

It is working on emulator now I will be adding up the screen recording. Initially I think I added it in xml or I mistook it that I couldn't observe the correct behavior on the emulator when I was toggling between the Languages and playing around the same screen without reloading it.

2021-10-13 00:59 UTC, BenHenning requested changes
Thanks @veena14cs. Per the videos, I think this looks quite god. Just had some comments about the latest approach, but this seems like a good approach.

Can you please check this on a KitKat emulator to make sure that it's working correctly for KitKat, too? To test, you should use the Bazel build (which you can download from CI: https://github.com/oppia/oppia-android/pull/3920/checks?check_run_id=3875395434 see artifacts)--I'm not sure whether the Gradle build works on KitKat.

The Bazel failure in CI seems to be an infra flake. I restarted it.

2021-10-13 00:59 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +  private var textView = this
Why is this needed?

2021-10-13 00:59 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +  }
Just to clarify, do we not initially play the marquee since this only changes direction upon clicking? Also, does this result in any stuttering when the user taps on the text view?

2021-10-13 00:59 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +  private fun setTextDirection(view: TextView) {
Why not use 'this' instead of passing in a TextView?

2021-10-13 00:59 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +    }
Is this something that we can do in onAttachedToWindow instead of onClick?

2021-10-13 00:59 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +      textView.textDirection = View.TEXT_DIRECTION_LOCALE
I'm wondering if this is actually correct. I'm assuming we actually want to set the text direction using https://github.com/oppia/oppia-android/blob/f266da8dc41c7313b1e220f5eed38d05461cc078/utility/src/main/java/org/oppia/android/util/locale/OppiaLocale.kt#L241. I think we inject this in other views, so see usages of that method to see how to get access to a DisplayLocale.

Without using DisplayLocale, this might get set based on the system locale rather than the app-specified one.

2021-10-13 00:59 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +    if (ViewCompat.isLayoutDirectionResolved(view)) {
Why is this needed? Can we just set the direction to the one we know it needs to be per my comment below?

2021-10-13 00:59 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/customview/MarqueeToolbarTextViewTest.kt
> +      .perform(ViewActions.click())
Prefer directly importing withId()/click().

2021-10-13 00:59 UTC, BenHenning commented on app/src/main/res/layout/exploration_activity.xml
> +          <org.oppia.android.app.customview.MarqueeToolbarTextView
Should we be removing the marquee-specific properties from these uses & instead specify them directly in the custom view? Otherwise it's sort of not a marquee text view if we need to set up the marquee properties each place that it needs to be used.

2021-10-13 00:59 UTC, BenHenning commented on app/BUILD.bazel
> +    "src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt",
It doesn't import org.oppia.android.R, so it should go in the other VIEW list.

2021-10-13 00:59 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
> +      .perform(click())
Should be on one line. Ditto for all other similar lines elsewhere in the PR.

2021-10-13 07:06 UTC, veena14cs commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +  private var textView = this
Removed this.

2021-10-14 08:17 UTC, veena14cs commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +  }
Removed this method from onclick and moved to onAttachWindow().

2021-10-14 08:19 UTC, veena14cs commented on app/src/sharedTest/java/org/oppia/android/app/customview/MarqueeToolbarTextViewTest.kt
> +      .perform(ViewActions.click())
Done.

2021-10-14 09:00 UTC, veena14cs commented on app/src/main/res/layout/exploration_activity.xml
> +          <org.oppia.android.app.customview.MarqueeToolbarTextView
Done.

2021-10-14 09:01 UTC, veena14cs commented on app/BUILD.bazel
> +    "src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt",
Done.

2021-10-14 09:04 UTC, veena14cs commented on app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
> +      .perform(click())
Done.

2021-10-14 09:17 UTC, veena14cs commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +    }
Done.

2021-10-14 09:17 UTC, veena14cs commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +      textView.textDirection = View.TEXT_DIRECTION_LOCALE
Done.

2021-10-14 09:18 UTC, veena14cs commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +    if (ViewCompat.isLayoutDirectionResolved(view)) {
Done.

2021-10-14 09:18 UTC, veena14cs commented on app/src/sharedTest/java/org/oppia/android/app/customview/MarqueeToolbarTextViewTest.kt
> +      .perform(ViewActions.click())
Done.

2021-10-14 09:21 UTC, veena14cs commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +  private fun setTextDirection(view: TextView) {
Removed this function.

2021-10-14 19:10 UTC, BenHenning requested changes
Thanks @veena14cs. Took another full pass--PTAL.

2021-10-14 19:10 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +  )
Can we keep the previous constructor declaration (as we do for other custom views)?

2021-10-14 19:10 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +    if (isRtl) {
Suggest just inlining this isRtl value to avoid potentially accessing it before it's actually initialized (this is a bit clearer when trying to access injectable fields, but the by lazy is once removed & a bit harder to tell when it can be called).

2021-10-14 19:10 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +      textDirection = View.TEXT_DIRECTION_LTR
Could we maybe just do something like ``textDirection = resourceHandler.getLayoutDirection()`` or do the constants differ?

2021-10-14 19:10 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +    setFadingEdgeLength(20)
Is the '20' here in dp or pixels? We might need to convert for it to be correct.

2021-10-14 19:10 UTC, BenHenning commented on app/src/main/res/layout/marquee_toolbar_text_view_test_fragment.xml
> +<layout xmlns:android="http://schemas.android.com/apk/res/android"
We aren't using databinding to inflate this view--should this top-level declaration instead be the ConstraintLayout declared below?

2021-10-14 19:10 UTC, BenHenning commented on app/src/main/res/layout/story_fragment.xml
> -          android:focusableInTouchMode="true"
Is this one defined programmatically in the custom view? It seems missing. Is it default true for clickable text views?

2021-10-14 19:10 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/customview/MarqueeToolbarTextViewTest.kt
> +  @RunOn(TestPlatform.ROBOLECTRIC) // TODO(#3840): Make this test work on Espresso & Robolectric
Is this correct? It should pass on Robolectric, but might not on Gradle. See that other tests are restricted to running on Bazel--can you see if this passes on Bazel before disabling this for Robolectric?

2021-10-14 19:10 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/customview/MarqueeToolbarTextViewTest.kt
> +      .perform(click())
Please also import withId directly.

And, this can fit on one line (wrapping isn't needed).

2021-10-14 19:10 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt
> -  @Test
This shouldn't be removed--it stops the test from running.

2021-10-14 19:10 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/story/StoryFragmentTest.kt
> -  fun testStoryFragment_toolbarTitle_marqueeInRtl_isDisplayedCorrectly() {
Why remove these tests? Ditto for ExplorationActivityTest and RevisionCardActivityTest.

2021-10-14 19:10 UTC, BenHenning commented on scripts/assets/kdoc_validity_exemptions.textproto
> +exempted_file_path: "app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt"
Don't exempt this--prefer to add the missing documentation, instead.

2021-10-14 19:10 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +/** The custom Textview class for toolbar with Marquee effect. */
``Custom text view that should be configured as the child of a toolbar to display a toolbar's title with an RTL-capable marquee effect.``

Bit more specific on why & how to use this.

2021-10-14 19:10 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +  }
Thanks, but I don't think that actually answers my questions about juttering/initial behavior.

I think I have the answer to the first one (that tapping is necessary), but can you clarify on the second point: is there any juttering when in RTL mode? It doesn't seem like it from the video, but the video might not show jutters.

2021-10-14 19:10 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/customview/MarqueeToolbarTextView.kt
> +    if (ViewCompat.isLayoutDirectionResolved(view)) {
Replaced with newer comment (I don't think this was fully resolved).

2021-10-14 19:10 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/customview/MarqueeToolbarTextViewTest.kt
> +      .perform(ViewActions.click())
One was done, but not the other. Replaced with a newer comment.

2021-10-14 19:10 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
> +      .perform(click())
Not fully resolved, but replaced with a newer comment.

2021-10-14 19:15 UTC, veena14cs commented on app/src/sharedTest/java/org/oppia/android/app/story/StoryFragmentTest.kt
> -  fun testStoryFragment_toolbarTitle_marqueeInRtl_isDisplayedCorrectly() {
I removed it because I need to create Fragment test for these activity test as its not present in current code, so I just removed it from here.

2021-10-16 10:52 UTC, rt4914 commented
For this particular PR I will have to defer to @BenHenning . Once he approves I will take a look at my code-owner files just to be sure.

2021-10-19 10:31 UTC, veena14cs commented
Closing this PR as its getting fixed in #3935

2021-10-19 10:31 UTC, closed without merging