Updated .gitignore and automated setup procedure
oppia/oppia-android pull request #3943
Opened 2021-10-16 17:25 UTC by FareesHussain

Updated scripts for setup.sh to automatically update the local.properties for M1 mac (to use protoc using gradle)
Added misc.xml and runconfigurations.xml to .gitignore

2021-10-16 17:32 UTC, FareesHussain commented on scripts/setup.sh
> +        echo '\nprotobuf_platform=osx-x86_64' >> ../oppia-android/local.properties
https://github.com/oppia/oppia-android/pull/3891 for context

2021-10-19 03:31 UTC, BenHenning requested changes
Thanks @FareesHussain! Just had one comment--PTAL.

2021-10-19 03:31 UTC, BenHenning commented on .gitignore
> +/.idea/runConfigurations.xml
Here & above: can you remove the existing ones if we're now ignoring them?

2021-10-19 09:07 UTC, FareesHussain commented on .gitignore
> +/.idea/runConfigurations.xml
I don't get it which ones do you mean?

2021-10-20 05:48 UTC, BenHenning commented
Sorry, will need to review this tomorrow.

2021-10-20 16:05 UTC, vinitamurthi approved these changes
LGTM thanks Farees!

2021-10-21 07:06 UTC, BenHenning reviewed
Apologies; I probably could have followed up yesterday (I didn't realize you were just looking for clarification). PTAL @FareesHussain.

2021-10-21 07:06 UTC, BenHenning commented on .gitignore
> +/.idea/runConfigurations.xml
Ah sorry. Can you please remove misc.xml and runConfigurations.xml? Now that they're being ignored, they no longer need to be tracked in VCS.

However, we need to make sure that removing these files from GitHub does *not* result in the files being deleted locally (since that might break people). I forgot how I did this last time, but I think https://stackoverflow.com/a/20241145/3689782 is what you want to do. To check: after pushing the removal to GitHub, you should verify that:
- The files are now removed on GitHub in your branch
- Checking out develop then checking out your branch in the same repository does not result in the files being removed locally

Once you confirm this & the PR is updated, I think it will look good to check in.

2021-10-23 02:00 UTC, anandwana001 requested changes

2021-10-23 02:00 UTC, anandwana001 commented on scripts/setup.sh
> +fi
Can we put this in a separate script and call it from here, something like `buf_m1_mac_setup.sh`

2021-10-23 06:05 UTC, FareesHussain commented on scripts/setup.sh
> +fi
Sounds good, done

2021-10-23 06:06 UTC, FareesHussain commented on .gitignore
> +/.idea/runConfigurations.xml
Done

2021-10-25 16:34 UTC, anandwana001 requested changes

2021-10-25 16:34 UTC, anandwana001 commented on scripts/buf_m1_mac_setup.sh
> +fi
add EOF

2021-10-25 16:34 UTC, anandwana001 commented on scripts/setup.sh
> +bash ../oppia-android/scripts/buf_m1_mac_setup.sh
isn't the `buf_m1_mac_setup` script is dependent on the `buf_download` script? 
We should add a NOTE in the comment here about this.

2021-10-25 16:34 UTC, anandwana001 commented on scripts/setup.sh
> +bash ../oppia-android/scripts/buf_m1_mac_setup.sh
or can we do this here as `echo Buf setup completed`
https://github.com/oppia/oppia-android/blob/02013abd737cebd8f4931fa9b174ed35c4314eb1/scripts/buf_download.sh#L9


Need to confirm that if this change doesn't break our GitHub action!!

2021-10-25 16:34 UTC, anandwana001 commented on scripts/buf_m1_mac_setup.sh
> +        echo 'Added protobuf platform to local properties.'
Do we need to echo this? 
if yes, can we say it `Buf` rather than `protobuf`?

2021-10-25 16:34 UTC, anandwana001 commented on scripts/buf_m1_mac_setup.sh
> +# Add protobuf platform for M1 Mac
```suggestion
# Setup protobuf platform for M1 Mac
```

2021-10-25 16:34 UTC, anandwana001 commented on scripts/setup.sh
> +# Add protobuf platform for M1 Mac
```suggestion
# Add buf platform for M1 Mac
```

2021-10-25 16:41 UTC, FareesHussain commented
@anandwana001 PTAL https://github.com/oppia/oppia-android/pull/3891 and https://github.com/oppia/oppia-android/issues/3912

2021-10-25 16:47 UTC, FareesHussain commented on scripts/buf_m1_mac_setup.sh
> +fi
Done

2021-10-25 16:49 UTC, FareesHussain commented on scripts/setup.sh
> +bash ../oppia-android/scripts/buf_m1_mac_setup.sh
for this and others
PTAL  https://github.com/oppia/oppia-android/pull/3891 and https://github.com/oppia/oppia-android/issues/3912
here the protobuf only for the protobuf dependency in gradle

2021-10-25 16:56 UTC, anandwana001 commented
Got it, PTAL at my one last comment for comment update, else all LGTM

2021-10-25 17:15 UTC, FareesHussain commented
> Got it, PTAL at my one last comment for comment update, else all LGTM

@anandwana001 can you resolve the other comments I'm unable to understand which one (all of them are related to comment)

2021-10-25 19:04 UTC, FareesHussain commented on scripts/buf_m1_mac_setup.sh
> +# Add protobuf platform for M1 Mac
DONE

2021-10-26 01:39 UTC, anandwana001 approved these changes
LGTM

2021-10-26 04:31 UTC, BenHenning reviewed
Thanks @FareesHussain. Just had two more comments, PTAL.

2021-10-26 04:31 UTC, BenHenning commented on .gitignore
> +/.idea/runConfigurations.xml
I see the files removed. Can you also confirm that checking out this branch locally does _not_ delete the files when checked out?

2021-10-26 04:31 UTC, BenHenning commented on .gitignore
> +/.idea/deploymentTargetDropDown.xml
At this point, should we just allowlist the files that *should* be tracked under .idea/? It may be simpler.

2021-10-29 03:48 UTC, FareesHussain commented on .gitignore
> +/.idea/runConfigurations.xml
No, it doesn't get deleted 

I checked out to develop then this branch 
These files weren't deleted

2021-10-29 03:52 UTC, FareesHussain commented on .gitignore
> +/.idea/deploymentTargetDropDown.xml
can we do that?

I found this [ans](https://stackoverflow.com/a/6011532) as a opposite of `.gitignore`
In this case maybe we need a new .gitignore file under the .idea directory

2021-10-29 04:02 UTC, FareesHussain commented on .gitignore
> +/.idea/deploymentTargetDropDown.xml
https://gist.github.com/FareesHussain/b2596f21294570ae129cf0705e225ad7
Can you confirm if this is what we need

2021-10-29 19:43 UTC, BenHenning commented on .gitignore
> +/.idea/runConfigurations.xml
Thanks for checking!

2021-10-29 19:43 UTC, BenHenning commented on .gitignore
> +/.idea/deploymentTargetDropDown.xml
That seems correct, except why can't we keep it in the top-level .gitignore? E.g.:

```gitignore
.idea/*
!.idea/encodings.xml
!.idea/codeStyles/Project.xml
!.idea/codeStyleConfig.xml
```

Will that not work?

2021-10-29 19:44 UTC, BenHenning commented on scripts/setup.sh
> +        echo '\nprotobuf_platform=osx-x86_64' >> ../oppia-android/local.properties
Suggest adding this context as a comment if it's important to make the association (it's more important to have that as a permanent record in code vs. a PR comment that might be hard to find in the future).

2021-11-10 10:24 UTC, FareesHussain commented on .gitignore
> +/.idea/deploymentTargetDropDown.xml
It works and updated too

sry for the huge delay

2021-11-10 21:39 UTC, BenHenning approved these changes
Thanks @FareesHussain. I think this looks great! Approved for codeowners.

2021-11-10 21:39 UTC, BenHenning commented on scripts/setup.sh
> +        echo '\nprotobuf_platform=osx-x86_64' >> ../oppia-android/local.properties
It seems my comment is no longer relevant--the latest version of this is now using a shell script.

2021-11-10 21:40 UTC, BenHenning commented
Merging since there don't seem to be any outstanding comments to address, CI checks are passing, and this should be a big help with contributor PRs (since we keep seeing people changing unrelated .idea files).

2021-11-10 21:40 UTC, merged