Fix #3559 : Merged profile_edit_fragment.xml into single xml file
oppia/oppia-android pull request #3948
Opened 2021-10-19 20:58 UTC by mahmood199

Phone portrait 
Before    
![Screenshot_20211020_010509_org oppia android](https://user-images.githubusercontent.com/58071934/137988200-c726b96f-14b6-45a8-bfc4-9e5863708050.jpg)  
And After
![Screenshot_20211020_011834_org oppia android](https://user-images.githubusercontent.com/58071934/137988275-48f2fe7a-abed-4b72-aa25-4e6faf8e2806.jpg)

Phone landscape(2 pictures in each)(because to view full layout i had to scroll and therefore total 4 images)
Before 
![Screenshot_20211020_013439_org oppia android](https://user-images.githubusercontent.com/58071934/137988582-cdf529c9-906d-4ad3-8ad6-100186e92954.jpg)
![Screenshot_20211020_010528_org oppia android](https://user-images.githubusercontent.com/58071934/137988693-f3b486f9-17b8-4563-b720-a8d747c68e8e.jpg)
And After
![Screenshot_20211020_010525_org oppia android](https://user-images.githubusercontent.com/58071934/137988687-eff768e7-9e4f-4ff1-93d4-e912c60fc736.jpg)
![Screenshot_20211020_013444_org oppia android](https://user-images.githubusercontent.com/58071934/137988587-7c2d005c-9fd0-4cd5-8af9-cf5e53a36d4a.jpg)

Tablet Portrait
Before 
![Screenshot (27)](https://user-images.githubusercontent.com/58071934/137988766-ac43f3e2-24a6-4275-97ac-36f31b7a85c1.png)
And After
![Screenshot (28)](https://user-images.githubusercontent.com/58071934/137988770-15e492d9-2fa1-4493-a834-5e489627fd13.png)

Tablet landscape
Before 
![Screenshot (29)](https://user-images.githubusercontent.com/58071934/137988844-ba861781-2a23-4ce3-93a3-28c5b412a8c6.png)
and After
![Screenshot (30)](https://user-images.githubusercontent.com/58071934/137988851-645b40ef-b95a-495c-b5ee-712a0bf7f6da.png)

In the previous Phone landscape there was a big spacing above and below deletion button and view margin misallignment. It is fixed in this PR.
Thank you. :)

2021-10-23 10:57 UTC, mahmood199 commented
Please merge this @rt4914 🙂

2021-10-27 20:03 UTC, FareesHussain commented
@mahmood199 Thanks for showing interest in oppia. Please check out our [wiki](https://github.com/oppia/oppia-android/wiki#onboarding-instructions) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

2021-10-28 00:40 UTC, mahmood199 commented
@FareesHussain I have filled the form already.
Actually I had created a PR then got the prompt to fill the form....do i  need to create a PR again?

2021-10-28 01:47 UTC, FareesHussain commented
@mahmood199 did you fill the contributors survey

2021-10-28 02:13 UTC, mahmood199 commented
Yes, just filled the form
Please check once

2021-11-01 12:02 UTC, ARJUPTA requested changes
I have took an initial pass over you PR and here are some points to work improve.
- Always try to remove file changes under ` .idea` directory from the commit.
- Mention the Issue number for which you have created this PR.
- The PR title should be in this format `Fix #issue_number: Description`

2021-11-01 12:19 UTC, mahmood199 reviewed
.idea files deleted

2021-11-08 05:22 UTC, mahmood199 commented
Me waiting for my PR to be merged.
[https://www.google.com/url?sa=i&url=https%3A%2F%2Ftenor.com%2Fview%2Fmr-bean-waiting-still-waiting-gif-13052487&psig=AOvVaw3sN4NiIOHbQH-Hi747sb4U&ust=1636435303853000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCPjRoNqCiPQCFQAAAAAdAAAAABAD](url)

2021-11-09 02:56 UTC, BenHenning commented
@ARJUPTA per https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section please make sure that you assign your PR to whoever needs to look at it next (otherwise it's likely that we won't see it).

2021-11-09 20:36 UTC, rt4914 requested changes
@mahmood199 Thanks. PTAL

2021-11-09 20:36 UTC, rt4914 commented on .idea/misc.xml
> -</project>
We don't need any change to `.idea` file, this must have been done automatically from android studio please do not add this file to your commit. 
Note: Don't delete this file, we need this file we just don't need the changes this file contains.

2021-11-09 20:36 UTC, rt4914 commented on .idea/runConfigurations.xml
> -  </component>
We don't need any change to `.idea` file, this must have been done automatically from android studio please do not add this file to your commit. 
Note: Don't delete this file, we need this file we just don't need the changes this file contains.

2021-11-09 20:36 UTC, rt4914 commented on app/src/main/res/layout-land/profile_edit_fragment.xml
> +        android:layout_width="@dimen/profile_edit_fragment_profile_width_and_height"
Instead of one single dimens introduce two separate dimens as below:
profile_edit_fragment_profile_width
profile_edit_fragment_profile_height

2021-11-09 20:36 UTC, rt4914 commented on app/src/main/res/values/dimens.xml
> +  <dimen name="elevation_of_2dp">2dp</dimen>
Rename this to `profile_edit_fragment_profile_image_elevation` and use it in all xml files.

2021-11-09 20:36 UTC, rt4914 commented on app/src/main/res/values/dimens.xml
> +  <dimen name="profile_delete_button_padding_end">16dp</dimen>
If a value is same in both the files then do not define it in `dimens.xml` file, instead hard code it in xml file only.
Apply this to all dimens that you have introduced.

2021-11-10 05:51 UTC, BenHenning commented
My review is only needed due to the .idea file changes. Please remove them from the PR & assign back to me if my review is still needed/wanted.

2021-11-11 03:25 UTC, ARJUPTA commented
> @ARJUPTA per https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section please make sure that you assign your PR to whoever needs to look at it next (otherwise it's likely that we won't see it).

@BenHenning actually I was supposed to take a second pass but @mahmood199 forgot to ask my review because of which ther was delay. I would have surely assigned you guys after my review.

2021-11-11 20:19 UTC, BenHenning commented
No problem--thanks for the context @ARJUPTA. :)

2021-11-20 00:54 UTC, BenHenning commented
FYI I'm listed as a codeowner for this PR & I'll be unavailable to perform code reviews over the next 2 weeks--thanks for your patience.

2021-11-24 04:07 UTC, rt4914 commented
Closing this PR and un-assigning because of inactivity @mahmood199

2021-11-24 04:07 UTC, closed without merging