Fix #3332: Created a BUILD.bazel file in domain/audio
oppia/oppia-android pull request #3967
Opened 2021-10-24 17:24 UTC by yash10019coder

## Explanation

Fixes #3332 
Created the bazel file in audio and also added targets to the needed targets.
## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

N/A -- this PR is only changing the Bazel build graph and doesn't affect any user flows.

2021-10-24 17:26 UTC, yash10019coder reviewed
Hi @BenHenning created a PR PTAL

2021-10-26 04:37 UTC, BenHenning commented
Thanks @yash10019coder. Apologies, will need to look at this tomorrow.

2021-10-27 06:21 UTC, BenHenning requested changes
Thanks @yash10019coder. Just had a couple of comments, otherwise the PR looks quite good to me.

Regarding the PR itself, three things:
1. Could you please update the title? It's currently cut-off. Titles should generally be concise and specific as to the high-level thing the PR is accomplishing.
2. Could you please move the explanation portion in your PR description to be under the 'explanation' section? 
3. You can (& should) remove the bits under "For UI-specific PRs only" and describe why this PR doesn't need that (e.g. "N/A -- this PR is only changing the Bazel build graph and doesn't affect any user flows"). In general, please make sure to follow the instructions in the PR description to ensure that all the needed pieces are included. This really helps both reviewers and future people who come across the PR after it gets merged.

2021-10-27 06:21 UTC, BenHenning commented on domain/BUILD.bazel
> +        "//domain/src/main/java/org/oppia/android/domain/audio:cellular_audio_dialog_controller",
Do any domain classes actually depend on these, or is it only UI? Prefer importing it in the UI layer if the latter since we shouldn't be relying on implicit dependencies this way.

2021-10-27 06:21 UTC, BenHenning commented on domain/src/main/java/org/oppia/android/domain/audio/BUILD.bazel
> +Package for audio controlling
```suggestion
Domain services & definitions corresponding to managing and playing audio tracks.
```

Bit clearer on what "controlling" means, and is consistent with another modularized domain subpackage.

2021-10-28 19:28 UTC, yash10019coder reviewed
@BenHenning Please PTAL

2021-10-29 19:25 UTC, yash10019coder reviewed
Hi @BenHenning added the dependencies and removed the old dependencies from domian/bazel PTAL

2021-10-30 06:42 UTC, BenHenning approved these changes
Thanks @yash10019coder! The PR LGTM.

Two things:
1. I updated your PR description since you didn't address point (3) in my earlier comment. Please see how I changed it for a reference on future PRs--copying that approach will help streamline future PRs that you send.
2. Please remember to reply to comment threads directly when they're addressed

2021-10-30 06:42 UTC, merged

2021-10-30 10:13 UTC, yash10019coder commented
Thanks a lot, @BenHenning for merging this PR 😄

2021-10-30 10:49 UTC, yash10019coder commented
> Thanks @yash10019coder! The PR LGTM.
> 
> Two things:
> 
> 1. I updated your PR description since you didn't address point (3) in my earlier comment. Please see how I changed it for a reference on future PRs--copying that approach will help streamline future PRs that you send.
> 2. Please remember to reply to comment threads directly when they're addressed

apologies for not replying I forgot I will always reply in the future for all the comments
thanks

2021-11-02 00:19 UTC, BenHenning commented
> > Thanks @yash10019coder! The PR LGTM.
> > Two things:
> > 
> > 1. I updated your PR description since you didn't address point (3) in my earlier comment. Please see how I changed it for a reference on future PRs--copying that approach will help streamline future PRs that you send.
> > 2. Please remember to reply to comment threads directly when they're addressed
> 
> apologies for not replying I forgot I will always reply in the future for all the comments thanks

Thanks @yash10019coder, I appreciate it. :)

2021-11-02 02:59 UTC, yash10019coder commented
Thanks for merging the PR

On Tue, Nov 2, 2021, 5:50 AM Ben Henning ***@***.***> wrote:

> Thanks @yash10019coder <https://github.com/yash10019coder>! The PR LGTM.
> Two things:
>
>    1. I updated your PR description since you didn't address point (3) in
>    my earlier comment. Please see how I changed it for a reference on future
>    PRs--copying that approach will help streamline future PRs that you send.
>    2. Please remember to reply to comment threads directly when they're
>    addressed
>
> apologies for not replying I forgot I will always reply in the future for
> all the comments thanks
>
> Thanks @yash10019coder <https://github.com/yash10019coder>, I appreciate
> it. :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/oppia/oppia-android/pull/3967#issuecomment-956976269>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASG5QUNQLP2NAYHFQLEGAMTUJ4VDDANCNFSM5GTVKHAA>
> .
>