Fix part of #3971: Add style for all the TextViews in the app.
oppia/oppia-android pull request #3976
Opened 2021-10-28 10:56 UTC by veena14cs

## Explanation
This PR fixes part of #3971 . This PR ensures that all the Textviews have style attribute set, to generally manage the text alignment for RTL/LTR where the texts are aligned to  right or left and the texts that are center-aligned.
This PR is divided into multiple parts to keep minimal file changes
1] Part 1 #3976.
2] Part 2 #3984.
3] Part 3 #3987.
4] Part 4 #3988.
5] Part 5 #3989 .

## Screenshot LTR and RTL

`Stories You Can Play`

<img width="144" alt="Screenshot_1635463060" src="https://user-images.githubusercontent.com/16301028/139242061-c4ec3153-1107-4d79-93c7-64ac2b722314.png">,,,,<img width="144" alt="Screenshot_1635463128" src="https://user-images.githubusercontent.com/16301028/139242107-ec0f0b82-b220-4e4d-87b4-923c68508f34.png">

<img width="256" alt="Screenshot_1635463069" src="https://user-images.githubusercontent.com/16301028/139242372-5c73b192-3588-4da7-a643-e9aa0d0c5ee5.png">....<img width="256" alt="Screenshot_1635463121" src="https://user-images.githubusercontent.com/16301028/139242422-b5ca990b-dad6-4684-ad51-05d3a19ddc79.png">

`All Topics`

<img width="144" alt="Screenshot_1635481677" src="https://user-images.githubusercontent.com/16301028/139292890-97348099-c146-466c-98e2-db1c3291d40f.png">...<img width="144" alt="Screenshot_1635481641" src="https://user-images.githubusercontent.com/16301028/139292721-3f119c76-98f7-4d79-b9b5-fbbc233915dd.png">

<img width="256" alt="Screenshot_1635481687" src="https://user-images.githubusercontent.com/16301028/139293081-7edc02aa-620d-4621-b778-3a87da1922fd.png">.....<img width="256" alt="Screenshot_1635481627" src="https://user-images.githubusercontent.com/16301028/139293016-833ede43-0e69-4796-a13c-d4b58a3fb6d2.png">

`Revision tab`

<img width="144" alt="Screenshot_1635465169" src="https://user-images.githubusercontent.com/16301028/139293461-8850f638-a776-4ede-b876-ce89da383084.png">....<img width="144" alt="Screenshot_1635465191" src="https://user-images.githubusercontent.com/16301028/139293561-0290eaea-8d5c-4f36-b06b-6bd13b9347da.png">

<img width="256" alt="Screenshot_1635465246" src="https://user-images.githubusercontent.com/16301028/139293328-0ca03167-6358-4f0e-8e7c-38999f50ed21.png">...<img width="256" alt="Screenshot_1635465197" src="https://user-images.githubusercontent.com/16301028/139293234-b9e99a55-3864-4d8b-882c-be0b1519011a.png">

`Practice tab`

<img width="144" alt="Screenshot_1635465149" src="https://user-images.githubusercontent.com/16301028/139294024-f31709df-dc68-4a5c-a744-3f01c9cc4ba5.png">...<img width="144" alt="Screenshot_1635465208" src="https://user-images.githubusercontent.com/16301028/139293926-d46ad8f9-06d6-49ed-84e3-f317e6fcb621.png">
<img width="256" alt="Screenshot_1635465157" src="https://user-images.githubusercontent.com/16301028/139294127-0ec6e3f3-4856-4cc2-aaeb-25efb8f1c36e.png">....<img width="256" alt="Screenshot_1635465214" src="https://user-images.githubusercontent.com/16301028/139294212-6aa11bd4-2493-46ef-aed7-fe7284c6f910.png">

## Tablet:

<img width="160" alt="Screenshot_1635491321" src="https://user-images.githubusercontent.com/16301028/139316366-7851ccf3-cd8e-47ce-bc37-7b3eac7e04cf.png">....<img width="160" alt="Screenshot_1635491398" src="https://user-images.githubusercontent.com/16301028/139316473-656a9a83-cd81-469c-897f-2ccce21a9502.png">
<img width="256" alt="Screenshot_1635491316" src="https://user-images.githubusercontent.com/16301028/139316712-988d6cb4-48ef-4180-b453-79f88dd1edca.png">...<img width="256" alt="Screenshot_1635491410" src="https://user-images.githubusercontent.com/16301028/139316663-901e63fe-c926-43b7-89f5-cbe0a33a83dd.png">

<img width="160" alt="Screenshot_1635491299" src="https://user-images.githubusercontent.com/16301028/139316162-84096596-24b7-4a07-bb6b-4bafd01d571e.png">.....<img width="160" alt="Screenshot_1635491456" src="https://user-images.githubusercontent.com/16301028/139316080-4c912ba6-ea62-4419-b739-bede580812d0.png">
<img width="256" alt="Screenshot_1635491308" src="https://user-images.githubusercontent.com/16301028/139316281-b47e5874-9c16-4cc7-834f-861281ebfebc.png">....<img width="256" alt="Screenshot_1635491420" src="https://user-images.githubusercontent.com/16301028/139316250-d4cb5062-ccb4-46de-b48d-f3d922c2eacc.png">

<img width="160" alt="Screenshot_1635491330" src="https://user-images.githubusercontent.com/16301028/139316854-1cece518-b636-43de-adaa-598f062c3ec8.png">...<img width="160" alt="Screenshot_1635491436" src="https://user-images.githubusercontent.com/16301028/139317141-487b3787-8327-4491-8f8c-a02fbbaab3fd.png">

<img width="256" alt="Screenshot_1635491341" src="https://user-images.githubusercontent.com/16301028/139316943-a5fea637-10e7-4aac-90f1-b146fab2460a.png">...<img width="256" alt="Screenshot_1635491428" src="https://user-images.githubusercontent.com/16301028/139317006-dab958ca-594f-4a77-8773-49a2cad6c56f.png">

<img width="160" alt="Screenshot_1635491367" src="https://user-images.githubusercontent.com/16301028/139317301-5cd54a9d-1887-46c1-9ddb-7bcdf73f7f10.png">.....<img width="160" alt="Screenshot_1635491392" src="https://user-images.githubusercontent.com/16301028/139317238-97051110-f4b5-480c-ac13-8bffa8a87b8c.png">

<img width="256" alt="Screenshot_1635491359" src="https://user-images.githubusercontent.com/16301028/139318394-a50899d4-406a-454c-bc84-ab4ed33e010c.png">..<img width="256" alt="Screenshot_1635492223" src="https://user-images.githubusercontent.com/16301028/139318427-a4d7400a-b675-42a7-97a3-39c251f1c955.png">

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2021-10-29 01:35 UTC, BenHenning requested changes
Thanks @veena14cs. Took a first pass.

Some thoughts:
1. Can you please update the PR description to explain what's specifically being addressed for #3971 in this PR?
2. I think we need to define the styles such that they make sense with how the page is laid out (just like they would, for example, in a Google Doc or on a web page).
3. We need to be consistent about defining layout width/height & text color between the different text view styles.

It'd be really good for @rt4914 to take a pass when he has a chance since some high-level style decisions are being made here.

2021-10-29 01:35 UTC, BenHenning commented on app/src/main/res/layout-land/topic_revision_summary_view.xml
> +        style="@style/SummaryText1"
It seems a bit odd that a title uses a summary style. Do we need more title styles, too?

2021-10-29 01:35 UTC, BenHenning commented on app/src/main/res/layout-land/topic_summary_view.xml
> -          android:layout_width="wrap_content"
Per the style, this is being changed now to match_parent. Is that correct?

2021-10-29 01:35 UTC, BenHenning commented on app/src/main/res/layout-land/topic_summary_view.xml
>            android:id="@+id/topic_name_text_view"
Similarly, this is probably more like a title.

2021-10-29 01:35 UTC, BenHenning commented on app/src/main/res/layout-sw600dp-land/topic_revision_summary_view.xml
>          android:layout_height="wrap_content"
Still needed now that the style specifies both of these?

2021-10-29 01:35 UTC, BenHenning commented on app/src/main/res/layout-sw600dp-port/topic_revision_summary_view.xml
>          android:layout_height="wrap_content"
Ditto here & elsewhere in the PR.

2021-10-29 01:35 UTC, BenHenning commented on app/src/main/res/layout-land/topic_lessons_story_summary.xml
> -              android:layout_height="wrap_content"
Heading5 doesn't define layout width/height. Should it?

I'm actually a bit concerned with the inconsistency here. Should we ever be defining layout width/height for text view styles?

2021-10-29 01:35 UTC, BenHenning commented on app/src/main/res/layout-land/topic_lessons_story_summary.xml
> -              android:textColor="@color/oppiaPrimaryText"
This isn't being defined in Heading5.

2021-10-29 01:35 UTC, BenHenning commented on app/src/main/res/layout-land/topic_lessons_story_summary.xml
> +              style="@style/Subtitle1"
Is this actually a subtitle? Similarly for the other headings. @rt4914 do you have any thoughts on how the text styles *should* be laid out? They seem a bit at odds at the moment on what's a heading vs. body text vs. titles/subtitles.

2021-10-29 01:35 UTC, BenHenning commented on app/src/main/res/layout-land/topic_practice_header_view.xml
> -      android:textColor="@color/oppiaPrimaryText"
Doesn't seem defined in Heading2.

2021-10-29 14:32 UTC, veena14cs commented on app/src/main/res/layout-land/topic_revision_summary_view.xml
> +        style="@style/SummaryText1"
Yes, we need to have some more title styles. And the view over here relates to summary view so instead of id having as title we can have it as a subtopic_name. Just a thought.

2021-10-29 14:49 UTC, veena14cs commented on app/src/main/res/layout-land/topic_summary_view.xml
> -          android:layout_width="wrap_content"
I removed it as there is no change in the view. And the style has `ellipsize= end` for this to work for LTR/RTL we need to define match_parent if we have textalignment set to viewstart. Otherwise what I have seen while development for RTL is the ellipsize shows left aligned in RTL.

2021-10-29 14:52 UTC, veena14cs commented on app/src/main/res/layout-land/topic_practice_header_view.xml
> -      android:textColor="@color/oppiaPrimaryText"
Its defined in the parent style `TextView.Common1`

2021-10-29 14:53 UTC, veena14cs commented on app/src/main/res/layout-land/topic_lessons_story_summary.xml
> -              android:textColor="@color/oppiaPrimaryText"
Defined in the parent style` TextView.Common1`

2021-10-29 14:57 UTC, veena14cs commented on app/src/main/res/layout-land/topic_lessons_story_summary.xml
> -              android:layout_height="wrap_content"
I am also confused here. I am thinking I will keep these width/height regardless of the attributes defined in the style. Or please let me know your thoughts. What we shall be including in the styles as all the styles extend TextView.Common1.

2021-10-29 15:01 UTC, veena14cs commented on app/src/main/res/layout-land/topic_summary_view.xml
>            android:id="@+id/topic_name_text_view"
Let me know how I can define styles for these kind of titles as I am confused here to define a new title style .

2021-10-29 15:03 UTC, veena14cs commented on app/src/main/res/layout-sw600dp-port/topic_revision_summary_view.xml
>          android:layout_height="wrap_content"
Replied here https://github.com/oppia/oppia-android/pull/3976#discussion_r739306871

2021-10-29 15:03 UTC, veena14cs commented on app/src/main/res/layout-sw600dp-land/topic_revision_summary_view.xml
>          android:layout_height="wrap_content"
Replied on https://github.com/oppia/oppia-android/pull/3976#discussion_r739306871

2021-10-29 15:05 UTC, veena14cs commented
> Thanks @veena14cs. Took a first pass.
> 
> Some thoughts:
> 
> 1. Can you please update the PR description to explain what's specifically being addressed for #3971 in this PR?
> 2. I think we need to define the styles such that they make sense with how the page is laid out (just like they would, for example, in a Google Doc or on a web page).
> 3. We need to be consistent about defining layout width/height & text color between the different text view styles.
> 
> It'd be really good for @rt4914 to take a pass when he has a chance since some high-level style decisions are being made here.

Its bit confusing how to define styles for some of the titles that does not match the styles that are already defined in the styles file. Please suggest me how I can do this.

2021-10-30 06:45 UTC, BenHenning commented
> > Thanks @veena14cs. Took a first pass.
> > Some thoughts:
> > 
> > 1. Can you please update the PR description to explain what's specifically being addressed for [Ensure all TextViews have style attribute set. #3971](https://github.com/oppia/oppia-android/issues/3971) in this PR?
> > 2. I think we need to define the styles such that they make sense with how the page is laid out (just like they would, for example, in a Google Doc or on a web page).
> > 3. We need to be consistent about defining layout width/height & text color between the different text view styles.
> > 
> > It'd be really good for @rt4914 to take a pass when he has a chance since some high-level style decisions are being made here.
> 
> Its bit confusing how to define styles for some of the titles that does not match the styles that are already defined in the styles file. Please suggest me how I can do this.

This will likely require renaming the existing styles such that those + the new ones follow a cohesive pattern based on the different kinds of texts that we want to be able to show. For example, it may make sense to have multiple title styles like we have multiple heading styles, or we may need to change the heading styles to incorporate other kinds of headings that weren't previously considered.

I think in order for us to consider this part done, we need to:
1. Make sure that all TextViews have styles
2. Make sure that all TextView styles seem like they belong to the same style "group" (i.e. that they all seem related to each other in how to lay out a document or page)

2021-10-30 17:44 UTC, rt4914 requested changes
@veena14cs and @BenHenning 
I haven't reviewed the PR has based on Ben's comment it can have significant changes in styles.xml file and therefore different layout files too.
I have created this gist which highlights two possible solutions that we can do. Have a look and please confirm which one we should finalise. 
https://gist.github.com/rt4914/464763d4c634abbccfa1fada080be5e8

2021-10-30 18:02 UTC, veena14cs commented
> @veena14cs and @BenHenning I haven't reviewed the PR has based on Ben's comment it can have significant changes in styles.xml file and therefore different layout files too. I have created this gist which highlights two possible solutions that we can do. Have a look and please confirm which one we should finalise. https://gist.github.com/rt4914/464763d4c634abbccfa1fada080be5e8

Thanks @rt4914 2nd approach looks good to me. I would defer it to @BenHenning  too  for what more can be done to simplify it.

2021-11-02 00:18 UTC, BenHenning commented
> > @veena14cs and @BenHenning I haven't reviewed the PR has based on Ben's comment it can have significant changes in styles.xml file and therefore different layout files too. I have created this gist which highlights two possible solutions that we can do. Have a look and please confirm which one we should finalise. https://gist.github.com/rt4914/464763d4c634abbccfa1fada080be5e8
> 
> Thanks @rt4914 2nd approach looks good to me. I would defer it to @BenHenning too for what more can be done to simplify it.

Just followed up on the Gist.

2021-11-05 00:40 UTC, BenHenning commented
De-assigning per the email thread. Please assign back once you confirm the final approach here, and the PR is fully up-to-date.

2021-11-08 19:21 UTC, rt4914 requested changes
I haven't checked it fully but the comment is similar to your other PRs which is where ever you have introduced a style make sure layout_width and layout_height  is removed if not required.

Thanks @veena14cs

2021-11-09 13:10 UTC, veena14cs commented
> I haven't checked it fully but the comment is similar to your other PRs which is where ever you have introduced a style make sure layout_width and layout_height is removed if not required.
> 
> Thanks @veena14cs

Done Thanks.

2021-11-09 20:43 UTC, rt4914 requested changes
@veena14cs Left suggestions on couple files but I think they will apply to all files. Can you please update all files accordingly and do a self-review. Thanks.

2021-11-09 20:43 UTC, rt4914 commented on app/src/main/res/layout-land/lessons_chapter_view.xml
>        android:layout_height="wrap_content"
Remove `layout_width` and `layout_height` attribute as it is already mentioned in `Body` style. (Make sure its `wrap_content` only in styles.xml)

2021-11-09 20:43 UTC, rt4914 commented on app/src/main/res/layout-land/lessons_chapter_view.xml
>        android:layout_height="wrap_content"
Remove `layout_width` and `layout_height` attribute as it is already mentioned in `Body` style. (Make sure its `wrap_content` only in styles.xml)

2021-11-09 20:43 UTC, rt4914 commented on app/src/main/res/layout-land/ongoing_story_card.xml
> -          android:layout_width="match_parent"
Why was this removed? I think this is different from `styles.xml` file as it is not wrap_content

2021-11-09 20:43 UTC, rt4914 commented on app/src/main/res/layout-land/ongoing_topic_item.xml
>            android:layout_height="wrap_content"
Remove `layout_height` attribute as it is already mentioned in `Body` style. (Make sure its `wrap_content` only in styles.xml)

2021-11-09 20:43 UTC, rt4914 commented on app/src/main/res/layout-land/ongoing_topic_item.xml
>            android:layout_height="wrap_content"
Remove`layout_height` attribute as it is already mentioned in `Body` style. (Make sure its `wrap_content` only in styles.xml)

2021-11-09 20:43 UTC, rt4914 commented on app/src/main/res/layout-land/option_app_language.xml
>        android:layout_height="wrap_content"
Remove `layout_height` attribute as it is already mentioned in `Body` style. (Make sure its `wrap_content` only in styles.xml)

2021-11-09 20:43 UTC, rt4914 commented on app/src/main/res/layout-land/option_app_language.xml
>        android:layout_height="wrap_content"
Remove `layout_height` attribute as it is already mentioned in `Body` style. (Make sure its `wrap_content` only in styles.xml)

2021-11-09 20:43 UTC, rt4914 commented on app/src/main/res/layout-land/option_audio_language.xml
>        android:layout_height="wrap_content"
Remove `layout_height` attribute as it is already mentioned in `Body` style. (Make sure its `wrap_content` only in styles.xml)

2021-11-09 20:43 UTC, rt4914 commented on app/src/main/res/layout-land/option_audio_language.xml
>        android:layout_height="wrap_content"
Remove `layout_height` attribute as it is already mentioned in `Body` style. (Make sure its `wrap_content` only in styles.xml)

2021-11-10 07:02 UTC, BenHenning commented
See https://github.com/oppia/oppia-android/pull/3989#pullrequestreview-802197532.

2021-11-16 09:25 UTC, veena14cs commented
Closing this PR as it is getting fixed in #3989 .

2021-11-16 09:25 UTC, closed without merging