Break *Required into 2 parts.
oppia/oppia-android pull request #4019
Opened 2021-11-30 20:10 UTC by rishidyno

#3890 
## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2021-12-01 08:08 UTC, rishidyno commented
@BenHenning I am getting this error. I tried adding app_language_resource_handler dependency in the app BUILD.bazel file. 

This is the error log

rishi@r:~/opensource/oppia-android$ bazel build //:oppia
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:oppia (280 packages loaded, 5615 targets configured).
INFO: Found 1 target...
ERROR: /home/rishi/opensource/oppia-android/app/BUILD.bazel:628:19: KotlinCompile //app:view_models_kt { kt: 156, java: 0, srcjars: 0 } for armeabi-v7a failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/io_bazel_rules_kotlin/src/main/kotlin/builder '--flagfile=bazel-out/android-armeabi-v7a-fastbuild/bin/app/view_models_kt-kt-java.jar-0.params'
warning: runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib-jdk7.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib-jdk8.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.5.0/header_kotlin-stdlib-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.5.0/header_kotlin-stdlib-common-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.5.0/header_kotlin-reflect-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.10/header_kotlin-stdlib-jdk8-1.4.10.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.4.10/header_kotlin-stdlib-jdk7-1.4.10.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-script-runtime.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-reflect.jar (version 1.4)
warning: some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
warning: runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib-jdk7.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib-jdk8.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.5.0/header_kotlin-stdlib-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.5.0/header_kotlin-stdlib-common-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.5.0/header_kotlin-reflect-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.10/header_kotlin-stdlib-jdk8-1.4.10.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.4.10/header_kotlin-stdlib-jdk7-1.4.10.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-script-runtime.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-reflect.jar (version 1.4)
warning: some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
app/src/main/java/org/oppia/android/app/profile/AddProfileViewModel.kt:25:79: error: unresolved reference: add_profile_required
  val starRequired: String = "*" + resourceHandler.getStringInLocale(R.string.add_profile_required)
                                                                              ^
Compilation failure: compile phase failed:
warning: runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib-jdk7.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib-jdk8.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.5.0/header_kotlin-stdlib-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.5.0/header_kotlin-stdlib-common-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.5.0/header_kotlin-reflect-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.10/header_kotlin-stdlib-jdk8-1.4.10.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.4. [...]

2021-12-07 20:38 UTC, BenHenning commented
@rishidyno it looks like you addressed that problem by moving the view model to the VIEW_MODELS_WITH_RESOURCES list. However, you're also using a kotlinx import which shouldn't be used per https://developer.android.com/topic/libraries/view-binding/migration. You should use a direct resource reference, instead, and retrieve the view using findViewById.

2021-12-10 19:02 UTC, rishidyno commented
@BenHenning All tests have passed PTAL.

2021-12-14 05:36 UTC, BenHenning requested changes
Thanks @rishidyno! Took a full pass on the PR. Besides the comments I left in code, could you also please update your PR description to:

1. Include an explanation for what this PR is doing, and some context on the approach you're taking
2. To include a filled-in "For UI-specific PRs only" section (you should follow all the instructions list)
3. Under the 'For UI-specific PRs only' please also include at least one screenshot with Arabic to demonstrate the RTL behavior for this string (I want to make sure it reverses correctly)

2021-12-14 05:36 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/profile/AddProfileViewModel.kt
> +  val starRequired: String = "*" + resourceHandler.getStringInLocale(R.string.add_profile_required)
Suggest instead: ``requiredTextWithStar``

2021-12-14 05:36 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/profile/AddProfileActivityTest.kt
> +    ).use {
```suggestion
    launch(AddProfileActivity::class.java).use {
```

Nit: this can fit on one line.

2021-12-14 05:36 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/profile/AddProfileActivityTest.kt
> +  fun testAddProfileActivity_required_heading_text_view_hasCorrectRequiredString() {
This isn't really a heading, it's just a label. Perhaps instead:

```
testAddProfileActivity_hasRequiredTextPrefixedWithStar
```

2021-12-14 12:30 UTC, rishidyno commented
@BenHenning  I have added the SS and have addressed the changes. But there is no option for `Arabic [XB]` or `cibarA [XB]` in 
Emulators so, I am adding SS By `Force RTL layout direction` in the developer option.

2021-12-16 01:11 UTC, BenHenning approved these changes
Thanks @rishidyno. This LGTM--nothing else to add!

2021-12-16 01:12 UTC, BenHenning commented
I'm force merging this since @rt4914 is out & I'm more or less covering his codeowners this week. I reviewed the whole PR & everything LGTM, plus tests are passing.

2021-12-16 01:12 UTC, merged

2021-12-16 03:55 UTC, rishidyno commented
Thanks @BenHenning