Fix #3333: Create BUILD.bazel file for domail/profile.
oppia/oppia-android pull request #4074
Opened 2021-12-30 07:18 UTC by rishidyno

Fix #3333 
## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2022-01-04 12:10 UTC, rishidyno commented
@BenHenning All tests have passes PTAL .

2022-01-08 07:07 UTC, BenHenning requested changes
Thanks @rishidyno! Apologies for the late review. The PR looks good; just had 1 comment nit. PTAL.

2022-01-08 07:07 UTC, BenHenning commented on domain/src/main/java/org/oppia/android/domain/profile/BUILD.bazel
> +Utilities for managing profile.
```suggestion
Domain definitions and controllers for managing profiles.
```

These are specific to the domain layer and aren't general-purpose utilities.

2022-01-08 08:39 UTC, rishidyno commented
@BenHenning PTAL changes were made

2022-01-12 04:15 UTC, BenHenning approved these changes
Thanks @rishidyno. LGTM!

2022-01-12 04:15 UTC, merged