Fix #bugnum: #3560  Merge profile_list_fragment.xml into single xml file
oppia/oppia-android pull request #4088
Opened 2022-01-08 06:37 UTC by Rishavgupta12345

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

Fix #bugnum: #3560   Merge profile_list_fragment.xml into single xml file

screenshorts :-

mobile portrait before -
![Screenshot 2022-01-07 195039](https://user-images.githubusercontent.com/74723804/148634434-08379fd4-defe-463c-8e70-85a91320712e.png)

mobile portrait after -
![Screenshot 2022-01-07 195039](https://user-images.githubusercontent.com/74723804/148634443-3c7f42de-9625-41c8-8e5b-d8da2afc19f9.png)

mobile landscape before -
![Screenshot 2022-01-07 195108](https://user-images.githubusercontent.com/74723804/148634463-7300a6ec-2581-48fc-9540-b42645e78982.png)

mobile landscape after -
![Screenshot 2022-01-07 195108](https://user-images.githubusercontent.com/74723804/148634471-8d1163ec-650d-40cb-996d-b651407707be.png)

tab portrait before -
![Screenshot 2022-01-07 195201](https://user-images.githubusercontent.com/74723804/148634482-9637dbed-0546-4561-bc48-930654d1cb1b.png)

tab portrait after -
![Screenshot 2022-01-07 195201](https://user-images.githubusercontent.com/74723804/148634490-9c5c906e-069b-4382-bec8-6c7518e449a8.png)

tab landscape before -
![Screenshot 2022-01-07 195146](https://user-images.githubusercontent.com/74723804/148634495-91361334-b1cf-4e12-966e-a674fd4a8ccf.png)

tab landscape after -
![Screenshot 2022-01-07 195146](https://user-images.githubusercontent.com/74723804/148634504-e25eb542-12fd-4081-819a-00fbfa04a719.png)

2022-01-10 04:48 UTC, Rishavgupta12345 commented
PTAL @rt4914

2022-01-10 05:32 UTC, bkaur-bkj requested changes
@Rishavgupta12345 the screenshots you have provided is incorrect, you have to run the app in your mobile or emulator and then take screenshots

2022-01-10 05:55 UTC, Rishavgupta12345 commented
> @Rishavgupta12345 the screenshots you have provided is incorrect, you have to run the app in your mobile or emulator and then take screenshots

then I have to download many emulators , for mobile and tab all of that

2022-01-10 06:30 UTC, Rishavgupta12345 commented
PTAL @rt4914

2022-01-11 04:28 UTC, bkaur-bkj commented
> > @Rishavgupta12345 the screenshots you have provided is incorrect, you have to run the app in your mobile or emulator and then take screenshots
> 
> then I have to download many emulators , for mobile and tab all of that

yes you need to download a mobile and tablet emulator

2022-01-11 04:29 UTC, bkaur-bkj requested changes
@Rishavgupta12345 your branch has merge conflicts, kindly resolve them

2022-01-11 04:39 UTC, Rishavgupta12345 commented
> @Rishavgupta12345 your branch has merge conflicts, kindly resolve them

I don't know how to do that please explain

after clicking the resolve conflicts button Dimens.xml file is opening what to do there ??? I am not getting it

2022-01-13 04:10 UTC, bkaur-bkj commented
@Rishavgupta12345 remember to keep the assignee section updated, if you wont assign us back we won't be notified

2022-01-13 04:14 UTC, bkaur-bkj requested changes
@Rishavgupta12345to resolve conflicts you don't need to add these extra blank lines, kindly remove them, if you know that the conflict which is coming is fine or can be pushed so remove that comment line from code and push it back after marking it resolved

2022-01-13 04:14 UTC, bkaur-bkj commented on app/src/main/res/values/dimens.xml
> +
@Rishavgupta12345 why are extra line spaces here?

2022-01-13 04:14 UTC, bkaur-bkj commented on app/src/main/res/values/dimens.xml
> +
@Rishavgupta12345 also here?

2022-01-13 04:34 UTC, Rishavgupta12345 commented
PTAL @bkaur-bkj done the requested changes

2022-01-13 14:23 UTC, Rishavgupta12345 commented
PTAL @bkaur-bkj

2022-01-14 13:42 UTC, bkaur-bkj requested changes

2022-01-14 13:42 UTC, bkaur-bkj commented on app/src/main/res/values-land/dimens.xml
> +
@Rishavgupta12345 As I asked in last review these are not removed

2022-01-14 13:43 UTC, bkaur-bkj commented
@Rishavgupta12345 also you don't need to resolve any conversation yourself, just reply done to my msg

2022-01-15 04:35 UTC, Rishavgupta12345 commented
PTAL @bkaur-bkj

2022-01-17 05:36 UTC, bkaur-bkj requested changes
@Rishavgupta12345 the fragments are not merged properly , we have app bar in tablet mode whereas we don't have that in mobile layout , also we have padding bottom va;lue different also which is not addressed kindly use textcompare to compare the differences between files

2022-01-17 12:57 UTC, Rishavgupta12345 commented
> @Rishavgupta12345 the fragments are not merged properly , we have app bar in tablet mode whereas we don't have that in mobile layout , also we have padding bottom va;lue different also which is not addressed kindly use textcompare to compare the differences between files

that app bar in tablet mode is a layout configuration of the tablet emulater i am using . It has nothing to do with the code . if someone use different emulater for that then he wont get that app bar , nothing to worry with it PTAL @bkaur-bkj

2022-01-17 15:16 UTC, ARJUPTA requested changes
@Rishavgupta12345 PTAL at the requested changes and reply done to all of them once you have committed your changes. Also avoid resolving the comments on your own.

2022-01-17 15:16 UTC, ARJUPTA commented on app/src/main/res/layout-land/profile_list_fragment.xml
> -      android:layout_height="wrap_content"
> that app bar in tablet mode is a layout configuration of the tablet emulater i am using . It has nothing to do with the code . if someone use different emulater for that then he wont get that app bar , nothing to worry with it PTAL @bkaur-bkj

@Rishavgupta12345 I see that you have merged the sw600dp (tablet) and mobile xml files without considering the fact that the tablet one doesn't have any `AppBarLayout` component. This means when we would be using `profile_list_fragment` for a tablet device, we will be seeing an extra AppBar in the screen (You can see that there is an unnecessary AppBar shown in the tablet screenshots)

2022-01-17 15:16 UTC, ARJUPTA commented on app/src/main/res/values-land/dimens.xml
>    <!-- StoryFragment -->
The `profile_list_fragment_recycler_view_padding_bottom` for the landscape xml file is 108dp, please verify this at your end.

2022-01-17 15:16 UTC, ARJUPTA commented on app/src/main/res/values-sw600dp-land/dimens.xml
>  </resources>
As the `profile_list_fragment_recycler_view_padding_bottom` for both sw600dp and mobile layout is same (40dp) therefore we don't need to create another dimens here.

2022-01-17 15:16 UTC, ARJUPTA commented on app/src/main/res/values/dimens.xml
>  </resources>
Avoid introducing unnecessary blank lines. Ditto in other xml files too.

2022-01-20 13:26 UTC, ARJUPTA requested changes
@Rishavgupta12345 you have not made any of the suggested changes. If you feel the suggested changes are not reasonable then reply with an explaination for the same so that we can discuss it over comments

2022-01-20 13:57 UTC, Rishavgupta12345 commented
> @Rishavgupta12345 you have not made any of the suggested changes. If you feel the suggested changes are not reasonable then reply with an explaination for the same so that we can discuss it over comments

I have written a reply to each of your suggested comments I just want you to give a look at them

2022-01-20 13:58 UTC, Rishavgupta12345 commented
> > @Rishavgupta12345 you have not made any of the suggested changes. If you feel the suggested changes are not reasonable then reply with an explaination for the same so that we can discuss it over comments
> 
> I have written a reply to each of your suggested comments I just want you to give a look at them and guide me as requested

2022-01-21 06:45 UTC, rt4914 commented
> > @Rishavgupta12345 you have not made any of the suggested changes. If you feel the suggested changes are not reasonable then reply with an explaination for the same so that we can discuss it over comments
> 
> I have written a reply to each of your suggested comments I just want you to give a look at them

@Rishavgupta12345 Can you please check that again as I am unable to see your replies on previous comments.

2022-01-21 08:47 UTC, Rishavgupta12345 commented
> > > @Rishavgupta12345 you have not made any of the suggested changes. If you feel the suggested changes are not reasonable then reply with an explaination for the same so that we can discuss it over comments
> > 
> > 
> > I have written a reply to each of your suggested comments I just want you to give a look at them
> 
> @Rishavgupta12345 Can you please check that again as I am unable to see your replies on previous comments.

GO TO THE FILES CHANGED OPTION you will get the comments there

2022-02-02 07:48 UTC, rt4914 commented
@Rishavgupta12345 

> > > @Rishavgupta12345 you have not made any of the suggested changes. If you feel the suggested changes are not reasonable then reply with an explaination for the same so that we can discuss it over comments
> > 
> > 
> > I have written a reply to each of your suggested comments I just want you to give a look at them
> 
> @Rishavgupta12345 Can you please check that again as I am unable to see your replies on previous comments.

@Rishavgupta12345 Actually it will be visible to you only and not us. You have commented in "Files changed" section in that case to submit all your comments for everyone you will need to "Review changes" green-button on top-right corner and click on "Submit review". Currently the changes are available on your local machine only and have not been pushed for public view.
<img width="1057" alt="Screenshot 2022-02-02 at 1 18 40 PM" src="https://user-images.githubusercontent.com/9396084/152113840-dcd0e70f-0f90-4633-b011-64e8317674bd.png">

2022-02-02 12:29 UTC, Rishavgupta12345 commented on app/src/main/res/values-land/dimens.xml
> +
done PTAl @bkaur-bkj

2022-02-02 12:29 UTC, Rishavgupta12345 commented on app/src/main/res/values/dimens.xml
>  </resources>
this isn't a extra line basically after line 598 a gap of line 599 was already present to separate with the line 600 , so it is a necessary thing to do

2022-02-02 12:29 UTC, Rishavgupta12345 commented on app/src/main/res/values-sw600dp-land/dimens.xml
>  </resources>
so should i delete this three lines ???

2022-02-02 12:29 UTC, Rishavgupta12345 commented on app/src/main/res/values-land/dimens.xml
>    <!-- StoryFragment -->
yes I am rectifying it

2022-02-02 12:29 UTC, Rishavgupta12345 commented on app/src/main/res/layout-land/profile_list_fragment.xml
> -      android:layout_height="wrap_content"
how should I resolve this problem , can you please guide me

2022-02-02 12:29 UTC, Rishavgupta12345 commented
> @Rishavgupta12345
> 
> > > > @Rishavgupta12345 you have not made any of the suggested changes. If you feel the suggested changes are not reasonable then reply with an explaination for the same so that we can discuss it over comments
> > > 
> > > 
> > > I have written a reply to each of your suggested comments I just want you to give a look at them
> > 
> > 
> > @Rishavgupta12345 Can you please check that again as I am unable to see your replies on previous comments.
> 
> @Rishavgupta12345 Actually it will be visible to you only and not us. You have commented in "Files changed" section in that case to submit all your comments for everyone you will need to "Review changes" green-button on top-right corner and click on "Submit review". Currently the changes are available on your local machine only and have not been pushed for public view. <img alt="Screenshot 2022-02-02 at 1 18 40 PM" width="1057" src="https://user-images.githubusercontent.com/9396084/152113840-dcd0e70f-0f90-4633-b011-64e8317674bd.png">

acha got it now

2022-02-09 20:07 UTC, rt4914 requested changes
@Rishavgupta12345 You cannot make changes to tablet file because if you compare it correctly the tablet file does not contain toolbar and the mobile related files do contain toolbar.

Undo the changes file tablet files.

2022-02-09 20:07 UTC, rt4914 commented on app/src/main/res/values-land/dimens.xml
> +
Remove this extra blank line

2022-02-09 20:07 UTC, rt4914 commented on app/src/main/res/values/dimens.xml
> +
Remove this extra blank line

2022-02-09 20:07 UTC, rt4914 commented on app/src/main/res/values-land/dimens.xml
> +  <dimen name="profile_list_fragment_recycler_view_padding_bottom">40dp</dimen>
This value should be `108dp` please check and confirm this once again.

2022-02-14 11:50 UTC, rt4914 commented
@Rishavgupta12345 @ARJUPTA Any updates on this?

2022-02-15 05:36 UTC, ARJUPTA commented
> @Rishavgupta12345 @ARJUPTA Any updates on this?

@rt4914 I guess @Rishavgupta12345 is inactive currently so we can close this PR now so that any other contributor can work in this issue.

2022-02-15 05:48 UTC, rt4914 commented
Thanks @ARJUPTA . Make the necessary adjustments to new-contributor-tracker.

2022-02-15 05:48 UTC, closed without merging