Fix #3554 Merge options_without_drawer_activity.xml
oppia/oppia-android pull request #4089
Opened 2022-01-09 15:21 UTC by bhaktideshmukh

## Explanation

There are 3 files with the same name, 2 of them are identical
(now merged to a single file) and the third one has a different
layout.

![Screenshot from 2022-01-09 20-50-20](https://user-images.githubusercontent.com/78796264/148688635-c9c9a5be-1d81-4ee5-bf8f-e6552702b91c.png)

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2022-01-18 18:23 UTC, bhaktideshmukh commented
PTAL @rt4914 
Thanks.

2022-01-18 18:28 UTC, yash10019coder commented
Hi @bhaktideshmukh please add proper screenshots of tablet and emulator you can take a look at this PR for reference [link](https://github.com/oppia/oppia-android/pull/3523) and @rt4914 please approve the workflow, thanks.

2022-01-18 18:30 UTC, yash10019coder requested changes
also try to remove swp600/land and swp600/port and try to run the app and see if anything breaks thanks.

2022-01-19 13:08 UTC, rt4914 approved these changes
LGTM, the solution is correct.

2022-01-19 13:09 UTC, rt4914 commented
> Hi @bhaktideshmukh please add proper screenshots of tablet and emulator you can take a look at this PR for reference [link](https://github.com/oppia/oppia-android/pull/3523) and @rt4914 please approve the workflow, thanks.

@yash10019coder For this PR the description does contain correct screenshots and the reason mentioned is also correct.

2022-01-26 04:13 UTC, bhaktideshmukh commented
Gentle reminder for merging this PR .
PTAL @rt4914 
Thanks.

2022-01-26 09:58 UTC, yash10019coder approved these changes
LGTM @bhaktideshmukh thanks

2022-01-27 16:31 UTC, merged