Fix #3551 option audio language.xml
oppia/oppia-android pull request #4112
Opened 2022-01-19 12:01 UTC by shankarpriyank

PTAL @bkaur-bkj
## Explanation
- Merged 2 files of option_audio_language.xml
  - "Fixes #3551:" 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing
- ![oopia landscape](https://user-images.githubusercontent.com/75121767/150120043-2f9b43b1-cd91-4dac-bdcc-cefe5ab82c45.png)
![oppia portrait](https://user-images.githubusercontent.com/75121767/150120059-aa1418ce-d520-4a24-a224-03eb3eeb809e.png)
![oppia tablet  landscape](https://user-images.githubusercontent.com/75121767/150120062-d29b0879-e67a-4fae-83fb-be568f955389.png)
![oppia tablet potrait](https://user-images.githubusercontent.com/75121767/150120064-d53a02c6-0425-4db8-bc65-3f74fc953c19.png)
![rtl oppia](https://user-images.githubusercontent.com/75121767/150120070-bc7b9257-91bc-44e4-914c-dac4e4dc23ce.png)
![rtl oppia1](https://user-images.githubusercontent.com/75121767/150120077-c56c68ad-b843-487e-9c91-c20fa1f154c0.png)

2022-01-19 12:25 UTC, bkaur-bkj reviewed
@shankarpriyank merging of mobile layout files looks fine to me, have you checked for the tablet layout files?

2022-01-19 14:13 UTC, shankarpriyank commented
> @shankarpriyank merging of mobile layout files looks fine to me, have you checked for the tablet layout files?
It has some differences I don't know how to deal with , which are
` <variable
      name="commonViewModel"
      type="org.oppia.android.app.options.OptionControlsViewModel" />
 android:background="@{commonViewModel.selectedFragmentIndex == viewModel.itemIndex ? @drawable/general_item_background_border_cyan : @drawable/general_item_background_border}"`

2022-01-21 08:09 UTC, bkaur-bkj commented
> > @shankarpriyank merging of mobile layout files looks fine to me, have you checked for the tablet layout files?
> > It has some differences I don't know how to deal with , which are
> > ` <variable       name="commonViewModel"       type="org.oppia.android.app.options.OptionControlsViewModel" />  android:background="@{commonViewModel.selectedFragmentIndex == viewModel.itemIndex ? @drawable/general_item_background_border_cyan : @drawable/general_item_background_border}"`

Yes I think tablet and mobile layout can't be merged further. LGTM

2022-01-21 08:09 UTC, bkaur-bkj approved these changes
@rt4914 PTAL, It LGTM

2022-01-25 15:36 UTC, rt4914 requested changes
Similar to this comment https://github.com/oppia/oppia-android/pull/4125#pullrequestreview-862412352

Even all files in this PR can be merged. Also please recreate the after screenshots once these changes are done.

2022-01-25 15:36 UTC, rt4914 commented on app/src/main/res/values/dimens.xml
> +  <!--OptionAudioLanguage-->
Nit: `<!-- OptionAudioLanguage -->`

2022-01-25 15:36 UTC, rt4914 commented on app/src/main/res/values-land/dimens.xml
> +  <!--OptionAudioLanguage-->
Ditto

2022-02-08 16:12 UTC, closed without merging