Fix #3552 option_story_text_size.xml
oppia/oppia-android pull request #4125
Opened 2022-01-21 16:17 UTC by shankarpriyank

PTAL @bkaur-bkj
## Explanation
- Merged 2 files of  option_story_text_size.xml 
 - Fixes #3552

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

![land](https://user-images.githubusercontent.com/75121767/150561692-1be13afd-fdec-4547-94ab-e863fda761fd.png)
![potrait ](https://user-images.githubusercontent.com/75121767/150561704-2f7443d6-a93c-4ba9-9bcf-c0def1e04997.png)
![rtl land](https://user-images.githubusercontent.com/75121767/150561726-ec67b18d-09de-4075-9414-f30d7478b9ec.png)
![rtl](https://user-images.githubusercontent.com/75121767/150561740-afca03c2-67b1-450f-bb5c-a190e95f9a4e.png)

2022-01-21 16:30 UTC, bkaur-bkj commented
@shankarpriyank Write PTAL @reviewe name  in the comments not in the explanation, do edit it

2022-01-21 16:37 UTC, shankarpriyank commented
PTAL @bkaur-bkj

2022-01-21 16:38 UTC, bkaur-bkj approved these changes
The changes LGTM. @rt4914 PTAL

2022-01-25 15:00 UTC, rt4914 reviewed
Thanks @shankarpriyank 

I think sw600dp/option_story_text_size can also be merged.

Basically use the code of `sw600dp/option_story_text_size` in `layout/option_story_text_size.xml` and also in `sw600dp/dimens.xml` file use following:

```
<!-- StoryTextSize -->
  <dimen name="option_story_text_size_padding_start">16dp</dimen>
  <dimen name="option_story_text_size_padding_end">16dp</dimen>
```

2022-01-25 15:01 UTC, rt4914 requested changes
PTAL.  Also please recreate the after screenshots once these changes are done.

2022-01-25 15:01 UTC, rt4914 commented on app/src/main/res/values/dimens.xml
> +  <!-- StoryTextSize -->
Update to `Options story text size` as this is not a file instead just a regular comment. For files we use `AbcXyz`

2022-01-25 17:30 UTC, bkaur-bkj commented
> Thanks @shankarpriyank
> 
> I think sw600dp/option_story_text_size can also be merged.
> 
> Basically use the code of `sw600dp/option_story_text_size` in `layout/option_story_text_size.xml` and also in `sw600dp/dimens.xml` file use following:
> 
> ```
> <!-- StoryTextSize -->
>   <dimen name="option_story_text_size_padding_start">16dp</dimen>
>   <dimen name="option_story_text_size_padding_end">16dp</dimen>
> ```

@rt4914 I wanted to know that how is it possible to access a property from viewmodel if it has been not initialised for mobile xmls.

2022-01-25 17:41 UTC, shankarpriyank commented
@rt4914 There are two files for the tablet layout(landscape,potrait), should I add dimens in both of them?

2022-02-02 07:55 UTC, rt4914 commented
> > Thanks @shankarpriyank
> > I think sw600dp/option_story_text_size can also be merged.
> > Basically use the code of `sw600dp/option_story_text_size` in `layout/option_story_text_size.xml` and also in `sw600dp/dimens.xml` file use following:
> > ```
> > <!-- StoryTextSize -->
> >   <dimen name="option_story_text_size_padding_start">16dp</dimen>
> >   <dimen name="option_story_text_size_padding_end">16dp</dimen>
> > ```
> 
> @rt4914 I wanted to know that how is it possible to access a property from viewmodel if it has been not initialised for mobile xmls.

@bkaur-bkj If the values are not initialised then we cannot use it. But if we thing that merging files can become easy, in that case you can inititalse the value in ViewModel so that you can use it in xml files.

2022-02-02 07:56 UTC, rt4914 commented
> @rt4914 There are two files for the tablet layout(landscape,potrait), should I add dimens in both of them?

@shankarpriyank If needed then yes add it in both files.

2022-02-02 10:34 UTC, bkaur-bkj commented
> > > Thanks @shankarpriyank
> > > I think sw600dp/option_story_text_size can also be merged.
> > > Basically use the code of `sw600dp/option_story_text_size` in `layout/option_story_text_size.xml` and also in `sw600dp/dimens.xml` file use following:
> > > ```
> > > <!-- StoryTextSize -->
> > >   <dimen name="option_story_text_size_padding_start">16dp</dimen>
> > >   <dimen name="option_story_text_size_padding_end">16dp</dimen>
> > > ```
> > 
> > 
> > @rt4914 I wanted to know that how is it possible to access a property from viewmodel if it has been not initialised for mobile xmls.
> 
> @bkaur-bkj If the values are not initialised then we cannot use it. But if we thing that merging files can become easy, in that case you can inititalse the value in ViewModel so that you can use it in xml files.

Okay got it

2022-02-14 13:18 UTC, rt4914 requested changes
@shankarpriyank There are couple of issues with this PR. 

1. Looks like your branch has been deleted as I am unable go to your branch.
2. There are changes which should not be part of this PR. See "File Changed" section in github. To fix this either merge with latest develop from oppia or undo the changes.

2022-02-14 13:18 UTC, rt4914 commented on app/src/main/res/values/dimens.xml
> +  <!-- Options story text size  -->
Update to `<!-- Options story text size -->` . There is one extra space just after `size`. Ditto change for other xml files.

2022-02-14 13:20 UTC, rt4914 commented
@bkaur-bkj How did this PR work for you? I am unable to check the branch. Looks like it has been deleted and also all theCI checks are stopped is weird.

2022-02-14 13:31 UTC, shankarpriyank commented
> @shankarpriyank There are couple of issues with this PR.
> 
> 1. Looks like your branch has been deleted as I am unable go to your branch.
> 2. There are changes which should not be part of this PR. See "File Changed" section in github. To fix this either merge with latest develop from oppia or undo the changes.

Yes I actually deleted this repo, I had a talk with my mentors ,  I messed up the branch real bad , so and it was suggested  that it would  be best if I make a new pr for this issue

2022-02-14 13:33 UTC, shankarpriyank commented
Also I actually merged all the three files in one , but It was not working as intended , I will attach the screenshots in a fresh pr

2022-02-14 14:46 UTC, closed without merging