Fix #4123: Duplicate recently played stories list
oppia/oppia-android pull request #4127
Opened 2022-01-22 16:34 UTC by ShivanshGoel221B

## Explanation

Fix #4123 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

The recently played card list seemed to be duplicated every time the fragment is recreating (or on Activity onResume).
This is because the updated list was getting added to the previous list without clearing it first. So, I added a line to CLEAR the list before adding the updating the items in it by calling `itemList.clear()` before adding new items.

2022-01-31 09:18 UTC, ayush0402 commented
@rt4914 Can you approve the workflow? Thanks.

2022-02-02 11:10 UTC, rt4914 requested changes
@ShivanshGoel221B Please add a video/gif displaying that this issue no longer exists. 

@ayush0402 Can you please run this and confirm that this does work correctly.

Make sure that when you reach any `Exploration` (Place where you can actually answer few questions) you answer couple of questions before leaving it.

2022-02-03 12:57 UTC, ayush0402 commented
@rt4914 Yes, this seems to have fixed the bug.

2022-02-04 06:07 UTC, ShivanshGoel221B commented
> @ShivanshGoel221B Please add a video/gif displaying that this issue no longer exists.
> 
> @ayush0402 Can you please run this and confirm that this does work correctly.
> 
> Make sure that when you reach any `Exploration` (Place where you can actually answer few questions) you answer couple of questions before leaving it.

@rt4914 Done

2022-02-08 15:42 UTC, rt4914 approved these changes
LGTM.

 Just merge your PR with latest develop and it should be ready to merge.

2022-02-08 18:03 UTC, ShivanshGoel221B commented
> LGTM.
> 
> Just merge your PR with latest develop and it should be ready to merge.

@rt4914 Done that

2022-02-14 11:54 UTC, rt4914 commented
@ShivanshGoel221B Unfortunately I will need to close this PR.



> > LGTM.
> > Just merge your PR with latest develop and it should be ready to merge.
> 
> @rt4914 Done that

Unfortunately I will have to close this PR.

There is one force-push commit in this PR and we cannot merge this. 
Force-push commits actually tampers the commit-history.
It has been mentioned in Step 3 in https://github.com/oppia/oppia-android/wiki/making-a-code-change#making-a-code-change-using-the-terminal

You can create a new PR without force-push and assign it to correct reviewers.

2022-02-14 11:54 UTC, closed without merging