Fix #1951 Optimise hints_summary.xml
oppia/oppia-android pull request #4153
Opened 2022-02-03 16:52 UTC by ArchitJain1201

## Explanation

Fix #1951
Fix #3537 Merge hints_summary.xml into single xml file 
## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

**Before**
![3 1](https://user-images.githubusercontent.com/80871543/152388351-a040fb17-01d1-4d63-884b-db132a6e0728.jpg)
**After**
![3 1a](https://user-images.githubusercontent.com/80871543/152388392-6edc44e0-c21b-4955-9f2d-9133d359ef11.jpg)
**Before**
![3 2](https://user-images.githubusercontent.com/80871543/152388420-8e824b2b-db4e-4f6c-ac37-e790a7f56828.jpg)
**After**
![3 2a](https://user-images.githubusercontent.com/80871543/152388428-6beb0f22-d1bc-4494-9a28-122589d4dd81.jpg)

2022-02-03 16:54 UTC, ArchitJain1201 commented
## Changes Made
- Optimize hints_summary.xml
- Merged hints_summary.xml files into Single xml file 
- changed the textSize from 18sp to 16sp in style for Heading4

2022-02-03 16:59 UTC, ArchitJain1201 commented
Problem
- App is crashing in Table mode not able to find the Reason
- Not able to use contraintLayout in @+id/hint_summary_container and @+id/hint_list_container as @+id/hint_list_container require to be constraint which is disturbing the UI
- Not able to add app:layout_constraintStart_toEndOf="@+id/hint_title" in FrameLayout @+id/expand_list_icon as Table mode don't require it.

PTAl @rt4914  @bkaur-bkj

2022-02-04 14:14 UTC, bkaur-bkj requested changes
@ArchitJain1201 PTAL at these minor changes, also regarding the problem mentioned I am also not sure why it crashes, @rt4914 PTAL

2022-02-04 14:14 UTC, bkaur-bkj commented on app/src/main/res/layout/hints_summary.xml
> +</layout>
@ArchitJain1201 add a newline here

2022-02-04 14:14 UTC, bkaur-bkj commented on app/src/main/res/values-sw600dp-land/dimens.xml
> +  <dimen name="hint_summary_hint_list_container_layout_marginTop">0dp</dimen>
@ArchitJain1201 newline above `</resources>` like it was before, also do it in all the dimens file too.

2022-02-04 14:22 UTC, bkaur-bkj commented on app/src/main/res/values/styles.xml
> +    <item name="android:textSize">16sp</item>
@ArchitJain1201 also I think this heading 4 value should not be altered. Can you pls explain the reason for this change?

2022-02-04 14:41 UTC, ArchitJain1201 commented
PTAL @rt4914 @bkaur-bkj

2022-02-06 12:20 UTC, ArchitJain1201 commented on app/src/main/res/values/styles.xml
> +    <item name="android:textSize">16sp</item>
as Heading1 have textsize =24, Heading2 have textsize= 20, Heading3 have textsize= 18sp and Heading5 have textsize=14sp. So, I do think the textSize of Heading4 should be 16sp

2022-02-06 12:20 UTC, ArchitJain1201 commented on app/src/main/res/layout/hints_summary.xml
> +</layout>
done

2022-02-06 12:20 UTC, ArchitJain1201 commented on app/src/main/res/values-sw600dp-land/dimens.xml
> +  <dimen name="hint_summary_hint_list_container_layout_marginTop">0dp</dimen>
done

2022-02-08 15:58 UTC, rt4914 commented
Will review it after @bkaur-bkj 's approval.

2022-02-09 05:19 UTC, bkaur-bkj commented
@rt4914 I just have doubt regarding the change of heading size rest it LGTM

2022-02-09 18:48 UTC, ArchitJain1201 commented
PTAL @rt4914

2022-02-09 20:16 UTC, rt4914 requested changes
@ArchitJain1201 & @bkaur-bkj Apologies for delay. 

This PR has been done with great efforts but unfortunately I will have to close this PR and issue.

Reason: As I see the changes in this PR it looks that combining these xml files is really complicated, especially because of usage of `bias` in `mobile-portrait` and not in any other file. As a result I think that the better solution is to actually keep these files separate because even a minor change in any of the design for this screen will end up create a lot of confusion. But if we keep 4 files it will not be confusing it will just require extra efforts.

What are you thoughts?

2022-02-10 05:06 UTC, ArchitJain1201 commented
@rt4914 Sir, I do not think `bias` is a problem as by default bias is 0.5 (as far as I know) and I have assigned 0.5 in tablet mode but even if it is a problem then we can make it into two .XML file one for mobile and other for the tablet mode.(as basis is not used in tablet mode)

2022-02-10 05:09 UTC, ArchitJain1201 commented
@rt4914 please also look at the changes I made for `Heading4` in `style` file.

2022-02-13 06:58 UTC, ArchitJain1201 commented
PTAL @rt4914

2022-02-13 07:00 UTC, bkaur-bkj commented
> @ArchitJain1201 & @bkaur-bkj Apologies for delay.
> 
> This PR has been done with great efforts but unfortunately I will have to close this PR and issue.
> 
> Reason: As I see the changes in this PR it looks that combining these xml files is really complicated, especially because of usage of `bias` in `mobile-portrait` and not in any other file. As a result I think that the better solution is to actually keep these files separate because even a minor change in any of the design for this screen will end up create a lot of confusion. But if we keep 4 files it will not be confusing it will just require extra efforts.
> 
> What are you thoughts?

Yes as you said confusion can be created because of design changes, what are your reviews about the point mentioned by @ArchitJain1201 on bias?

2022-02-14 11:29 UTC, rt4914 commented
@ArchitJain1201 Your point is valid. If you can merge this in two files one for mobile (portrait + landscape) and second for tablet (portrait + landscape). I think that would be great. But do keep this point is mind: while making changes if you think that the changes are complicated and might create confusion in future then I suggest not to work on that further and instead close the PR/issue.

2022-02-18 13:35 UTC, ArchitJain1201 commented
PTAL @rt4914 @bkaur-bkj

2022-02-18 13:38 UTC, ArchitJain1201 commented
@rt4914 Sir, I have made two XML files one for mobile and the other for tablet versions. But it is still crashing for tablet version can you please check it. Please also look at the `Heading4` in the `style` file. I have provided the reasoning above on the @bkaur-bkj comment.

2022-02-21 16:35 UTC, rt4914 requested changes
@ArchitJain1201 Couple of points:
1. Have you tried these [steps](https://github.com/oppia/oppia-android/wiki/Frequent-Errors-and-Solutions#crashing-layout-tags-in-tablet) to fix the error. If the error still occurs can you mention the error.
2. Your Thought process regarding Heading4 is correct but we cannot make this change because Heading4 is getting used at other places too and it will change the UI for other screens. I suggest undo this change.

3. @bkaur-bkj Can you help Archit arrange the screenshot side-by-side for comparison in before/after screenshots. In current format they are hard to compare.

2022-03-07 17:56 UTC, closed without merging