Fix #3557 Merge profile chooser fragment into 2 fargments
oppia/oppia-android pull request #4158
Opened 2022-02-06 11:15 UTC by priyatanu

## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2022-02-06 11:19 UTC, priyatanu commented
![Profile_Chooser1](https://user-images.githubusercontent.com/18245363/152678331-d7e9b0d9-81c1-49a8-91b1-ee0b0145134e.PNG)

2022-02-06 11:19 UTC, priyatanu commented
![ProfileChooser2](https://user-images.githubusercontent.com/18245363/152678337-1ef777dc-bc77-4e24-8f37-a70c172dfd13.PNG)

2022-02-06 11:22 UTC, priyatanu commented
![ProfileChooser3](https://user-images.githubusercontent.com/18245363/152678461-2e8a213e-9bbf-4f1c-b44b-438543d9950a.PNG)

2022-02-06 11:22 UTC, priyatanu commented
![ProfileChooser4](https://user-images.githubusercontent.com/18245363/152678466-bdb6b669-82ee-497b-80f3-10ef414de3e0.PNG)

2022-02-06 11:42 UTC, priyatanu commented
PTAL @rishidyno , @ARJUPTA ,

Kindly review .

I made mistakes while rebasing the old PR while trying to open it https://github.com/oppia/oppia-android/pull/4143

So I created a new PR. sorry for the confusion

2022-02-09 10:14 UTC, rishidyno requested changes
@priyatanu Please add SS in a table take reference [here](https://github.com/oppia/oppia-android/pull/3644)

2022-02-09 10:14 UTC, rishidyno commented on app/src/main/res/values/dimens.xml
Please remove empty spaces.

2022-02-09 10:14 UTC, rishidyno commented on app/src/main/res/values/dimens.xml
> +
Ditto. Remove this extra line.

2022-02-09 10:24 UTC, rishidyno commented
Also, I can see that you are taking SS separately, use emulator SS feature to Take SS. 
![image](https://user-images.githubusercontent.com/78549195/153178957-3e4d7a5b-68fc-4681-b7ca-370c5266c98d.png)

2022-02-11 17:23 UTC, ARJUPTA requested changes
@priyatanu PTAL at the requested changes.

2022-02-11 17:23 UTC, ARJUPTA commented on app/src/main/res/layout-land/profile_chooser_fragment.xml
> -          android:layout_marginStart="36dp"
The style attribute here differs from the one in portrait xml (mobile). you forgot to resolve this.

2022-02-11 17:23 UTC, ARJUPTA commented on app/src/main/res/layout-sw600dp/profile_chooser_fragment.xml
>          android:minHeight="48dp"
can you also explain why a new **gravity** attribute has been introduced?

2022-02-11 17:23 UTC, ARJUPTA commented on app/src/main/res/values-sw600dp-land/dimens.xml
> +
If the `profile_chooser_fragment_margin_top_profile_already_added` and `profile_chooser_fragment_margin_top_profile_not_added` are already defined in the portrait xml (mobile). Then we do not need to denfine it here again.

2022-02-25 18:20 UTC, closed without merging

2022-04-01 09:08 UTC, priyatanu commented
open

2022-04-01 09:12 UTC, priyatanu commented
Hi, 
@rishidyno @ARJUPTA ,

I got extremely bsy with work. So the pull request is stale. I have addressed the comments in my new Pull request
- https://github.com/oppia/oppia-android/pull/4282,

Extremely sorry for the inconvenice