Merge administrator controls download permissions view into single xml
oppia/oppia-android pull request #4160
Opened 2022-02-07 13:37 UTC by Akshatkamboj14

## Explanation
solves #3411

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

| **BEFORE**  | **AFTER** |
| ------------- | ------------- |
| ![Screenshot_20220205_074706](https://user-images.githubusercontent.com/92685493/152796214-d21543ed-7bbf-43b7-ac73-fed4d4870b7c.png)| ![Screenshot_20220207_190240](https://user-images.githubusercontent.com/92685493/152797779-88963734-d959-4d4a-b656-065e46b39cc3.png) |
|  ![Screenshot_20220205_074800](https://user-images.githubusercontent.com/92685493/152796350-886dfff0-8378-4b74-9185-5b213da9330e.png)| ![Screenshot_20220207_190329](https://user-images.githubusercontent.com/92685493/152797961-00cb7ee7-109a-4b66-9cef-07bfad426db7.png) |
| ![Screenshot_20220205_080734](https://user-images.githubusercontent.com/92685493/152796493-14db1ee6-95f9-4712-b8b4-1fc21ac2214a.png) | Content Cell  |
| ![Screenshot_20220205_080916](https://user-images.githubusercontent.com/92685493/152796555-823d0627-9dbc-4c46-97b7-0d25b7f7c0a2.png) | Content Cell  |

2022-02-07 13:43 UTC, Akshatkamboj14 commented
my oppia app is not working on the tablet even before applying changes, it doesn't show any error but the app is crashing only when I am running it on the tablet otherwise on the phone it's working properly.

2022-02-07 14:13 UTC, Akshatkamboj14 commented
This is the error....
![Screenshot 2022-02-07 193828](https://user-images.githubusercontent.com/92685493/152804118-f1dc368b-299c-4849-b422-480cf8bd1a8f.jpg)
![Screenshot 2022-02-07 193908](https://user-images.githubusercontent.com/92685493/152804126-1e582594-4674-4555-9916-cc81d32c4998.jpg)
@rishidyno @rt4914

2022-02-07 15:32 UTC, ayush0402 commented
@Akshatkamboj14 Hey, I just tried running this PR locally and though I wasn't getting any error during the build but the app was crashing on the first screen on Pixel C API 28 tablet. But Cleaning and Rebuilding the project through the BUILD menu on toolbar has fixed that crash for me. Did you try doing so?

2022-02-07 17:12 UTC, Akshatkamboj14 commented
@ayush0402 thank you for your help now it's working fine.

2022-02-08 09:46 UTC, Akshatkamboj14 commented
@ayush0402 @rishidyno can you please check this failed test?

2022-02-08 17:32 UTC, rishidyno requested changes

2022-02-08 17:32 UTC, rishidyno commented on app/src/main/res/layout/administrator_controls_download_permissions_view.xml
> +        android:layout_marginEnd="@dimen/administrator_controls_download_permissions_view_lower_switch_compat_margin_end"
What does lower signify here? I suggest `administrator_controls_download_permissions_view_widget_switch_compat_margin_end` instead

2022-02-08 17:32 UTC, rishidyno commented on app/src/main/res/values-sw600dp-land/dimens.xml
> +  <!--  AdministratorControlDownloadPermissionsView-->
Please make sure spacing Is correct in comments.  e.g. `<!-- FAQ Single -->`
Ditto for others.

2022-02-08 17:32 UTC, rishidyno commented on app/src/main/res/layout/administrator_controls_download_permissions_view.xml
> +        android:layout_marginEnd="@dimen/administrator_controls_download_permissions_view_upper_switch_compat_margin_end"
I suggest `administrator_controls_download_permissions_view_widget_switch_compat_margin_end` instead
Ditto for others.

2022-02-08 17:32 UTC, rishidyno commented on app/src/main/res/layout/administrator_controls_download_permissions_view.xml
> +      android:paddingStart="@dimen/administrator_controls_download_permissions_view_upper_text_view_padding_start"
@Akshatkamboj14 please explain upper in this dimension name ? 
I suggest `administrator_controls_download_permissions_view_download_permissions_text_view_padding_start` instead.

2022-02-08 17:32 UTC, rishidyno commented on app/src/main/res/layout/administrator_controls_download_permissions_view.xml
> +      android:paddingEnd="@dimen/administrator_controls_download_permissions_view_upper_text_view_padding_end"
Ditto. Remove `upper` and use `administrator_controls_download_permissions_view_download_permissions_text_view_padding_end` instead

2022-02-08 17:32 UTC, rishidyno commented on app/src/main/res/layout/administrator_controls_download_permissions_view.xml
> +      android:paddingStart="@dimen/administrator_controls_download_permissions_view_upper_constraint_layout_padding_start"
Ditto.

2022-02-08 17:32 UTC, rishidyno commented on app/src/main/res/layout/administrator_controls_download_permissions_view.xml
> +      android:paddingEnd="@dimen/administrator_controls_download_permissions_view_upper_constraint_layout_padding_end"
Ditto.

2022-02-08 17:38 UTC, rishidyno commented
@Akshatkamboj14 I suggest cleaning and rebuilding the project. You can find these options in `Build` menu

![image](https://user-images.githubusercontent.com/78549195/153043900-0ce6ef4b-512d-496b-9cf7-6d96c303abd1.png)

2022-02-09 00:42 UTC, Akshatkamboj14 commented
@rishidyno okay i will do it.

2022-02-09 16:58 UTC, Akshatkamboj14 commented
@rishidyno please take a look

2022-02-23 18:30 UTC, closed without merging