Fix #3245 [A11y] Enabling AccessibilityChecks for QuestionPlayerActivityTest
oppia/oppia-android pull request #4173
Opened 2022-02-11 20:45 UTC by Rohit1173

## Explanation
Fix #3245 :Enable AccessibiltyChecks

Removed the `@DisableAccessibilityChecks` Annotation from the QuestionPlayerActivityTest
There are 2 tests with `@DisableAccessibilityChecks` Annotation in QuestionPlayerActivityTest
`fun testQuestionPlayer_terminalState_recyclerViewItemCount_countIsTwo()` and      
`fun testQuestionPlayer_terminalState_recyclerView_contentItem_isNotEmpty()`
and these were the screenshots after successfully running them

Device : Pixel 3a API 28
![A11y-1](https://user-images.githubusercontent.com/78897906/153663627-5f304cbd-ec3a-4cd4-8db2-2529c018b9d4.png)
![A11y-2](https://user-images.githubusercontent.com/78897906/153663930-a2b52388-6f3c-4496-a4f4-176f19360a0d.png)
                                                                                                                                                              

So after Fixing the layout height and width of `feedback_text_view` in `feedback_item.xml` to 48dp each and running again these were the results.

Device : Pixel 3a API 28
![A11y -1 after](https://user-images.githubusercontent.com/78897906/153664369-968f5858-8e3c-4f62-b287-c3a5768814ab.png)
![A11y-2 after](https://user-images.githubusercontent.com/78897906/153664379-0907a4fa-9f48-4986-9c5e-d7ad11404f78.png)

As the tests were successful, I have created new `dimens` values in `dimens.xml`,`dimens.xml (land)`,`dimens.xml(sw600dp-land)`,
`dimens.xml(sw600dp-port)` for layout height and width of `feedback_text_view`.

After that I have tested the above tests for tablets, these were the screenshots after successfully running them

Device : Pixel C API 28
![A11y -1 tab before](https://user-images.githubusercontent.com/78897906/153665631-49b21497-cb44-4a3c-9fdf-1e001958fb59.png)
![A11y-2 tab before](https://user-images.githubusercontent.com/78897906/153665640-e09938c7-a428-4e25-a481-1b5954ab1cb8.png)

So to fix these failing tests, I have set the layout height and width of `content_text_view` in `content_item.xml` to 48dp each

After making these changes and running again, these were the results

Device : Pixel C API 28
![A11y-1 tab after](https://user-images.githubusercontent.com/78897906/153666015-027a4d35-a086-4426-8d04-2965343eadd9.png)
![A11y-2 tab after](https://user-images.githubusercontent.com/78897906/153666026-0122daa6-1c72-44e4-b08b-f05e0ea48103.png)

As tests were passing again created `dimens` values for `content_text_view`, I thought these changes might affect the tests in the mobile emulator(Pixel 3a API 28), So I had tried running them again and the tests were passing.

Device : Pixel 3a API 28
![A11y-1 mobile last](https://user-images.githubusercontent.com/78897906/153666351-bc8e943e-b0cf-4f25-8956-0540a15b41aa.png)
![A11y-2 mobile last](https://user-images.githubusercontent.com/78897906/153666364-d88849e7-56a3-4998-a610-baf800998615.png)

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2022-02-11 21:14 UTC, Rohit1173 commented
@rt4914 I have got an error in tablet (Pixel-C API 28) to change the size of content_text_view but after changing it the tests were passed but the UI had changed and the content_item was shrunk. Could you please guide on me how to solve this

2022-02-14 07:45 UTC, rt4914 commented
> @rt4914 I have got an error in tablet (Pixel-C API 28) to change the size of content_text_view but after changing it the tests were passed but the UI had changed and the content_item was shrunk. Could you please guide on me how to solve this

1. I think we dont' need to worry about the width. Just mentioned `minWidth=48dp` should be fine.
2. Also for height also use `minWidth` instead of `layout_height`.
3. If there is any extra margin around the TextView you can shift that to padding of TextView and that way the height should automatically get fixed (upto certain extent and not fully).
4. As the changes in this PR deal with UI change please create before/after screenshot in mobile-portrait, landscape and tablet-portrait, landscape for Question Player as well as Exploration Player. Also as we are dealing with min-height based solution suggest picking an example for screenshot where the feedback item contains only 1 line of text so that we can correctly see the changes in before/after screenshots

2022-02-14 07:45 UTC, rt4914 commented
Also if you need reply on anything please Assign me in `Assignees` section so that I know I have check the PR.

2022-02-14 08:48 UTC, Rohit1173 commented
> > @rt4914 I have got an error in tablet (Pixel-C API 28) to change the size of content_text_view but after changing it the tests were passed but the UI had changed and the content_item was shrunk. Could you please guide on me how to solve this
> 
> 1. I think we dont' need to worry about the width. Just mentioned `minWidth=48dp` should be fine.
> 2. Also for height also use `minWidth` instead of `layout_height`.
> 3. If there is any extra margin around the TextView you can shift that to padding of TextView and that way the height should automatically get fixed (upto certain extent and not fully).
> 4. As the changes in this PR deal with UI change please create before/after screenshot in mobile-portrait, landscape and tablet-portrait, landscape for Question Player as well as Exploration Player. Also as we are dealing with min-height based solution suggest picking an example for screenshot where the feedback item contains only 1 line of text so that we can correctly see the changes in before/after screenshots

Got it, Thanks!!

2022-02-15 09:29 UTC, Rohit1173 commented
@rt4914 PTAL

2022-02-15 11:34 UTC, rt4914 requested changes
@Rohit1173 Suggested changes:

1. This PR is part of #3245 and does solve the entire issue. So please rename this to "Fix part of " in title and description.
2. This PR focuses on Exploration Player only. You should also check this for Question Player.
3. Have a look at https://github.com/oppia/oppia-android/issues/3927 as you are actually solving that issue too (sort of duplicate). Make sure that QuestionPlayerTests also pass and also share the before/after screenshot of question player UI for this particular test in #3927 is focused on.


From code wise it looks correct but we should still check UI and question player.

2022-02-17 08:30 UTC, Rohit1173 commented
@rt4914 updated the screenshots, PTAL, Thanks!

2022-02-22 04:41 UTC, rt4914 approved these changes
LGTM, thanks.

2022-02-22 04:41 UTC, rt4914 approved these changes
LGTM, thanks.

2022-02-22 04:42 UTC, merged