Fix: #3411 Merge administrator_controls_download_permissions_view into single xml file.
oppia/oppia-android pull request #4175
Opened 2022-02-13 06:35 UTC by Akshatkamboj14

## Explanation
FIXES #3411

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

| BEFORE  | AFTER  |
| --------- | -------- |
| ![Screenshot_20220212_235918](https://user-images.githubusercontent.com/92685493/153741234-79665fd5-fb33-49c8-b64a-47f0ce28ee67.png) | ![Screenshot_20220213_111909](https://user-images.githubusercontent.com/92685493/153741256-52e1e35e-04a0-4c5f-8ab3-86fae9d0bdd1.png) |
| ![Screenshot_20220213_000010](https://user-images.githubusercontent.com/92685493/153741333-bb31bcaf-5024-439a-9088-ef19ff292689.png) | ![Screenshot_20220213_111936](https://user-images.githubusercontent.com/92685493/153741353-00ea0372-29a3-40c0-891c-2d4ce3184f48.png) |
|![Screenshot_20220213_001428](https://user-images.githubusercontent.com/92685493/153741736-ff031c48-05ad-44ff-ae2e-0c01ccb1ccff.png)|![Screenshot_20220213_111012](https://user-images.githubusercontent.com/92685493/153741743-133a93f1-2c2e-4ddf-abfb-1df8408465f0.png)|
|![Screenshot_20220213_114014](https://user-images.githubusercontent.com/92685493/153741766-cfec4369-b707-4263-b4c2-e02491715efd.png)|![Screenshot_20220209_213851](https://user-images.githubusercontent.com/92685493/153741776-d0988902-db9d-4e00-ade4-1ae31967f665.png)|

2022-02-13 06:35 UTC, Akshatkamboj14 commented
@rishidyno please review it

2022-02-13 11:17 UTC, rishidyno requested changes

2022-02-13 11:17 UTC, rishidyno commented on app/src/main/res/values-sw600dp-land/dimens.xml
> +
Please remove this extra line.

2022-02-13 11:17 UTC, rishidyno commented on app/src/main/res/values-sw600dp-port/dimens.xml
> +
Ditto.

2022-02-13 11:21 UTC, rishidyno commented
And try to fix the failing check. I think this should not happen but seems to happen in other ps as well. Just commit the requested changes and will see what happens.

2022-02-13 12:28 UTC, rishidyno commented
Also update your project.

2022-02-13 14:21 UTC, Akshatkamboj14 commented
done @rishidyno

2022-02-14 13:12 UTC, rishidyno requested changes
@Akshatkamboj14 I think this pr is good to go, but always use same device to take SS. I suggest updating SS for mobile-land, thanks.

2022-02-15 07:17 UTC, Akshatkamboj14 commented
hey, @rishidyno I have updated the ss of mobile ones with the new emulator.

2022-02-15 08:02 UTC, rishidyno commented
@Akshatkamboj14 also resolve the merge conflict

2022-02-15 08:03 UTC, rishidyno commented
Also please keep the `Assignees` section up-to-date, so that we can know whether to review this PR or not.

2022-02-15 08:04 UTC, rishidyno commented
FYI the who has to review should be assigned

2022-02-15 09:27 UTC, rishidyno requested changes

2022-02-15 09:27 UTC, rishidyno commented on app/src/main/res/values-sw600dp-land/dimens.xml
> +
PTAL -->  this can be corrected.

2022-02-15 11:32 UTC, Akshatkamboj14 commented on app/src/main/res/values-sw600dp-land/dimens.xml
> +
done

2022-02-15 11:33 UTC, rishidyno commented
LGTM thanks @Akshatkamboj14 .

2022-02-21 16:23 UTC, rt4914 approved these changes
This is really clean code. Great work @Akshatkamboj14 and @rishidyno 

LGTM

2022-02-21 16:23 UTC, merged