Fix #377: Control submit button
oppia/oppia-android pull request #418
Opened 2019-11-19 12:47 UTC by rt4914

## Explanation

This PR controls the styling of "Submit " button.
1. If answer is not entered -> Submit button is inactive.
<img width="346" alt="Screenshot 2019-11-19 at 6 12 45 PM" src="https://user-images.githubusercontent.com/9396084/69147551-3eccd580-0af8-11ea-9106-73cac044a5fd.png">

2. If answer is entered -> Submit button is active.
<img width="342" alt="Screenshot 2019-11-19 at 6 12 59 PM" src="https://user-images.githubusercontent.com/9396084/69147557-40969900-0af8-11ea-9589-9d8f24439eeb.png">

Also, I have found one issue while working on this PR which has been mentioned in #417 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2019-11-19 16:13 UTC, nikitamarysolomanpvt reviewed
<img width="374" alt="small" src="https://user-images.githubusercontent.com/54615666/69164145-7433ec00-0b15-11ea-8323-84b161800386.png">
While the input is empty submit button should be active color?

2019-11-19 16:14 UTC, nikitamarysolomanpvt reviewed
PTAL on the comment

2019-11-19 18:05 UTC, BenHenning commented
Could we address this via data binding and the top level view model, instead? See https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/app/player/state/StateViewModel.kt#L33 

We ought to not have classes directly depend their parents. We could use listeners to indirect this, but there may be a cleaner reactive solution possible.

2019-11-22 09:30 UTC, veena14cs commented on app/src/main/java/org/oppia/app/player/state/itemviewmodel/SelectionInteractionViewModel.kt
> +  existingAnswer: InteractionObject?, val isReadOnly: Boolean, @Suppress("UNUSED_PARAMETER") stateFragmentPresenter: StateFragmentPresenter
use cmd+option+L to wrap this.

2019-11-22 09:32 UTC, veena14cs requested changes
Please update this code with latest develop as there are too many changes.

2020-01-22 05:46 UTC, rt4914 commented
Closing this PR as this will be done once `temp-integration-pt-3` code is in develop.

2020-01-22 05:46 UTC, closed without merging