Merge admin_auth_activity.xml into one file
oppia/oppia-android pull request #4180
Opened 2022-02-14 09:12 UTC by adizcode

## Explanation

Fixes #3453 by merging 4 different layout files into one

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

| Before  | After |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/42904676/152803882-45a3bb52-b65c-4168-b5b8-dddc0f7b17ee.png" >  | <img src="https://user-images.githubusercontent.com/42904676/152805391-489c812d-df7b-4b22-896c-7442b6f37fbf.png"  >  |
| <img src="https://user-images.githubusercontent.com/42904676/152803889-d106586f-0a55-47da-b4d4-a15802b4f185.png" >  | <img src="https://user-images.githubusercontent.com/42904676/152805395-2ca4e710-2604-45bf-91f6-bed304f16553.png" >   |
| <img src="https://user-images.githubusercontent.com/42904676/152803895-6fe7fa05-926c-47c9-a87d-e2a4daaeae0d.png" >  | <img src="https://user-images.githubusercontent.com/42904676/152805402-b1662830-7b4f-478c-a98f-b81978aa6b5b.png" >  |
| <img src="https://user-images.githubusercontent.com/42904676/152803899-4e206152-e5d0-47e2-ad36-7ec868e29d34.png">  | <img src="https://user-images.githubusercontent.com/42904676/152805404-a26b45b1-f948-4092-b7f9-18180e5663b8.png">  |

2022-02-14 12:26 UTC, vrajdesai78 approved these changes

2022-02-14 13:52 UTC, rt4914 commented
@adizcode I have informed @vrajdesai78 to schedule a meeting today (all three of us) so that I can explain you what changes are expected in this PR. You are on right track but still we need some changes to make it better.

2022-02-14 13:57 UTC, adizcode commented
@rt4914 Thank you. Happy to learn from you all. 

Just a tiny request, can we move the meet to tomorrow since I'm already occupied today?

2022-02-18 14:31 UTC, addy-zero commented
@rt4914 I've made the requested changes and updated the screenshots. The values were taken directly from the mockups.

The only visual difference lies in the mobile-landscape setting. The reason for that is that the **previous XML layout used a fixed margin for the TextInputLayout**, when in fact we are supposed to be using a variable margin with fixed content (if I'm not wrong).

I'm yet to pull changes from develop. Will do that if everything looks good to you.

2022-02-22 08:29 UTC, rt4914 commented
@adizcode Will review this today. If you end up reading this message before my review, please merge it with latest develop, else its fine.

2022-02-25 17:21 UTC, adizcode commented
@rt4914 I had merged the new changes, PTAL.

2022-02-25 20:14 UTC, rt4914 requested changes
@adizcode Just update the screenshots as per latest code. Otherwise everything looks great.


FYI: This will take time in merging as I will have to explain to Ben about the -1px and -2px values as a reminder and get his final approval as this is something which we will apply to all other files in time. That being said you can work on other issues in that time.

2022-02-25 20:14 UTC, rt4914 commented on app/src/main/res/values/dimens.xml
> +  <!-- Admin Auth Activity -->
Update to `<!-- AdminAuthActivity -->`

2022-02-25 20:14 UTC, rt4914 commented on app/src/main/res/values/dimens.xml
> +  <dimen name="admin_auth_layout_width">-1px</dimen>
At top of this file create a value 
`<dimen name="match_parent">-1px</dimen>`
and then use that `match_parent` here.

2022-02-25 20:14 UTC, rt4914 commented on app/src/main/res/values-land/dimens.xml
> +  <!-- Admin Auth Activity -->
Change to `<!-- AdminAuthActivity -->` here and in other files too.

2022-02-25 20:40 UTC, adizcode commented
@rt4914 Done and updated the screenshots. Please merge when you can :)

2022-03-04 05:46 UTC, rt4914 approved these changes
LGTM, thanks.

2022-03-04 05:46 UTC, rt4914 commented
@adizcode Just merge this with latest develop and its ready to merge.

2022-03-04 07:01 UTC, adizcode commented
@rt4914 One of the checks is apparently failing. However, my branch seems to work locally.

2022-03-13 04:18 UTC, bhaktideshmukh commented
@adizcode 
Your branch has conflicts , try resolving them
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github
Thanks

2022-03-13 12:51 UTC, adizcode commented
@rt4914 It seems that the layout of admin_auth_activity.xml was changed by someone else's PR. All the four files as well as their particular dimens files were modified.

However, since I had already merged all the four files into one, how can I proceed further and resolve these conflicts?

2022-03-27 13:12 UTC, closed without merging