Fix part of #3245 : Enabling AccessibilityChecks for WalkthroughActivityTest
oppia/oppia-android pull request #4214
Opened 2022-02-22 05:49 UTC by bhaktideshmukh

## Explanation

Fix part of #3245  : Enable AccessibilityChecks for WalkthroughActivityTest
Removed the @DisableAccessibilityChecks from the WalkthroughActivityTest

All the 10 tests are passing successfully.

![Screenshot from 2022-02-22 10-38-42](https://user-images.githubusercontent.com/78796264/155070948-35c491b7-0827-497a-ad18-fd0456afd2da.png)

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2022-02-22 08:11 UTC, rt4914 requested changes
@bhaktideshmukh The Accessibility Tests only work on Espresso and not on Robolectric. 

They are passing on `Robolectric` which they will always.

Please run tests on `Espresso` and you will notice that they are failing. We will need to find suitable solution for that to fix it.

<img width="1131" alt="Screenshot 2022-02-22 at 1 40 52 PM" src="https://user-images.githubusercontent.com/9396084/155089684-ab0f3031-9589-41b2-aae1-e855ce6a82af.png">

2022-02-26 05:38 UTC, vrajdesai78 approved these changes

2022-02-26 05:40 UTC, vrajdesai78 commented
I have applied changes from my side and all tests are passing on Espresso. 
![Screenshot from 2022-02-26 11-09-40](https://user-images.githubusercontent.com/43074241/155830845-c71772dd-a4c9-4134-8998-46a64fe20640.png)

2022-02-26 14:52 UTC, Rohit1173 commented
@bhaktideshmukh try removing `@DisableAccessibilityChecks` annotation in `WalkthroughFinalFragmentTest.kt` and `WalkthroughTopicListFragmentTest.kt` this PR is actually solving the issue in those files too

2022-02-26 16:21 UTC, bhaktideshmukh commented
> @bhaktideshmukh try removing `@DisableAccessibilityChecks` annotation in `WalkthroughFinalFragmentTest.kt` and `WalkthroughTopicListFragmentTest.kt` this PR is actually solving the issue in those files too

Yup! you're right. All the 5 tests from WalkthroughFinalFragmentTest and all the tests from WalkthroughTopicListFragmentTest are passing successfully.
So shall I push the changes from these 2 files in this PR?

2022-02-26 16:58 UTC, Rohit1173 commented
> Yup! you're right. All the 5 tests from WalkthroughFinalFragmentTest and all the tests from WalkthroughTopicListFragmentTest are passing successfully. So shall I push the changes from these 2 files in this PR?

Yes

2022-02-26 17:32 UTC, bhaktideshmukh commented
> > Yup! you're right. All the 5 tests from WalkthroughFinalFragmentTest and all the tests from WalkthroughTopicListFragmentTest are passing successfully. So shall I push the changes from these 2 files in this PR?
> 
> Yes

Done

2022-03-01 16:11 UTC, rt4914 requested changes
@bhaktideshmukh Suggested nit change.

Thanks.

2022-03-01 16:11 UTC, rt4914 commented on app/src/main/res/layout/walkthrough_activity.xml
>        android:layout_margin="16dp"
Convert this margin to padding.

2022-03-01 19:08 UTC, rt4914 approved these changes
LGTM, thanks.

2022-03-01 19:08 UTC, merged