fix of CheckBox to unselect CheckBox #4186
oppia/oppia-android pull request #4244
Opened 2022-03-12 16:56 UTC by visheshkadian

## Explanation
this pull request fixes the "Unselect All option in Developer Options not working" [#4186](https://github.com/oppia/oppia-android/issues/4186)

## Essential Checklist

- [x] fix of CheckBox to unselect all the CheckBoxes of topics [#4186](https://github.com/oppia/oppia-android/issues/4186) which fixes the issue unselecting and selecting all the topics given
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".

2022-03-14 02:28 UTC, anandwana001 commented
Hi @visheshkadian Thank you for your first PR. Please check the comment above.

2022-03-14 14:26 UTC, visheshkadian commented
hey! @anandwana001 I have signed/filled the CLA Sheet now can anyone review my PR

2022-03-15 01:56 UTC, anandwana001 commented
@visheshkadian Please keep the PR description unchanged and only mark the point which is followed in PR.
Example - https://github.com/oppia/oppia-android/pull/4230 Check the PR description.

2022-03-16 17:51 UTC, visheshkadian commented
@anandwana001 sir, as you said I have changed the PR description
but, I have no idea how to fix Kotlin lint error as I have already followed all the steps given in the document in my android studio before making any contribution.
should I uninstall and install the software again following all the steps again??

2022-03-17 00:50 UTC, anandwana001 commented
1. Keep the checklist intact (no changes to it other mark/unmark)
```
[ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
[ ]  Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
[ ]  The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
[ ]  The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
[ ]  The PR is made from a branch that's not called "develop" and is up-to-date with "develop".
[ ]  The PR is assigned to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).
```
2. Follow the checklist and make changes to your PR accordingly. 
`The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)`
3. You will get the kotlin lint error while you were pushing the code. The git will not push the code to the PR unless you fix the error. As wiki says, we suggest using the terminal to perform all the git operations like pull/push, etc.
4. For ktlint, follow this - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide. Skip the installation part.

2022-03-18 18:43 UTC, visheshkadian commented
@anandwana001 after fixing the Ktlint error should I make a new PR, right? 
And close this PR

2022-03-19 02:18 UTC, anandwana001 commented
No, you xan commit in this PR only.

2022-03-19 14:14 UTC, visheshkadian commented
@anandwana001 @rt4914 sir, I have uploaded all the necessary details and all the test cases passed now can you review my PR

2022-03-23 16:30 UTC, visheshkadian commented
@anandwana001 sir, I wanted to ask that Mark Chapter Completed and Mark Stories Completed are getting the same issue as [#4186](https://github.com/oppia/oppia-android/issues/4186), should I make a new PR for that?

2022-03-24 14:00 UTC, rt4914 commented
@visheshkadian 
You have not yet filled the survey form. Please, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you `sign the CLA` and `fill the survey form`.

Once you have done that a mentor will get assigned to you who will help in contributions.

2022-03-24 14:13 UTC, visheshkadian commented
@rt4914 sir, I have already filled both the CLA form as well as survey form

2022-03-24 14:17 UTC, rt4914 commented
@visheshkadian Can you please try that once again as I am unable to see your name in our list. Once you fill the survey form we will receive your details for contributions.

2022-03-24 16:57 UTC, visheshkadian commented
@rt4914 I have filled both the form can you check now

2022-03-29 18:42 UTC, yash10019coder approved these changes
Thanks @visheshkadian for the work your pull request LGTM 
just update the description to `Fixes #4186` so that pull requests and issues gets linked together as we merge the pull request then issue automatically gets closed
thanks @anandwana001 @rt4914 for helping @visheshkadian.

2022-03-29 18:54 UTC, visheshkadian commented
@yash10019coder I have updated `Fixes #4186` in my explanation part, is it ok?

2022-03-31 21:27 UTC, visheshkadian commented
@yash10019coder you have reviewed my PR but still, I can't merge my PR 
It is still showing code owner review required 
I guess @rt4914 review is required

2022-04-12 16:26 UTC, rt4914 requested changes
Please add a test case for this bug fix in correct test file. Considering that you are fixing a bug there should always be a test case.

2022-04-12 16:26 UTC, rt4914 commented on app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt
> +                //viewModel.chapterSummary.explorationId
Remove this comment.

2022-04-12 17:12 UTC, visheshkadian commented on app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt
> +                //viewModel.chapterSummary.explorationId
I have removed the comment but I don't know how to add a test case can you help me with that, like what kind of tool I have to use?

2022-04-26 18:00 UTC, closed without merging