Merge profile edit fragment.xml
oppia/oppia-android pull request #4280
Opened 2022-03-31 20:21 UTC by ShivamMadlani

## Explanation

  Fix part of issue #3559 by merging 2 layout files into a single file.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing
- 
Before           |  After
:-------------------------:|:-------------------------:
![Screenshot_20220331_163917](https://user-images.githubusercontent.com/94903454/161139980-399c7bac-b957-4820-9f42-5dec3855f4df.png)  |  ![Screenshot_20220331_163008](https://user-images.githubusercontent.com/94903454/161140260-f8d2be53-e467-47d3-8cec-c940acb552be.png)
https://user-images.githubusercontent.com/94903454/161140043-d8bebb5f-e80a-4436-ba6b-a92bffea15a5.mp4 | https://user-images.githubusercontent.com/94903454/161140271-a2aee99c-3168-49eb-8c26-9a6a0f022c0d.mp4
![Screenshot_20220401_014630](https://user-images.githubusercontent.com/94903454/161142106-f5ed5f60-c8fb-4b57-adb8-242e92f3398c.png) | ![Screenshot_20220401_014401](https://user-images.githubusercontent.com/94903454/161142154-5b773c36-2c2a-4272-addd-b2245a9f012a.png)
![Screenshot_20220401_014642](https://user-images.githubusercontent.com/94903454/161142121-25fdc115-9eb5-4228-ae0f-42aefa44554f.png) | ![Screenshot_20220401_014417](https://user-images.githubusercontent.com/94903454/161142166-9ab6e811-c670-4210-adb4-66ef98338365.png)

2022-04-12 16:31 UTC, rt4914 commented
Closing this PR. Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

2022-04-13 16:36 UTC, MaskedCarrot commented
Reopening these PRs as Shivam has signed the CLA earlier with an incorrect GitHub handle. Sean corrected his handle.

2022-04-15 04:48 UTC, rishidyno requested changes

2022-04-15 04:48 UTC, rishidyno commented on app/src/main/res/layout/profile_edit_fragment.xml
> +        android:layout_marginStart="@dimen/profile_edit_image_marginStart"
Should be `profile_edit_image_margin_start` instead. Ditto for others.

2022-04-15 04:48 UTC, rishidyno commented on app/src/main/res/values/dimens.xml
> -
Please remove these spaces everywhere.

2022-04-15 04:48 UTC, rishidyno commented on app/src/main/res/layout/profile_edit_fragment.xml
> +        android:layout_marginTop="@dimen/view2_marginTop"
same goes here

2022-04-15 06:32 UTC, ShivamMadlani commented
@rishidyno I made changes as per your comments. PTAL at them and let me know if further changes are required.

2022-04-20 04:52 UTC, BenHenning commented
Apologies. I will need to look at this tomorrow.

2022-05-03 20:52 UTC, BenHenning commented
Not stale--I need to follow up on this.

2022-05-06 18:26 UTC, BenHenning commented
Hi. Since I was requested as a reviewer on this PR: Please note that I will be away & unavailable for reviews starting today until 23 May 2022. Please try to make any progress that you can which doesn't require me, and I'll catch up on my reviews when I return. Thanks for your flexibility--I really appreciate it.

2022-05-06 18:43 UTC, BenHenning commented
Deferring to @rt4914 here since he's the codeowner.

2022-05-17 08:26 UTC, rt4914 requested changes
The changes in this PR are incorrect.

1. If there is a dimens defined in any xml file like `values-land/dimens.xml` then it must be defined it global dimens file too which is `values/dimens.xml` otherwise it can lead to crashes  in app.
2. We define a `dimens` only for those values which are different and if the value is same like the margins to profile-edit-image then we keep it as it is in layout file and do not define it in dimens.xml file
3. This particular file is already optimised a lot as there are only two xml files. And in both of these xml files the way the layout has been created is a bit different and therefore merging them is not a correct option.

Closing this PR for two reasons:
1. The PR itself is incorrect and also over-optimised of code here can make it less readable
2. The issue can be closed because of above reason.

2022-05-17 08:26 UTC, rt4914 commented on app/src/main/res/layout/profile_edit_fragment.xml
> +        android:layout_marginTop="@dimen/profile_edit_image_margin_top"
Because these values are are same for landscape as well as portrait please remove it and instead directly write `28dp`

2022-05-17 08:28 UTC, closed without merging