Merge profile list fragment
oppia/oppia-android pull request #4283
Opened 2022-04-02 08:45 UTC by ShivamMadlani

## Explanation
  Fixes #3560 by merging files

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing
- 
Before           |  After
:-------------------------:|:-------------------------:
![port](https://user-images.githubusercontent.com/94903454/161374997-002f0d8d-9755-4be5-8bd4-a2d35d823fc3.png) |  ![port1](https://user-images.githubusercontent.com/94903454/161375019-8f105086-a775-48db-adc8-f8981375ae57.png)
Before | After
![land](https://user-images.githubusercontent.com/94903454/161375038-d76ca39a-b23f-48b8-9337-ed2b128c9464.png) |  ![land1](https://user-images.githubusercontent.com/94903454/161375055-63072482-fb9f-45a3-a353-7bf6e6b1eabd.png)

2022-04-12 16:31 UTC, rt4914 commented
Closing this PR. Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

2022-04-13 16:37 UTC, MaskedCarrot commented
Reopening these PRs as Shivam has signed the CLA earlier with an incorrect GitHub handle. Sean corrected his handle.

2022-04-15 06:32 UTC, rishidyno requested changes
Rest of the pr LGTM. Just address the suggested changes.

2022-04-15 06:32 UTC, rishidyno commented on app/src/main/res/layout/profile_list_fragment.xml
> +        android:paddingBottom="@dimen/profile_list_recycler_view_paddingBottom"
Should be `profile_list_recycler_view_padding_bottom` instead.

2022-04-15 06:38 UTC, rishidyno requested changes
Rest of the pr LGTM. Just address the suggested changes.

2022-04-15 06:38 UTC, rishidyno commented on app/src/main/res/values-land/dimens.xml
> +  <!--  Profile list fragment-->
Make it Pascal case. Ditto for others. Ex- `Profile List Fragment`.

2022-04-15 06:44 UTC, ShivamMadlani commented
@rishidyno Made changes as per your comments. PTAL at them. Thanks!

2022-04-15 06:49 UTC, rishidyno commented
@ShivamMadlani please add tablet Screenshots.

2022-04-15 07:09 UTC, ShivamMadlani commented
@rishidyno I have added the screenshots of tablet view. PTAL.

2022-04-20 02:05 UTC, BenHenning requested changes, later dismissed
Thanks @ShivamMadlani. Two things:
1. The PR title should include the issue that's being fixed (see the PR description 'explanation' section).
2. It seems that per #3560 it's expected that all three ``profile_list_fragment.xml`` files be merged into one (the portrait, landscape, and tablet versions), but it seems only the landscape one is being merged into portrait here. Shouldn't the PR also be removing the tablet version & making sure only one layout file is needed?

2022-04-20 05:21 UTC, ShivamMadlani commented
@BenHenning The tablet and the smartphone versions have many other changes other than just dimensions. Both the versions are using different layouts. Also the constraints of both the files vary and I don't think these can be merged. If they can then please let me know how.

2022-05-03 20:51 UTC, BenHenning commented
Not stale--I need to follow up on this.

2022-05-06 18:42 UTC, BenHenning commented
> @BenHenning The tablet and the smartphone versions have many other changes other than just dimensions. Both the versions are using different layouts. Also the constraints of both the files vary and I don't think these can be merged. If they can then please let me know how.

@ShivamMadlani apologies for the super late delay in my follow-up--I've been really slammed with various time-sensitive obligations lately.

The only differences I see between the handset & tablet versions of the layout is one difference in constraints and the addition of a toolbar & shadow for the handset version. @rt4914 is it not possible to move the toolbar bits to a common shared layout that we can just replace with a simple ``FrameLayout`` in tablet mode? That might also unlock merging other layouts that have the same constraint.

Furthermore, note that I dismissed my review since I'll be unavailable to follow-up, and @rt4914 has codeowners again for these files (so my review shouldn't be needed, anyway).

2022-05-17 08:32 UTC, rt4914 requested changes
@ShivamMadlani Thanks. Just suggested minor changes

2022-05-17 08:32 UTC, rt4914 commented on app/src/main/res/values-land/dimens.xml
> +  <!--  Profile List Fragment-->
Correct spacing at start and end of text

`<!-- Profile List Fragment -->`

2022-05-17 08:32 UTC, rt4914 commented on app/src/main/res/values/dimens.xml
> +  <!--  Profile List Fragment-->
Correct spacing at start and end of text

`<!-- Profile List Fragment -->`

2022-05-17 08:32 UTC, rt4914 commented on app/src/main/res/values/dimens.xml
> +  <dimen name="profile_list_recycler_view_padding_bottom">40dp</dimen>
Rename to `profile_list_fragment_recycler_view_padding_bottom `

2022-05-17 08:32 UTC, rt4914 commented on app/src/main/res/values-land/dimens.xml
> +  <dimen name="profile_list_recycler_view_padding_bottom">108dp</dimen>
Rename to `profile_list_fragment_recycler_view_padding_bottom `

2022-05-17 08:32 UTC, rt4914 commented on app/src/main/res/values-land/dimens.xml
> +  <dimen name="profile_list_recycler_view_padding_bottom">108dp</dimen>
Rename to `profile_list_fragment_recycler_view_padding_bottom `

2022-05-17 10:51 UTC, rt4914 commented
Closing this as it got solved in #4354

2022-05-17 10:51 UTC, closed without merging