Fixes #4182: Added dark mode support to OptionActivity and OptionWithoutDrawerActivity
oppia/oppia-android pull request #4284
Opened 2022-04-02 23:15 UTC by Akshatkamboj14

**Fixes #4182 
Added dark mode support to OptionActivity and OptionWithoutDrawerActivity**

| **Default Mode** | **After Dark Mode** |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/92685493/161404363-3ab3f25e-9a10-4b14-9ff1-312b364d65c4.png)  | ![image](https://user-images.githubusercontent.com/92685493/161404377-cc30297e-5e1c-4c42-bc6a-9270934d0624.png)  |

## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2022-04-02 23:17 UTC, Akshatkamboj14 commented
@rt4914 @ayush0402 PTAL, thanks.

2022-04-12 16:25 UTC, rt4914 requested changes
@Akshatkamboj14 Suggested changes

2022-04-12 16:25 UTC, rt4914 commented on app/src/main/res/layout-sw600dp/option_story_text_size.xml
> -    android:background="@{commonViewModel.selectedFragmentIndex == viewModel.itemIndex ? @drawable/general_item_background_border_cyan : @drawable/general_item_background_border}"
I think this condition is important so as it show the divider which is not visible in your screenshots now.

2022-04-12 16:25 UTC, rt4914 commented on app/src/main/res/layout/option_audio_language.xml
> +    android:background="@color/component_color_option_activity_options_background_color"
Ditto

2022-04-27 13:21 UTC, Akshatkamboj14 commented
@rt4914 @ayush0402 @BenHenning **PTAL.**

2022-05-03 21:45 UTC, BenHenning commented
@ayush0402 can you please take a first pass? I'm otherwise assuming @rt4914 will follow up as the code owner, but please let me know if I need to review anything here.

2022-05-05 16:00 UTC, rt4914 approved these changes
LGTM, just one change in PR description is required.

2022-05-05 16:00 UTC, rt4914 commented on app/src/main/res/drawable/general_item_border.xml
> +</shape>
Please mention the in the PR description why this and the other file has been introduced.

2022-05-05 16:57 UTC, Akshatkamboj14 commented on app/src/main/res/drawable/general_item_border.xml
> +</shape>
Okay @rt4914

2022-05-06 18:26 UTC, BenHenning commented
Hi. Since I was requested as a reviewer on this PR: Please note that I will be away & unavailable for reviews starting today until 23 May 2022. Please try to make any progress that you can which doesn't require me, and I'll catch up on my reviews when I return. Thanks for your flexibility--I really appreciate it.

2022-05-14 11:20 UTC, merged