Fixes #1383: Audio content highlighting
oppia/oppia-android pull request #4342
Opened 2022-05-05 11:13 UTC by bhaktideshmukh

## Explanation
Fixes issue #1383 

This PR covers following cases:

- Corresponding content card is highlighted, while playing audio
- Whenever audio is paused, stops highlighting
- Feedback card gets highlighted while playing audio
- Feedback card stops highlighting whenever paused
- Correct feedback starts highlighting while playing audio and stops accordingly when audio is paused
- Automatically highlight feedback item on answer selection if the audio was already playing earlier
- For multiple feedbacks only last feedback gets highlighted

**Screenshots**

|<img src="https://user-images.githubusercontent.com/78796264/166911786-d9c33cfa-dc49-41fb-8a36-f38e21595b3d.jpeg" width="250" />|
|<img src="https://user-images.githubusercontent.com/78796264/166911795-d7ae4e2e-e1f2-40d6-8a53-d5eafe47f9ed.jpeg" width="250" />|
|<img src="https://user-images.githubusercontent.com/78796264/166911804-cadcf32a-0d16-4fe1-a2ea-5df2c6df4f3e.jpeg" width="250" />|
|<img src="https://user-images.githubusercontent.com/78796264/166911824-e927aa17-a447-433e-bb9b-30cad3e9d6da.jpeg" width="250" />|
|<img src="https://user-images.githubusercontent.com/78796264/166911814-41c47672-5736-4a65-ac83-664b78179a5d.jpeg" width="250" />|

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2022-05-05 16:11 UTC, rt4914 requested changes
@bhaktideshmukh I will review it tomorrow but I suggest adding a video link in description displaying all the edge cases in a single video.

2022-05-06 06:12 UTC, rt4914 commented
Pending Items / Bugs found in implementation:

1. As soon as I open the app, mainly "What is a Fraction" exploration, the content-item is highlighted by default.
2. Play the audio on state-2, now go back and notice the audio stops playing but the card is still selected.
3. When audio finishes playing and stops, the card is still highlighted.

2022-05-06 06:17 UTC, rt4914 commented on app/src/main/res/layout/feedback_item.xml
> +    android:background="@{viewModel.isAudioPlaying ? @drawable/content_yellow_background : @drawable/content_blue_background}"
Changes in xml files does affect the question player too. It does mess up the entire question player/ practice mode.

2022-05-06 06:17 UTC, rt4914 requested changes
PTAL

2022-05-06 18:24 UTC, BenHenning commented
Deferring to @rt4914 to approve before I take a look (since I suspect I won't have much to add after that).

2022-05-06 18:26 UTC, BenHenning commented
Hi. Since I was requested as a reviewer on this PR: Please note that I will be away & unavailable for reviews starting today until 23 May 2022. Please try to make any progress that you can which doesn't require me, and I'll catch up on my reviews when I return. Thanks for your flexibility--I really appreciate it.

2022-06-01 06:00 UTC, closed without merging