Fixes part of #4178: Added dark mode support to PinPasswordActivity
oppia/oppia-android pull request #4380
Opened 2022-06-01 19:32 UTC by bhaktideshmukh

## Explanation
Fixes part of #4178 : Added dark mode support to PinPasswordActivity.

**Mock link** : https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/81c45a9d-5c70-46f0-8b02-b57a3df3ff50/specs/

**Screenshots**

| Default  | Dark mode |
|-------|---|
|<img src="https://user-images.githubusercontent.com/78796264/171486711-5433d3b4-cad6-48c0-9269-52c9073dcaa6.jpg" width="280" />|<img src="https://user-images.githubusercontent.com/78796264/171986374-aa7e3189-a5b6-495b-8816-c45a06bb8191.jpg" width="280" />|

| Default  | Dark mode |
|-------|---|
|<img src="https://user-images.githubusercontent.com/78796264/171550270-f825b552-9ac9-41d0-9652-20a422a94ef6.jpg" width="280" />|<img src="https://user-images.githubusercontent.com/78796264/171986376-ed49f141-df76-46c8-8dab-2424ddb3f635.jpg" width="280" />|

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2022-06-01 19:42 UTC, rt4914 requested changes
@bhaktideshmukh Please do following things:

1. Check the checklist correctly in the PR description.
2. Add the link of dark-mode mock in PR description.
3. Also add screenshot showing error color too which gets displayed when you enter incorrect pin.

2022-06-01 19:42 UTC, rt4914 commented on app/src/main/res/layout/pin_password_activity.xml
> +                android:textColor="@color/component_color_pin_password_activity_show_color"
`component_color_pin_password_activity_show_hide_text_color `

2022-06-02 04:01 UTC, bhaktideshmukh commented on app/src/main/res/layout/pin_password_activity.xml
> +                android:textColor="@color/component_color_pin_password_activity_show_color"
Done

2022-06-02 04:02 UTC, bhaktideshmukh commented
> @bhaktideshmukh Please do following things:
> 
>     1. Check the checklist correctly in the PR description.
> 
>     2. Add the link of dark-mode mock in PR description.
> 
>     3. Also add screenshot showing error color too which gets displayed when you enter incorrect pin.

Done all the three things

2022-06-03 17:39 UTC, rt4914 requested changes
@bhaktideshmukh Please update the error color as mentioned here: https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/9f441ec1-76e4-43e3-badf-42e70d584ab6/specs/

2022-06-04 04:30 UTC, bhaktideshmukh commented
@rt4914 
Color for ic_show_eye_icon.xml in dark mode should be #035D63 as per mocks and same goes with ic_hide_eye_icon.xml but adding this color in component_colors.xml is giving error --

![Screenshot from 2022-06-04 09-44-14](https://user-images.githubusercontent.com/78796264/171982737-e22fb97e-2cd4-49a5-b0c3-720c050b6116.png)

2022-06-04 04:30 UTC, bhaktideshmukh commented
> @bhaktideshmukh Please update the error color as mentioned here: https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/9f441ec1-76e4-43e3-badf-42e70d584ab6/specs/

Done

2022-06-06 20:23 UTC, rt4914 approved these changes
LGTM, thanks.

2022-06-06 20:23 UTC, merged