Fix #3537: merge hints summary xml files into one file, aided by use…
oppia/oppia-android pull request #4422
Opened 2022-07-04 20:09 UTC by ma-za-kpe

… of the dimens folder for different device settings

## Explanation
This pr merges all four hint_summary.xml files into on existing default XML file. It uses dimen files to set different dimensions for individual device configuations. 

## Essential Checklist

- [x ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

## BEFORE SCREENSHOTS
![hint_land](https://user-images.githubusercontent.com/28810111/177211739-40ac70a1-0d81-4dc0-8132-09ea04438866.PNG)
![hint_port](https://user-images.githubusercontent.com/28810111/177211744-88b34933-3da5-4825-b5eb-88dd9aa3306f.PNG)
![hint_tab_land](https://user-images.githubusercontent.com/28810111/177211747-9053b807-6de6-47a0-993a-d812be733989.PNG)
![hint_tab_port](https://user-images.githubusercontent.com/28810111/177211750-1555ce45-dca7-41ac-b029-7cf7903f32ec.PNG)
 
##AFTER SCREENSHOTS
![phone_land](https://user-images.githubusercontent.com/28810111/177212021-907649d0-b8b9-40e2-94e4-79c3a12f7d7c.PNG)
![phone_port](https://user-images.githubusercontent.com/28810111/177212026-e1be436e-fc46-4c5f-a35c-5a8e45d50cd9.PNG)
![tablet_land](https://user-images.githubusercontent.com/28810111/177212028-1c4a0945-70f8-4d04-a701-19043a96ced8.PNG)
![tablet_port](https://user-images.githubusercontent.com/28810111/177212029-e452ae38-2a31-4467-8e2d-190897fa7a42.PNG)

2022-07-08 06:47 UTC, vrajdesai78 requested changes

2022-07-08 06:47 UTC, vrajdesai78 commented on app/src/main/res/layout/hints_summary.xml
> +        android:layout_marginBottom="@dimen/hint_title_margin_bottom"
Also add android:paddingBottom and assign its dimensions in dimens.xml files

2022-07-08 06:47 UTC, vrajdesai78 commented on app/src/main/res/values-land/dimens.xml
> +
remove this extra space

2022-07-08 06:47 UTC, vrajdesai78 commented on app/src/main/res/values-land/dimens.xml
> +
remove this extra space

2022-07-08 06:47 UTC, vrajdesai78 commented on app/src/main/res/values-land/dimens.xml
> +
remove this extra space

2022-07-08 06:47 UTC, vrajdesai78 commented on app/src/main/res/values-land/dimens.xml
> +
remove this extra space

2022-07-08 06:47 UTC, vrajdesai78 commented on app/src/main/res/values-sw600dp-land/dimens.xml
> +
Here and everywhere else where you have given extra space in dimens.xml remove it as mentioned above

2022-07-08 06:47 UTC, vrajdesai78 commented on app/src/main/res/values-land/dimens.xml
> +  <!-- Hints summary  -->
change 'summary' to 'Summary' here and in other dimens.xml also

2022-07-08 06:47 UTC, vrajdesai78 commented on app/src/main/res/values-sw600dp-port/dimens.xml
> +  <dimen name="hint_list_container_layout_margin_start">128dp</dimen>
Name for every dimension should start from name of activity/fragment. So, here and everywhere else start the name of dimension with hints_summary as you have done for previous dimensions. Here, change the current name `hint_list_container_layout_margin_start` to `hints_summary_hint_list_container_layout_margin_start`

2022-07-08 06:47 UTC, vrajdesai78 commented on app/src/main/res/values-sw600dp-port/dimens.xml
> +  <dimen name="reveal_hint_btn_margin_bottom">28dp</dimen>
Don't use abbreviations like btn, use full name button

2022-07-08 06:47 UTC, vrajdesai78 commented on app/src/main/res/values-sw600dp-port/dimens.xml
> +  <dimen name="expand_list_icon_margin_top">32dp</dimen>
To maintain consistency, make sure that all dimensions are present in all four dimens.xml files. For example, here you mentioned just two dimensions for `expand_list_icon*`. So, add another two dimensions i.e. `hints_summary_expand_list_icon_margin_end` and `hints_summary_expand_list_icon_margin_start` and assign 0 dp. Do these for other dimensions also

2022-07-11 17:03 UTC, ma-za-kpe commented
Hello @vrajdesai78 , i have made the requested changes, please have a look.

2022-07-13 16:52 UTC, vrajdesai78 requested changes
After doing changes, run your app again and update the screenshots.

2022-07-13 16:52 UTC, vrajdesai78 commented on app/src/main/res/layout/hints_summary.xml
> +        android:paddingBottom="@dimen/hint_title_padding_bottom"
Here, and in other places also you have to change the dimen name exactly same as you mentioned in dimens.xml. Here, you have written `@dimen/hint_title_padding_bottom` which should be `@dimen/hints_summary_hint_title_padding_bottom`

2022-07-13 16:52 UTC, vrajdesai78 commented on app/src/main/res/layout/hints_summary.xml
> +        android:layout_marginTop="@dimen/reveal_hint_btn_margin_top"
change dimen name

2022-07-13 16:52 UTC, vrajdesai78 commented on app/src/main/res/layout/hints_summary.xml
> +        android:layout_marginBottom="@dimen/reveal_hint_btn_margin_bottom"
change dimen name

2022-07-13 16:52 UTC, vrajdesai78 commented on app/src/main/res/layout/hints_summary.xml
> +        android:layout_marginStart="@dimen/expand_list_icon_margin_start"
change dimen name

2022-07-13 16:52 UTC, vrajdesai78 commented on app/src/main/res/layout/hints_summary.xml
> +      android:layout_marginStart="@dimen/hint_list_container_layout_margin_start"
change dimen name

2022-07-13 18:16 UTC, ma-za-kpe commented
Okay, let me upload new screenshots...


On Wed, Jul 13, 2022 at 7:55 PM oppiabot[bot] ***@***.***>
wrote:

> Unassigning @vrajdesai78 <https://github.com/vrajdesai78> since the
> review is done.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/oppia/oppia-android/pull/4422#issuecomment-1183462241>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG3ZW76ZXMGCBW3T6LCG3ATVT3YHLANCNFSM52UDJA6Q>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-07-13 21:18 UTC, ma-za-kpe commented
Hello @vrajdesai78, I have made the requested changes, with new screenshots

2022-07-14 05:12 UTC, vrajdesai78 approved these changes

2022-07-16 20:39 UTC, rt4914 commented
@vrajdesai78 @ma-za-kpe  In the PR description the screenshots are not correct.

Those screenshots have been taken from android studio where they show the previews which might be incorrect. Instead you should create screenshot in devices mainly mobile-portrait, mobile-landscape, tablet-portrait, tablet-landscape.

Also each screenshot should show atleast 2 hints where one is open and another is closed.

@vrajdesai78 Can you help @ma-za-kpe in creating such screenshots.

2022-07-21 05:45 UTC, ma-za-kpe commented
Hello, I have updated the screenshots as required.

2022-07-21 12:35 UTC, ma-za-kpe commented
Hello, i have added theother variation of screenshots.

2022-08-06 13:58 UTC, closed without merging