Partially Fixes #4194: Added dark mode support to DrawerFragment, ConceptCardFragment and AudioFragment.
oppia/oppia-android pull request #4545
Opened 2022-08-30 20:57 UTC by Akshatkamboj14

## Explanation

Partially Fixes #4194 

**Drawer Fragment:** https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/eb119ee3-033f-4757-8aee-7ea234d6f126/specs/

**Concept Card Fragment:** https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/2ee531cf-c358-4a7d-b9dd-b772b51c3d3c/specs/

**Audio Fragment:** https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/d67b268b-f6d9-434f-8897-24a2b13ccd84/specs/

**-> This PR is Broken into two pieces, First-one is to Add dark mode support to DrawerFragment, ConceptCardFragment, and AudioFragment. _The second is to Add dark mode support to HomeActivity and RevisionCardActivity (this is to be done by @bhaktideshmukh)_**

| **Default** | **Dark Mode** |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/92685493/187538945-bb6adbce-1eda-433b-bf12-de95a37e9f89.png)  | ![image](https://user-images.githubusercontent.com/92685493/187539510-9b4621fa-b7a3-4b5f-8bb2-29b6384179d8.png)  |
| ![image](https://user-images.githubusercontent.com/92685493/187539083-8c7c6ebe-e934-4464-92e8-7d05db865bc8.png)  | ![image](https://user-images.githubusercontent.com/92685493/187539391-231cd97d-8875-4506-9e77-d81dffef330e.png)  |
| ![image](https://user-images.githubusercontent.com/92685493/187539152-c406513c-1e55-4aab-b563-76e45afcdb39.png)  | ![image](https://user-images.githubusercontent.com/92685493/187539286-049bf53b-bb4d-4ec7-bcc2-867e468aded9.png))  |
| ![image](https://user-images.githubusercontent.com/92685493/187539820-e3f447f9-63c7-4108-aacb-1456c0ba14aa.png) | ![image](https://user-images.githubusercontent.com/92685493/187539726-ceb1b3e3-9ad8-4666-ac96-dc12f8f33bc5.png)  |
| ![image](https://user-images.githubusercontent.com/92685493/187539979-6b6ff6be-a4b3-4100-8fff-c6353c57cd59.png)  | ![image](https://user-images.githubusercontent.com/92685493/187540047-7f940c60-b98a-47b0-bee3-44b3d3e24ab4.png)  |

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2022-08-30 21:16 UTC, Akshatkamboj14 commented
I have a doubt in the   `audio_fragment.xml` as there is textView that recently got added and the mocks are not up to date with the new text view, Please tell me if I have to add dark mode to that as well?

![image](https://user-images.githubusercontent.com/92685493/187544700-6052c00c-b455-4cba-b11a-888e8509bfff.png)

2022-08-31 10:58 UTC, rt4914 commented
@Akshatkamboj14 File a separate issue for the view/UI which does not have dark-mode implemented. That way it will be helpful in following cases:
1. We can ask designers to create mock and solve in separate PR
2. If we decide to solve this without mock than also its nice to track separately which issue got solved without mock and if needed to revert in future, it will be easy.

2022-09-06 15:54 UTC, Akshatkamboj14 commented
Okay sure @rt4914

2022-09-06 16:02 UTC, Akshatkamboj14 commented
Done @rt4914 
[https://github.com/oppia/oppia-android/issues/4561](url)

2022-09-10 19:35 UTC, Akshatkamboj14 commented
Hey @rt4914 PTAL, Thanks.

2022-09-12 19:05 UTC, rt4914 requested changes
@Akshatkamboj14 Nice work. One minor change

2022-09-12 19:05 UTC, rt4914 commented on app/src/main/res/values/color_palette.xml
> +
Remove this blank line

2022-09-13 14:34 UTC, Akshatkamboj14 commented on app/src/main/res/values/color_palette.xml
> +
Done @rt4914

2022-09-14 19:43 UTC, rt4914 requested changes
@Akshatkamboj14 Merge with latest develop.

FYI you might need to remerge as a lot of conflicting PRs are getting merged daily.

2022-09-19 21:01 UTC, rt4914 approved these changes
LGTM, Thanks.

2022-09-19 21:01 UTC, merged