Fix #4086: Changed the revision tab icon.
oppia/oppia-android pull request #4635
Opened 2022-10-01 10:59 UTC by pratyaksh1610

## Explanation

Fix #4086
Changed the revision tab icon.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## Before

![WhatsApp Image 2022-10-01 at 2 32 15 PM](https://user-images.githubusercontent.com/76740999/193406326-80c413d4-9849-40b4-9b04-1aa55f3e8db5.jpeg)

![WhatsApp Image 2022-10-01 at 2 32 14 PM (1)](https://user-images.githubusercontent.com/76740999/193406328-8b659d5b-be1b-4c68-8c99-e6f85ec9c0fe.jpeg)

## After

![WhatsApp Image 2022-10-01 at 2 32 13 PM](https://user-images.githubusercontent.com/76740999/193406332-52424416-ebb7-4964-ab3c-f3f91800ffc8.jpeg)

![WhatsApp Image 2022-10-01 at 2 32 14 PM](https://user-images.githubusercontent.com/76740999/193406335-bd3952b9-fc58-4d3b-ae60-a6f8f4122821.jpeg)

2022-10-01 10:59 UTC, pratyaksh1610 commented
PTAL @BenHenning

2022-10-04 07:55 UTC, BenHenning commented
Sorry, will need to look at this tomorrow.

2022-10-05 02:43 UTC, BenHenning requested changes
Thanks @pratyaksh1610. I've left some follow-up comments--PTAL.

2022-10-05 02:43 UTC, BenHenning commented on app/src/main/res/drawable/_revision.xml
> +</vector>
Please add EOF newline.

2022-10-05 02:43 UTC, BenHenning commented on app/src/main/res/drawable/_revision.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Please reformat this in Android Studio using it's Reformat Code option.

2022-10-05 02:43 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/topic/TopicTab.kt
> -    tabIconResId = R.drawable.ic_revision_icon_24dp
Do we use ic_revision_icon_24dp elsewhere? We should be replacing the existing drawable itself rather than introducing a new one.

2022-10-05 08:36 UTC, pratyaksh1610 commented
I have made the change

2022-10-05 08:36 UTC, pratyaksh1610 commented
PTAL @BenHenning

2022-10-06 03:43 UTC, BenHenning commented on app/src/main/res/drawable/_revision.xml
> +</vector>
Resolved in the latest changes.

2022-10-06 03:43 UTC, BenHenning commented on app/src/main/res/drawable/_revision.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Resolved in the latest changes.

2022-10-06 03:43 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/topic/TopicTab.kt
> -    tabIconResId = R.drawable.ic_revision_icon_24dp
Resolved in the latest changes.

2022-10-06 03:46 UTC, BenHenning approved these changes
Thanks @pratyaksh1610. This looks good to me.

However, please make sure to reply to all comments when you've addressed them, otherwise it's difficult for your reviewers to know what to check.

2022-10-06 03:46 UTC, merged