Improve flow in onboarding screen #4655
oppia/oppia-android pull request #4768
Opened 2022-11-26 18:09 UTC by iampradeep-hr

## Explanation
  - Improve flow in onboarding screen #4655
  - "Fixes #4655:" improved the talkback flow in onborading
  

## For UI-specific PRs only

https://user-images.githubusercontent.com/81664507/204102872-a30b751f-e92f-4a6c-8c84-f357e9a00b1f.mp4

2022-11-26 18:31 UTC, pratyaksh1610 commented
@iampradeep-hr Looks like you have not signed the CLA , refer [this](https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android#onboarding-instructions) to get started.

2022-11-26 18:36 UTC, iampradeep-hr commented
> @iampradeep-hr Looks like you have not signed the CLA , refer [this](https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android#onboarding-instructions) to get started.

Hi @pratyaksh1610 , Thanks a lot. I am new to this. What is CLA sheet and how to sign it up? 
I don't see any sign up option that page.

2022-11-26 18:38 UTC, pratyaksh1610 commented
@iampradeep-hr You will need to fill the form to get started (refer to the first point).

2022-11-27 04:56 UTC, iampradeep-hr commented
> @iampradeep-hr You will need to fill the form to get started (refer to the first point).

Ok, Thanks a lot. I submitted the form.

2022-11-29 05:06 UTC, BenHenning commented
Once the CI checks are done, you can assign it to me to take a review pass @iampradeep-hr by replying in a comment with 'PTAL @BenHenning'.

2022-11-29 08:34 UTC, iampradeep-hr commented
PTAL @BenHenning

2022-11-29 18:34 UTC, BenHenning requested changes
Thanks @iampradeep-hr. Took a pass. I left one comment, but otherwise:
- Please update the PR description & title to be consistent with other PRs (I think you erased parts of the PR description). See #4685 for an example of both.
- We should add tests for the change to make sure the event is being sent when expected.

2022-11-29 18:34 UTC, BenHenning commented on app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragmentPresenter.kt
> +          binding.onboardingSlideViewPager.performAccessibilityAction(
Why does this need to be done on both the root and the view pager?

2022-12-13 20:40 UTC, closed without merging