Fix #3558: Merge profile_chooser_profile_view.xml into single xml file
oppia/oppia-android pull request #4784
Opened 2022-12-09 14:33 UTC by dmdbilal

2022-12-09 14:37 UTC, yash10019coder commented
Hi @dmdbilal also refernce the issue to this PR by add Fixes #3558 into this PR description

2022-12-09 14:42 UTC, dmdbilal commented
> Hi @dmdbilal also refernce the issue to this PR by add Fixes #3558 into this PR description

@yash10019coder Referenced the issue in the PR description.

2022-12-18 09:11 UTC, yash10019coder requested changes
Hi @dmdbilal I recently tried to run the app from your latest code on the PR it seemed to work I tried on both tablet and mobile in both portrait and landscape. 

Now your can add the screenshots of the old and new UI in the PR description and also add the passing test cases for files ProfileChooserFragment and ProfileChooserActivity

Thanks,
Yash

2022-12-18 09:11 UTC, yash10019coder commented on app/src/main/res/layout-land/profile_chooser_profile_view.xml
> +</layout>
add newline at the end.

2022-12-18 09:11 UTC, yash10019coder commented on app/src/main/res/layout/profile_chooser_profile_view.xml
> +</layout>
same here

2022-12-18 09:12 UTC, yash10019coder commented
also please resolve merge conflicts in your PR

2022-12-18 17:01 UTC, yash10019coder commented
Here @dmdbilal https://www.jetbrains.com/help/idea/resolving-conflicts.html#distributed-version-control-systems this article will help you to resolve merge conflict.

2022-12-20 17:33 UTC, yash10019coder commented
Hi @dmdbilal try viewing this video it may help
https://www.youtube.com/watch?v=4ag6lJaSwzc

2022-12-21 13:00 UTC, yash10019coder commented
Hi @dmdbilal please try to setup a upstream according to this 
https://github.com/oppia/oppia-android/wiki/Fork-and-Clone-Oppia-Android#fork-and-clone-the-oppia-android-repository
after setting the upstream  run this command to get the latest develop code.
```
git pull upstream develop
```

2022-12-21 13:19 UTC, dmdbilal commented
Ok I'll try these methods.

2022-12-21 17:11 UTC, dmdbilal commented
@yash10019coder I've resolved the merge conflicts and the app works well in both mobile and tab. But the problem is when i run the ProfileChooserFragmentTest and ProfileChooserActivityTest I'm getting this error

```
Error running 'ProfileChooserActivityTest': 
Class 'org.oppia.android.app.profile.ProfileChooserActivityTest' not found in module 'oppia-android.app.unitTest'
```
```
Error running 'ProfileChooserFragmentTest': 
Class 'org.oppia.android.app.profile.ProfileChooserFragmentTest' not found in module 'oppia-android.app.unitTest'
```

2022-12-21 17:12 UTC, yash10019coder commented
Try rebuilding the project after invalidating the caches

2022-12-22 14:10 UTC, dmdbilal commented
> Try rebuilding the project after invalidating the caches

@yash10019coder I've rebuild and re-run the test now, but still it shows the same error.

2022-12-22 14:29 UTC, yash10019coder commented
@dmdbilal you can follow this https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-robolectric-tests

2022-12-22 15:02 UTC, dmdbilal commented
> @dmdbilal you can follow this https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-robolectric-tests

### Still I'm getting the same issue here.
![Screenshot 2022-12-22 203126](https://user-images.githubusercontent.com/91405690/209162383-1b60c4e2-6d8a-46e7-9938-398a43dcbaa8.png)

2022-12-24 03:02 UTC, dmdbilal commented
@yash10019coder I've rebuilt the project many times but still I'm getting this same issue again and again.

2022-12-31 05:54 UTC, yash10019coder commented
Hi @rt4914 could you approve the workflow run for this PR.

2022-12-31 06:03 UTC, dmdbilal commented
> workflow run

What's that workflow run ?

2023-01-01 14:43 UTC, yash10019coder commented
@dmdbilal a workflow run is like running all the test cases and other ci/cd(continuous integration and deployment) on the GitHub to test for any errors.
Continuous integration is like for the development whenever a developer pushes on the github these tests are ran and it makes sure that it doesn'te break the exiting code.

and continuous deployment means like build the app after the code is merged into the main branch like `develop` and then upload it to play store and make the release.

So I saw the tests run and I see what's failling the current tests [bazel](https://github.com/oppia/oppia-android/actions/runs/3810553828/jobs/6485921621#step:17:308) [gradle](https://github.com/oppia/oppia-android/actions/runs/3810553830/jobs/6485906098#step:7:701)

I think maybe you missed some of the dimens value for high density devices like xxhdpi devices
![image](https://user-images.githubusercontent.com/76404817/210174531-fccc291a-d4b4-4a31-955f-6fe5d53f4eda.png)

2023-01-01 15:41 UTC, dmdbilal commented
> @dmdbilal a workflow run is like running all the test cases and other ci/cd(continuous integration and deployment) on the GitHub to test for any errors.
> Continuous integration is like for the development whenever a developer pushes on the github these tests are ran and it makes sure that it doesn'te break the exiting code.
> 
> and continuous deployment means like build the app after the code is merged into the main branch like `develop` and then upload it to play store and make the release.
> 
> So I saw the tests run and I see what's failling the current tests [bazel](https://github.com/oppia/oppia-android/actions/runs/3810553828/jobs/6485921621#step:17:308) [gradle](https://github.com/oppia/oppia-android/actions/runs/3810553830/jobs/6485906098#step:7:701)
> 
> I think maybe you missed some of the dimens value for high density devices like xxhdpi devices
> ![image](https://user-images.githubusercontent.com/76404817/210174531-fccc291a-d4b4-4a31-955f-6fe5d53f4eda.png)
> 

@yash10019coder I'll solve that issue and let you know soon.

2023-01-01 16:41 UTC, yash10019coder commented
also merge with the latest develop.

2023-01-02 04:39 UTC, dmdbilal commented
@yash10019coder I've added the sizes in all the dimens.xml.

2023-01-12 13:19 UTC, yash10019coder commented
> @yash10019coder I've added the sizes in all the dimens.xml.

Ok @dmdbilal I'll rerun the tests workflow let's see if the tests are passing now if they we can merge your first PR.

2023-01-12 13:20 UTC, dmdbilal commented
> > @yash10019coder I've added the sizes in all the dimens.xml.
> 
> Ok @dmdbilal I'll rerun the tests workflow let's see if the tests are passing now if they we can merge your first PR.

Ok 👍

2023-01-12 14:56 UTC, yash10019coder commented
Hi @dmdbilal could you please make another PR as you've force-pushed into this PR. Remember to never do a force push in a PR as repositories where commits are pushed and are public should never be overwritten.

Thanks,
Yash

2023-01-12 14:56 UTC, closed without merging