Dark mode implementation for AdministratorControls, Help, Options, ProfileReset, ProfileRename, AppVersion, ProfileList, ProfileEdit etc
oppia/oppia-android pull request #4795
Opened 2022-12-19 17:35 UTC by rt4914

## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2022-12-20 12:10 UTC, MohitGupta121 commented on app/src/main/res/layout-sw600dp/help_activity.xml
> +        android:tint="@color/component_color_shared_multipane_icon_color"
@rt4914 Please make similar like as shared text color.

2022-12-20 15:14 UTC, MohitGupta121 requested changes
@rt4914 PTAL

2022-12-21 06:50 UTC, rt4914 commented
Me and @MohitGupta121 did review this PR over a 2 hr call where we went through each and every view, compared it with mocks and if something was changed w.r.t to mocks then if both of us agreed we finalised that and applied that change.

Its not possible to review this PR using mocks as they are inconsistent and this PR does require a lot of context.

2022-12-21 06:50 UTC, rt4914 commented on app/src/main/res/layout-sw600dp/help_activity.xml
> +        android:tint="@color/component_color_shared_multipane_icon_color"
Done.

2022-12-21 09:51 UTC, MohitGupta121 approved these changes
@rt4914 LGTM, Thanks.

2022-12-21 09:54 UTC, MohitGupta121 approved these changes
@rt4914 I not find any open issues related to these screens in the [dark-mode-project-board](https://github.com/orgs/oppia/projects/11). So I think there is no need to link any issue.

2022-12-21 11:12 UTC, rt4914 commented
@seanlip With [reference](https://github.com/oppia/oppia-android/pull/4795#issuecomment-1360921037) to this can you approve this PR?

2022-12-21 17:32 UTC, seanlip approved these changes
Confirming this looks good from a UI perspective. Thanks!

2022-12-21 17:33 UTC, merged