Fix #3384 : Arranged string resources based on screens
oppia/oppia-android pull request #4823
Opened 2023-01-03 14:06 UTC by MohitGupta121

## Explanation
Fix #3384 : Arranged string resources based on screens

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-01-03 14:09 UTC, MohitGupta121 commented
I open this new PR due to this [comment](https://github.com/oppia/oppia-android/pull/4665#issuecomment-1369709109)
As it is due to my mistake I delete my fork repo as that branch is so many commits ahead.

2023-01-03 14:19 UTC, MohitGupta121 reviewed
@BenHenning can you please review this PR as reference to your review on my last PR https://github.com/oppia/oppia-android/pull/4665#pullrequestreview-1177955860

2023-01-11 00:00 UTC, BenHenning commented
Thanks @MohitGupta121. Will need to look at this tomorrow.

2023-01-21 01:40 UTC, BenHenning commented
@MohitGupta121 really sorry will need to look at this on Monday (had an urgent deadline to address this week, but that will be resolved today).

2023-01-21 05:30 UTC, MohitGupta121 commented
> @MohitGupta121 really sorry will need to look at this on Monday (had an urgent deadline to address this week, but that will be resolved today).

Yes sure, no problem. I understand that release is in 1st priority.

2023-01-25 01:06 UTC, BenHenning commented
Need a bit more time, I plan to take at least a partial pass tomorrow.

2023-02-07 04:02 UTC, BenHenning commented
Not stale--this is blocked on me reviewing & I still have it backlogged.

2023-02-21 04:38 UTC, MohitGupta121 commented
Need review from @BenHenning and resolving merge conflicts.

2023-03-14 01:55 UTC, BenHenning commented
Hi @MohitGupta121. Apologies, I couldn't quite get to this today with my other PR reviews. I plan to look at this tomorrow or Wed since I now have a shortcut way to more quickly check it.

2023-03-22 02:52 UTC, BenHenning commented
I plan to look at this tomorrow or possibly Thursday, barring any high priority things that come my way. :)

2023-03-24 05:22 UTC, BenHenning requested changes, later dismissed
Thanks @MohitGupta121 both for the changes & your patience in me taking quite a while to get back to this.

I created a script to help me verify the correctness of the changes (which I want to pin down first, then I'll focus on naming specifics). I left some comments, but my script also detected the following changes being needed:

```
Discovered incorrect ID renames:
- An occurrence of policy_activity_title was changed to policy_activity_label_title, but expected one of:
  - privacy_policy_activity_title

- An occurrence of recently_played_stories was changed to profile_progress_header_activity_recently_played_stories, but expected one of:
  - recently_played_stories

- An occurrence of reading_text_size was changed to reading_text_size_activity_title, but expected one of:
  - reading_text_size

- An occurrence of recently_played_stories was changed to profile_progress_header_activity_recently_played_stories, but expected one of:
  - recently_played_stories

- An occurrence of reading_text_size was changed to reading_text_size_activity_title, but expected one of:
  - reading_text_size

- An occurrence of recently_played_stories was changed to profile_progress_header_activity_recently_played_stories, but expected one of:
  - recently_played_stories

- An occurrence of privacy_policy_title was changed to privacy_policy_activity_title, but expected one of:
  - policy_activity_label_title

- An occurrence of privacy_policy_title was changed to privacy_policy_activity_title, but expected one of:
  - policy_activity_label_title

- An occurrence of privacy_policy_title was changed to privacy_policy_activity_title, but expected one of:
  - policy_activity_label_title

- An occurrence of privacy_policy_title was changed to privacy_policy_activity_title, but expected one of:
  - policy_activity_label_title

- An occurrence of privacy_policy_title was changed to privacy_policy_activity_title, but expected one of:
  - policy_activity_label_title

- An occurrence of privacy_policy_title was changed to privacy_policy_activity_title, but expected one of:
  - policy_activity_label_title

- An occurrence of privacy_policy_title was changed to privacy_policy_activity_title, but expected one of:
  - policy_activity_label_title

- An occurrence of privacy_policy_title was changed to privacy_policy_activity_title, but expected one of:
  - policy_activity_label_title

- An occurrence of privacy_policy_title was changed to privacy_policy_activity_title, but expected one of:
  - policy_activity_label_title
```

Unfortunately, it won't say where these are but they seem to be straightforward to find. Can you look into this, the other comments, and then sync with the latest develop before sending back to me? I'll take another correctness pass, and then probably review everything except the strings in detail (since that's the largest part).

2023-03-24 05:22 UTC, BenHenning commented on app/src/main/res/values/strings.xml
> +  <string name="exploration_activity_voiceover_language_icon_spotlight_hint">Tap to change voiceover language.</string>
This value has appeared to have regressed. Shouldn't it be: ``Tap to change the voiceover language.``?

2023-03-24 05:22 UTC, BenHenning commented on app/src/main/res/values/strings.xml
> +  <string name="add_profile_activity_required_fields_content_description">Fields marked with an * are required.</string>
Is this string actually being used? It doesn't seem to be and I think it was removed in #4601.

2023-03-24 05:22 UTC, BenHenning commented on app/src/main/res/values/strings.xml
> +  <string name="add_profile_activity_add_profile_input_confirm_pin_hint_text">Confirm 3-Digit PIN*</string>
I believe all three of these no longer need the asterisk per #4601. Maybe this was missed during a sync with develop?

2023-03-24 05:22 UTC, BenHenning commented on app/src/main/res/values/strings.xml
> +  <string name="admin_pin_activity_admin_pin_requirement_description">Before we add profiles, we need to protect your account by creating a PIN. This gives you the ability to authorize downloads and
This text is out-of-date. It should be: ``Before we add profiles, we need to protect your account by creating a PIN. This gives you the ability to authorize manage profiles on the device.``.

2023-03-24 05:22 UTC, BenHenning commented on app/src/main/res/layout-sw600dp-land/profile_chooser_fragment.xml
This file was deleted in #4849.

2023-03-24 05:28 UTC, MohitGupta121 commented
@BenHenning Thanks you so much for giving time to review this. I will update this PR as per review and update all missing strings as per develop.

2023-05-01 18:43 UTC, MohitGupta121 commented on app/src/main/res/values/strings.xml
> +  <string name="exploration_activity_voiceover_language_icon_spotlight_hint">Tap to change voiceover language.</string>
Done.

2023-05-01 18:44 UTC, MohitGupta121 commented on app/src/main/res/values/strings.xml
> +  <string name="add_profile_activity_required_fields_content_description">Fields marked with an * are required.</string>
Done.

2023-05-01 18:46 UTC, MohitGupta121 commented on app/src/main/res/values/strings.xml
> +  <string name="add_profile_activity_add_profile_input_confirm_pin_hint_text">Confirm 3-Digit PIN*</string>
Done.

2023-05-01 18:47 UTC, MohitGupta121 commented on app/src/main/res/values/strings.xml
> +  <string name="admin_pin_activity_admin_pin_requirement_description">Before we add profiles, we need to protect your account by creating a PIN. This gives you the ability to authorize downloads and
Done.

2023-05-01 18:54 UTC, MohitGupta121 commented on app/src/main/res/layout-sw600dp-land/profile_chooser_fragment.xml
Done.

2023-05-13 18:53 UTC, MohitGupta121 commented
> ```
> Discovered incorrect ID renames:
> - An occurrence of policy_activity_title was changed to policy_activity_label_title, but expected one of:
>   - privacy_policy_activity_title

Hey @BenHenning, if possible can you please explain what exactly this "Discovered incorrect ID renames" detected by your script in this https://github.com/oppia/oppia-android/pull/4823#pullrequestreview-1355847791 ? What I exactly need to change. Please reply whenever you free no rush.
Thanks!

2023-08-02 18:56 UTC, MohitGupta121 commented
@adhiamboperes as per this comment of Ben, he transfers the review of this PR to you:



![Screenshot 2023-08-02 at 12 51 04 PM](https://github.com/oppia/oppia-android/assets/76530270/a71bd26b-16c5-4a86-b8eb-ff68ab16140f)

2023-09-26 17:55 UTC, MohitGupta121 commented
@adhiamboperes PTAL, Thanks!

2023-10-06 18:06 UTC, adhiamboperes requested changes
Hey @MohitGupta121 , thanks for organizing this file!

In addition to my inline comments, 

- [ ] Let's resolve the activity title rename issue once it's been resolved in the discussion.
- [ ] You do no need to make changes to the string files in the other languages, translatewiki will do the updates.
- [ ] Please resolve the merge conflicts.

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/AndroidManifest.xml
> +      android:label="@string/completed_story_list_activity_toolbar_title"
The label should be for the activity and not title.

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/AndroidManifest.xml
> +      android:label="@string/faq_single_activity_title"
```suggestion
      android:label="@string/faq_list_activity_title"
```

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/AndroidManifest.xml
> +      android:label="@string/reading_text_size"
Please make sure that the activity/toolbar title strings are not confused with the label strings that are used in the options fragment. I think you will notice that you need 2 seperate strings for this.

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/AndroidManifest.xml
> +      android:label="@string/pin_password_activity_pin_password_activity_label_title"
This does not conform to the expected pattern.

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="administrator_controls_activity_label_title">Administrator Controls</string>
There is another instance of AdministratorControlActivity grouping on line 25, shouldn't they be together?

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <!-- AdministratorControlsActivity -->
Per issue description, all activities should be in the correcte alphabetical order, so we should have something like **AdminAuthActivity**, followed by **AdministratorControlsActivity** the **AdminPinActivity**. **AddProfileActivity** will come before **AppVersionActivity** and so on.

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <!-- AppVersionActivity -->
This does not need to be it's own category as it is still part of `administrator_controls_*`

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <!-- AudioLanguageActivity -->
Th
```suggestion
  <!-- AudioDialogFragment -->
```

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <!-- CellularAudioActivity -->
```suggestion
  <!-- CellularAudioDialogFragment -->
```

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="stop_exploration_dialog_fragment_stop_exploration_dialog_title">Leave to Topic Page?</string>
These are in the same category, and `stop_exploration_dialog_fragment_stop_exploration_dialog_title` can move to the bottom of this category.

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="admin_pin_activity_admin_pin_requirement_description">Before we add profiles, we need to protect your account by creating a PIN. This gives you the ability to authorize downloads and
Looks like a typo, should be `Before we add profiles, we need to protect your account by creating a PIN. This gives you the ability to manage profiles on the device.`

I think that the text we are removing is `authorize downloads and`

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="solution_summary_activity_show_solution">Show solution</string>
```suggestion
  <string name="hints_and_solution_summary_hide_solution">Hide solution</string>
  <string name="hints_and_solution_summary_show_solution">Show solution</string>
```

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="solution_summary_activity_show_solution_button_text">Show solution</string>
This sting is duplicated in ln174 below

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="reveal_solution_dialog_fragment_this_will_reveal_the_solution_message">This will show the solution. Are you sure?</string>
```suggestion
  <string name="reveal_solution_dialog_fragment_message">This will show the solution. Are you sure?</string>
```

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="reveal_solution_dialog_fragment_reveal_text">Reveal</string>
```suggestion
  <string name="reveal_solution_dialog_fragment_text">Reveal</string>
```

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="text_input_interaction_item_activity_text_input_default_content_description">Enter text.</string>
```suggestion
  <string name="input_interaction_activity_text_input_default_content_description">Enter text.</string>
```

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="numeric_input_interaction_item_activity_numeric_input_hint">Enter a number.</string>
```suggestion
  <string name="input_interaction_activity_numeric_input_hint">Enter a number.</string>
```

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="math_expression_activity_error_generic_text">Sorry, we couldn\'t understand your answer. Please check it to make sure there aren\'t any errors.</string>
I saw that these are used in the MathExpressionInteractionsViewModel, and not in an activity so they should probably revert to their original naming, and this category heading should change from `MathExpressionActivity` to  `MathExpressionInteractionsViewModel`

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <!-- PinPasswordActivity -->
PinPasswordActivity comes before ProfileChooserFragment and ProgressDatabaseFullDialogActivity in alphabetical order

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="policy_activity_label_title">Privacy Policy</string>
I think these two strings have been switched.

2023-10-06 18:06 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <!-- RecentlyPlayedActivity -->
RevisionCardActivity comes after RecentlyPlayedActivity

2023-10-07 13:23 UTC, MohitGupta121 commented
> * [ ]  You do no need to make changes to the string files in the other languages, translatewiki will do the updates.

@adhiamboperes Thank you so much for taking the time to review this PR. 
Basically, if I change a string's name in the string.xml file then I need to also change the name of that string to other language files otherwise that string is unresolved in other languages. Right? So how do we ignore that?

2023-10-19 07:49 UTC, adhiamboperes commented
> @adhiamboperes Thank you so much for taking the time to review this PR. Basically, if I change a string's name in the string.xml file then I need to also change the name of that string to other language files otherwise that string is unresolved in other languages. Right? So how do we ignore that?

@MohitGupta121, we resolved in team meeting to change the names in all translations so that we do not loose all our translations, but you need to file an issue to follow up on translatewiki to remove the "fuzzy" attribute that will likely be added.

2023-11-18 09:13 UTC, closed without merging