Migrate to rules_jvm_external 5.1
oppia/oppia-android pull request #4925
Opened 2023-03-27 20:36 UTC by BenHenning

## Explanation

TODO: Finish & explain that this mainly allows for slightly better error detection & a much cleaner maven_install.

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-05-22 18:49 UTC, BenHenning commented
Still active.

2024-05-17 00:37 UTC, BenHenning reviewed
Finished initial self-review pass.

2024-05-17 00:37 UTC, BenHenning commented on app/BUILD.bazel
> -        "//third_party:com_crashlytics_sdk_android_crashlytics",
Revert this & the change in version?

2024-05-17 00:56 UTC, BenHenning commented on app/BUILD.bazel
> -        "//third_party:com_crashlytics_sdk_android_crashlytics",
Done.

2024-05-17 01:11 UTC, BenHenning reviewed
Self-reviewed most recent changes.

2024-05-17 01:11 UTC, BenHenning commented
This looks to be in a good place for review now. PTAL @adhiamboperes.

2024-05-17 01:12 UTC, BenHenning commented
@seanlip PTAL for owners group codeowners changes (mainly ``maven_install.json`` I think which is auto-generated).

2024-05-17 01:59 UTC, seanlip approved these changes
LGTM for one codeowner file: scripts/assets/maven_dependencies.textproto

2024-05-20 08:03 UTC, adhiamboperes requested changes
Thanks @BenHenning. I have two questions, PTAL.

2024-05-20 08:03 UTC, adhiamboperes commented on scripts/src/java/org/oppia/android/scripts/license/MavenDependenciesRetriever.kt
> +            withContext(Dispatchers.IO) {
Is it worth simplifying this to run without wrapping the `withContext` in the outer CoroutineScope?

2024-05-20 08:03 UTC, adhiamboperes commented on scripts/src/java/org/oppia/android/scripts/license/MavenDependenciesRetriever.kt
> +        }
Creating a  new list for every iteration looks expensive(using filter). Could this be implemented by using mutable lists that can be updated directly?

```kotlin
fun retrieveDependencyListFromPomAsync(
    finalDependenciesList: List<MavenListDependency>
): Deferred<MavenDependencyList> {
    return CoroutineScope(scriptBgDispatcher).async {
        val pomCandidates = finalDependenciesList.map { MavenListDependencyPomCandidate(it) }.toMutableList()
        var attemptCount = 0

        while (pomCandidates.any { it.latestPomFileText == null && it.downloadTryCount < 10 }) {
            val pomCandidatesToUpdate = pomCandidates.filter { it.latestPomFileText == null && it.downloadTryCount < 10 }
            println(
                "Attempt ${++attemptCount} to download POM files for" +
                " ${pomCandidatesToUpdate.size}/${pomCandidates.size} Maven artifacts..."
            )

            try {
                val results = pomCandidatesToUpdate.map { pomCandidate ->
                    withContext(Dispatchers.IO) {
                        mavenArtifactPropertyFetcher.scrapeText(pomCandidate.pomFileUrl)
                    }
                }

                pomCandidatesToUpdate.forEachIndexed { index, pomCandidate ->
                    pomCandidate.latestPomFileText = results[index]
                    pomCandidate.downloadTryCount++
                }
            } catch (e: Exception) {
                println("Error downloading POM file: ${e.message}")
            }
        }

        val failedToDownload = pomCandidates.filter { it.latestPomFileText == null }
        check(failedToDownload.isEmpty()) {
            "Failed to download ${failedToDownload.size}/${pomCandidates.size} POM files:" +
            " $failedToDownload."
        }

        return@async MavenDependencyList.newBuilder().apply {
            this.addAllMavenDependency(
                pomCandidates.map { pomCandidate ->
                    MavenDependency.newBuilder().apply {
                        this.artifactName = pomCandidate.dep.coord.reducedCoordinateString
                        this.artifactVersion = pomCandidate.dep.coord.version
                        // NB: the '!!' is fine here since previous checks should ensure the POM file text is
                        // impossible to be null at this point.
                        this.addAllLicense(extractLicenseLinksFromPom(pomCandidate.latestPomFileText!!))
                    }.build()
                }
            )
        }.build()
    }
}

```

2024-05-22 22:05 UTC, BenHenning reviewed
Thanks @adhiamboperes!

Self-reviewed latest changes & followed-up to review comments. PTAL @adhiamboperes.

2024-05-22 22:05 UTC, BenHenning commented on scripts/src/java/org/oppia/android/scripts/license/MavenDependenciesRetriever.kt
> +            withContext(Dispatchers.IO) {
Unless I'm mistaken, I think this will be more efficient because of line 212. It's creating one async job for each candidate to update, then blocks on all finishing before proceeding with the outer operation. The I/O wrapping is just to ensure actual blocking I/O happens on Kotlin's large I/O executor (since blocking I/O is non-cooperative, unlike ``awaitAll()`` which is a coroutine operation).

Kotlin's documentation isn't specifically clear on this point, but I suspect we want to minimize use of the I/O dispatcher to only I/O operations where we can help it so I don't see a huge benefit to wrapping the outer context in the I/O dispatcher (plus, we'd need to re-wrap with our background executor and then I/O again for the individual ``map`` results in order to benefit from the ``awaitAll`` call).

Please let me know if I'm misunderstanding your suggestion.

2024-05-22 22:05 UTC, BenHenning commented on scripts/src/java/org/oppia/android/scripts/license/MavenDependenciesRetriever.kt
> +        }
FWIW the lists are fairly small (usually at most ~250 items with our current dependencies if I recall) so I'm not sure the optimization will matter that much.

That being said, I'm not opposed to making it mutable. Implemented a version based on your suggestion though I also noticed there are several lists being created each iteration, anyway (with the ``map`` call), so I'm not sure how much of a difference this makes.

2024-05-24 21:48 UTC, adhiamboperes commented on scripts/src/java/org/oppia/android/scripts/license/MavenDependenciesRetriever.kt
> +            withContext(Dispatchers.IO) {
It appears that my suggestion was a bit vague, I was wondering why we needed to use both the background executor and withcontext while scraping the text. Your explanation makes sense, and I'm happy with the update.

2024-05-24 21:48 UTC, adhiamboperes commented on scripts/src/java/org/oppia/android/scripts/license/MavenDependenciesRetriever.kt
> +        }
This sounds good.

2024-05-24 21:49 UTC, adhiamboperes approved these changes
Thanks @BenHenning! This LGTM.

2024-05-26 19:14 UTC, BenHenning commented on scripts/src/java/org/oppia/android/scripts/license/MavenDependenciesRetriever.kt
> +        }
Seems like this is resolved now, unless I'm missing something (so going ahead and closing it).

2024-05-26 19:14 UTC, BenHenning commented
Thanks @adhiamboperes! Looks like this is ready to be merged, so syncing with the latest develop and enabling auto-merge.

2024-05-26 20:00 UTC, merged