Update README.md
oppia/oppia-android pull request #4927
Opened 2023-03-28 17:33 UTC by prafulbbandre

## Explanation

## Essential Checklist

- [X] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [X] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [X] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [X] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [X] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [X] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-03-31 17:51 UTC, prafulbbandre commented
@BenHenning can you approve this workflow.

2023-04-04 01:58 UTC, BenHenning commented
The workflows are running now @prafulbbandre, but per the issue there's more work to do here yet. You should also update the branch to the latest develop changes, as well.

2023-04-14 12:55 UTC, prafulbbandre commented
@BenHenning PTAL

2023-04-15 00:17 UTC, BenHenning requested changes
Thanks @prafulbbandre. Left one follow-up comment and synced with the latest develop. PTAL.

2023-04-15 00:17 UTC, BenHenning commented on .github/README.md
> +The Android app is frontend for Oppia that provides...household. The app is now available in beta and can be installed from the [Play Store](https://play.google.com/store/apps/details?id=org.oppia.an
The '...' means to keep the contents between the surrounding words ('provides' and 'household', in this case). You should re-add those words.

2023-04-25 19:08 UTC, prafulbbandre commented
@BenHenning PTAL

2023-04-27 02:54 UTC, BenHenning requested changes
Thanks @prafulbbandre! Took another pass. Just had one nit--PTAL.

2023-04-27 02:54 UTC, BenHenning commented on .github/README.md
> +The Android app is frontend for Oppia that provides access to Oppia's curated numeracy lessons for users who may not have regular access to internet connectivity, and in a way that can be easily shar
```suggestion
The Android app is a frontend for Oppia that provides access to Oppia's curated numeracy lessons for users who may not have regular access to internet connectivity, and in a way that can be easily shared across multiple members of the same household. The app is now available in beta and can be installed from the [Play Store](https://play.google.com/store/apps/details?id=org.oppia.android).
```

2023-04-27 02:56 UTC, BenHenning commented
Also @prafulbbandre when addressing reviewer comments, please reply to the comment thread with an affirmative that you addressed the issue (e.g. "Done"), or with a follow-up indication of why you can't (e.g. because you're stuck & need clarification) or shouldn't make the change. Please don't mark other reviewers' comment threads as resolved, either, as reviewers use these to keep track of past comments when performing incremental follow-up reviews.

2023-04-27 19:21 UTC, prafulbbandre commented
> Thanks @prafulbbandre! Took another pass. Just had one nit--PTAL.

@BenHenning Done.

2023-05-01 19:27 UTC, prafulbbandre commented on .github/README.md
> +The Android app is frontend for Oppia that provides access to Oppia's curated numeracy lessons for users who may not have regular access to internet connectivity, and in a way that can be easily shar
@BenHenning Done

2023-05-03 08:38 UTC, BenHenning approved these changes
Thanks @prafulbbandre! Apologies for the delayed review. The changes LGTM--just waiting on CI at this point (though I see no reason why it wouldn't pass, so enabling auto-merge as well).

2023-05-03 08:39 UTC, prafulbbandre commented
Thanks @BenHenning

2023-05-03 18:33 UTC, merged