Style Change: New styles for the Oppia Deprecation Dialog Design
oppia/oppia-android pull request #4997
Opened 2023-05-24 15:24 UTC by kkmurerwa

## Explanation

The introduction of the new deprecation dialogs for the App/OS Deprecation feature led to a minor redesign of the dialogs. This includes style changes to the dialogs that will display various deprecation messages. The proposed dialogs can be seen on this [Figma link](https://www.figma.com/file/dTWHwMDdZ8RUrR3rFmzxey/Oppia-deprecation-project?type=design&node-id=0-1&t=oJZSjk9XX4yQKo4f-0). When merged, this PR will introduce the new theme needed to achieve the desired dialog designs.

The difference between the current  and the proposed dialog are highlighted below;
### A screenshot of the current deprecation dialog
![A screenshot of the current deprecation dialog](https://github.com/oppia/oppia-android/assets/18438114/4518dbd5-a5b5-4d37-b4a9-a5d02e465e87)

### A screenshot of the proposed deprecation dialog redesign
![A screenshot of the redesigned deprecation dialog](https://github.com/oppia/oppia-android/assets/18438114/271704cd-a593-446a-9acd-1458343e2a7e)

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-05-24 17:27 UTC, kkmurerwa commented
Hey @adhiamboperes. I have assigned you this PR for a preliminary review before we get to Ben. Go through it and leave some feedback.

2023-05-30 10:13 UTC, adhiamboperes requested changes
Hi @kkmurerwa, I have requested some changes.

I suggest looking at the wiki sections for **working on the UI**  and  **dark mode** for more clarity on patterns.

2023-05-30 10:13 UTC, adhiamboperes commented on app/src/main/res/drawable/positive_button_rounded_border_solid_color_primary.xml
> +  <solid android:color="@color/component_color_story_chapter_default_progress_solid_color" />
Could you use a more appropriately named color resource, e.g. `component_color_shared_primary_button_background_color`?

For this and all color usages in this PR.

2023-05-30 10:13 UTC, adhiamboperes commented on app/src/main/res/drawable/positive_button_rounded_border_solid_color_primary.xml
> +<?xml version="1.0" encoding="utf-8"?>
Suggestion: rename this drawable to convey its explicit usage, e.g. dialog_positive_rounded_button_background, or prefix it with 'deprecation' if it will only be used by dialogs in this feature.

2023-05-30 10:13 UTC, adhiamboperes commented on app/src/main/res/values/themes.xml
> +    <item name="android:textColor">@color/color_palette_white_text_color</item>
I believe that for dark mode support we need to be using component_colors. See [wiki](https://github.com/oppia/oppia-android/wiki/Dark-Mode).

2023-05-30 10:13 UTC, adhiamboperes commented on app/src/main/res/values/themes.xml
> +  <style name="AlertDialogBackgroundPositiveButtonTheme" parent="Theme.MaterialComponents.Light.Dialog.Alert.Bridge">
This implies that it is a style to be applied to the buttons specifically, and not to the alert dialog itself. Is that the case? In which case should it be in a styles file?

2023-05-31 04:59 UTC, kkmurerwa commented
Hi @adhiamboperes. I have made the suggested changes. You can take another look at it now.

2023-05-31 23:27 UTC, adhiamboperes requested changes
I have left further comments @kkmurerwa, PTAL.

2023-05-31 23:27 UTC, adhiamboperes commented on app/src/main/res/values/styles.xml
> +    <item name="android:radius">10dp</item>
Is this needed, given that the background already has a radius?

2023-05-31 23:27 UTC, adhiamboperes commented on app/src/main/res/values/themes.xml
> +    <item name="android:paddingBottom">3dp</item>
Should be 4, per android [best practices](https://github.com/oppia/oppia-android/wiki/Working-on-UI#paddingmarginview-dimensions)

2023-05-31 23:27 UTC, adhiamboperes commented on app/src/main/res/values/themes.xml
> +    <item name="android:color">@color/component_color_shared_dialogs_radio_button_unchecked_color</item>
This color does not appear to be named correctly yet. You can define a new component_color for it if none exists, per the darkmode guidelines.

2023-06-02 06:14 UTC, kkmurerwa commented
Hi @adhiamboperes. I think I forgot to request another review. I have made all the suggested changes and you can have another pass at this PR.

2023-06-03 13:00 UTC, adhiamboperes approved these changes
Thanks @kkmurerwa! These changes LGTM.

Please respond to all review comments so that I can resolve them before merge.

2023-06-04 07:15 UTC, kkmurerwa commented
Hi @adhiamboperes. I think I have responded to all conversations.

2023-06-04 07:20 UTC, adhiamboperes commented
> Hi @adhiamboperes. I think I have responded to all conversations.

I think you're seeing this: https://github.com/oppia/oppia-android/pull/4874#issuecomment-1488392499

2023-06-22 10:31 UTC, kkmurerwa commented
Hi @adhiamboperes. Should I resolve the conversation or reviews that I inadvertently started while replying to comments or should I just resolve the conversations?

2023-06-22 11:11 UTC, kkmurerwa reviewed
Here are the review comments.

2023-06-22 11:11 UTC, kkmurerwa commented on app/src/main/res/values/themes.xml
> +  <style name="AlertDialogBackgroundPositiveButtonTheme" parent="Theme.MaterialComponents.Light.Dialog.Alert.Bridge">
The `AlertDialogBackgroundPositiveButtonTheme` will be used as the main style of the alert dialog. There is a different button style to be used that is named `AlertDialogPositiveButtonBackgroundTheme` and has been moved to the style file. The `AlertDialogBackgroundPositiveButtonTheme` could be named better so I will work on the renaming.

2023-06-22 11:11 UTC, kkmurerwa commented on app/src/main/res/values/themes.xml
> +  <style name="AlertDialogBackgroundPositiveButtonTheme" parent="Theme.MaterialComponents.Light.Dialog.Alert.Bridge">
I have renamed the alert dialog theme has been renamed to `DeprecationAlertDialogTheme` and the button style has been renamed to `DeprecationAlertDialogPositiveButton`.

2023-06-22 11:11 UTC, kkmurerwa commented on app/src/main/res/values/themes.xml
> +    <item name="android:textColor">@color/color_palette_white_text_color</item>
I have replaced all color references with better-related colors and switched to using component colors for all color-related styling.

2023-06-22 11:11 UTC, kkmurerwa commented on app/src/main/res/values/styles.xml
> +    <item name="android:radius">10dp</item>
I found that it was not needed and removed the radius.

2023-06-22 11:11 UTC, kkmurerwa commented on app/src/main/res/values/themes.xml
> +    <item name="android:paddingBottom">3dp</item>
I have modified all paddings to be 4dp.

2023-06-22 11:11 UTC, kkmurerwa commented on app/src/main/res/values/themes.xml
> +    <item name="android:color">@color/component_color_shared_dialogs_radio_button_unchecked_color</item>
I used a shared secondary test component color. This should now use a more descriptive color.

2023-06-22 12:06 UTC, merged