Fix #4793 : Talkback is reading close icon as navigator button in Hints page
oppia/oppia-android pull request #5082
Opened 2023-07-09 15:26 UTC by prafulbbandre

## Explanation
Fixes #4793 

## Essential Checklist

- [X] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [X] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [X] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [X] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [X] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [X] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-07-10 09:03 UTC, adhiamboperes requested changes
Thanks @prafulbbandre! 

PTAL at the comment I have left.  Additionally,
1. Please add to the PR (UI specific section) a screen recording video of talkback reading the final output. Please refer to the  issue description on how to activate a hint dialog, and if you need reference on talkback please look at https://support.google.com/accessibility/android/answer/6007100?sjid=5513377839108153520-EU.

2023-07-10 09:03 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="hints_andSolution_close_icon_description">Close Button</string>
Talkback recognises and will always announce the view, so this will be read as "Close Button, button". Please change the text to "Close" only.

2023-07-10 09:05 UTC, prafulbbandre commented
> Thanks @prafulbbandre!
> 
> PTAL at the comment I have left. Additionally,
> 
> 1. Please add to the PR (UI specific section) a screen recording video of talkback reading the final output. Please refer to the  issue description on how to activate a hint dialog, and if you need reference on talkback please look at https://support.google.com/accessibility/android/answer/6007100?sjid=5513377839108153520-EU.

The installing oppia-android issue is not solved for me so i am not able to provide the screen-recording.

2023-07-11 10:41 UTC, prafulbbandre commented
@adhiamboperes PTAL

2023-07-16 09:23 UTC, prafulbbandre commented on app/src/main/res/values/strings.xml
> +  <string name="hints_andSolution_close_icon_description">Close Button</string>
Done

2023-07-16 09:24 UTC, prafulbbandre commented
Hi @adhiamboperes Please review the changes.

2023-07-17 13:41 UTC, prafulbbandre commented
@adhiamboperes I am opening new PR.
Thanks for help.

2023-07-17 13:41 UTC, closed without merging