Fix #5079 : Gradle Build Failed - Task :utility:kaptGenerateStubsDebugKotlin FAILED
oppia/oppia-android pull request #5083
Opened 2023-07-09 17:49 UTC by MohitGupta121

## Explanation

Fix #5079 : Gradle Build Failed - Task :utility:kaptGenerateStubsDebugKotlin FAILED Wiki updated

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-07-09 18:15 UTC, MohitGupta121 reviewed
@adhiamboperes PTAL, Thanks!

2023-07-10 09:21 UTC, adhiamboperes requested changes
Thanks @MohitGupta121!

In addition to my in-line suggestions:

The PR title and description are a bit misleading; they seem to imply that this PR fixes the gradle build issue instead of updating the wiki. Please update that.

2023-07-10 09:21 UTC, adhiamboperes commented on wiki/Troubleshooting-Installation.md
> +7. If you getting this error while gradle build
```suggestion
7. If you encounter this error while building gradle:
```

2023-07-10 09:21 UTC, adhiamboperes commented on wiki/Troubleshooting-Installation.md
> +
```suggestion
You are seeing this because Oppia android currently compiles with Java 8, or 9. Higher versions of Java are not supported by our version of Gradle.

The `model.jar` was compiled with Java 15/major version 59, hence the incompatibility.
   

To fix this error, you need to lower the version of Java to compile the JAR file. Please see [here](https://developer.android.com/studio/intro/studio-config#jdk) for more information about Java versions.

```

2023-07-10 20:06 UTC, MohitGupta121 commented on wiki/Troubleshooting-Installation.md
> +
Done.

2023-07-10 20:06 UTC, MohitGupta121 commented on wiki/Troubleshooting-Installation.md
> +7. If you getting this error while gradle build
Done.

2023-07-10 20:07 UTC, MohitGupta121 reviewed
@adhiamboperes PTAL, Thanks.
I updated the suggested changes.

2023-07-10 20:15 UTC, adhiamboperes approved these changes
Thanks @MohitGupta121, this LGTM!

Assigning @seanlip for codeowners.

2023-07-11 03:44 UTC, merged