Fix #4391: Fix failing build on m1 macs
oppia/oppia-android pull request #5111
Opened 2023-07-29 08:10 UTC by kkmurerwa

Fix #4391 : Fix failing build on M1 Macs
## Explanation

Some M1 Macs fail to build the Oppia app because of unused imports in some of the proto files in the project. This PR attempts to fix this issue by removing unused imports in proto files. Only two files have been modified by this PR;
- profile.proto
- deprecation.proto

This is a temporary fix and more investigation will need to be done to properly understand why this behavior is erratic and why it only happens in some instances and not in others. More checks are also needed to ensure that proto files only have imports that are used in the proto file before they are merged.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

2023-07-31 09:55 UTC, adhiamboperes approved these changes
Thanks @kkmurerwa! This PR LGTM. Just one thing: could you change both the title and description to "Fix Part of"? Otherwise the issue will be closed, yet it is not fully resolved.

2023-07-31 09:55 UTC, adhiamboperes commented on scripts/static_checks.sh
This is a really nice addition. Thanks!

2023-07-31 09:59 UTC, adhiamboperes commented
One more thing, please refer to https://github.com/oppia/oppia-android/pull/5108#issuecomment-1655063018 on how to fix your failing TODO check.

2023-07-31 12:45 UTC, seanlip requested changes

2023-07-31 12:45 UTC, seanlip commented on scripts/static_checks.sh
> +# Download Buildifier in oppia-andoid-tools folder (pre-requisite for buildifier checks)
andoid --> android

2023-07-31 12:45 UTC, seanlip commented on scripts/static_checks.sh
> +#!/bin/bash
Thanks @kkmurerwa! Just wondering, how long does this script take to run (typically)? Might be worth mentioning that in the wiki so that devs know what to expect.

2023-08-01 14:44 UTC, kkmurerwa commented on scripts/static_checks.sh
I have fixed the issue number reference and title. And thank you.

2023-08-01 15:14 UTC, kkmurerwa commented on scripts/static_checks.sh
> +#!/bin/bash
I tried to be a bit scientific about this. I made three runs without running bazel clean and three while running bazel clean. Without bazel clean, the average runtime was 1 and a half minutes. Running bazel clean each time, the average time was 5 and a half minutes. Bearing in mind I'm using a quite powerful M1 chip, I would say it should be around 6-10 minutes for a clean run and around 2-5 minutes for a subsequent run. I will update the Wiki with these estimates.

2023-08-01 15:16 UTC, kkmurerwa commented on scripts/static_checks.sh
> +# Download Buildifier in oppia-andoid-tools folder (pre-requisite for buildifier checks)
Thanks for spotting this.

2023-08-03 07:49 UTC, kkmurerwa commented
Hi @seanlip. This is PR ready for another pass.

2023-08-03 13:12 UTC, seanlip approved these changes
Looks great. Thanks @kkmurerwa!

2023-08-03 14:01 UTC, adhiamboperes approved these changes
Thanks @kkmurerwa, this LGTM

2023-08-03 16:20 UTC, merged