Fix #5120 Missing Text Margins In Topic Revision Cards in Large Screens
oppia/oppia-android pull request #5127
Opened 2023-08-09 11:45 UTC by pingu-73

## Explanation

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

## Changes made:
added layout_marginStart and layout_marginEnd in oppia-android/app/src/main/res/layout-sw600dp/revision_card_fragment.xml
<img width="846" alt="Screenshot 2023-08-09 at 4 52 46 PM" src="https://github.com/oppia/oppia-android/assets/121669947/b2ed2602-2e5c-4124-a856-f6209e3dc0a1">

Absence of marginStart and marginEnd caused missing text margins on Large Screens. 

## Screenshots:
**before fix:**
![padding and margin](https://github.com/oppia/oppia-android/assets/121669947/a50dd61f-2574-493d-a482-720bbe6d5970)

**after fix:**
![ratiocorrect](https://github.com/oppia/oppia-android/assets/121669947/69261f78-6f66-4aa1-a616-8827f7108035)

2023-08-09 13:19 UTC, adhiamboperes requested changes
Thanks @pingu-73!


Please read the PR description and make sure you have addressed the items on the checklist that I have unchecked.

2023-08-09 13:19 UTC, adhiamboperes commented on .idea/codeStyles/Project.xml
Please remove this file

2023-08-09 13:29 UTC, pingu-73 commented on .idea/codeStyles/Project.xml
do I need to remove .idea folder of project.xml file?

2023-08-09 13:33 UTC, MohitGupta121 commented on .idea/codeStyles/Project.xml
Yes @pingu-73, you have to follow all conditions mentioned in Essential Checklist of your PR description.

2023-08-09 13:50 UTC, pingu-73 commented on .idea/codeStyles/Project.xml
@MohitGupta121 is it fine?

2023-08-09 13:51 UTC, MohitGupta121 commented on .idea/codeStyles/Project.xml
No you have to remove unnecessary files

2023-08-09 15:23 UTC, pingu-73 commented on .idea/codeStyles/Project.xml
@MohitGupta121 @adhiamboperes please have a look at it now

2023-08-10 01:16 UTC, pingu-73 commented
@MohitGupta121 can you please approve checks

2023-08-10 01:18 UTC, MohitGupta121 commented
@pingu-73 after your code is approved the maintainer will approve the checks also. Don't worry.

2023-08-10 13:07 UTC, adhiamboperes approved these changes
Thanks @pingu-73! 

Congratulations! Your changes LGTM.

2023-08-10 13:45 UTC, merged