contrast issue fixed
oppia/oppia-android pull request #5144
Opened 2023-09-06 09:38 UTC by Vishwajith-Shettigar

## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-09-06 09:52 UTC, Vishwajith-Shettigar commented
@adhiamboperes PTAL

2023-09-06 14:14 UTC, Vishwajith-Shettigar commented
@adhiamboperes  Could you please review the failed checks and provide guidance on how to resolve them? Thank you.

2023-09-06 19:35 UTC, adhiamboperes requested changes
Thanks @Vishwajith-Shettigar! 
I have left some suggestions, but this looks okay.

Could you also just add the screen recordings so that we can see the active/inactive state color changes in action?

2023-09-06 19:35 UTC, adhiamboperes commented on app/src/main/res/color/component_color_textlayout.xml
Please use proper snake case on the file name

2023-09-06 19:35 UTC, adhiamboperes commented on app/src/main/res/color/component_color_textlayout.xml
> +</selector>
Add newline to eof

2023-09-07 02:07 UTC, Vishwajith-Shettigar commented on app/src/main/res/color/component_color_textlayout.xml
> +</selector>
okay

2023-09-07 02:08 UTC, Vishwajith-Shettigar commented on app/src/main/res/color/component_color_textlayout.xml
component_color_text_layout.xml is that okay ?

2023-09-07 02:20 UTC, Vishwajith-Shettigar commented
> Thanks @Vishwajith-Shettigar! I have left some suggestions, but this looks okay.
> 
> Could you also just add the screen recordings so that we can see the active/inactive state color changes in action?

I added Screen recordings,thank you.

2023-09-07 11:42 UTC, adhiamboperes approved these changes
This LGTM, thanks @Vishwajith-Shettigar!

2023-09-07 12:36 UTC, merged