Fixed Splash Screen Stretched issue by using sdp library
oppia/oppia-android pull request #5147
Opened 2023-09-09 14:59 UTC by backpackerdeveloper

**Splash Screen Stretched issue Fix -**
**Changes**:
 - Added SDP library in dependency
 - in SplashScreenActivity : in ImageView Changed the dp to sdp
 - Now it fits on different sizes of devices

2023-09-09 15:43 UTC, backpackerdeveloper commented
Signed the CLA sheet 👍

2023-09-12 22:06 UTC, adhiamboperes commented
Hey @backpackerdeveloper, can you tell me about any alternative solutions you considered before adding the sdp lib?

Please also read the wiki on [submitting a PR.](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR) You deleted the PR template but you need to fill it out instead. Please look at [this](https://github.com/oppia/oppia-android/pull/5148) other PRs in the repo and copy the PR description template and add it to this PR.

2023-09-12 22:07 UTC, adhiamboperes requested changes
Hey @backpackerdeveloper, can you tell me about any alternative solutions you considered before adding the sdp lib?

Please also read the wiki on [submitting a PR.](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR) You deleted the PR template but you need to fill it out instead. Please look at https://github.com/oppia/oppia-android/pull/5148 other PRs in the repo and copy the PR description template and add it to this PR.

2023-09-15 20:22 UTC, backpackerdeveloper commented
@adhiamboperes As I saw ConstraintLayout is properly, assigned, so I directly sdp lib, and it worked.
and yes I was slightly confused with the PR Template at that time, and mistakenly deleted the template

2023-09-24 00:11 UTC, adhiamboperes requested changes
Hi @backpackerdeveloper, thanks for this PR. There are a number of things that need work in order for us to accept this solution:

- [ ] The library needs to be added to bazel as well as gradel. Please follow [this wiki](https://github.com/oppia/oppia-android/wiki/Updating-Maven-Dependencies) to add a dependency to bazel.
- [ ] We do not need to update gradle now, so please exclude any gradle wrapper update changes from your PR.
- [ ] Please refer to the [wiki on submitting a PR](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR). Your branch is called develop, and that is prohibited in the repo.
- [ ] Add before and after screenshots to your PR, to demostrate the changes.(Also make sure you read the essential checklist because it has important requirements)

This means that you should close this PR and open a new one with an appropriately named branch, and also please address all these comments in the new PR.

2023-09-24 00:11 UTC, adhiamboperes commented on gradle/wrapper/gradle-wrapper.jar
This should not be part of the commit.

2023-09-24 00:11 UTC, adhiamboperes commented on gradle/wrapper/gradle-wrapper.properties
Please remove this change, we do not want to update gradle at the moment.

2023-09-28 12:17 UTC, closed without merging