Update AudioViewModel.kt
oppia/oppia-android pull request #5156
Opened 2023-09-21 21:10 UTC by vaibhavmehrotraa

## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-09-24 09:54 UTC, vaibhavmehrotraa commented
Hey! Is there anything else I need to do to this PR ?

2023-09-24 10:57 UTC, adhiamboperes commented
> Hey! Is there anything else I need to do to this PR ?


I'll give it a pass and leave some comments.

2023-09-26 06:42 UTC, adhiamboperes requested changes
@vaibhavmehrotraa thanks for your PR.

Two things:
1. You code contains compile eerors. Please always test your code locally before pushing.
2. I tested this fix and it does not actually work. It would be helpful to investigate the issue further to understand the root cause and try a different solution. In your new solution, please laso add tests and screenshots to prove that your solution works, per the PR template;s essential checklist.

2023-09-26 06:42 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt
> +        languages.add(defaultLanguage)
`languages` is not a mutable list therefore it does not have an `add` function. This will not compile.

You should create a new mutable list from the elements of the immutable list, e.g. `immutableList.toMutableList()`

2023-10-03 02:12 UTC, closed without merging