fix #5150: set layout params correctly
oppia/oppia-android pull request #5160
Opened 2023-09-26 21:17 UTC by nikitaevg

fix #5150. Previously layout params were not set after being updated. Also, the `requestLayout` call on the view is not needed, because the view layout is not changing. Video which shows that it works: https://drive.google.com/file/d/13sw2PiZ_5lu2mnW0y4PjSS502hOZ_Vni/view?usp=sharing

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-09-26 21:31 UTC, nikitaevg commented
Hey @adhiamboperes!

Could you please check this PR? I also have a problem adding an assignee. See the screenshot, I simply can't do it.
![image](https://github.com/oppia/oppia-android/assets/6707908/0fe15575-e541-4018-80e1-6f5fb395e186)

I guess I don't have permissions for that. Is that intended?

Thanks!

2023-09-27 13:04 UTC, adhiamboperes requested changes
Thanks @nikitaevg!

I noticed that your PR changes are different from the ones proposed in the issue thread. Could you explain why?

Additionally, we have previously had some issues with changes in the MarginBindingadapters, and it would be great to verify that your changes so not break the UI elswhere. Please refer to https://github.com/oppia/oppia-android/pull/4951.

2023-09-27 13:05 UTC, adhiamboperes commented
> Hey @adhiamboperes!
> 
> Could you please check this PR? I also have a problem adding an assignee. See the screenshot, I simply can't do it. !
> I guess I don't have permissions for that. Is that intended?
> 
> Thanks!

You can assign a reviewer by mentioning them with `@`xxx`, PTAL`.

2023-09-27 13:06 UTC, adhiamboperes commented
@nikitaevg, PTAL.

2023-09-27 18:46 UTC, nikitaevg commented
Thanks for the review!

> I noticed that your PR changes are different from the ones proposed in the issue thread. Could you explain why?

My explanation in the discussion wouldn't fix the whole problem. It would fix the issue only when the home activity is restarted. I was able to reproduce the original issue without restarting the home activity: first open some lesson, go back to the home screen, and then scroll down, the lessons might become unaligned.

I guessed it wasn't a fix for the root cause, more of a workaround. I googled and found, that if we want to set margins programmatically, we need to set layout params ([link](https://stackoverflow.com/a/12728484)).

> Additionally, we have previously had some issues with changes in the MarginBindingadapters, and it would be great to verify that your changes so not break the UI elswhere. Please refer to https://github.com/oppia/oppia-android/pull/4951.

Thanks for highlighting that! See the screenshots, there's no such problem. I think it shouldn't break anything, because I'm not adding anything strange, just setting the layout params.
![Screenshot from 2023-09-27 19-34-04](https://github.com/oppia/oppia-android/assets/6707908/059a6812-a8bb-48f7-bc3d-7fb37f3dceee)
![image](https://github.com/oppia/oppia-android/assets/6707908/0b1d97a1-bdf2-4bad-bc89-0ef9ade59aa8)

2023-09-27 18:48 UTC, nikitaevg commented
@adhiamboperes, PTAL.

2023-09-28 17:18 UTC, adhiamboperes reviewed
Thanks @nikitaevg, I tested these changes with the production assests and they issue is resolved. But @BenHenning, is there some way that we can improve the tests for this class? I'm not sure that there's a specific way to check that the layout params have been set beyond what we have currently.  

Phone: [device-2023-09-28-201012.webm](https://github.com/oppia/oppia-android/assets/59600948/1848e2b8-a03d-4cc2-8d29-07510910c629)

Tablet: [device-2023-09-28-201315.webm](https://github.com/oppia/oppia-android/assets/59600948/a63e51ee-8555-4e03-9049-71b3a4d2f6a4)

2023-10-13 20:56 UTC, BenHenning commented
@adhiamboperes and I discussed some strategies on how to investigate why this solution works (which is a good way to figure out what to test to verify that these changes correctly fix what needs to be fixed, and stay fixed).

Please assign back to me if follow-up thoughts are needed, or when this is ready for review again.

2023-11-06 10:50 UTC, adhiamboperes commented
Added a follow up comment on the issue https://github.com/oppia/oppia-android/issues/5150#issuecomment-1794548399

2023-11-20 12:16 UTC, closed without merging