Fix #5133  Audio language name showing two times
oppia/oppia-android pull request #5178
Opened 2023-10-04 12:00 UTC by Vishwajith-Shettigar

## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-10-04 12:09 UTC, Vishwajith-Shettigar commented
@adhiamboperes , PTAL

2023-10-04 18:03 UTC, adhiamboperes requested changes
Thanks @Vishwajith-Shettigar! 

1. Could you please add before and after screenshots?
2.  We currently do not have tests for `LanguageDialogFragment`. Do you think you can explore adding one, and testing this fix?

2023-10-04 18:03 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt
> +  }
Could be flattened:
```suggestion
  fun getSupportedLanguageCodes(): List<String> {
    val supportedAudioLanguageCodes = AudioLanguage.values()
      .map { audioLanguage ->
        getAudioLanguage(audioLanguage)
      }
      .toMutableList()
    supportedAudioLanguageCodes.add("hi-en")
    return supportedAudioLanguageCodes
  }
```

2023-12-04 22:30 UTC, adhiamboperes commented
@Vishwajith-Shettigar, I'm closing this PR since the desiredd implementation is blocked. See https://github.com/oppia/oppia-android/issues/5133#issuecomment-1839602314

2023-12-04 22:30 UTC, closed without merging