Fix #3596: Adds Audio Loading UI
oppia/oppia-android pull request #5179
Opened 2023-10-07 03:22 UTC by theMr17

## Explanation

Fixes #3596

This PR adds a indeterminate progress bar when the audio is loading, before it starts playing.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

https://github.com/oppia/oppia-android/assets/84731134/5c6fe393-5d89-4bda-a144-57bdc42a9c57

2023-10-07 03:39 UTC, theMr17 commented
@adhiamboperes Probably, I have used the wrong color resource for the `CircularProgressIndicator`. I am not sure exactly which color resource to use in this case.

2023-10-09 12:33 UTC, adhiamboperes commented
Hey @theMr17, if this is ready for a review please assign it to me.

2023-10-09 13:05 UTC, theMr17 commented
@adhiamboperes This is ready for a review, but I am not sure why the tests are failing. Can you please help me with that?

2023-10-09 13:13 UTC, adhiamboperes commented
> @adhiamboperes This is ready for a review, but I am not sure why the tests are failing. Can you please help me with that?

Since you have changed the behavior of the audio icon, an associated UI test is failing. You need to update the test to assert the new behaviour, and maybe add additional tests to make sure the new behaviour is adequately tested.
<img width="1053" alt="Screenshot 2023-10-09 at 16 11 10" src="https://github.com/oppia/oppia-android/assets/59600948/90528578-71d4-4f80-a137-58b8f8a1da61">

2023-10-14 12:28 UTC, adhiamboperes requested changes
Thanks @theMr17!

This PR changes the behavior of the audio icon. Can we please add tests to verify all the expected states:
- when is the progress indicator expected to show
- when is the progress indicator expected to be hidden?
- once the progress indicator has been hidden and the pause play button shown, can the rest of the flow be verified to have remained the same?
This looks like you need to add 2 new tests, and modify an existing one, or 2. Please verify.

2023-10-14 12:28 UTC, adhiamboperes commented on app/src/main/res/layout/audio_fragment.xml
> +        android:id="@+id/audio_loading_bar"
```suggestion
        android:id="@+id/audio_fragment_voiceover_progressbar"
```

2023-10-14 12:28 UTC, adhiamboperes commented on app/src/main/res/layout/audio_fragment.xml
> +        app:indicatorColor="@color/component_color_shared_icon_white_color"
You should create a component color specific to this feature so that the usage is clear. As for specific color, white is alright.

2023-10-14 12:28 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
> +      onView(withId(R.id.audio_loading_bar)).check(matches(isDisplayed()))
The test name is not in line with the assertion being made. At a glance, I can see that the original test was to verify that if a user clicks the audio icon a second time, the cellular data dialog will not be shown.
This test nolonger verifies that, and I do not see a replacement test for it.

2023-11-11 04:17 UTC, theMr17 commented
@adhiamboperes, PTAL

2023-11-14 16:33 UTC, adhiamboperes approved these changes
Thanks @theMr17, this LGTM!

2023-11-14 17:13 UTC, merged