Fix #5039 Terms of Service and Privacy Policy content should still be left-aligned, even if the app is in an RTL language.
oppia/oppia-android pull request #5181
Opened 2023-10-08 07:35 UTC by ShubhadeepKarmakar

## Explanation

  - Fix #5039 
  Under the ListItemLeadingMarginSpan class we have the ulSpan class and the olSpan class which takes displayLocal as an input and then retrieves the direction of the layout using the getLayoutDirection() method to get the bullet drawing position.
That's why I created an object of the DisplayLocaleImp class and overridden the getLayoutDirection() method to pretend it's LTR.
  

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-10-09 12:35 UTC, adhiamboperes commented
Hey @ShubhadeepKarmakar , if this is ready for a review please assign it to me. Otherwise, please assign it to yourself.

YOu can run this command to fix your lint failures from terminal `java -jar /home/runner/oppia-android-tools/ktlint -F --android domain/src/**/*.kt utility/src/**/*.kt data/src/**/*.kt app/src/**/*.kt testing/src/**/*.kt scripts/src/**/*.kt  instrumentation/src/**/*.kt`, and don't forget to add screenshots to the PR.

2023-10-18 22:43 UTC, adhiamboperes commented
@ShubhadeepKarmakar is this ready to be reviewed?

2023-10-19 00:21 UTC, ShubhadeepKarmakar commented
> @ShubhadeepKarmakar is this ready to be reviewed?

Yeah.

2023-10-20 17:45 UTC, adhiamboperes requested changes
Thanks @ShubhadeepKarmakar!

I was not able to understand the explanation you gave on the PR description, in relation to the problem and the solution. Could you please edit it and clarify?

Overall, I'm unsure of the approach, so I've brought it up with the team. I'll be able to review this further once that's resolved.

Meanwhile, please feel free to work on something else.

2023-10-20 17:45 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/policies/PoliciesFragmentPresenter.kt
> +    if (resourceHandler.getLayoutDirection() == ViewCompat.LAYOUT_DIRECTION_RTL) {
I believe we want to align to the start of the textview?

2023-10-20 17:45 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/policies/PoliciesFragmentPresenter.kt
> +     */
This should be a regular comment, not a KDoc.

```
//...
//...
```

2023-10-24 10:23 UTC, adhiamboperes commented
Hi @ShubhadeepKarmakar, Could you PTAL at this feedback?
 
<img width="948" alt="Screenshot 2023-10-24 at 13 22 52" src="https://github.com/oppia/oppia-android/assets/59600948/6533bcdb-6f47-436f-bde6-63934ea501af">

2023-11-02 14:02 UTC, adhiamboperes commented
@ShubhadeepKarmakar, are you still working on this PR?

2023-11-02 14:11 UTC, ShubhadeepKarmakar commented on app/src/main/java/org/oppia/android/app/policies/PoliciesFragmentPresenter.kt
> +     */
Done

2023-11-02 18:02 UTC, ShubhadeepKarmakar commented on app/src/main/java/org/oppia/android/app/policies/PoliciesFragmentPresenter.kt
> +    if (resourceHandler.getLayoutDirection() == ViewCompat.LAYOUT_DIRECTION_RTL) {
Yes, but isn't the screen already set to RTL?

2023-11-16 18:45 UTC, closed without merging