Fix #5187  Text contrast issue
oppia/oppia-android pull request #5189
Opened 2023-10-13 13:53 UTC by Vishwajith-Shettigar

## Explanation

Fixes #5187, changing the background color of the locked lessons' TextView fixed the contrast ratio issue.

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

Before Fix

| Light Mode| Dark Mode|
|--------|--------|
| ![textcontrast](https://github.com/oppia/oppia-android/assets/76042077/01ffdf6c-3a20-4ce5-ab20-54ff7a82fedee)|![testdark](https://github.com/oppia/oppia-android/assets/76042077/d3f1fb3a-f267-4ced-9a00-3bdd67d4192a)| 

After Fix

| Light Mode| Dark Mode|
|--------|--------|
| ![afterlight](https://github.com/oppia/oppia-android/assets/76042077/7d00b264-0bfb-4b35-8b99-b0b44ff7149d)| ![afterdark](https://github.com/oppia/oppia-android/assets/76042077/42f5f736-15e6-40b7-975a-58dfb8d55f6c)| 

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-10-13 13:54 UTC, Vishwajith-Shettigar commented
@adhiamboperes, PTAL

2023-10-14 13:05 UTC, adhiamboperes commented
@MohitGupta121, could you please take a look and let me know if @Vishwajith-Shettigar has made appropriate changes per darkmode guidelines?

2023-10-17 12:43 UTC, MohitGupta121 requested changes
@Vishwajith-Shettigar Thanks for PR, as I observed there is some inconsistency with background color of text and lock, so I recommend to keep the color of both lock background and text same for dark mode.
And let see that passing the accessibility scan.

<img width="492" alt="Screenshot 2023-10-17 at 6 10 59 PM" src="https://github.com/oppia/oppia-android/assets/76530270/e1315010-a247-4824-87bb-7870ebd30189">

@adhiamboperes what your suggestion on this inconsistency? 
<img width="489" alt="Screenshot 2023-10-17 at 6 12 54 PM" src="https://github.com/oppia/oppia-android/assets/76530270/613b5994-8212-4f57-9831-45782a187848">

2023-10-17 14:55 UTC, Vishwajith-Shettigar commented
> @Vishwajith-Shettigar Thanks for PR, as I observed there is some inconsistency with background color of text and lock, so I recommend to keep the color of both lock background and text same for dark mode. And let see that passing the accessibility scan.
> 
> <img alt="Screenshot 2023-10-17 at 6 10 59 PM" width="492" src="https://user-images.githubusercontent.com/76530270/275836043-e1315010-a247-4824-87bb-7870ebd30189.png">
> @adhiamboperes what your suggestion on this inconsistency? <img alt="Screenshot 2023-10-17 at 6 12 54 PM" width="489" src="https://user-images.githubusercontent.com/76530270/275836570-613b5994-8212-4f57-9831-45782a187848.png">


@MohitGupta121, PTAL.

![lockbackground](https://github.com/oppia/oppia-android/assets/76042077/9147686c-e573-4285-aced-0af599d68d67)

2023-10-17 15:07 UTC, MohitGupta121 approved these changes
@Vishwajith-Shettigar LGTM, Thanks!

2023-10-18 22:42 UTC, adhiamboperes approved these changes
Thanks @Vishwajith-Shettigar, LGTM.

2023-10-18 22:42 UTC, merged