Fix: #5186: MissingDefaultResource + AppCompatCustomView + FragmentTagUsage
oppia/oppia-android pull request #5191
Opened 2023-10-16 11:36 UTC by theMr17

## Explanation

Fixes #5186 [part of #5169]

1. `MissingDefaultResource` has been fixed already by https://github.com/oppia/oppia-android/pull/5172. It had issues with these plurals:
   -  [minutes_ago](https://github.com/oppia/oppia-android/blob/e060e2ff265ce35c92f1b969f6d7ad002d1a62ad/app/src/main/res/values/strings.xml#L456)
   - [hours_ago](https://github.com/oppia/oppia-android/blob/e060e2ff265ce35c92f1b969f6d7ad002d1a62ad/app/src/main/res/values/strings.xml#L461C18-L461C27)
   -  [days_ago](https://github.com/oppia/oppia-android/blob/e060e2ff265ce35c92f1b969f6d7ad002d1a62ad/app/src/main/res/values/strings.xml#L465C18-L465C26)

3. For `AppCompatCustomView`, it is fixed by replacing the Normal views with AppCompat views

4. `<fragment/>` tags are replaced with `<androidx.fragment.app.FragmentContainerView/>`, with some changes in the NavigationDrawerFragment to ensure that binding has been initialized before it is accessed.

## Screenshots
To be added.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).
<br>

2023-10-18 23:02 UTC, adhiamboperes requested changes
Thanks @theMr17!

Please add a video demonstrating that the navigation drawer behaves as expected with the initialization changes, for all the menu options.

2023-10-18 23:02 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragment.kt
> +    this.menuItemId = menuItemId
Could you please move this to the `navigationDrawerFragmentPresenter`, and please use databinding---initialize bindings for this particular layout and use it.

2023-12-05 08:45 UTC, theMr17 commented
@adhiamboperes PTAL

2023-12-05 10:46 UTC, adhiamboperes approved these changes
Thanks @theMr17, this LGTM!

2023-12-05 10:46 UTC, merged