Fixes #4708:
oppia/oppia-android pull request #5202
Opened 2023-10-20 15:05 UTC by Bontrey

## Explanation
Fixes #4708: Don't submit answer if it's invalid according to the input
or else after submitting the recycler view will not restore items on configuration change. See #4708 for more details

Video demo:
[before](https://drive.google.com/file/d/1bLgo-AYro0UbffR6X8nWo8Xv7oUuNJFa/view?usp=sharing)
[after](https://drive.google.com/file/d/1Oek7j6dgjJmgasyyd9FHtQo4E7zTvEBd/view?usp=sharing)

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

Not adding extra proof in this section since reviewer can tell that the change doesn't affect issues related to light mode, RTL, accessibility. Creating PR without running all the tests locally to get the CI result, as suggested in the issue

2023-10-23 16:11 UTC, Bontrey commented
@adhiamboperes PTAL

Seems like the checks passed

2023-10-23 16:14 UTC, Bontrey commented
Oops looks pressing 'rebase' to sync with repo head wiped the check results, and I don't see a historical record =/

2023-10-24 10:04 UTC, adhiamboperes requested changes
Thanks @Bontrey! and sorry for the delay in review here.

Since you force pushed this branch, we are not able to merge this PR directly (See [wiki](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR)). Can you please checkout your branch under a new name and resubmit the PR with the cahnges requested? You can close this one afterwards.

2023-10-24 10:04 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt
> +      }
The answer will never be null, since in [StateViewModel](https://github.com/oppia/oppia-android/blob/9cc5ec4533b160a39629c55f6ee434350d25f4df/app/src/main/java/org/oppia/android/app/player/state/StateViewModel.kt#L102), a default instance is always returned, so it might be useful to check that the return is not a default instance,.

2023-10-24 10:04 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt
> +      }
In your solution, you have modified the viewmodel function to be nullable, but I am concerned that you have not handled the null case.

2023-10-24 10:04 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt
> +  // Regression test for #4708.
Please remove comment

2023-10-24 10:04 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt
> +  fun testStateFragment_loadExp_secondState_invalidAnswer_changeConfiguration_submitButtonExists() {
```suggestion
  fun testStateFragment_loadExp_secondState_invalidAnswer_changeConfiguration_submitButtonIsEnabled() {
```

2023-10-24 11:06 UTC, Bontrey commented on app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt
> +      }
I don't know that there is anything else to do in the null case. There's already code elsewhere responsible for showing the error and disabling the submit button, for example.

So the handling of the null case here is just do to nothing, as far as I know.

2023-10-24 11:06 UTC, Bontrey commented on app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt
> +  // Regression test for #4708.
Ok will do in new PR

2023-10-24 11:06 UTC, Bontrey commented on app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt
> +  fun testStateFragment_loadExp_secondState_invalidAnswer_changeConfiguration_submitButtonExists() {
Ok will do in new PR

2023-10-24 11:27 UTC, Bontrey commented
Continuing at #4708

2023-10-24 11:27 UTC, closed without merging