Fix oppia#4760 In Terms of Service the website should be displayed as link and should be clickable
oppia/oppia-android pull request #5206
Opened 2023-10-24 14:26 UTC by Tejas-67

## Explanation
Fix #4760 In Terms of Service the website should be displayed as link and should be clickable

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-10-24 15:01 UTC, adhiamboperes requested changes
Thanks @Tejas-67!

I will take a deep dive into your solution later, but for now, there are PR-specific items for you to fix. Please see this [wiki section](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR) on submitting PRs, and also take a look at the Essential checklist on this PR.
1. branch name should not be develop
2. android studio, idea or git related files that change configs should be excluded from the PR.
3. PR description will include an explanation of the fix that you are implemenating(What you changed and why)
4. Please sign the CLA as instructed

Overall, please check out your code to a new branch not called develop, and create a new PR to replace this one.

2023-10-24 15:01 UTC, adhiamboperes commented on gradle.properties
Please remove this from the PR

2023-10-24 15:01 UTC, adhiamboperes commented on app/src/main/res/values/terms_of_service.xml
> +    <br>
Could you explain why you modified this file? Ditto the privacy_policy.xml above.

2023-10-24 15:01 UTC, adhiamboperes commented on .gitignore
Remove this file

2023-10-24 16:48 UTC, Tejas-67 commented on gradle.properties
okay!

2023-10-24 16:49 UTC, Tejas-67 commented on app/src/main/res/values/terms_of_service.xml
> +    <br>
The <br> tags were added to ensure the correct space formatting between the different sections of the pages.

2023-10-24 16:49 UTC, Tejas-67 commented on .gitignore
okay

2023-10-24 16:51 UTC, closed without merging

2023-10-26 10:57 UTC, adhiamboperes commented
@Tejas-67, I have noticed you have not created a replacement PR for this. Are you experiencing any issues?

2023-10-27 17:17 UTC, Tejas-67 commented
@adhiamboperes  hey, sorry for the delay. I am having my exams hence will be raising a PR in some days.