Fix #5032 [BUG]: Images in Arabic (RTL) lessons are right-aligned rather than center-aligned.
oppia/oppia-android pull request #5212
Opened 2023-10-28 10:05 UTC by Vishwajith-Shettigar

## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-10-29 05:06 UTC, Vishwajith-Shettigar commented
@adhiamboperes, PTAL

2023-10-31 11:59 UTC, adhiamboperes requested changes
Thanks @Vishwajith-Shettigar! This is a really interesting solution.

2023-10-31 11:59 UTC, adhiamboperes commented on utility/src/main/java/org/oppia/android/util/parser/image/UrlImageParser.kt
> +        }
Could you move this function outside of computeBounds(), but  keep it still within the BlockImageTarget class? The function could also be private to the class.

2023-10-31 12:49 UTC, Vishwajith-Shettigar commented on utility/src/main/java/org/oppia/android/util/parser/image/UrlImageParser.kt
> +        }
I made changes, PTAL.
Thank you

2023-10-31 12:53 UTC, adhiamboperes approved these changes
Thanks @Vishwajith-Shettigar! This LGTM.

2023-10-31 15:56 UTC, merged