Fix #3345 Images are not fully displayed
oppia/oppia-android pull request #5234
Opened 2023-11-17 10:48 UTC by Vishwajith-Shettigar

## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-11-17 10:59 UTC, Vishwajith-Shettigar commented
@adhiamboperes, PTAL

2023-11-20 23:57 UTC, adhiamboperes requested changes
Thanks @Vishwajith-Shettigar. This is fantastic! 

Some general points:

- [ ] Can you please confirm that these two images display the same way in the before? Confirming distortion.

|||
|---|---|
|![Screenshot_1700522031](https://github.com/oppia/oppia-android/assets/59600948/94593c55-6378-431b-a8ea-90ec1bf4b967)|![Screenshot_1700522887](https://github.com/oppia/oppia-android/assets/59600948/7c78273f-1c20-4bf2-ae8f-5f7c17de597e)|


- [ ] You can make it easier to do a side by side comparison of your before/after screenshots by using a markdown table like I have used here. See: https://www.tablesgenerator.com/markdown_tables.

- [ ] The last screensot of the bakery in your screenshots does not seem related to this issue.

2023-11-20 23:57 UTC, adhiamboperes commented on utility/src/main/java/org/oppia/android/util/parser/image/UrlImageParser.kt
> +        drawableWidth-=maxContentItemPadding
Nit: Please format code.

2023-11-21 10:34 UTC, Vishwajith-Shettigar commented on utility/src/main/java/org/oppia/android/util/parser/image/UrlImageParser.kt
> +        drawableWidth-=maxContentItemPadding
okay

2023-11-21 10:37 UTC, Vishwajith-Shettigar commented
> Thanks @Vishwajith-Shettigar. This is fantastic!
> 
> Some general points:
> 
> * [ ]  Can you please confirm that these two images display the same way in the before? Confirming some apparent distortion.
> 
> ![Screenshot_1700522031](https://user-images.githubusercontent.com/59600948/284420868-94593c55-6378-431b-a8ea-90ec1bf4b967.png)	![Screenshot_1700522887](https://user-images.githubusercontent.com/59600948/284420896-7c78273f-1c20-4bf2-ae8f-5f7c17de597e.png)
> * [ ]  You can make it easier to do a side by side comparison of your before/after screenshots by using a markdown table like I have used here. See: https://www.tablesgenerator.com/markdown_tables.
> * [ ]  The last screenshot of the bakery in your screenshots does not seem related to this issue.

The bakery screenshot is takes in RTL, referencing [this issue](https://github.com/oppia/oppia-android/issues/5032)

2023-11-21 10:44 UTC, Vishwajith-Shettigar commented
| Before  | After  |  
|---|---|
| ![newbefore](https://github.com/oppia/oppia-android/assets/76042077/aa45d911-800b-4d83-ad48-c5ba3cc04967)|![newafter](https://github.com/oppia/oppia-android/assets/76042077/0abda00b-599d-4721-86d6-53b61594c0eb)|
|![new2before](https://github.com/oppia/oppia-android/assets/76042077/29d30476-bfde-4ca6-b335-10369d258b93) | ![new2after](https://github.com/oppia/oppia-android/assets/76042077/194f2844-f4a3-4bff-afd3-082442f0605e)|

2023-11-21 10:45 UTC, Vishwajith-Shettigar commented
> Before	After
> ![newbefore](https://user-images.githubusercontent.com/76042077/284550158-aa45d911-800b-4d83-ad48-c5ba3cc04967.png)	![newafter](https://user-images.githubusercontent.com/76042077/284550296-0abda00b-599d-4721-86d6-53b61594c0eb.png)
> ![new2before](https://user-images.githubusercontent.com/76042077/284550510-29d30476-bfde-4ca6-b335-10369d258b93.png)	![new2after](https://user-images.githubusercontent.com/76042077/284550541-194f2844-f4a3-4bff-afd3-082442f0605e.png)

@adhiamboperes, PTAL.

2023-11-21 23:38 UTC, adhiamboperes approved these changes
Thanks @Vishwajith-Shettigar! I think the latest changes look good. 

I would suggest however updating the PR description to explain your solution, before we merge the PR.

2023-11-22 01:52 UTC, Vishwajith-Shettigar commented
@adhiamboperes, PTAL, PR description updated.

2023-11-22 11:59 UTC, merged