Fix #3384 : Arrange strings file
oppia/oppia-android pull request #5236
Opened 2023-11-18 12:54 UTC by MohitGupta121

## Explanation

Fix #3384 : Arrange strings file

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-11-19 07:31 UTC, MohitGupta121 commented on app/src/main/res/values/strings.xml
@adhiamboperes PTAL, please pass your 1st review on this PR, Thanks!

2023-11-22 14:13 UTC, adhiamboperes requested changes
Thanks @MohitGupta121! I took a first pass to verify the general patterns that we had agreed on. There are some small changes needed.

Additionally, can we move **GeneralStrings** and **SharedStrings** sections to the bottom of the strings files, so that the screen based sections come first?

Lastly, please update the PR description as discussed.

2023-11-22 14:13 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="admin_auth_activity_controls_subject_text">Enter the Administrator PIN in order to access Administrator Controls.</string>
Why the word _subject_ here? Could we use subheading instead?

2023-11-22 14:13 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="administrator_controls_fragment_profile_management_text">Profile Management</string>
I think this was meant to be `_label`, based on 
```suggestion
  <string name="administrator_controls_fragment_profile_management_label">Profile Management</string>
```
![Screenshot_1700660844](https://github.com/oppia/oppia-android/assets/59600948/dcbc8526-ce32-4e1b-87c6-40cc7bc07ffa)

2023-11-22 14:13 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="administrator_controls_fragment_topic_update_on_wifi_text">Download and update only on Wi-fi</string>
Please confirm that these are named **label** or **text** based on their correct usages.

2023-11-22 14:13 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="administrator_controls_fragment_log_out_text">Log Out</string>
This section looks like it should be moved up to be below the `AdministratorControlActivity` section.

2023-11-22 14:13 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="add_profile_activity_text">Add Profile</string>
I think this is the activity title, please rename accroding to the expected pattern

2023-11-22 14:13 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="admin_settings_dialog_subject_text">Administrator\'s PIN required to change user\'s PIN</string>
```suggestion
  <string name="admin_settings_dialog_message_text">Administrator\'s PIN required to change user\'s PIN</string>
```

2023-11-22 14:13 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="concept_card_test_activity_two_button_text">Concept Card 2</string>
```suggestion
  <string name="concept_card_test_activity_button_one_text">Concept Card 1</string>
  <string name="concept_card_test_activity_button_two_text">Concept Card 2</string>
```

2023-11-28 16:10 UTC, MohitGupta121 commented on app/src/main/res/values/strings.xml
> +  <string name="administrator_controls_fragment_topic_update_on_wifi_text">Download and update only on Wi-fi</string>
`administrator_controls_fragment_edit_profiles_text` & `administrator_controls_fragment_topic_update_on_wifi_text` are **Text** but as per your above screenshot `administrator_controls_fragment_download_permissions_text` is **Label**

2023-11-28 16:23 UTC, MohitGupta121 commented on app/src/main/res/values/strings.xml
> +  <string name="admin_auth_activity_controls_subject_text">Enter the Administrator PIN in order to access Administrator Controls.</string>
Done.

2023-11-28 16:23 UTC, MohitGupta121 commented on app/src/main/res/values/strings.xml
> +  <string name="administrator_controls_fragment_profile_management_text">Profile Management</string>
Done.

2023-11-28 16:23 UTC, MohitGupta121 commented on app/src/main/res/values/strings.xml
> +  <string name="administrator_controls_fragment_topic_update_on_wifi_text">Download and update only on Wi-fi</string>
Done.

2023-11-28 16:23 UTC, MohitGupta121 commented on app/src/main/res/values/strings.xml
> +  <string name="administrator_controls_fragment_log_out_text">Log Out</string>
Done.

2023-11-28 16:23 UTC, MohitGupta121 commented on app/src/main/res/values/strings.xml
> +  <string name="add_profile_activity_text">Add Profile</string>
Done.

2023-11-28 16:24 UTC, MohitGupta121 commented on app/src/main/res/values/strings.xml
> +  <string name="admin_settings_dialog_subject_text">Administrator\'s PIN required to change user\'s PIN</string>
Done.

2023-11-28 16:24 UTC, MohitGupta121 commented on app/src/main/res/values/strings.xml
> +  <string name="concept_card_test_activity_two_button_text">Concept Card 2</string>
Done.

2023-12-01 03:33 UTC, MohitGupta121 commented
Deleting this PR because of unnecessary commit history.

2023-12-01 03:33 UTC, closed without merging