Fixing Audio Tests
oppia/oppia-android pull request #5245
Opened 2023-11-25 02:49 UTC by theMr17

## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-11-28 09:01 UTC, adhiamboperes commented
@theMr17, could you please walk me through the solution that you are trying to achieve in this PR?

2023-11-29 02:45 UTC, theMr17 commented
@adhiamboperes, By this PR, I am trying to figure out exactly why the tests are failing in https://github.com/oppia/oppia-android/issues/2480 and finding a fix a for it.

2023-12-04 13:32 UTC, adhiamboperes requested changes
@theMr17, this was not assigned to me, so I'm not sure it is ready for review, but I took a look anyway. 

The tests look good, with one minor comment.

Please also update the PR explanation with what you identified the problem as, and the fix you applied.

2023-12-04 13:32 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
> +  // @Ignore("The ExplorationActivity takes time to finish, needs to fixed in #89.")
Do remove the comment

2023-12-07 08:38 UTC, theMr17 commented
@adhiamboperes PTAL

2023-12-07 09:20 UTC, adhiamboperes requested changes

2023-12-07 09:20 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
> +      onView(withText("What is a Ratio?"))
Whats the purpose of this? No assertion is being performed on the view. Same as in the test below.

2023-12-07 09:31 UTC, theMr17 commented on app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
> +      onView(withText("What is a Ratio?"))
I have added assertion to it now. It checks for _"audioFragHasDefaultLang"_. And removed the line from the test below

2023-12-07 22:38 UTC, adhiamboperes approved these changes
Thanks @theMr17! This LGTM.

2023-12-07 23:30 UTC, merged