Fix part of #5070: Display empty answer message in ratio input interaction
oppia/oppia-android pull request #5263
Opened 2023-12-08 06:40 UTC by theMr17

## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2023-12-11 10:58 UTC, adhiamboperes commented
@theMr17 is this ready for a full pass or are you looking for a preliminary review on approach? Please convert to ready and assign to me if the former.

2023-12-11 11:53 UTC, theMr17 commented
@adhiamboperes, please do a preliminary review of the approach. I will proceed to write tests after that.

2023-12-14 09:42 UTC, adhiamboperes requested changes
@theMr17, I have left some suggestions, but the overall approach looks good to me.

2023-12-14 09:42 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/RatioExpressionInputInteractionViewModel.kt
> +            true
Maybe add a comment explaining why this is `true`.

2023-12-14 09:42 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/RatioExpressionInputInteractionViewModel.kt
> +      true
can you add here the argument names so it is clear what is null/true, so that your code is self-documenting.

2023-12-14 09:42 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="ratio_error_empty_input">Enter a ratio to continue</string>
```suggestion
  <string name="ratio_error_empty_input">Enter a ratio to continue.</string>
```

2023-12-17 05:35 UTC, theMr17 commented
@adhiamboperes PTAL

2023-12-18 08:24 UTC, adhiamboperes approved these changes
Thanks @theMr17! This LGTM. 

Thanks for moving the ratio tests to their own suite as well.

2024-01-03 21:29 UTC, adhiamboperes commented
@BenHenning, this PR is blocked on codeowner, PTAL.

2024-01-09 17:26 UTC, BenHenning requested changes
Thanks @theMr17! Really sorry about the late review here. I just had two small comments, otherwise the PR LGTM.

2024-01-09 17:26 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/testing/RatioInputInteractionViewTestActivityTest.kt
> +      Truth.assertThat(pendingAnswer.answer).isInstanceOf(InteractionObject::class.java)
Please directly import assertThat (for consistency with other tests and per Truth convention).

2024-01-09 17:26 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/testing/RatioInputInteractionViewTestActivityTest.kt
> +    Espresso.onView(ViewMatchers.withId(R.id.test_ratio_input_interaction_view))
Espresso functions like onView & others should also be directly imported. Ditto for ViewMatchers, ViewAssertions, and ViewActions.

2024-01-11 12:33 UTC, theMr17 commented
@BenHenning PTAL

2024-01-11 23:03 UTC, BenHenning approved these changes
Thanks @theMr17! Please make sure to respond to addressed comments on future PRs. Otherwise the PR LGTM.

2024-01-11 23:03 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/testing/RatioInputInteractionViewTestActivityTest.kt
> +    Espresso.onView(ViewMatchers.withId(R.id.test_ratio_input_interaction_view))
This has been resolved in the latest changes.

2024-01-11 23:03 UTC, BenHenning commented on app/src/sharedTest/java/org/oppia/android/app/testing/RatioInputInteractionViewTestActivityTest.kt
> +      Truth.assertThat(pendingAnswer.answer).isInstanceOf(InteractionObject::class.java)
This has been resolved in the latest changes.

2024-01-11 23:03 UTC, merged

2024-01-12 02:03 UTC, theMr17 commented
> Thanks @theMr17! Please make sure to respond to addressed comments on future PRs. Otherwise the PR LGTM.

Thanks @BenHenning, I will surely keep that in mind.