Fixed #2652
oppia/oppia-android pull request #5265
Opened 2023-12-10 07:50 UTC by Cyclotron17

[untitled.webm](https://github.com/oppia/oppia-android/assets/105651436/60d22db7-2dbb-418e-85fa-cd6cf4164342)

[6inch.webm](https://github.com/oppia/oppia-android/assets/105651436/e4b983e0-8e9f-45d0-ab83-29f632299617)

Resolved the Streched Splash Screen issue in both mobile phones of sizes 6 inches or more and on Tablets, added the bazel dependency as well , please review it once.

earlier the splash screen use to look like this
![oppia_earlier](https://github.com/oppia/oppia-android/assets/105651436/91b35d1b-e9c1-40f3-af65-9e9ee094f98d)

2023-12-11 10:56 UTC, adhiamboperes requested changes
Thanks @Cyclotron17!

In addition to the comments I have left inline, I have noticed that you haven't added the bazel dependency in the project.

The library needs to be added to bazel as well as gradle. Please follow [this wiki](https://github.com/oppia/oppia-android/wiki/Updating-Maven-Dependencies) to add a dependency to bazel. Here is a commit that shows an example of what is expected when adding a new dependency to bazel: https://github.com/oppia/oppia-android/commit/c85a6e6e4c0a2b32cf9da5b94bf09e1109ec981e.

Please ask a question for any clarifications needed.

2023-12-11 10:56 UTC, adhiamboperes commented on app/build.gradle
> +      //Sambhrant Tiwari
Please remove the comment. All attributions are handled by git when you make a commit with your username.

2023-12-11 10:56 UTC, adhiamboperes commented on app/build.gradle
> +     'com.intuit.sdp:sdp-android:1.0.5'
I think adding the sdp lib only is sufficient, and there is a newer version, 'com.intuit.sdp:sdp-android:1.1.0',

2023-12-11 10:56 UTC, adhiamboperes commented on app/src/main/res/layout/splash_activity.xml
> +      android:layout_height="@dimen/height_88dp"
```suggestion
      android:layout_width="@dimen/splash_imageview_width"
      android:layout_height="@dimen/splash_imageview_height"
```

2023-12-11 10:56 UTC, adhiamboperes commented on app/src/main/res/values/dimens.xml
> +  <dimen name="height_88dp">88dp</dimen>
This file is organized according to screen name, kindly add splash screen related dimens under the relevant category, or create one if it does not exist. Please stick to the patterns in the file.

Additionally, Your dimensions are in **dp**, contrary to the fix you proposed in https://github.com/oppia/oppia-android/issues/2652#issuecomment-1847579110.

Just adding the dependency and not using it does not fix the issue.

2023-12-12 21:39 UTC, Cyclotron17 commented
Sure thing, will make the required changes and re raise the PR.

2024-01-04 06:57 UTC, closed without merging