Fix #5143: Update Robolectric to 4.7
oppia/oppia-android pull request #5326
Opened 2024-01-31 05:35 UTC by sandy99405

## Explanation

According to issue #5143, there was an error ```unexpected element <queries> found in <manifest>``` during the Bazel build.
That issue has been resolved in this PR.

1) #### Robolectric version has been changed to 4.7 and espresso-core to 3.5.0-alpha03 in every build.gadle file

2) #### In scripts/assets folder, the maven_dependencies.textproto file has been changed due to an exception.

### This is the Bazel output after updating the Robolectric to 4.7 and maven_install
![image](https://github.com/oppia/oppia-android/assets/55664068/54f2f3cf-70ed-4d4b-a5f6-53a4af69d699)

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2024-02-06 13:43 UTC, sandy99405 commented
Hi @adhiamboperes, do you want me to create another PR or solve what's in this PR? Please confirm

2024-02-06 14:17 UTC, adhiamboperes commented
> Hi @adhiamboperes, do you want me to create another PR or solve what's in this PR? Please confirm

I'm still in the process of reviewing the PR. I will leave my full feedback and assign it back to you.

2024-02-06 17:42 UTC, sandy99405 commented
Sure, thank you :)

2024-02-08 08:06 UTC, adhiamboperes requested changes
Thanks @sandy99405!

To address the comments that I have left, please create a new PR. Make sure your branch name is not called "develop", because it is prohibited. Read the PR essential checklist carefully.

We have a wiki page for reading the CI results to help you debug: https://github.com/oppia/oppia-android/wiki/Interpreting-CI-Results

And finally to run the bazel tests locally, follow the instructions here: https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions. Please note the you can also run one test class at a time.

2024-02-08 08:06 UTC, adhiamboperes commented on app/build.gradle
> -      'org.robolectric:annotations:4.5',
Please check the CI logs, you will see that building with gradle fails with:

`Caused by: java.lang.RuntimeException: Failed to transform '/root/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.68/46a080368d38b428d237a59458f9bc915222894d/bcprov-jdk15on-1.68.jar' using Jetifier. Reason: Unsupported class file major version 59. (Run with --stacktrace for more details.)`

Please refer to the following for an explanation and a fix: issue with [gradle plugin](https://issuetracker.google.com/issues/159151549#comment12), [jetifier](https://issuetracker.google.com/issues/159151549#comment13) and [robolectric](https://github.com/robolectric/robolectric/issues/6521), [this comment](https://issuetracker.google.com/issues/159151549#comment14) and [this other one](https://issuetracker.google.com/issues/159151549#comment12).

2024-02-08 08:06 UTC, adhiamboperes commented on third_party/versions.bzl
> +    "org.robolectric:robolectric": "4.7",
In the bazel test failure logs, I could still see that it fails with the error mentioned in the issue.

Could I propose that you test this PR by running some tests in bazel and see if it is reproducible? If say the tests always pass on your machine, we could look into the platform.

From the bazel logs, I saw that the issue is similar to this one: https://github.com/bazelbuild/rules_android/issues/39, and one of the test runs fails because of the DrawableBindingAdapters.kt. You will need to verify from the CI logs if this particular class is the cause of all the test failures, and figure out why.

2024-02-22 08:47 UTC, closed without merging