Fix #2536: Introduce a central utility for matching item in RecyclerView
oppia/oppia-android pull request #5391
Opened 2024-04-28 12:42 UTC by deonwaju

## Explanation

I worked on the below functions renaming the title and adding an argument for the recyclerviewId to each function to make it reusable, I also added kdocs to help understand the functions.
P.S:- I created the functions in the RecyclerviewMatcher class.
 
![Screenshot 2024-04-28 at 13 38 40](https://github.com/oppia/oppia-android/assets/54560535/febec71a-6865-4bc6-8b6b-8e24029161de)

![Screenshot 2024-04-28 at 13 38 28](https://github.com/oppia/oppia-android/assets/54560535/e1a01108-2a56-4ba3-bdbe-70182daf412f)

![Screenshot 2024-04-28 at 13 38 14](https://github.com/oppia/oppia-android/assets/54560535/92fea2f0-f01e-46e5-9a7a-e2ae9d3526f0)

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

2024-04-30 00:30 UTC, deonwaju commented
PTAL @adhiamboperes

2024-05-08 12:46 UTC, adhiamboperes requested changes
Thanks @deonwaju!

Juat one minor comment but the rest LGTM.

2024-05-08 12:46 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/recyclerview/RecyclerViewMatcher.kt
> +      ).check(ViewAssertions.doesNotExist())
Directly import ViewAssertions so that it is cleaner.
```suggestion
      ).check(doesNotExist())
```

2024-05-08 14:00 UTC, deonwaju commented
PTAL @adhiamboperes

2024-05-08 15:19 UTC, adhiamboperes approved these changes
LGTM, thanks @deonwaju.

2024-05-08 15:19 UTC, merged