Fix #5404 : Migrate onBackPressed
oppia/oppia-android pull request #5427
Opened 2024-06-18 13:46 UTC by Tejas-67

## Explanation
For devices running on API 33 or above, onBackPressedDispatcher doesn't work, hence we need to use onBackInvokeDispatcher.

In the app:manifest,
`<application android:enableOnBackInvokedCallback="true"/>`
has been added so that the onBackInvokedDispatcher works.

- [x]  app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity
- [ ]  app/src/main/java/org/oppia/android/app/administratorcontrols/appversion/AppVersionActivity
- [ ]  app/src/main/java/org/oppia/android/app/administratorcontrols/learneranalytics/ProfileAndDeviceIdActivity
- [ ]  app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedActivity
- [ ]  app/src/main/java/org/oppia/android/app/devoptions/markstoriescompleted/MarkStoriesCompletedActivity
- [ ]  app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/MarkTopicsCompletedActivity
- [ ]  app/src/main/java/org/oppia/android/app/options/ReadingTextSizeActivityPresenter
- [ ]  app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivityPresenter
- [ ]  app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter
- [x]  app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivity
- [x]  app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivityPresenter
- [ ]  app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerActivityPresenter
- [ ]  app/src/main/java/org/oppia/android/app/walkthrough/end/WalkthroughFinalFragmentPresenter

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2024-06-19 13:58 UTC, Tejas-67 commented
@adhiamboperes please check. If this is alright then I would proceed with the others as well.

2024-06-20 14:11 UTC, adhiamboperes requested changes
Thanks @Tejas-67!

The main comment is to use `onBackPressedDispatcher.addCallback()` for backward comaptibility.

I would also encourage handling the back press in a function that you can call, that will remove the need to move code from the presenter to activity or fragment in some cases.

2024-06-20 14:11 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt
> +      onBackInvokedDispatcher.registerOnBackInvokedCallback(1000) {
This needs to be a constant, e.g. `OnBackInvokedDispatcher.PRIORITY_DEFAULT`

2024-06-20 14:11 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivityPresenter.kt
> +  }
Why is this needed? It does not appear to be in use.

2024-06-20 14:11 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt
> +    } else {
I propose removing this bit of the onBackInvokedDispatcher.registerOnBackInvokedCallback() and remaining with the part that is under "else".

According to the documentation, https://developer.android.com/reference/android/app/Activity#onBackPressed(), `onBackPressedDispatcher.addCallback()` is backward compatible, eliminating the need to gate the logic with the sdk version.

2024-06-20 14:11 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivity.kt
> +      }
Same comment regarding gating sdk

2024-06-20 14:11 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivity.kt
>    }
We can improve readability by putting this in a function.
```suggestion
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    ....
    handleBackPress()
  }

  private fun handleBackPress() {
    onBackPressedDispatcher.addCallback(
      this@AdministratorControlsActivity, object : OnBackPressedCallback(true) {
        override fun handleOnBackPressed() {
          val fragment =
            supportFragmentManager.findFragmentById(
              R.id.administrator_controls_fragment_multipane_placeholder
            )
          /*
           * If the current fragment is ProfileListFragment then the activity should end on back press.
           * If it's instead ProfileEditFragment then profileListFragment should be inflated via
           * handleOnBackPressed.
           */
          if (fragment is ProfileEditFragment) {
            administratorControlsActivityPresenter.handleOnBackPressed()
          } else {
            isEnabled = false
            onBackPressedDispatcher.onBackPressed()
            isEnabled = true
          }
        }
      })
  }
```

2024-06-20 14:11 UTC, adhiamboperes commented on app/src/main/AndroidManifest.xml
> +    android:enableOnBackInvokedCallback="true"
This is not needed as far as I can tell.

2024-06-27 18:06 UTC, Tejas-67 commented
hey @adhiamboperes, I have migrated the activities, but facing problem in the WalkthroughFinalFragmentPresenter. Even after setting up the onBackPressedDispatcher in the WalkthroughFinalActivity, I am unable to get the reference of the onBackPressedDispatcher in the Presenter. how can i fix this?

2024-06-27 18:54 UTC, adhiamboperes commented
> hey @adhiamboperes, I have migrated the activities, but facing problem in the WalkthroughFinalFragmentPresenter. Even after setting up the onBackPressedDispatcher in the WalkthroughFinalActivity, I am unable to get the reference of the onBackPressedDispatcher in the Presenter. how can i fix this?

Could you please share a screenshot of your implementation so that I can understand your issue better?

2024-07-04 11:26 UTC, Vishwajith-Shettigar commented
Hi @Tejas-67, could you please provide an update on your progress? If you are facing any blockers, let us know. Kindly attach all the relevant details and push the code that is not working, so we can have a clearer understanding of the issues.

2024-07-04 13:36 UTC, Tejas-67 commented
hey @Vishwajith-Shettigar ,  I am done with the WalkthroughFinalPresenter as well. But I am facing this error while pushing. 
`buf_lint_check.sh: line 13: ../oppia-android-tools/buf-Darwin-x86_64: No such file or directory
********************************
Protobuf lint check issues found. Please fix them before pushing your code.
********************************
` . Any idea on how to fix this?

2024-07-04 14:33 UTC, Vishwajith-Shettigar commented
`Protobuf lint check issues found. Please fix them before pushing your code.`

Since I'm a Windows user, I never encountered this (this lint check doesn't support Windows, I assume), but I can see you may have made changes in protobuf files. If so, check for lint issues. But I don't have a clue about this (maybe you missed some commands while setting up oppia-android) `buf_lint_check.sh: line 13: ../oppia-android-tools/buf-Darwin-x86_64: No such file or directory.`

@adhiamboperes may help you!

2024-07-04 20:57 UTC, adhiamboperes commented
@Tejas-67 Could you please confirm that you have the `android-tools` directory?

<img width="924" alt="Screenshot 2024-07-04 at 23 56 13" src="https://github.com/oppia/oppia-android/assets/59600948/08d60f67-d568-4b9c-b3e8-1297c3fd79e8">

2024-07-07 11:54 UTC, Tejas-67 commented
@adhiamboperes I have the oppia-android-tools folder already, but i have buf-Darwin-arm64 instead of buf-Darwin-x86_64 .

2024-07-07 12:40 UTC, adhiamboperes commented
> @adhiamboperes I have the oppia-android-tools folder already, but i have buf-Darwin-arm64 instead of buf-Darwin-x86_64 .


Do you use intel Mac or M1/M2

2024-07-07 14:14 UTC, Tejas-67 commented
@adhiamboperes , M2

2024-07-21 15:00 UTC, closed without merging