Change profile id defaulting to invalid profile
oppia/oppia-android pull request #5482
Opened 2024-08-08 15:53 UTC by MohitGupta121

## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2024-08-13 06:23 UTC, MohitGupta121 reviewed
@adhiamboperes PTAL, can you please do inital review pass, so that I get clear idea before proceed towards tests. Thanks!

2024-08-19 10:35 UTC, adhiamboperes requested changes
Thanks @MohitGupta121!

I have looked at the highlevel solution but not done a full review yet. Please see comments inline. Additionally,  please make sure you correct all the instances  where internal id is currently set to -1.

2024-08-19 10:35 UTC, adhiamboperes commented on model/src/main/proto/profile.proto
> +  }
Please format comments correctly based on what the rest of this file comments look like.

2024-08-19 10:35 UTC, adhiamboperes commented on model/src/main/proto/profile.proto
> -  int32 internal_id = 1;
Instead of deleting this, mark it as reserved.

2024-08-19 10:35 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/classroom/ClassroomListActivity.kt
> +  private lateinit var internalProfileId: ProfileId
Variable name should not be `internalProfileId` if the object is of type `ProfileId`.

2024-08-19 10:35 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/classroom/ClassroomListActivity.kt
> +        .setProfileId(
Why not just directly add the profileId object from above? This is redundant.

2024-08-19 10:35 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentPresenter.kt
>      administratorControlsViewModel.setProfileId(profileId)
```suggestion
    profileId = activity.intent.extractCurrentUserProfileId()
    administratorControlsViewModel.setProfileId(profileId)
```

2024-08-19 10:35 UTC, adhiamboperes commented on domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt
> +private val DEFAULT_LOGGED_OUT_PROFILE_ID = ProfileId.newBuilder().setLoggedOut(true).build()
Semantically more correct now:
```suggestion
private val LOGGED_OUT_PROFILE_ID = ProfileId.newBuilder().setLoggedOut(true).build()
```

2024-08-25 11:44 UTC, MohitGupta121 commented on model/src/main/proto/profile.proto
> +  }
Done.

2024-08-25 11:53 UTC, MohitGupta121 commented on model/src/main/proto/profile.proto
> -  int32 internal_id = 1;
Done!

2024-08-25 12:03 UTC, MohitGupta121 commented on app/src/main/java/org/oppia/android/app/classroom/ClassroomListActivity.kt
> +  private lateinit var internalProfileId: ProfileId
Done.

2024-08-25 12:10 UTC, MohitGupta121 commented on app/src/main/java/org/oppia/android/app/classroom/ClassroomListActivity.kt
> +        .setProfileId(
Done.

2024-08-25 12:12 UTC, MohitGupta121 commented on app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentPresenter.kt
>      administratorControlsViewModel.setProfileId(profileId)
Done, Thanks! I missed

2024-08-25 12:13 UTC, MohitGupta121 commented on domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt
> +private val DEFAULT_LOGGED_OUT_PROFILE_ID = ProfileId.newBuilder().setLoggedOut(true).build()
Done.

2024-08-25 12:24 UTC, MohitGupta121 reviewed
@adhiamboperes updated PTAL, Thanks!

2024-08-26 09:40 UTC, adhiamboperes commented
@MohitGupta121, please reasign PR once fully ready for review.

2024-09-03 01:50 UTC, adhiamboperes commented
@MohitGupta121, are you blocked on this PR?

2024-09-03 03:02 UTC, MohitGupta121 commented
> @MohitGupta121, please reasign PR once fully ready for review.

I missed this message, NO I'm not blocked.

2024-09-09 20:53 UTC, adhiamboperes commented
@MohitGupta121, is this PR blocked?

2024-11-21 06:49 UTC, closed without merging