Fix part of #5404: Migrate away from onBackPressed
oppia/oppia-android pull request #5521
Opened 2024-08-26 15:32 UTC by dattasneha

## Explanation

Fixes part of #5404 
## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2024-08-29 09:52 UTC, dattasneha commented
Hi,@adhiamboperes PTAL.

2024-08-30 12:34 UTC, adhiamboperes requested changes
Thanks @dattasneha! I have a couple of comments, PTAL.

2024-08-30 12:34 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt
> +  private fun handleTheOnBackPressed() {
```suggestion
  private fun handleBackPress() {
```

2024-08-30 12:34 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt
> +      finish()
When you finish the current activity, does it go back to the previous expected activity?

2024-08-30 14:59 UTC, dattasneha commented on app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt
> +  private fun handleTheOnBackPressed() {
Done, updated the function name.

2024-08-30 14:59 UTC, dattasneha commented on app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt
> +      finish()
Yes, I have run and tested all the files in the PR to verify if, when the current activity is finished, it correctly returns to the previous expected activity, except for `ReadingTextSizeActivity`  in the options package as I could not find the Activity in the app's Options navigation menu.

2024-08-30 15:34 UTC, dattasneha commented
@adhiamboperes PTAL. Also, should I work on the remaining activities as well, since the other PR seems to be inactive?

2024-09-02 13:15 UTC, adhiamboperes commented
> @adhiamboperes PTAL. Also, should I work on the remaining activities as well, since the other PR seems to be inactive?

Thanks, once this PR is merged, please feel free to create a new one with the remaining activities.

2024-09-02 22:54 UTC, adhiamboperes commented
@dattasneha PTAl at failing lint check.

2024-09-04 12:16 UTC, dattasneha commented
@adhiamboperes PTAL.

2024-09-05 07:38 UTC, adhiamboperes commented
Thanks @dattasneha. The cahnges look good, but will take another look once CI passes.

2024-09-05 12:25 UTC, dattasneha commented
> > @adhiamboperes PTAL. Also, should I work on the remaining activities as well, since the other PR seems to be inactive?
> 
> Thanks, once this PR is merged, please feel free to create a new one with the remaining activities.

Thanks. I have created a new PR for the remaining activities.

2024-09-11 10:05 UTC, adhiamboperes approved these changes
LGTM, thanks @dattasneha!

2024-09-15 14:29 UTC, dattasneha commented
Hi, @adhiamboperes, is there anything else needed to be done by me on this PR ?

2024-09-19 08:35 UTC, merged