Feature Request part1 #5485 Create means for verifying Fragment Arguments
oppia/oppia-android pull request #5522
Opened 2024-08-26 17:05 UTC by subhajitxyz

## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2024-08-30 02:35 UTC, theMr17 commented
@subhajitxyz per discussion through chat, some checks were canceled, possibly due to closing and reopening the PR. I have re-run the checks, and everything seems to be fine now.

2024-08-30 02:40 UTC, subhajitxyz commented
Thanks @theMr17 .

2024-08-30 02:41 UTC, subhajitxyz commented
@adhiamboperes, PTAL.

2024-09-02 13:05 UTC, adhiamboperes requested changes
Thanks @subhajitxyz! 

The implementation looks good to. My only suggestion is to refactoor the test names to follow the pattern in my suggestion.

2024-09-02 13:05 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt
> +  fun testMarkChaptersCompletedFragment_arguments_workingProperly() {
Rename this and other tests to be more descriptive.
```suggestion
  fun testFragment_fragmentLoaded_verifyCorrectArgumentsPassed() {
```

2024-09-02 13:11 UTC, subhajitxyz commented on app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt
> +  fun testMarkChaptersCompletedFragment_arguments_workingProperly() {
Ok

2024-09-03 16:47 UTC, subhajitxyz commented on app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt
> +  fun testMarkChaptersCompletedFragment_arguments_workingProperly() {
Done.

2024-09-03 18:00 UTC, subhajitxyz commented
Hi @theMr17, Could you please take a look at why ExplorationActiveTimeControllerTest > testSessionTimer_explorationStarted_appInBackground_pausesSessionTimer FAILED ??

2024-09-04 15:16 UTC, theMr17 commented
> Hi @theMr17, Could you please tell me why this test failed ?ExplorationActiveTimeControllerTest > testSessionTimer_explorationStarted_appInBackground_pausesSessionTimer FAILED

@subhajitxyz The test seems to be flaky, I have re-run the test, hopefully the check will pass this time.

/cc @adhiamboperes.

2024-09-04 16:15 UTC, subhajitxyz commented
@adhiamboperes , PTAL.

2024-09-05 07:32 UTC, adhiamboperes approved these changes
Thanks @subhajitxyz! This LGTM.

2024-09-05 07:32 UTC, merged