Fix #5357: Remove CDATA from translatable strings
oppia/oppia-android pull request #5524
Opened 2024-08-30 12:18 UTC by adhiamboperes

## Explanation

Fixes https://github.com/oppia/oppia-android/issues/5357

This PR includes the changes previously included in #5361, with an additional fix for missing closing html tags described in #5403:

```
faq_answer_app_language: Missing </strong> tag after the email address.
faq_answer_bug_reporting: Missing closing </ol> tag.
faq_answer_exploration_player: Missing closing </ul> tag.
faq_answer_update_app: Missing closing </ol> tag and closing </p> tag.
faq_answer_update_os: Missing closing </ol> tag and closing </p> tag.
```

This PR removes all CDATA declarations in the translatable strings.xml file and instead escapes all necessary characters: < and > (& didn't need to be escaped since no strings use that character at the moment). This is needed because Translatewiki doesn't seem to extract the HTML within the CDATA declaration correctly, so it may not be translated (some existing strings were never translated, and per https://github.com/oppia/oppia-android/pull/5274 the latest FAQ changes aren't being processed correctly (leading to empty translation strings being submitted).

This PR also introduces a regex check + test to ensure that CDATA isn't used anymore in strings.

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2024-09-04 20:58 UTC, BenHenning requested changes
Thanks @adhiamboperes! The fixes look quite good. I just had one clarification comment to make sure everything was converted correctly.

That being said, I wonder if we need to perform any stronger analysis on the strings to ensure their HTML is well-formed? Or, perhaps that's something we can tackle as part of #4562? WDYT?

2024-09-04 20:58 UTC, BenHenning commented on app/src/main/res/values/strings.xml
> +  <string name="agree_to_terms">By using %s, you agree to our &lt;br&gt; <oppia-noninteractive-policy link="tos">Terms of Service</oppia-noninteractive-policy> and <oppia-noninteractive-policy link="
Don't the custom tags also need to be escaped?

2024-09-09 08:17 UTC, adhiamboperes commented on app/src/main/res/values/strings.xml
> +  <string name="agree_to_terms">By using %s, you agree to our &lt;br&gt; <oppia-noninteractive-policy link="tos">Terms of Service</oppia-noninteractive-policy> and <oppia-noninteractive-policy link="
Fixed.

2024-09-10 23:16 UTC, BenHenning approved these changes
Thanks @adhiamboperes! LGTM.

2024-09-10 23:17 UTC, BenHenning commented
Going ahead and merging this since it is important to unblock Translatewiki. I believe we'll see the effects of this during the Thursday pull from Translatewiki.

2024-09-10 23:17 UTC, merged