Fix #5404: Migrate away from onBackPressed for remaining activities
oppia/oppia-android pull request #5526
Opened 2024-09-05 12:19 UTC by dattasneha

## Explanation

 Fixes #5404 

 This PR migrates deprecated `onBackPressed` usage to `OnBackPressedDispatcher` callback in the following activities and presenters.

- ProfileEditActivity
- ProfileEditActivityPresenter
- QuestionPlayerActivityPresenter
- WalkthroughFinalFragmentPresenter

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2024-09-05 12:25 UTC, dattasneha commented
@adhiamboperes PTAL

2024-09-16 09:22 UTC, adhiamboperes commented
@dattasneha, checks are failing in this PR. PTAL.

2024-09-19 08:41 UTC, dattasneha commented
@adhiamboperes PTAL.

2024-09-20 14:10 UTC, theMr17 requested changes
Thanks @dattasneha! I have left some comments, PTAL.

2024-09-20 14:10 UTC, theMr17 commented on app/src/main/java/org/oppia/android/app/walkthrough/WalkthroughActivity.kt
> +        }
The `finish()` call may not be necessary here, since the `moveToPreviousPage()` function in the presenter, triggered via `walkthroughActivityPresenter.handleSystemBack()`, already handles finishing the activity.

https://github.com/oppia/oppia-android/blob/8d44bf7b006aae8fbd0bab5db609ec76cd481151/app/src/main/java/org/oppia/android/app/walkthrough/WalkthroughActivityPresenter.kt#L133-L135

https://github.com/oppia/oppia-android/blob/8d44bf7b006aae8fbd0bab5db609ec76cd481151/app/src/main/java/org/oppia/android/app/walkthrough/WalkthroughActivityPresenter.kt#L72-L78

2024-09-20 14:10 UTC, theMr17 commented on app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerActivity.kt
> +          finish()
The `finish()` call here doesn't seem necessary either. The `showStopExplorationDialogFragment()` already displays a dialog where the user can choose to either `Leave` or `Cancel`. Pressing the `Leave` button should navigate the user back to the previous screen. However, with the `finish()` call in place, the `QuestionPlayerActivity` closes before the user can interact with the dialog. Please take a look at the recording below.


https://github.com/user-attachments/assets/4c8fb8e8-da8a-4fb9-939b-82a434217c8c

2024-09-22 09:10 UTC, dattasneha commented on app/src/main/java/org/oppia/android/app/walkthrough/WalkthroughActivity.kt
> +        }
Removed the `finish()` call.

2024-09-22 09:11 UTC, dattasneha commented on app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerActivity.kt
> +          finish()
Removed the `finish()` call here also. @theMr17, PTAL

2024-09-23 10:24 UTC, theMr17 approved these changes
Thanks @dattasneha, this LGTM!

2024-09-23 10:25 UTC, theMr17 commented
@BenHenning PTAL.

2024-10-03 10:52 UTC, adhiamboperes approved these changes
Thanks @dattasneha! This LGTM. Thanks @theMr17 for the initial review pass.

2024-10-03 10:53 UTC, merged