Fix #1468: Retain Drag and Drop state after an incorrect answer
oppia/oppia-android pull request #5541
Opened 2024-09-22 11:11 UTC by Rd4dev

## Explanation

Fix #1468 

### This PR includes

- Utilized `explorationProgressController` to retrieve the **'wrongAnswerList'** from ephemeralState's pendingState and use it to populate the `DragDropInteractionContentViewModel` list.
- When `wrongAnswerList` is available, corresponding content IDs and HTML values are applied. If not, the original `contentIdHtmlMap` and `SubtitledHtml` values are used as a fallback.

https://github.com/user-attachments/assets/3e97c175-66fc-4ca5-a2f0-9e7e6f36e416

**Todo:**
- to confirm the blocking retrieval approach
- to figure out the tests

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2024-09-22 11:15 UTC, Rd4dev commented
@BenHenning, @adhiamboperes, could you PTAL and confirm if this could effectively retain the drag-and-drop states? 
I'm uncertain if using `runBlocking` is the right approach here. 

```
runBlocking {
  when (val result = explorationProgressController.getCurrentState().retrieveData()) { ...}
}
```

2024-09-29 21:18 UTC, Rd4dev commented
@adhiamboperes, utilized LiveData to retain the states and added corresponding Robolectric tests. However, I haven't been able to add or verify the Espresso tests with issues, as mentioned in #5435. Is there anything I missed or any workaround to resolve this? Could you PTAL.

2024-09-30 11:33 UTC, Vishwajith-Shettigar commented
> @adhiamboperes, utilized LiveData to retain the states and added corresponding Robolectric tests. However, I haven't been able to add or verify the Espresso tests with issues, as mentioned in #5435. Is there anything I missed or any workaround to resolve this? Could you PTAL.

The workaround would be to comment out the Oppia test rule in that test class.

2024-09-30 21:06 UTC, Rd4dev commented
> The workaround would be to comment out the Oppia test rule in that test class.

@Vishwajith-Shettigar -- thanks for helping out, I commented the Oppia Test Rule, but it led to the `MockitoException` shared in the additional context #5435. After bumping Mockito to version 3.11.1, the tests started working with Espresso!

_Yet to approve the version bump._

2024-10-01 02:55 UTC, Vishwajith-Shettigar commented
> > The workaround would be to comment out the Oppia test rule in that test class.
> 
> @Vishwajith-Shettigar -- thanks for helping out, I commented the Oppia Test Rule, but it led to the `MockitoException` shared in the additional context #5435. After bumping Mockito to version 3.11.1, the tests started working with Espresso!
> 
> _Yet to approve the version bump._

I usually bump to version 2.27.0 as a workaround, but version 2.22.0 >= may also work well with Java 11.

2024-10-01 18:03 UTC, Rd4dev commented
> I usually bump to version 2.27.0 as a workaround, but version 2.22.0 >= may also work well with Java 11.

Thanks, @Vishwajith-Shettigar, would try that. It was also mentioned during the meeting that PR #5467 would be revived sometime soon and that would resolve this more thoroughly.

2024-10-11 09:13 UTC, adhiamboperes requested changes
Thank you @Rd4dev! I have left some suggestions, PTAL.

2024-10-11 09:13 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt
> +  private val fragment: Fragment,
We typically dont pass fragments or contexts to the viewmodel as this could lead to memory leaks.

2024-10-11 09:13 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt
> +  }
Instead of observing livedata, you can use `Transformations`. this eliminates the need for the fragment instance.
```suggestion
    val ephemeralStateLiveData: LiveData<MutableList<DragDropInteractionContentViewModel>> by lazy {
      Transformations.map(explorationProgressController.getCurrentState().toLiveData()){result->
        return@map when(result){
          is AsyncResult.Failure -> _originalChoiceItems.toMutableList()
          is AsyncResult.Pending -> _originalChoiceItems.toMutableList()
          is AsyncResult.Success -> {
            val state = result.value
            val wrongAnswerList = state.pendingState.wrongAnswerList

            if (wrongAnswerList.isNotEmpty()) {
              val latestWrongAnswerContentIdList = wrongAnswerList.last()
                .userAnswer
                .answer
                .listOfSetsOfTranslatableHtmlContentIds
                .contentIdListsList

              latestWrongAnswerContentIdList.mapIndexed { index, setOfTranslatableHtmlContentIds ->
                DragDropInteractionContentViewModel(
                  contentIdHtmlMap = contentIdHtmlMap,
                  htmlContent = SetOfTranslatableHtmlContentIds.newBuilder().apply {
                    for (contentIds in setOfTranslatableHtmlContentIds.contentIdsList) {
                      addContentIds(
                        TranslatableHtmlContentId.newBuilder().apply {
                          contentId = contentIds.contentId
                        }
                      )
                    }
                  }.build(),
                  itemIndex = index,
                  listSize = latestWrongAnswerContentIdList.size,
                  dragAndDropSortInteractionViewModel = dragAndDropSortInteractionViewModel,
                  resourceHandler = resourceHandler
                )
              }.toMutableList()
            } else {
              _originalChoiceItems.toMutableList()
            }
          }
        }
      }
    }
```

2024-11-22 09:49 UTC, Rd4dev commented on app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt
> +  private val fragment: Fragment,
Got it, updated it with `Transformations` as suggested.

2024-11-22 09:52 UTC, Rd4dev commented on app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt
> +  }
Thanks for the suggestion, updated it accordingly.

2024-11-22 10:02 UTC, Rd4dev commented
@adhiamboperes, thanks for the review and the helpful direction. 
I've applied the changes, incorporating some adjustments -- PTAL.

2024-12-09 21:20 UTC, adhiamboperes approved these changes
Thanks @Rd4dev! This fix LGTM.

Just a note, however, that the video demos seem to be broken. Could you please re-upload them?

2024-12-10 12:31 UTC, Rd4dev commented
Thanks @adhiamboperes for the review. I've updated the video demos in the description. Could you please check if they're functioning properly now?

2024-12-10 19:00 UTC, adhiamboperes commented
Thanks @Rd4dev, the recordings play now.

2024-12-10 19:46 UTC, merged