Fix #2652 : Improve splash screen implementation with new drawable and updated styles
oppia/oppia-android pull request #5555
Opened 2024-10-16 17:22 UTC by TanishMoral11

## Explanation
This PR aims to enhance the splash screen implementation by making the following changes:

1. **splash_image.xml**: Created a new layer-list drawable that includes a background color (`@color/oppiaPrimaryLight`) and centers the splash image (`@drawable/splash_page`).

2. **splash_page.xml**: Modified the path data for the splash image and removed the old clip-path to ensure proper rendering.

3. **styles.xml**: Updated the `SplashScreenTheme` to reference the new `splash_image` drawable and set `adjustViewBounds` to true, allowing for better handling of different screen sizes.

These changes are intended to improve the visual consistency and responsiveness of the splash screen across various devices.

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

Before :-

https://github.com/user-attachments/assets/b9e795c3-279d-45fd-8210-23f2fead9b8b

After : -

https://github.com/user-attachments/assets/9fd2337c-b3b2-4ad9-8e9a-09c4df9173bf

2024-10-21 14:59 UTC, adhiamboperes commented
@TanishMoral11, could you please double check that the screen recordings are playable?

2024-10-21 15:07 UTC, adhiamboperes requested changes
Thanks @TanishMoral11! PTAL at the requested changes.

2024-10-21 15:07 UTC, adhiamboperes commented on app/src/main/res/drawable/splash_page.xml
> +<!--  </group>-->
Please remove unused code instead of commenting it out.

2024-10-21 15:07 UTC, adhiamboperes commented on app/src/main/res/drawable/splash_image.xml
> +  <item android:drawable="@color/color_def_oppia_green" />
I believe a static check will fail becaus we only use component colors in xml for darkmode support. Please see: https://github.com/oppia/oppia-android/wiki/Dark-Mode

2024-10-22 11:29 UTC, TanishMoral11 commented
@adhiamboperes PTAL

2024-10-23 09:05 UTC, TanishMoral11 commented
Hey @adhiamboperes , Could You Please Reassign This Issue To Me? 
I've Addressed All The Requested Changes And Resolved The Issue.
However, I'm Not Sure Why The Oppia Bot Unassigned Me. 
 
 Thanks!!

2024-10-23 10:58 UTC, adhiamboperes commented
@TanishMoral11, oppiabot can reassign the PR to the next person who should take a look at it when a review is complete or requested. The issue is assigned to one person, but the corresponding PR rotates responsibility. Please refer to the guidaance to submitting a PR section of the wiki.

Additionally, I have noticed that you have force pushed this branch several times, which is against our guidelines. I would advice you to do the following:
- In android studio, rename your local branch
- Pull latest changes from develop with `git pull upstream develop`
- Push the new branch `git push  --set-upstream origin new-branch-name`
- Create a new PR and copy the PR desscription from this PR
- Close this PR.

2024-10-24 08:20 UTC, closed without merging