Fixes #3641 Use finish() instead of intent for smoother navigation
oppia/oppia-android pull request #5557
Opened 2024-10-21 18:15 UTC by theayushyadav11

## Description:
- Fixes #3641  
This PR simplifies the navigation logic in `AddProfileActivity` and documents the reasoning behind not using `finish()` in `ExitProfileDialogFragment`.  

### Changes Made:
- **AddProfileActivity:**  
  - Replaced the use of `Intent` with `FLAG_ACTIVITY_CLEAR_TOP` by calling `finish()`.  
  - With the live data bug resolved, the activity stack can now be managed more cleanly without requiring a new intent.  

  **Benefits:**  
  - Avoids unnecessary activity recreation.  
  - Improves navigation efficiency and reduces overhead.  

- **ExitProfileDialogFragment:**  
  - Retained the use of an `Intent` to navigate to `ProfileChooserActivity` instead of switching to `finish()`.  
  - **Reason:**  
    - `ProfileChooserActivity` is not directly below the current activity in the stack.  
    - If `finish()` were used, the app would incorrectly navigate to `PinPasswordActivity`, resulting in undesirable behavior.  

### Testing:
1. Verified that `AddProfileActivity` correctly navigates back to `ProfileChooserActivity` using `finish()` without activity recreation.  
2. Confirmed that `ExitProfileDialogFragment` behaves as expected, retaining the correct navigation path through `Intent` to `ProfileChooserActivity`.  

### Summary:
This PR ensures cleaner navigation for `AddProfileActivity` by using `finish()`, while maintaining correct behavior in `ExitProfileDialogFragment` by continuing to use an intent-based approach. This makes the app more efficient while preserving user experience.  

### Video Demo as everything is working fine.
https://github.com/user-attachments/assets/fb383845-5672-4236-8618-a87583cbbba0

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

2024-10-28 13:19 UTC, adhiamboperes requested changes
Thanks @theayushyadav11!

I have a few comments:
1. Re - UI tests. You can add a test for this change in te corresponding test file. You can base your test on this other one: https://github.com/oppia/oppia-android/blob/2301a52eae08f271fd4090e51470696f223c135a/app/src/sharedTest/java/org/oppia/android/app/onboarding/IntroFragmentTest.kt#L176C1-L187. Also, to invoke `onSupportNavigateUp` in Espresso, you can take a look at https://stackoverflow.com/a/42872727.

2. I agree with your assessment of [ExitProfileDialogFragment.kt#L67](https://github.com/oppia/oppia-android/blob/ef7ffb8/app/src/main/java/org/oppia/android/app/drawer/ExitProfileDialogFragment.kt#L67), but in order for the issue to be closed, you have to remove the TODO from the code. It would also be great to add the reason for this in the issue thread to make future investigation easier.

3. A screen recording oof the changes is usually required as an extra step to ensure the changes do what is promised.

2024-11-06 11:39 UTC, adhiamboperes commented
@theayushyadav11, friendly ping on this issue.

2024-11-07 10:53 UTC, theayushyadav11 commented
@adhiamboperes PTAL.

2024-11-07 15:24 UTC, adhiamboperes requested changes
Thanks @theayushyadav11!

You need to add a test for the bakpress for `AddProfileActivity.kt`. I left a suggestion in my previous review comment. PTAL. Please also feel free to ask incase you face difficulty setting up the test.

2024-11-07 15:24 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/profile/AddProfileActivity.kt
> +import javax.inject.Inject
Assuming your project is correctly set up, you can always run `java -jar ../oppia-android-tools/ktlint -F --android domain/src/**/*.kt utility/src/**/*.kt data/src/**/*.kt app/src/**/*.kt testing/src/**/*.kt scripts/src/**/*.kt  instrumentation/src/**/*.kt ` on terminal before creating a commit, which will show you any ktlint errors, and fix others automatically.

2024-11-07 15:24 UTC, adhiamboperes commented on .idea/codeStyles/Project.xml
This is an android studio file that should not be part of the PR. Please delete it in your next commit.

2024-11-13 15:38 UTC, theayushyadav11 commented
Hey @adhiamboperes PTAL,
Could you please review my code and let me know if it's good to merge, or suggest any changes you’d like to see?

2024-11-14 12:44 UTC, theayushyadav11 commented
Hey @adhiamboperes  PTAL .

2024-11-14 14:58 UTC, adhiamboperes requested changes
Thanks @theayushyadav11.

The solution and test look good, but cleanup is needed to get the PR merge ready. Please pull latest changes from develop and resolve the merge conflicts.

2024-11-14 14:58 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/profile/AddProfileActivityTest.kt
> +import androidx.test.core.app.ActivityScenario
This looks like an unused import

2024-11-14 14:58 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/profile/AddProfileActivityTest.kt
> +import javax.inject.Singleton
These are not properly ordered, they should be at the bottom of the import list. I mentioned this in my last review.

2024-11-14 14:58 UTC, adhiamboperes commented on .idea/codeStyles/Project.xml
I meant that the file be deleted from the PR but not project. What this means is that I did not expect any changes to have been made to this .idea file. To fix this, you can pull develop into this PR - `git pull upstream develop`. This is likely to cause a conflict. You should accept the change from develop, which should restore this file to its original state.

2024-11-14 18:47 UTC, theayushyadav11 commented
Hey @adhiamboperes PTAL.

2024-11-15 08:51 UTC, adhiamboperes approved these changes
Thanks @theayushyadav11. Excellent work here. This LGTM!

2024-11-15 08:53 UTC, merged