Fixes Multiple substitutions specified in non-positional format of st…
oppia/oppia-android pull request #5560
Opened 2024-10-24 10:15 UTC by jainv4156

## Explanation

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2024-10-29 06:26 UTC, adhiamboperes requested changes
Thanks @jainv4156! 

For this PR, we should revert the changes in all string files except the English file, since the translations will be overwritten by TranslateWiki anyway! We typically add English strings, then the translations team is responsible for creating translations.

Secondly, please ensure that you have addressed all the items in the PR Essential check list.

2024-10-30 05:48 UTC, jainv4156 commented
@adhiamboperes , PTAL

2024-10-30 07:25 UTC, adhiamboperes commented
Closing and reopening since CI appears stuck.

2024-11-04 10:36 UTC, adhiamboperes approved these changes
Thanks @jainv4156! LGTM.

2024-11-04 11:45 UTC, merged