Fixes part of #4302 - Introducing a JUnit annotation & rule for overriding Platform Parameters and Feature Flags
oppia/oppia-android pull request #5565
Opened 2024-11-04 13:37 UTC by Rd4dev

## Explanation

Fixes part of #4302 

### This PR includes

A draft implementation for overriding platform parameters and feature flags in the tests using the `PlatformParameterModule` at class and functional level.

#### Todo on approval / feedback:
- Alter the implementation based on feedback received from the review process.
- Once approved, the final version will replace the old module with the new functionality across all applicable tests.
- Remove debugging statements.
- KDocs will be added.

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

2024-11-04 13:59 UTC, Rd4dev commented
@BenHenning @adhiamboperes Would it be possible to provide a draft review or approval on the implementation to ensure things are on the right track before I proceed with the rest? I would like to confirm if the [mentioned ](https://github.com/oppia/oppia-android/issues/4302#:~:text=Updating%20all%20tests%20to%20use%20the%20production%20module%20instead%20of%20the%20test%20or%20a%20custom%20module%2C%20and%20adding%20OppiaTestRule/test%20annotations%20where%20needed%20to%20ensure%20overrides%20are%20still%20happening.)

> "Updating all tests to use the production module instead of the test or a custom module, and adding OppiaTestRule/test annotations where needed to ensure overrides are still happening." 

is done right. If not then will rework based on the feedback.

2024-11-05 17:21 UTC, BenHenning commented
Reviewed during CLaM meeting today and feedback was left in real-time.

2024-11-05 17:24 UTC, BenHenning commented
> @BenHenning @adhiamboperes Would it be possible to provide a draft review or approval on the implementation to ensure things are on the right track before I proceed with the rest? I would like to confirm if the [mentioned ](https://github.com/oppia/oppia-android/issues/4302#:~:text=Updating%20all%20tests%20to%20use%20the%20production%20module%20instead%20of%20the%20test%20or%20a%20custom%20module%2C%20and%20adding%20OppiaTestRule/test%20annotations%20where%20needed%20to%20ensure%20overrides%20are%20still%20happening.)
> 
> > "Updating all tests to use the production module instead of the test or a custom module, and adding OppiaTestRule/test annotations where needed to ensure overrides are still happening."
> 
> is done right. If not then will rework based on the feedback.

Everything looks right except the overriding mechanism. Rather than having an override built into the production module, we should be overriding the value via OkHttp and the platform parameter syncing. This might be a bit tricky to set up, so it may well be worth getting this working before migrating all uses over to the new system.

2024-12-27 05:26 UTC, Rd4dev commented
Removing stale label, will work on this next week.

2025-01-08 20:25 UTC, Rd4dev commented
@BenHenning, @adhiamboperes PTAL, and I also wanted to confirm a few requirements:

1.  What should be the scope of `OppiaTestRule` inclusion?

    Is it required in every module's test file, or are there exceptions?

    The concern is that `OppiaTestRule` attempts to acquire `Build.FINGERPRINT` to determine the Test Platform. While this works for other modules that access Android classes, the script module test cases throw a `NoClassDefFoundError`. Although the issue can be mitigated by redirecting to use Robolectric as the Test Platform, the previous error logs interfere with current assertion throw cases, leading to test failures. I wanted to clarify the scope and requirements for including the rule before investigating other workarounds.

2. Codeowners Check Failure

    Are there any specific changes I need to address to resolve the [CODEOWNERS check failure](https://github.com/oppia/oppia-android/actions/runs/12678024040/job/35334689300?pr=5565#step:4:16)?

3. Reset Annotation

    As discussed in a prior CLaM meeting, it was suggested to remove the `ResetPlatformParameter` annotation since `overridePlatformParameter` was deemed sufficient. I just have few questions:

    - If `ResetPlatformParameter` was removed for platform parameters, should it also be removed for feature flags? (I remember it being mentioned to not to) but the same functionality (resetting to a default value) could be achieved by utilizing `EnableFeatureFlag` or `DisableFeatureFlag`.
    - If keeping a reset annotation is advisable, would maintaining it for both feature flags and platform parameters be helpful to ensure parity and avoid confusion?
    - Alternatively, would keeping the reset annotation exclusively for feature flags suffice?

2025-01-16 17:42 UTC, Rd4dev commented on testing/src/main/java/org/oppia/android/testing/OppiaTestRule.kt
> +     * @param annotations a collection of annotations to be checked for feature flag annotations.
Todo: To remove ending periods from all KDocs.
```suggestion
     * @param annotations a collection of annotations to be checked for feature flag annotations
```

2025-01-21 14:27 UTC, adhiamboperes commented
Thanks @Rd4dev! Reviewing this today.

2025-01-21 14:31 UTC, Rd4dev commented
> Thanks @Rd4dev! Reviewing this today.

Thanks @adhiamboperes, appreciate the update!

2025-01-21 23:26 UTC, BenHenning reviewed
Thanks @Rd4dev! This is really exciting to see progress on.

I only looked at the top-level override classes for now, and still need to dig deeper into the PR. However, I do have one thought that I wanted to run by you.

I've had an idea for some time to leverage code generation for the feature flags to minimize the amount of Dagger binding boilerplate that needs to be done each time a new flag is added. Originally, I thought that this would require a custom annotation processor. However, now that Gradle is gone, we actually could do this with protobuf. Consider:
- A new textproto file that lists every feature flag and platform parameter with server string names and default values. I suspect this would be a twofold definition: explicit parameters in a proto file, and server names and default values in textproto (so that we have strong typing for the separate flags).
- Automatic compilation to binary proto (like we do with the language configuration under ``config/``).
- Some file loading logic similar to that which is needed for the languages configuration.
- Updating Dagger bindings that just generate the entire set of bound flags/parameters by loading the textproto file.\*

\* Note that this is a little trickier than it sounds because we can't technically do file I/O within Dagger providers without incurring some performance issues. However, something that we _could_ do is automatically bind implementation classes based on the proto structure (which is available at compile time since the individual flags would be defined within a proto file), and then have the implementations support asynchronously loading their state (either from the local file cache or from their local file configuration). It's possible we don't even need this second bit since I think the platform parameter system is technically supposed to be designed to fully load its asynchronous state during the app startup so that all flag values are fixed for the lifetime of the app process.

While a long explanation, I suspect that the delta might be relatively small and also be a pretty substantial improvement to how flags and parameters are interacted with in both tests and production code. There's probably more that could be done with real code generation, but that starts getting a bit scary in scope here.

Is this something you'd want to take on as part of this PR? If not, no worries. I just wanted to ask since you've already spent a lot of time thinking about the mechanisms. :)

2025-01-21 23:26 UTC, BenHenning commented on testing/src/main/java/org/oppia/android/testing/EnableFeatureFlag.kt
> +annotation class EnableFeatureFlag(val name: FeatureFlag)
For both this and the disable variant, it would be good to explain here how cascading cases or repeated cases are handled. For instance, consider the following setup:

```kotlin
@EnableFeatureFlag(FEATURE_1)
@DisableFeatureFlag(FEATURE_1)
class MyConfusingTest {

  @Test
  fun test_case1() {}

  @Test
  @EnableFeatureFlag(FEATURE_1)
  fun test_case2() {}

  @Test
  @DisableFeatureFlag(FEATURE_1)
  fun test_case3() {}

  @Test
  @EnableFeatureFlag(FEATURE_1)
  @DisableFeatureFlag(FEATURE_1)
  fun test_case4() {}

  @Test
  @DisableFeatureFlag(FEATURE_1)
  @EnableFeatureFlag(FEATURE_1)
  fun test_case5() {}
}
```

What is the expected state of ``FEATURE_1`` in each test case? Is it an error or does latest win?

Personally, I would expect that:
- More than one declaration for a single feature at the class or method level results in an error (i.e. ``MyConfusingTest``, ``test_case4``, and ``test_case5`` above should all fail).
- It's allowed to have at most 2 overrides for a single feature for a given test: one at the class level, and one at the method level, where the method annotation always takes precedence. This allows us to enable/disable a feature for the whole class, then selectively enable/disable it on a per-test basis as needed.

2025-01-21 23:26 UTC, BenHenning commented on testing/src/main/java/org/oppia/android/testing/OverrideStringParameter.kt
> +annotation class OverrideStringParameter(val name: PlatformParameter, val value: String)
For this & the other override classes: see my comment in ``EnableFeatureFlag`` as I think the same consideration is needed here on how cascading and overriding scenarios are handled.

2025-01-21 23:26 UTC, BenHenning commented on testing/src/main/java/org/oppia/android/testing/ResetFeatureFlagToDefault.kt
> +annotation class ResetFeatureFlagToDefault(val name: FeatureFlag)
Similar to my comment in ``EnableFeatureFlag``, cascading/duplication needs to be considered here. I'd expect any cases where an enable/disable happens and reset at the same level to be an error (i.e. a test method can only reset, not enable/disable and then reset).

For strictness, I'd also expect that reset throws an error if there's no explicit override of the feature at the class level (i.e. there's no reason to reset). While resetting a non-overridden flag is a no-op, allowing it to be checked in could result in false assumptions and a fundamental misunderstanding of what the test and surrounding test suite is actually doing.

2025-01-28 01:30 UTC, adhiamboperes requested changes
Thanks @Rd4dev! I have left a few comments, PTAL.

2025-01-28 01:30 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/home/HomeActivityTest.kt
> -    setUpTestWithOnboardingV2Enabled()
This test and 3 below require the feature flag to be enabled, but they are missing the annotation. Do they pass?

2025-01-28 01:30 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt
> +  @EnableFeatureFlag(FeatureFlag.EXTRA_TOPIC_TABS_UI)
Should this be disabled?

2025-01-28 01:30 UTC, adhiamboperes commented on domain/src/test/java/org/oppia/android/domain/survey/SurveyGatingControllerTest.kt
> +  @EnableFeatureFlag(FeatureFlag.ENABLE_NPS_SURVEY)
Since this test class is valid  only for the feature flag enabled situation, I think it is sufficient to enable the flag at class level.

2025-01-28 01:30 UTC, adhiamboperes commented on domain/src/main/java/org/oppia/android/domain/platformparameter/PlatformParameterModule.kt
> +      )
I don't understand why this is a combination of feature flag and platform parameter here and below.

2025-03-12 05:45 UTC, closed without merging