Refactor: Moved InteractionObjectTestBuilder to the testing module
oppia/oppia-android pull request #5587
Opened 2024-12-04 20:20 UTC by akshtshrma

## Explanation

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2024-12-06 04:02 UTC, akshtshrma commented
@BenHenning can you please approve this PR.

2024-12-07 17:47 UTC, akshtshrma commented
@BenHenning PTAL

2024-12-09 23:48 UTC, adhiamboperes requested changes
Thanks @akshtshrma! I have some comments. PTAL.

2024-12-09 23:48 UTC, adhiamboperes commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.3-bin.zip
This file should not have been changed.

2024-12-09 23:48 UTC, adhiamboperes commented on testing/build.gradle
> +      "org.jetbrains.kotlin:kotlin-test",
Why was this added? It is my understanding that nothing has actually changed in the test implementation.

2024-12-09 23:48 UTC, adhiamboperes commented on testing/build.gradle
> +  implementation project(":domain")
Why is this needed?

2024-12-12 18:32 UTC, akshtshrma commented
@adhiamboperes Thanks for the review. I think i have make some extra changes, and will fix them right away.

2024-12-23 14:25 UTC, adhiamboperes commented
@akshtshrma, could you please let us know if you are perharps blocked on this PR?

2024-12-23 17:14 UTC, akshtshrma commented
@adhiamboperes ,I am sorry for the delay. I having some problem while logging in to Github in android studio bumblebee and this is why I am not able to submit a PR. I have tried using tokens and also logging in directly. Can you please help me with this issue.

2024-12-23 20:02 UTC, adhiamboperes commented
> @adhiamboperes ,I am sorry for the delay. I having some problem while logging in to Github in android studio bumblebee and this is why I am not able to submit a PR. I have tried using tokens and also logging in directly. Can you please help me with this issue.

@akshtshrma, happy to help. I believe I have experienced this in the past. Could you please post question to the discussions section of the repo then mention me? Posting your error message will be helpful for quick resolution.

2025-01-21 08:13 UTC, closed without merging