Html parser tests
oppia/oppia-android pull request #5589
Opened 2024-12-05 15:50 UTC by manas-yu

## Explanation
Fix #455
- `testHtmlContentReplace_removesUnwantedNewlines`: Ensures that unwanted newlines are removed from HTML content when parsed.
- `testHtmlContent_withImageTag_trimsLeadingAndTrailingNewlines`: Verifies that leading and trailing newlines are trimmed from HTML content containing an image tag.

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

2024-12-05 21:23 UTC, manas-yu commented
@adhiamboperes, PTAL

2024-12-09 22:15 UTC, adhiamboperes requested changes
Thanks @manas-yu! These tests look good for the linked PRs. I have left some sugesstions to make the test names more descriptive. Otherwise LGTM.

2024-12-09 22:15 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/parser/HtmlParserTest.kt
> +  fun testHtmlContentReplace_removesUnwantedNewlines() {
```suggestion
  fun testHtmlContentParsing_removesUnwantedNewlines() {
```

2024-12-09 22:15 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/parser/HtmlParserTest.kt
> +  fun testHtmlContent_withImageTag_trimsLeadingAndTrailingNewlines() {
```suggestion
  fun testHtmlContentParsing_withImageTag_trimsLeadingAndTrailingNewlines() {
```

2024-12-10 17:59 UTC, adhiamboperes approved these changes
Approving and merging.

2024-12-10 17:59 UTC, merged