Fix #5592 : Enable submit button after linking items in Drag & Drop Sort Interaction
oppia/oppia-android pull request #5597
Opened 2024-12-14 16:18 UTC by TanishMoral11

## Explanation
This PR fixes an issue #5592 , where the submit button did not become enabled after linking items in the Drag & Drop Sort Interaction. Previously, even when the items were correctly linked, the submit button remained disabled, preventing users from proceeding.

### **Changes Made**
- Updated logic to track linking and unlinking of items as a meaningful "state change."
- Ensured that the submit button becomes enabled as soon as items are linked or unlinked.
- Refactored the relevant functions to make sure the submit button reflects changes in real-time.

This change improves the overall UX, making it more intuitive for users to submit their answers after linking items. 

### **Steps to Verify**
1. Navigate to **Second Test Topic Exploration** → **Fifth Exploration**.
2. Arrange the following items: `0.6`, `3/5`, `0.46`, `0.35`.
3. Link `0.6` and `3/5` together.
4. Verify that the **Submit** button becomes active/enabled after the items are linked.

---

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix #5592 ".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

---
After Changes Video : 

https://github.com/user-attachments/assets/b6e3830c-e01c-4e70-933d-8d24cfee2a41

Screenshot of Passing Tests :
![Screenshot 2024-12-13 232845](https://github.com/user-attachments/assets/1ebdcf82-03ce-4984-a799-d99c2f17f5af)

2024-12-14 16:29 UTC, TanishMoral11 commented
Hey @adhiamboperes , Could You PTAL !!

2024-12-16 11:18 UTC, TanishMoral11 commented
Hey @adhiamboperes , PTAL !! 
The PR is ready for review

2024-12-17 10:44 UTC, adhiamboperes requested changes
Thanks @TanishMoral11!

A UI test to verify the change in [StateFragmentTest.kt](https://github.com/oppia/oppia-android/pull/5323/files#diff-6cc8ab23c6444ea9c27014ead03753daf9fc4e240985de43775062dc314fe0ab) is required.

2024-12-17 10:44 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt
> +    // *Update the list*
Here and below: please format comment correctly. Asterisks are only used in kdocs.

2024-12-17 10:44 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt
> +    val hasItemsChanged = _originalChoiceItems.size != _choiceItems.size ||
```suggestion
    val haveItemsChanged = _originalChoiceItems.size != _choiceItems.size ||
```

2024-12-17 12:09 UTC, TanishMoral11 commented
Hey @adhiamboperes PTAL !!

Before Changes :

https://github.com/user-attachments/assets/ed2f0dc1-432d-4b5b-833d-7438d9557f3c

After Changes :

https://github.com/user-attachments/assets/12e8d0b1-0f98-46d2-beae-600419fa4d6e

StateFragmentTest.kt Screen Shot :
![Screenshot 2024-12-17 170906](https://github.com/user-attachments/assets/9aded14a-718f-4466-86ab-1140888c430e)

2024-12-17 12:09 UTC, TanishMoral11 commented on app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt
> +    val hasItemsChanged = _originalChoiceItems.size != _choiceItems.size ||
Done.

2024-12-17 12:09 UTC, TanishMoral11 commented on app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt
> +    // *Update the list*
Done.

2024-12-18 12:02 UTC, TanishMoral11 commented
Hey @adhiamboperes , PTAL !!
The PR is ready for review.

2024-12-18 15:35 UTC, adhiamboperes approved these changes
Thanks @TanishMoral11! This LGTM.

2024-12-18 16:21 UTC, merged