Refactor topic to use profile
oppia/oppia-android pull request #5598
Opened 2024-12-15 05:05 UTC by tobioyelekan

## Explanation
### Fixes part of #4865 

This PR aim to refactor `topic` package to use `ProfileId`
Changes include all topic fragments, presenters, and TopicActivity
Also updated the test classes.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

2024-12-15 05:05 UTC, tobioyelekan commented
@adhiamboperes PTAL

2024-12-16 23:34 UTC, tobioyelekan commented
@adhiamboperes not sure why the Roboelectric tests failed, could you please help run it again?

2024-12-17 09:19 UTC, adhiamboperes commented
> @adhiamboperes not sure why the Roboelectric tests failed, could you please help run it again?

```
> Process 'Gradle Test Executor 3' finished with non-zero exit value 134
```
 Is typically a timeout error. I have re-run the tests, it should pass.

2024-12-18 11:47 UTC, tobioyelekan commented
@adhiamboperes PTAL

2024-12-18 15:03 UTC, adhiamboperes requested changes
Thanks @tobioyelekan! PTAL at my comments.

2024-12-18 15:03 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/topic/TopicFragment.kt
> +      arguments?.extractCurrentUserProfileId() ?: ProfileId.newBuilder().setInternalId(-1).build()
Here and elsewhere in the PR, please set the default ProfileId as fallback. We are moving away from setting  -1(logged out) as default due to reasons outlined in https://github.com/oppia/oppia-android/issues/5440.

```suggestion
      arguments?.extractCurrentUserProfileId() ?: ProfileId.getDefaultInstance()
```

2024-12-18 15:03 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt
> +    viewModel.setInternalProfileId(profileId)
Looks like this function needs to be renamed to `setProfileId()`

2024-12-18 15:03 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/topic/TopicViewModel.kt
> +  fun setInternalProfileId(profileId: ProfileId) {
Rename the function.

2024-12-18 15:03 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/topic/info/TopicInfoFragment.kt
> +      arguments?.extractCurrentUserProfileId() ?: ProfileId.newBuilder().setInternalId(-1).build()
Default to DefaultInstance instead.

2024-12-18 15:03 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/topic/lessons/TopicLessonsFragment.kt
> +      arguments?.extractCurrentUserProfileId() ?: ProfileId.newBuilder().setInternalId(-1).build()
Default to DefaultInstance instead.

2024-12-18 15:03 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/topic/lessons/TopicLessonViewModel.kt
> +  fun setInternalProfileId(profileId: ProfileId) {
Rename the function.

2024-12-18 15:03 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/topic/practice/TopicPracticeFragment.kt
> +    val profileId = arguments?.extractCurrentUserProfileId() ?: ProfileId.newBuilder()
Default to DefaultInstance.

2024-12-18 15:03 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/topic/revision/TopicRevisionFragment.kt
> +      arguments?.extractCurrentUserProfileId() ?: ProfileId.newBuilder().setInternalId(-1).build()
switch to DefaultInstance.

2024-12-18 15:03 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/topic/revision/TopicRevisionViewModel.kt
> +  fun setInternalProfileId(profileId: ProfileId) {
Rename function

2024-12-18 23:53 UTC, tobioyelekan commented
Thanks @adhiamboperes , all changes made. PTAL

2024-12-23 13:07 UTC, adhiamboperes approved these changes
Thanks @tobioyelekan, this LGTM!

Just a note - we prefer allowing the person who created a comment to resolve it, so they can first verify that it has been satisfactorily addressed. On your part, you can respond to the comment with: done, fixed, updated etc.

2024-12-23 13:08 UTC, adhiamboperes commented
Rerunning CI since there were unclear failures.

2024-12-23 16:21 UTC, merged