Fragment tests part3
oppia/oppia-android pull request #5606
Opened 2024-12-18 15:30 UTC by subhajitxyz

## Explanation
Fixes part of #5485

Added tests for 11 fragment arguments and 'saveInstanceState'.

I have not added tests for the following:

 1. onSaveInstanceState of StateFragment.
 2. OptionsFragment.
Problems:

  1.When trying to recreate StateFragment, an error occurs: "State has not been initialized."
  2.In the OptionsFragmentTest class, when I try to run the test on Robolectric, it shows "No tests were found.

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2024-12-19 05:20 UTC, subhajitxyz commented
Hi @adhiamboperes , could you please check why these checks failed ?

2025-01-03 05:46 UTC, subhajitxyz commented
PTAL, @adhiamboperes .

2025-01-07 13:16 UTC, adhiamboperes requested changes
Thanks @subhajitxyz! I have left some suggestions that could be applied to basically all the tests in the PR.

Re: OptionsFragmentTest. We have 2 of these, so when running, please ensure the path is correct. I have used:
`bazel test app/src/sharedTest/java/org/oppia/android/app/testing/options/OptionsFragmentTest` and
`bazel test app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest `

2025-01-07 13:16 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt
> +  fun testFragmentArguments_afterCreation_areCorrect() {
Suggest name format for all the tests in PR.
```suggestion
  fun testFragment_argumentsAreCorrect() {
```

2025-01-07 13:16 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt
> +        val receivedIsMultipane = args.isMultipane
Can be simplified to:
```suggestion
  val arguments = checkNotNull(administratorControlsFragment.arguments) {
        "Expected arguments to be passed to AdministratorControlsFragment"
      }.getProto(
        ADMINISTRATOR_CONTROLS_FRAGMENT_ARGUMENTS_KEY,
        AdministratorControlsFragmentArguments.getDefaultInstance()
      )
      val receivedIsMultipane = arguments.isMultipane
```

2025-01-21 03:16 UTC, subhajitxyz commented on app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt
> +        val receivedIsMultipane = args.isMultipane
Done.

2025-01-21 03:16 UTC, subhajitxyz commented on app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt
> +  fun testFragmentArguments_afterCreation_areCorrect() {
Done

2025-01-21 03:17 UTC, subhajitxyz commented
PTAL, @adhiamboperes .

2025-01-21 14:10 UTC, adhiamboperes approved these changes
Thanks @subhajitxyz! This LGTM

2025-01-21 14:11 UTC, merged