Fix #4202: Add support for parsing HasIntegerPartEqualTo rule type.
oppia/oppia-android pull request #5610
Opened 2024-12-20 06:01 UTC by TanishMoral11

Fixes #4202 : This PR adds support for parsing the "HasIntegerPartEqualTo" rule type for fractions in the Oppia Android app.

### Changes Made
- **Updated** `test_exp_id_2.json` to include the "HasIntegerPartEqualTo" rule type to ensure the rule is tested properly.
- **Updated** `StateRetriever.kt` to handle the "HasIntegerPartEqualTo" rule in the `createExactInputForFractionInput()` method.
- **Added** parsing logic for the "HasIntegerPartEqualTo" rule by adding a new check in `createExactInputForFractionInput()` to handle this rule type.
---

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

2024-12-20 06:04 UTC, TanishMoral11 commented
Hey @adhiamboperes , PTAL !!

2024-12-23 08:10 UTC, TanishMoral11 commented
Hey @adhiamboperes , PTAL !!

2024-12-25 03:35 UTC, TanishMoral11 commented
Hey @adhiamboperes , PTAL .
This PR Is Ready For Review.

2025-01-05 16:53 UTC, TanishMoral11 commented
Hey @adhiamboperes , This PR is Ready For Review , PTAL.

2025-01-08 09:14 UTC, adhiamboperes requested changes
Thanks @TanishMoral11!

Can you add a demo to show that the changes here are correct? Maybe reproduce the original error and show that these changes fix it.

Additionally, could you check that `test_exp_id_2.textproto` has these changes too (used when building with Bazel).

2025-01-09 20:43 UTC, TanishMoral11 commented
Hey @adhiamboperes , 

I’ve implemented the changes as suggested in [this issue comment](https://github.com/oppia/oppia-android/issues/4202#issuecomment-1042790267) and wanted to confirm if I am on the right track. However, I am a bit confused about the term "Alpha production app" mentioned. Does it refer to this ?

![WhatsApp Image 2025-01-10 at 02 05 48_e36475ac](https://github.com/user-attachments/assets/9fc004b8-de9b-42b6-b0a5-886d77e9f4fe)

Additionally, I’m unsure about the testing process. If I run the app from Android Studio on my device, it won’t be in the Alpha version. Could you please guide me on how I can test these changes, so they will reflect in the Alpha version.

Your assistance would be greatly appreciated.

Thank you !!

2025-01-22 13:36 UTC, adhiamboperes commented
@TanishMoral11,
1. Alpha production app is the alpha version of the app that is not publicly available, only available to specific users. While this issue was observed by an alpha tester, the solution you provided can still be tested with dev assets.
2.  The changes you made in `test_exp_id_2.json`(gradle build assets) should be made to `test_exp_id_2.textproto`(bazel build assets) as well.
3. To test these changes, please refer to examples already present in `StateRetrieverTest`.

2025-01-25 18:26 UTC, TanishMoral11 commented
Hey @adhiamboperes PTAL !!




> 1. Alpha production app is the alpha version of the app that is not publicly available, only available to specific users. While this issue was observed by an alpha tester, the solution you provided can still be tested with dev assets.

Thank you for the confirmation!

> 2\. The changes you made in `test_exp_id_2.json`(gradle build assets) should be made to `test_exp_id_2.textproto`(bazel build assets) as well.

The changes have been made.


> 3\. To test these changes, please refer to examples already present in `StateRetrieverTest`.

I’ve added the tests as requested.



After Adding Tests :-
![Image](https://github.com/user-attachments/assets/72974144-4a31-465a-b80b-804e14b57c92)

2025-01-27 07:37 UTC, adhiamboperes approved these changes
Thanks @TanishMoral11! This LGTM.

2025-01-27 09:11 UTC, merged