Fix #5612 Talk back is not reading Arabic language in Preferred Audio Language
oppia/oppia-android pull request #5613
Opened 2024-12-21 03:07 UTC by subhajitxyz

## Explanation
Fix #5612

This PR includes adding a function languageContentDescription(), which return content description for audioLangueDisplayname Finally, it is set into the content description of the TextView.

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

2024-12-22 13:27 UTC, subhajitxyz commented
PTAL @adhiamboperes .

2024-12-23 14:55 UTC, adhiamboperes requested changes
Thanks @subhajitxyz! Just some minor changes suggested.

2024-12-23 14:55 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/options/AudioLanguageItemViewModel.kt
> +      AudioLanguage.ARABIC_LANGUAGE -> "Arabic"
Could you please move this to strings.xml with a descriptive name?

2024-12-23 14:55 UTC, adhiamboperes commented on app/src/sharedTest/java/org/oppia/android/app/options/AudioLanguageFragmentTest.kt
> +  fun testOpenFragment_withEnglish_verifyContentDescriptionOfArabicLanguage() {
```suggestion
  fun testFragment_withEnglish_verifyContentDescriptionReadsArabicLanguage() {
```

2024-12-24 03:54 UTC, subhajitxyz commented on app/src/sharedTest/java/org/oppia/android/app/options/AudioLanguageFragmentTest.kt
> +  fun testOpenFragment_withEnglish_verifyContentDescriptionOfArabicLanguage() {
Done.

2024-12-24 03:55 UTC, subhajitxyz commented on app/src/main/java/org/oppia/android/app/options/AudioLanguageItemViewModel.kt
> +      AudioLanguage.ARABIC_LANGUAGE -> "Arabic"
@adhiamboperes , I have added this to strings.xml. Please check if it is okay.

2025-01-03 06:57 UTC, subhajitxyz commented on app/src/main/java/org/oppia/android/app/options/AudioLanguageItemViewModel.kt
> +      AudioLanguage.ARABIC_LANGUAGE -> "Arabic"
Done.

2025-01-03 06:57 UTC, subhajitxyz commented
PTAL, @adhiamboperes .

2025-01-10 09:18 UTC, adhiamboperes requested changes
Thanks @subhajitxyz, just one more suggestion. PTAL.

2025-01-10 09:18 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/options/AudioLanguageItemViewModel.kt
> +      AudioLanguage.ARABIC_LANGUAGE -> "Arabic"
```suggestion
      AudioLanguage.ARABIC_LANGUAGE -> appLanguageResourceHandler.getStringInLocaleWithWrapping(
        R.string.arabic_language_display_name_content_description
      )
```

2025-01-21 10:14 UTC, subhajitxyz commented on app/src/main/java/org/oppia/android/app/options/AudioLanguageItemViewModel.kt
> +      AudioLanguage.ARABIC_LANGUAGE -> "Arabic"
Done

2025-01-21 10:15 UTC, subhajitxyz commented
PTAL @adhiamboperes

2025-01-22 13:26 UTC, adhiamboperes approved these changes
Thanks @subhajitxyz! This LGTM.

2025-01-22 13:31 UTC, adhiamboperes commented
This PR is temporarily blocked on merging because there is one already queued up for merging. Should be updated and merged in a couple of hours.

2025-01-22 15:51 UTC, merged

2025-01-22 15:56 UTC, subhajitxyz commented
Thanks @adhiamboperes .