Fix #4848: Ensure Complete Content Descriptions for Custom HTML Tags in CustomHtmlContentHandler
oppia/oppia-android pull request #5614
Opened 2024-12-22 10:04 UTC by manas-yu

## Explanation

Fix #4848: This PR resolves the issue with incomplete content descriptions being generated for custom HTML tags. The existing implementation stripped out spans and custom tag content, leading to incomplete descriptions.

The updated implementation introduces a custom generation pipeline for content descriptions in `CustomHtmlContentHandler`. It ensures that all custom tag content is correctly processed and appended, resulting in complete and accurate descriptions.

### Key Changes:
- Added a `StringBuilder` to accumulate content descriptions and a `MutableMap` to handle custom tag descriptions.
- Implemented `getContentDescription()` to combine default text with custom tag content descriptions, ensuring seamless integration.
- Introduced a `ContentDescriptionProvider` interface for handling custom tags.
- Updated relevant tag handlers (`ImageTagHandler`, `ConceptCardTagHandler`, and `MathTagHandler`) to implement the new interface.
- Verified the implementation with appropriate test cases.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

2024-12-23 14:57 UTC, adhiamboperes commented
@manas-yu, please assign to a reviewer if ready for a pass.

2024-12-23 18:29 UTC, manas-yu commented
> @manas-yu, please assign to a reviewer if ready for a pass.

Hey @adhiamboperes PTAL, the PR is now ready for review. I've made the necessary code changes and would appreciate your feedback on the approach. Let me know if you have any suggestions or if any improvements are needed. Thanks!

2025-01-10 09:53 UTC, adhiamboperes requested changes
Thanks @manas-yu! PTAL at some suggestions that I have left.

2025-01-10 09:53 UTC, adhiamboperes commented on utility/src/main/java/org/oppia/android/util/parser/html/ImageTagHandler.kt
> +    val altValue = attributes.getJsonStringValue("alt-with-value")
```suggestion
    val altValue = attributes.getJsonStringValue(CUSTOM_IMG_ALT_TEXT_ATTRIBUTE)
```

2025-01-10 09:53 UTC, adhiamboperes commented on utility/src/main/java/org/oppia/android/util/parser/html/ImageTagHandler.kt
> +    return if (altValue != null) {
Prefer using `isNullOrBlank()`, which is a more strict check and will prevent issues like https://github.com/oppia/lessons-team/issues/719 from re-curring.

2025-01-10 09:53 UTC, adhiamboperes commented on utility/src/main/java/org/oppia/android/util/parser/html/ImageTagHandler.kt
> +    } else null
Would it be better to return an empty string?

2025-01-10 09:53 UTC, adhiamboperes commented on utility/src/test/java/org/oppia/android/util/parser/html/ConceptCardTagHandlerTest.kt
> +  @Test
Insert new line between tests

2025-01-10 09:53 UTC, adhiamboperes commented on utility/src/test/java/org/oppia/android/util/parser/html/CustomHtmlContentHandlerTest.kt
> +  @Test
Please format this tes class correctly.

2025-01-10 09:53 UTC, adhiamboperes commented on utility/src/test/java/org/oppia/android/util/parser/html/PolicyPageTagHandlerTest.kt
> +  @Test
Insert newline above

2025-01-10 09:53 UTC, adhiamboperes commented on utility/src/main/java/org/oppia/android/util/parser/html/PolicyPageTagHandler.kt
> +  }
Could be simplified to:
```suggestion
 override fun getContentDescription(attributes: Attributes): String? {
    return when (attributes.getJsonStringValue("link")) {
        TERMS_OF_SERVICE_PAGE, PRIVACY_POLICY_PAGE -> "Link to "
        else -> null
    }
}
```

2025-01-10 15:13 UTC, manas-yu commented on utility/src/main/java/org/oppia/android/util/parser/html/ImageTagHandler.kt
> +    } else null
Thanks for pointing it out. Returning an empty string instead of a null one is safer and avoids null checks, so I'll make the change.

2025-01-10 16:36 UTC, manas-yu commented
Hey @adhiamboperes, PTAL, I have made the requested changes. Let me know if there is anything else.

2025-01-14 08:21 UTC, adhiamboperes approved these changes
Thanks @manas-yu! This LGTM!

2025-01-14 09:13 UTC, merged

2025-02-10 11:52 UTC, adhiamboperes commented on utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt
> +    }
This could have been:
```kotlin
val tagName = qName ?: localName  // Fallback to localName if qName is null
   if (tagName in blockTags) {
        isInListItem = false
    }
```

**qName** (qualified name) is generally more reliable unless your parser enforces namespaces.

2025-02-10 13:27 UTC, adhiamboperes reviewed
Did a post-merge review. I have some questions. PTAL @manas-yu.

2025-02-10 13:27 UTC, adhiamboperes commented on utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt
> +    ch?.let { contentDescriptionBuilder.append(String(it, start, length)) }
`    ch?.let { contentDescriptionBuilder.appendRange(it, start, start + length) }`

2025-02-10 13:27 UTC, adhiamboperes commented on utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt
> +  private var pendingNewline = false
I'm not sure what pending new line here means, maybe a rename or adding a comment might clear things up. I had a bit of trouble understanding how it is used in `override fun characters` below.

2025-02-10 13:27 UTC, adhiamboperes commented on utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt
> +    fun <T> getContentDescription(
I noticed that while this function was created, it was not used as required by the issue description. The only present usage is in `HintViewModel`, which means descriptions will be geneerated for Hints only. I believe that other content viewmodels need to use this too, in order to correctly generate descriptions.

According to https://github.com/oppia/oppia-android/issues/4848, we should ensure descriptions are generated for answers,  link cases, including anchors, or any case when text can appear between tags. This means this new function should be used with `ContentViewModel` and `SelectionInteractionContentViewModel`.

2025-02-10 13:27 UTC, adhiamboperes commented on utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt
> +      )
This code appears unused, what does it do?

2025-02-10 14:00 UTC, adhiamboperes commented on utility/src/main/java/org/oppia/android/util/parser/html/LiTagHandler.kt
> +) : CustomHtmlContentHandler.CustomTagHandler, CustomHtmlContentHandler.ContentDescriptionProvider {
Since `getContentDescription` doesn't do anything here, I don't think
`CustomHtmlContentHandler.ContentDescriptionProvider` should be implemented here.

2025-02-14 16:54 UTC, manas-yu commented on utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt
> +      )
The code is not unused, It triggers the HTML parsing process, allowing `CustomHtmlContentHandler` to intercept tags, extract content, and populate `contentDescriptionBuilder` to generate the final content description.

This approach leverages Android’s built-in HTML parsing system, ensuring compatibility with the framework’s expectations, and allows the reuse of the same parsing logic for both content description and display purposes.
 
I'll add comments explaining this and the `pendingNewline` in the PR to resolve:

> This means this new function should be used with ContentViewModel and SelectionInteractionContentViewModel.

2025-02-14 16:55 UTC, manas-yu commented on utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt
> +  private var pendingNewline = false
It acts as a flag that indicates whether a newline character should be inserted before the next text content. It's used when dealing with block-level HTML elements