Fix #5615 : Scroll Position For Policies Screen On Orientation Change
oppia/oppia-android pull request #5616
Opened 2024-12-22 19:39 UTC by TanishMoral11

## Explanation
This PR fixes #5615   the issue where the scroll position in the policies screen (Privacy Policy/Terms of Service) would reset after an orientation change.

### **Changes Made:**
1. **Updated `PoliciesFragmentPresenter`:**
   - Added a `scrollPosition` property to save and restore the scroll state.
   - Implemented `onSaveInstanceState` and `onRestoreInstanceState` handling using a constant key.
   - Ensured the scroll position is retained using `ScrollView.viewTreeObserver` in `onGlobalLayoutListener`.

2. **Modified `PoliciesFragment`:**
   - Delegated `onSaveInstanceState` calls to the presenter.
   - Passed the saved instance state to the presenter during fragment view creation.

### **Testing Performed:**
- Verified that scroll position is correctly retained:
  - Across orientation changes (portrait ↔️ landscape).
  - On both Privacy Policy and Terms of Service screens
---

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: ".
- [x] No unnecessary code changes or Android Studio formatting changes are included.
- [x] The branch is **not** called "develop" and is up-to-date with "develop".
- [x] Appropriate reviewers are assigned.

---

After Changes :
[Screen_recording_20241223_010758.webm](https://github.com/user-attachments/assets/f9648b03-5b27-4090-9eaa-82946214cd62)

2024-12-22 19:39 UTC, TanishMoral11 commented
Hey @adhiamboperes , PTAL

2025-01-05 15:22 UTC, TanishMoral11 commented
Hey @adhiamboperes , This PR is Ready For Review , PTAL.

2025-01-12 17:57 UTC, TanishMoral11 commented
Hey @adhiamboperes PTAL !!

2025-01-14 08:43 UTC, adhiamboperes requested changes
Thanks @TanishMoral11! 
While this implementation looks good, these kind of UI changes require UI tests. While I am not exactly sure the exact way to test this, I would suggest a test that replicates the bug e.g. launch screen > scroll to a specific test > perform orientation change> assert that that specific text or position is displayed.

2025-01-16 18:04 UTC, TanishMoral11 commented
Hey @adhiamboperes , PTAL !! 

![Image](https://github.com/user-attachments/assets/f364163b-0807-4579-808b-d32988fa697e)

2025-01-21 14:25 UTC, adhiamboperes requested changes
Thanks @TanishMoral11! Just one comment left to wrap this up

2025-01-21 14:25 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/policies/PoliciesFragmentPresenter.kt
> +  fun handleSaveInstanceState(outState: Bundle) {
This public function needs a kdoc.

2025-01-21 18:59 UTC, TanishMoral11 commented
Hey @adhiamboperes, PTAL !!

2025-01-21 19:00 UTC, TanishMoral11 commented on app/src/main/java/org/oppia/android/app/policies/PoliciesFragmentPresenter.kt
> +  fun handleSaveInstanceState(outState: Bundle) {
Done .

2025-01-22 13:20 UTC, adhiamboperes approved these changes
Thanks @TanishMoral11! LGTM.

2025-01-22 14:17 UTC, merged