Refactor admin control to use profile
oppia/oppia-android pull request #5619
Opened 2024-12-25 00:06 UTC by tobioyelekan

## Explanation

### Fixes part of #4865
This PR aim to refactor `administratorcontrols` package to use ProfileId
Changes include `AdministratorControlsActivity`, Fragment and Presenters
Also updated the test classes.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

2024-12-25 09:32 UTC, tobioyelekan commented
@adhiamboperes PTAL

2025-01-04 10:18 UTC, tobioyelekan commented
@BenHenning PTAL

2025-01-10 10:08 UTC, adhiamboperes requested changes
Thanks @tobioyelekan, and apologies for the delayed review. I had only one minor comment.

2025-01-10 10:08 UTC, adhiamboperes commented on app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt
> +            if (isProfileDeletionDialogVisible) {
The original condition `&& profileId != 0` should not be removed because it is meant to check if the profile is an admin. What you can instead to is the following:
```suggestion
            if (isProfileDeletionDialogVisible && profileId.internalId != 0) {
```

2025-01-22 13:06 UTC, adhiamboperes commented
@tobioyelekan, could you PTAL? There is just one minor issue to be addressed for this PR to be merged.

2025-01-30 18:48 UTC, tobioyelekan commented
Apologies for the delay in response @adhiamboperes , I've been super busy at work, I'll be fully back shortly in a week or 2

2025-01-31 12:27 UTC, adhiamboperes approved these changes
LGTM, thanks!

2025-01-31 16:02 UTC, merged