refactored overview to info #583
oppia/oppia-android pull request #587
Opened 2020-01-03 16:27 UTC by Abhishek0706

Mock Link:
https://user-images.githubusercontent.com/9396084/71710439-3fa89500-2e22-11ea-83c9-a5564e000459.png

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-01-03 19:08 UTC, rt4914 approved these changes
LGTM. (Looks good to me.)

2020-01-03 19:08 UTC, rt4914 commented on .idea/codeStyles/Project.xml
> +</component>
Please revert all the changes from this file, it might happen that it is not possible.

2020-01-03 19:12 UTC, rt4914 requested changes
Actually, blocking this PR for now, please make following changes:

1. Change the PR title to: `Fix #583: Refactored Overview to Info`
2. Also, I think you are unable to assign anyone in `Assignees` and `Reviewers` section present on the right side of this pull request. In that case you make a top level comment like this: `@rt4914 PTAL` meaning "Please take a look".
3. As mentioned in earlier comment, revert the changes from `Project.xml` file.

2020-01-06 08:36 UTC, Abhishek0706 commented on .idea/codeStyles/Project.xml
> +</component>
Done!

2020-01-06 09:12 UTC, rt4914 approved these changes
LGTM

2020-01-06 09:14 UTC, rt4914 commented
@Abhishek0706 This PR looks good. Congratulations on your first contribution. Now you can merge this PR using `Squash and merge` option visible on this PR and delete the branch after that.

2020-01-06 09:21 UTC, rt4914 commented
> @Abhishek0706 This PR looks good. Congratulations on your first contribution. Now you can merge this PR using `Squash and merge` option visible on this PR and delete the branch after that.

I will need to merge this as you are not currently a contributor to team yet.

2020-01-06 09:21 UTC, merged