fix #588 change review to revision
oppia/oppia-android pull request #601
Opened 2020-01-16 01:44 UTC by maheshpaliwal

## Explanation

Fixes #588 
all files related to review has been updated like package name, file names, test cases names, xml files names, variable names, strings.xml, drawables, etc

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-01-16 01:45 UTC, maheshpaliwal commented
@rt4914 PTAL

2020-01-16 05:20 UTC, rt4914 requested changes
Good work @maheshpaliwal . I have mentioned couple of changes. PTAL

2020-01-16 05:20 UTC, rt4914 commented on .idea/codeStyles/Project.xml
> +</component>
Please remove this file from your commit history. These changes must have come from android studio automatically.

2020-01-16 05:20 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/topic/revision/TopicReviewFragmentTest.kt
> -package org.oppia.app.topic.review
@maheshpaliwal This file name is still `TopicReviewFragmentTest`, please change that to `TopicRevisionFragmentTest`

2020-01-16 05:21 UTC, rt4914 commented
@maheshpaliwal also your PR title should be:
`Fix #588: Refactor review to revision`

2020-01-16 11:12 UTC, maheshpaliwal commented
@rt4914 worked on suggested changes PTAL

2020-01-16 11:28 UTC, rt4914 requested changes
@maheshpaliwal There is force push on this branch. Can you please explain why? Because in oppia we do not accept PR which have pull request unless it is entirely necessary.

2020-01-16 11:28 UTC, rt4914 commented on .idea/codeStyles/Project.xml
> +</component>
This file is still here, we need to revert this entire file.

2020-01-16 11:34 UTC, maheshpaliwal commented
I did force push because I wanted to edit commit history. Since force push is not accepted i'm closing this pull request and starting new one

2020-01-16 11:35 UTC, rt4914 commented
> I did force push because I wanted to edit commit history. Since force push is not accepted i'm closing this pull request and starting new one

Sounds good. No issues. We normally do not alter the commit history. Instead the next commit fixes  those changes. Thanks :-)

2020-02-18 07:31 UTC, rt4914 commented
Closing this as there has been no update on this for past 1 month and the contributor has been lapsed.

2020-02-18 07:31 UTC, closed without merging