Refactor play to lessons
oppia/oppia-android pull request #609
Opened 2020-01-18 11:04 UTC by PrarabdhGarg

Fixes #603 

As per the new mocks, the paly tab was renamed to lessons.
Hence, the entire project was refactored, along with tests, to maintain
consistency with mocks.

## Explanation

## Checklist

- [ x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [x ] The PR's branch is based on "develop" and not on any other branch.
- [x ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-01-20 06:00 UTC, rt4914 requested changes
Thanks for the PR. I have suggested some changes .

Also, following files needs to be updated,

1. `topic_play_fragment` -> `topic_lessons_fragment`
2. `topic_play_story_summary` -> `topic_lessons_story_summary`
3. `topic_play_title` -> `topic_lessons_title`

Also the corresponding data binding names will also get updated.

Please update your branch name to `Fix #603: Refactor play to lessons`

2020-01-20 06:00 UTC, rt4914 commented on .idea/codeStyles/Project.xml
> +</component>
Uncommit this file. This must have been automatically done by android studio.

2020-01-20 06:00 UTC, rt4914 commented on app/src/main/java/org/oppia/app/topic/lessons/TopicLessonsTitleViewModel.kt
> +/** [ViewModel] for title in [TopicPlayFragment]. */
Update this comment to 
`/** [ViewModel] for title in [TopicLessonsFragment]. */`

2020-01-20 06:00 UTC, rt4914 commented on app/src/main/res/layout/topic_play_story_summary.xml
>      <variable
Update this file name to `topic_lessons_story_summary`

2020-01-20 06:00 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/topic/lessons/TopicLessonsFragmentTest.kt
> +class TopicLessonsFragmentTest {
In this file update the function names too. They still contain `play` word in them.

2020-01-21 06:22 UTC, PrarabdhGarg commented
Changed branch name. 
Thus refer #612 for progress

2020-01-21 06:22 UTC, closed without merging