Fix 590 full ui switch profile option
oppia/oppia-android pull request #651
Opened 2020-02-12 17:13 UTC by PrarabdhGarg

## Explanation

Fixes #590 
This pull requests adds the switch profile option in the navigation drawer, along with the UI tests associated with it

## Checklist

- [ x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ x] The PR is made from a branch that's **not** called "develop".
- [x ] The PR is made from a branch that is up-to-date with "develop".
- [x ] The PR's branch is based on "develop" and not on any other branch.
- [ x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-02-12 17:15 UTC, PrarabdhGarg commented
@rt4914 I think this pull request also contains commits that were made when I updated my develop branch. How can I avoid these commits from being a part of my pull request?

2020-02-13 06:24 UTC, rt4914 commented
> @rt4914 I think this pull request also contains commits that were made when I updated my develop branch. How can I avoid these commits from being a part of my pull request?

Actually your branch is 4 commits behind oppia-develop. Because of which you are getting this unnecessary code and also your test cases are failing. I suggest you merge your branch with latest oppia-develop code. It should fix the issue if done correctly.

`git checkout fix-590-full-ui-switch-profile-option`
`git fetch upstream`
`git merge upstream/develop`
If there are any merge conflicts after this step (which they are in NavigationDrawerFragmentPresenter and NavigationDrawerTestActivityTest ), resolve those merge conflicts.
Then add / commit / push your code.

2020-02-13 08:45 UTC, rt4914 requested changes
Great. This looks really clean. I have just requested some few changes. PTAL

2020-02-13 08:45 UTC, rt4914 commented on app/src/main/java/org/oppia/app/drawer/NavigationDrawerFragmentPresenter.kt
> +              fragment.activity!!.startActivity(intent)
Prefer not to call intent this way. You might have found this in some Profile related code but that will be updated with time.
Instead prefer calling intend similar to HomeActivity code. Mainly you will need to create a companion object for intent in the ProfileActivity and then you can call that function wherever you want.

2020-02-13 08:45 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/testing/NavigationDrawerTestActivityTest.kt
> +      onView(withText(R.string.home_activity_back_dialog_message)).check(matches(ViewMatchers.isDisplayed()))
Update: For better code clarity write it like this:
`onView(withText(R.string.home_activity_back_dialog_message)).check(matches(isDisplayed()))`

Ditto in below test case.

2020-02-13 08:45 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/testing/NavigationDrawerTestActivityTest.kt
> +      onView(withText(R.string.home_activity_back_dialog_message)).check(matches(ViewMatchers.isDisplayed()))
Also, after this change make sure to check that you do not have any unused imports.

2020-02-13 08:45 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/testing/NavigationDrawerTestActivityTest.kt
> +      intended(IntentMatchers.hasComponent(ProfileActivity::class.java.name))
Update:

`intended(hasComponent(ProfileActivity::class.java.name))`

2020-02-13 09:11 UTC, PrarabdhGarg commented
@rt4914 I have made the required changes

2020-02-13 09:58 UTC, rt4914 approved these changes
LGTM, Thanks.

2020-02-13 09:59 UTC, rt4914 commented
@PrarabdhGarg before merging this PR, update your PR title to

`Fix #590: Full UI Switch Profile Option`

2020-02-13 10:00 UTC, PrarabdhGarg commented
> @PrarabdhGarg before merging this PR, update your PR title to
> 
> `Fix #590: Full UI Switch Profile Option`

@rt4914 Done

2020-02-13 10:01 UTC, rt4914 commented
> > @PrarabdhGarg before merging this PR, update your PR title to
> > `Fix #590: Full UI Switch Profile Option`
> 
> @rt4914 Done

Actually you missed out `#`, this is important as it automatically closes the corresponding issue.

2020-02-13 10:05 UTC, merged