Fix #588: Refactor 'Review' to 'Revision'
oppia/oppia-android pull request #667
Opened 2020-02-16 13:34 UTC by tanhengyeow

## Explanation

Fixes #588

All files affected e.g. package name, file names, test cases names, xml files names, variable names, strings.xml, drawables, etc are refactored.

## Checklist

- [X] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [X] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [X] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [X] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [X] The PR is made from a branch that's **not** called "develop".
- [X] The PR is made from a branch that is up-to-date with "develop".
- [X] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-02-17 13:44 UTC, nikitamarysolomanpvt commented
Please include the screen shot of UI updated.

2020-02-17 14:10 UTC, nikitamarysolomanpvt requested changes
I believe  we need to refactor review card to revision card , term review in Topic proto i.e. in Domain module, in JSON file (not so sure), and several comments in protos (i.e. EphemeralQuestion,Question(not so sure))@rt4914  Please finalise the requirement and suggest and deferring to you.

2020-02-17 14:10 UTC, nikitamarysolomanpvt commented on app/src/main/java/org/oppia/app/topic/revision/RevisionSkillSelector.kt
> +/** Listener for when a skill is selected for review. */
Rename review to revision in comment.

2020-02-18 08:01 UTC, rt4914 requested changes
This looks great. But there are some places in which we have missed this. Mainly `domain` and `model` layer. So I suggest you press `Shift` key twice and global search for `Review` keyword and that way you can easily find where this word is getting used and we can replace that. 
First try to work using this approach, if this does not work out, I can mention the files in which you need to make changes.

2020-02-18 08:02 UTC, rt4914 commented
@veena14cs Keep track of this PR, as this PR and your subtopic ReviewCard PR will have merge conflicts depending upon who's PR gets merged first.

2020-02-18 08:03 UTC, rt4914 commented
> I believe we need to refactor review card to revision card , term review in Topic proto i.e. in Domain module, in JSON file (not so sure), and several comments in protos (i.e. EphemeralQuestion,Question(not so sure))@rt4914 Please finalise the requirement and suggest and deferring to you.

Thanks a lot @nikitamarysolomanpvt . I have replied to @tanhengyeow about the approach.

2020-02-28 09:27 UTC, rt4914 commented
Closing this PR because of inactivity.

2020-02-28 09:27 UTC, closed without merging