Fix # : Lowfi Landscape: OngoingTopicListActivity
oppia/oppia-android pull request #807
Opened 2020-03-15 11:17 UTC by virajpatel2411

Mock: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/ce21cbf2-0439-47d7-bb37-005cfc6b9742/UP-Topics-in-Progress-

Landscape res of Ongoingtopicfragment created
Issue #791 
@rt4914 @veena14cs @nikitamarysolomanpvt Can anyone please check the UI as per mock so that if it is correct then after that I can add test case?

2020-03-16 05:05 UTC, nikitamarysolomanpvt commented
@virajpatel2411 Please add test cases.

2020-03-16 10:52 UTC, virajpatel2411 commented
@veena14cs @nikitamarysolomanpvt I have added the test cases. Please review it. @rt4914

2020-03-18 07:37 UTC, rt4914 requested changes
The implementation is correct but there is one major issue.

You have made changes on your `develop` branch. Instead you should create a new branch on your fork.
Follow these steps always: https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change

Now, do not add extra blank lines.

Also, the test case failing. Please always fun your test case and if they pass then only send it for review.

Your branch is not up-to-date with develop please update your code.

Your title does not have a issue number. Please add your issue number to your PR title as per the convention.

2020-03-18 07:37 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/ongoingtopiclist/OngoingTopicListActivityTest.kt
> +
Remove these 3 blank unnecessary lines.

2020-03-18 07:37 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/ongoingtopiclist/OngoingTopicListActivityTest.kt
> +  /////////////////////////////////////////////////////////////////////////////////////////////////////////
Remove this comment and a blank line above this.

2020-03-18 07:37 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/ongoingtopiclist/OngoingTopicListActivityTest.kt
> +///////////////////////////////////////Test Case for Landscape Mode////////////////////////////////////////
Remove this comment and a blank line below this.

2020-03-18 07:37 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/ongoingtopiclist/OngoingTopicListActivityTest.kt
> +      onView(ViewMatchers.isRoot()).perform(OrientationChangeAction.orientationLandscape())
Nit update to make code more readable
`onView(isRoot()).perform(orientationLandscape())`

2020-03-18 07:37 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/ongoingtopiclist/OngoingTopicListActivityTest.kt
> +        ViewActions.click())
Nit Update:
`onView(withId(R.id.ongoing_topic_list)).perform(click())`

2020-03-18 07:37 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/ongoingtopiclist/OngoingTopicListActivityTest.kt
> +      onView(withId(R.id.topic_name_text_view)).check(matches(withText(R.string.story_count_text_view)))
The ID of this case is incorrect.

2020-03-18 07:52 UTC, virajpatel2411 commented
@rt4914 Closing this PR...will make a new apt PR and let you know in some time. Will I be assigned to another issue so while this PR's review is going on I can work on another one?

2020-03-18 07:53 UTC, closed without merging

2020-03-18 07:55 UTC, rt4914 commented
> @rt4914 Closing this PR...will make a new apt PR and let you know in some time. Will I be assigned to another issue so while this PR's review is going on I can work on another one?

I suggest you focus on one PR at a time. Once you finish two PRs then we can think of multiple issues at a time.

2020-03-18 07:56 UTC, virajpatel2411 commented
> > @rt4914 Closing this PR...will make a new apt PR and let you know in some time. Will I be assigned to another issue so while this PR's review is going on I can work on another one?
> 
> I suggest you focus on one PR at a time. Once you finish two PRs then we can think of multiple issues at a time.

Okayy