Fix #772: Lowfi Landscape: AppLanguageActivity #772
oppia/oppia-android pull request #842
Opened 2020-03-20 13:48 UTC by MohamedMedhat1998

## Explanation

-Fixes #772: Lowfi Landscape: AppLanguageActivity   

## Before  
The `AppLanguageActivity` was locked to the portrait mode  
![Screenshot (129)](https://user-images.githubusercontent.com/8533363/77169308-f2070480-6ac1-11ea-8a68-d1fe88c9d321.png)
## After
The `AppLanguageActivity` now supports the landscape mode  
![Screenshot (128)](https://user-images.githubusercontent.com/8533363/77169359-064b0180-6ac2-11ea-81a2-f7cc35678114.png)
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.
- [x] Implementing a landscape for `AppLanguageActivity`
- [x] Unit tests for `AppLanguageActivity`

2020-03-20 13:49 UTC, MohamedMedhat1998 commented
@rt4914 please review this PR

2020-03-20 14:00 UTC, rt4914 requested changes
Suggested approach changes.

2020-03-20 14:00 UTC, rt4914 commented on app/src/main/java/org/oppia/app/options/AppLanguageActivity.kt
> +    outState.putSerializable(KEY_LANGUAGE_SELECTION_ADAPTER ,appLanguageActivityPresenter.getLanguageSelectionAdapter())
Spacing is incorrect there should be space after `,` and not before that:
`outState.putSerializable(KEY_LANGUAGE_SELECTION_ADAPTER, appLanguageActivityPresenter.getLanguageSelectionAdapter())`

2020-03-20 14:00 UTC, rt4914 commented on app/src/main/java/org/oppia/app/options/AppLanguageActivityPresenter.kt
> +
Remove this extra blank line

2020-03-20 14:00 UTC, rt4914 commented on app/src/main/java/org/oppia/app/options/AppLanguageActivityPresenter.kt
> +  fun handleOnCreate(prefKey: String, prefSummaryValue: String,savedAdapter : LanguageSelectionAdapter? = null) {
Spacing issue:
`fun handleOnCreate(prefKey: String, prefSummaryValue: String, savedAdapter: LanguageSelectionAdapter? = null) {`

2020-03-20 14:00 UTC, rt4914 commented on app/src/main/java/org/oppia/app/options/AppLanguageActivityPresenter.kt
> +  fun getLanguageSelectionAdapter(): LanguageSelectionAdapter{
Spacing issue:
`fun getLanguageSelected(): String {`

2020-03-20 14:00 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/options/OptionsFragmentTest.kt
> +          RecyclerViewActions.actionOnItemAtPosition<RecyclerView.ViewHolder>(
Nit:
`actionOnItemAtPosition<RecyclerView.ViewHolder>(`

2020-03-20 14:00 UTC, rt4914 commented on app/src/main/java/org/oppia/app/options/LanguageSelectionAdapter.kt
> +  RecyclerView.Adapter<LanguageSelectionAdapter.LanguageViewHolder>(),Serializable {
We don't want the entire Adapter to be Serializable. Instead check the implementation of `onSavedInstance` in `DefaultAudioActivity`.

2020-03-20 18:47 UTC, rt4914 requested changes
Everything looks great. Just one nit spacing issue change suggested.

2020-03-20 18:47 UTC, rt4914 commented on app/src/main/java/org/oppia/app/options/AppLanguageActivity.kt
> +    prefSummaryValue = if(savedInstanceState == null){
Spacing issue:
```
    prefSummaryValue = if (savedInstanceState == null) {
      intent.getStringExtra(KEY_APP_LANGUAGE_PREFERENCE_SUMMARY_VALUE)
    } else {
      savedInstanceState.get(KEY_SELECTED_LANGUAGE) as String
    }
    appLanguageActivityPresenter.handleOnCreate(prefKey, prefSummaryValue)
```

2020-03-23 05:58 UTC, rt4914 approved these changes
@MohamedMedhat1998 Everything is perfect in this PR but if you see at the bottom of the PR `non-flaky_tests` are failing and because of we cannot merge this PR. So to fix that we can do following steps:
Merge your branch with latest code from upstream/develop so that your current branch is ahead of `oppia-android/develop` and push that code. Once that is done mostly the CircleCI tests will pass. So that we can merge your PR. Thanks.

2020-03-23 19:28 UTC, rt4914 commented
Closing this PR as it has been replicated on #859

2020-03-23 19:28 UTC, closed without merging