Fix #143: Highfi TopicRevision Updated
oppia/oppia-android pull request #930
Opened 2020-04-01 06:19 UTC by rt4914

## Explanation

Fixes: #143 

This PR deals with the highfi changes in Topic Revision.

Mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/1adacef0-f245-4115-a0e0-d1c2e7d5a0bb/TP-Revision-/

## Changes:
As per recent email by @mschanteltc the border from topic revision has been removed and the foreground/background color of textview has been changed. This PR fixes just that.

## Screenshot
![Screenshot_1585721551](https://user-images.githubusercontent.com/9396084/78105201-4a1cff80-740e-11ea-8724-d383202c1605.png)
![Screenshot_1585721561](https://user-images.githubusercontent.com/9396084/78105209-4f7a4a00-740e-11ea-83c1-fb6c75fdfb48.png)

## Accessibility Test
The accessibility test fails for foreground/background color ratio and therefore it will get confirmed with Chantel.
![as_17](https://user-images.githubusercontent.com/9396084/78105276-6ae55500-740e-11ea-849f-f23a07ebb3eb.png)

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-04-01 06:23 UTC, rt4914 commented
@mschanteltc The accessibility tests are failing because of color contrast. Can we change this color?

2020-04-03 00:37 UTC, mschanteltc commented
> @mschanteltc The accessibility tests are failing because of color contrast. Can we change this color?

Use #BE563C for the orange color. I believe the accessibility requirements should pass with this.

2020-04-03 07:04 UTC, rt4914 commented
## Updated Screenshots:
![Screenshot_1585897424](https://user-images.githubusercontent.com/9396084/78333396-64d6ac00-75a7-11ea-9ea1-812dd071adae.png)
![Screenshot_1585897428](https://user-images.githubusercontent.com/9396084/78333408-6a33f680-75a7-11ea-8573-c2c3b5b792cc.png)


## All accessibility tests passed for the fragment.
![as_1](https://user-images.githubusercontent.com/9396084/78333462-7b7d0300-75a7-11ea-93e8-a5ed114d4d91.png)

2020-04-03 07:05 UTC, rt4914 commented
> > @mschanteltc The accessibility tests are failing because of color contrast. Can we change this color?
> 
> Use #BE563C for the orange color. I believe the accessibility requirements should pass with this.

It worked. Thanks.

2020-04-03 10:13 UTC, nikitamarysolomanpvt requested changes
PTAL on the suggestions

2020-04-03 10:13 UTC, nikitamarysolomanpvt commented on app/src/main/res/layout-land/topic_revision_summary_view.xml
>      app:cardCornerRadius="8dp"
As per mock radius is 4dp

2020-04-03 10:13 UTC, nikitamarysolomanpvt commented on app/src/main/res/layout/topic_revision_summary_view.xml
>      app:cardCornerRadius="8dp"
ditto

2020-04-03 10:13 UTC, nikitamarysolomanpvt commented on app/src/main/res/layout/topic_revision_summary_view.xml
>          android:fontFamily="sans-serif-medium"
Please update as per mock

2020-04-07 06:39 UTC, rt4914 commented on app/src/main/res/layout/topic_revision_summary_view.xml
>          android:fontFamily="sans-serif-medium"
Updated as per new mock.

2020-04-07 06:39 UTC, rt4914 commented on app/src/main/res/layout/topic_revision_summary_view.xml
>      app:cardCornerRadius="8dp"
Updated to `4dp`

2020-04-07 06:39 UTC, rt4914 commented on app/src/main/res/layout-land/topic_revision_summary_view.xml
>      app:cardCornerRadius="8dp"
Updated to `4dp`

2020-04-07 07:34 UTC, nikitamarysolomanpvt approved these changes
LGTM

2020-04-07 07:43 UTC, merged