Fix #935: Optimised test cases for HDPI devices
oppia/oppia-android pull request #942
Opened 2020-04-03 22:18 UTC by NullByte08

## Explanation
Fix #935 
All the test cases except for `player` package now run successfully on HDPI devices too as required by the issue. I used the `Nexus S` emulator.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-04-07 00:09 UTC, NullByte08 commented on app/src/sharedTest/java/org/oppia/app/settings/profile/ProfileEditActivityTest.kt
>      ActivityScenario.launch<ProfileEditActivity>(ProfileEditActivity.createProfileEditActivity(context, 0)).use {
This test is failing in other devices too. ActionBar does not have the text "Sean". It has "Oppia"

2020-04-07 00:11 UTC, NullByte08 commented on app/src/sharedTest/java/org/oppia/app/settings/profile/ProfileEditActivityTest.kt
>    fun testProfileEditActivity_configurationChange_startActivityWithUserProfile_checkUserInfoIsDisplayed() {
This test is failing in other devices too. ActionBar does not have the text "Ben". It has "Oppia".

2020-04-07 00:13 UTC, NullByte08 commented on app/src/sharedTest/java/org/oppia/app/topic/revision/TopicRevisionFragmentTest.kt
>    fun testTopicRevisionFragment_loadFragment_checkSpanCoun_isTwo() {
This test is failing in other devices too. There are 12 items in the recyclerview but check was made for 2 item count only.

2020-04-07 00:13 UTC, NullByte08 commented on app/src/sharedTest/java/org/oppia/app/topic/revision/TopicRevisionFragmentTest.kt
>    fun testTopicRevisionFragment_loadFragment_configurationChange_checkSpanCount_isThree() {
This test is failing in other devices too. There are 12 items in the recyclerview but check was made for 3 item count only.

2020-04-07 00:17 UTC, NullByte08 commented
@rt4914 I have just added the comments so as to bring them to your attention. Otherwise, all the test are completely compatible now with `HDPI` devices.

2020-04-07 05:57 UTC, rt4914 commented
@NullByte08 I ran all test cases at once. And here are some details regarding to that.
<img width="607" alt="Screenshot 2020-04-07 at 11 11 46 AM" src="https://user-images.githubusercontent.com/9396084/78634363-6a8f0300-78c1-11ea-9cfa-19b592240cb9.png">

`AdminstratorControlsActivityTest` -> Tests are failing because the UI is not visible on screen. Mainly you will need to add `scrollTo` functionality in the failing test cases.
`player` package test cases you can avoid.
`TopicRevisionFragmentTest` -> These test cases will need to be updated. For reference you can see `HomeActivityTest` in which we are checking span count in similar way. Try to use this information to fix the test cases if it does not workout, do inform me and I can give you more hints.
`ProfileEditActivityTest` -> For this the functionality in code is incorrect and the test case has been written in the correct way. 
Follow these steps:
1. ProfileChooser Screen -> `Administrator Controls` -> Enter Pin
2. Click on `Edit Profiles`
3. Click on `Sean`'s profile
4. Now in toolbar you will notice that the name is `Sean` now do orientation change in mobile and you will see that toolbar shows `Oppia`.
You should fix this functionality to fix the test case itself.


This issue is sort of a mini project as it was known that it will have multiple changes. 

Thanks a lot for working on this as it is an important issue.

2020-04-08 10:25 UTC, NullByte08 commented
@rt4914 Please review. I have ran all the test files individually and all at once also. All tests are successful.

2020-04-09 10:35 UTC, rt4914 commented
@NullByte08 Please don'e forget to assign it to correct reviewer, because the assign section was containing your name, I though that you are still working on this.
Read this: https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section

2020-04-09 11:51 UTC, rt4914 requested changes
There are still some test cases which are failing and we never use `SystemClock.sleep(1000)`.

Actually the best approach to finish this PR soon is to split this PR into 3-4 different PRs and making sure that 4-5 packages are fixed in each PR.

2020-04-09 11:51 UTC, rt4914 commented on app/src/main/java/org/oppia/app/settings/profile/ProfileEditActivityPresenter.kt
> +    activity.title=editViewModel.profileName
Nit: `activity.title = editViewModel.profileName`

2020-04-09 11:51 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt
> +
Remove this blank line

2020-04-09 11:51 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/profile/PinPasswordActivityTest.kt
> +      SystemClock.sleep(1000)
We never use this because this sleep can actually hide the actual issue that might be happening in PR.

2020-04-09 11:51 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/profile/PinPasswordActivityTest.kt
> +      SystemClock.sleep(1000)
Ditto. Remove this.

2020-04-15 09:51 UTC, rt4914 commented
This is finished via #960 #963 #965

2020-04-15 09:51 UTC, closed without merging