Fixes part of #935: Optimised test cases for HDPI devices ( Packages M-P)
oppia/oppia-android pull request #963
Opened 2020-04-10 14:02 UTC by NullByte08

## Explanation
Partially fixes #935
Tests made compatible for `HDPI` devices for packages `mydownloads` to `profileprogress`. All the tests pass successfully.

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-04-13 05:21 UTC, rt4914 requested changes
Looks great, the implementation is nice but you can optimise the code.

2020-04-13 05:21 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/profile/PinPasswordActivityTest.kt
> +  fun getCurrentActivity(): Activity? {
Make sure you always solve all the possible mentioned warnings/suggestions by android studio.
```
private fun getCurrentActivity(): Activity? {
    var currentActivity: Activity? = null
    getInstrumentation().runOnMainSync {
      run {
        currentActivity = ActivityLifecycleMonitorRegistry.getInstance().getActivitiesInStage(
          Stage.RESUMED
        ).elementAtOrNull(0)
      }
    }
    return currentActivity
  }

  private inline fun <reified T : Activity> isVisible(): Boolean {
    val am =
      InstrumentationRegistry.getInstrumentation().targetContext.getSystemService(ACTIVITY_SERVICE) as ActivityManager
    val visibleActivityName = this.getCurrentActivity()!!::class.java.name
    return visibleActivityName == T::class.java.name
  }

  private inline fun <reified T : Activity> waitUntilActivityVisible() {
    val startTime = System.currentTimeMillis()
    while (!isVisible<T>()) {
      Thread.sleep(CONDITION_CHECK_INTERVAL)
      if (System.currentTimeMillis() - startTime >= TIMEOUT) {
        throw AssertionError("Activity ${T::class.java.simpleName} not visible after $TIMEOUT milliseconds")
      }
    }
  }
```


Also, you can create top level constants like this:
```
private const val TIMEOUT = 1000L
private const val CONDITION_CHECK_INTERVAL = 100L

@RunWith(AndroidJUnit4::class)
class PinPasswordActivityTest {
```

2020-04-13 05:21 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/profile/ProfileChooserFragmentTest.kt
> +  fun getCurrentActivity(): Activity? {
Ditto as above.

2020-04-13 06:14 UTC, NullByte08 commented
@rt4914 Changes done.

2020-04-13 06:20 UTC, rt4914 approved these changes
LGTM, thanks.

2020-04-13 06:21 UTC, rt4914 commented
@NullByte08 Merge this PR with latest branch so that `non_flaky_tests` can pass.

2020-04-13 07:25 UTC, NullByte08 commented
@rt4914 My branch is up-to-date with oppia/develop. But still, the non_flaky_tests are failing. Please have a look. Thanks.

2020-04-14 05:59 UTC, rt4914 commented
> @rt4914 My branch is up-to-date with oppia/develop. But still, the non_flaky_tests are failing. Please have a look. Thanks.

Tests are failing because of an import missing in `PinPasswordActivityTest`. Once you fix this, it should pass.

2020-04-14 09:14 UTC, NullByte08 commented
@rt4914 Changes done, please merge. Thanks.

2020-04-14 09:30 UTC, rt4914 approved these changes
LGTM, thanks.

2020-04-14 09:30 UTC, merged