Fix #961: In AdminPinActivity save button and actionDone button issue
oppia/oppia-android pull request #964
Opened 2020-04-10 14:46 UTC by MohamedMedhat1998

## Explanation

Fixes #961 

## Before

- The scroll was not complete in the `AdminPinActivity` and the save button was unreachable.
- "Done" button in the soft-keyboard wasn't submitting the pin automatically in both `AdminPainActivity` and `AdminAuthActivity`

![1,2](https://user-images.githubusercontent.com/8533363/78998893-daafba00-7b49-11ea-851b-01b6d6b35158.gif)
![3](https://user-images.githubusercontent.com/8533363/78998919-e3a08b80-7b49-11ea-9903-c9bff1cb5975.gif)

## After

- The scroll in the `AdminPinActivity` is now fixed and the save button is unreachable.
- "Done" button in the soft-keyboard now submits the pin automatically in both `AdminPainActivity` and `AdminAuthActivity`

![1](https://user-images.githubusercontent.com/8533363/78999272-9244cc00-7b4a-11ea-8259-fe07401859f0.gif)
![2](https://user-images.githubusercontent.com/8533363/78999237-835e1980-7b4a-11ea-8787-d66652694803.gif)
![3](https://user-images.githubusercontent.com/8533363/78999260-8ce78180-7b4a-11ea-85ac-ffa77c3f47ce.gif)

**Note**:  
Please notice that the new test cases added here don't pass because of this issue: https://github.com/oppia/oppia-android/issues/962  

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-04-13 05:56 UTC, rt4914 commented
@anandwana001 Can you please review this PR? Once you have reviewed it, once this PR is fully correct from your side, please assign it to me for final review. Thanks.

2020-04-13 05:57 UTC, rt4914 commented
@MohamedMedhat1998 You had not assigned this PR to anyone and because of which PR reviews might get delayed, please follow these instructions while creating a PR. https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section

2020-04-13 10:50 UTC, rt4914 requested changes
I just ran test cases first and they are failing but they are passing on current develop, so maybe you can merge latest develop in this branch to fix that.

Also, all the test cases will be run on HDPI device so you will need to write test cases accordingly, I will be running all these test cases on `Nexus S` emulator.

2020-04-13 10:53 UTC, MohamedMedhat1998 commented
@rt4914 The test cases are failing because of this issue https://github.com/oppia/oppia-android/issues/962

2020-04-13 10:55 UTC, anandwana001 commented
This PR solving #591  issue also.

2020-04-13 10:56 UTC, rt4914 commented
> @rt4914 The test cases are failing because of this issue #962

Then in that case, add `@Ignore("IME_ACTIONS doesn't work properly in ProfileInputView") // TODO(#962): Reenable once IME_ACTIONS work correctly on ProfileInputView.` on test cases which are failing because of this issue.

2020-04-13 11:37 UTC, MohamedMedhat1998 commented
> 
> 
> This PR solving #591 issue also.

@anandwana001 Thanks.  
I added that in the PR description

2020-04-13 11:55 UTC, MohamedMedhat1998 commented
@rt4914 please check

2020-04-14 05:54 UTC, rt4914 approved these changes
Everything looks great. Thanks.

2020-04-14 05:54 UTC, merged

2020-04-14 05:55 UTC, rt4914 commented
@anandwana001 This PR has been merged because it was sort of following a deadline from @MohamedMedhat1998 side. Thanks for creating this issue.

2020-04-14 06:03 UTC, anandwana001 commented
@MohamedMedhat1998 @rt4914 Sorry for the delay, I am facing a bit of technical issue with resolving PR. I am working on it to speed up in future.

2020-04-14 08:54 UTC, rt4914 commented
> @MohamedMedhat1998 @rt4914 Sorry for the delay, I am facing a bit of technical issue with resolving PR. I am working on it to speed up in future.

@anandwana001 No issues, its fine.