Fixes part of #935: Optimised test cases for HDPI devices for remaining packages
oppia/oppia-android pull request #965
Opened 2020-04-11 08:56 UTC by NullByte08

## Explanation
Fixes part of #935 :
Tests made compatible for `HDPI` devices for all the remaining packages. All the tests pass successfully.

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

2020-04-13 05:46 UTC, rt4914 requested changes
All tests are passing, suggested optimmisations.

2020-04-13 05:46 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/testing/NavigationDrawerTestActivityTest.kt
> +  fun nestedScrollTo(): ViewAction {
Please update all these functions as mentioned on other PR review.

2020-04-13 05:46 UTC, rt4914 commented on app/src/sharedTest/java/org/oppia/app/topic/revision/TopicRevisionFragmentTest.kt
> +  class GridLayoutManagerColumnCountAssertion(expectedColumnCount:Int): ViewAssertion {
Update on suggested optimisation:
```
 class GridLayoutManagerColumnCountAssertion(expectedColumnCount: Int) : ViewAssertion {
    private var expectedColumnCount: Int = 0

    init {
      this.expectedColumnCount = expectedColumnCount
    }

    override fun check(view: View, noViewFoundException: NoMatchingViewException?) {
      if (noViewFoundException != null) {
        throw noViewFoundException
      }
      val recyclerView = view as RecyclerView
      if (recyclerView.layoutManager is GridLayoutManager) {
        val gridLayoutManager = recyclerView.layoutManager as GridLayoutManager
        val spanCount = gridLayoutManager.spanCount
        if (spanCount != expectedColumnCount) {
          val errorMessage =
            ("expected column count " + expectedColumnCount + " but was " + spanCount)
          throw AssertionError(errorMessage)
        }
      } else {
        throw IllegalStateException("no grid layout manager")
      }
    }
  }
```

2020-04-13 07:01 UTC, NullByte08 commented
@rt4914 Changes done.

2020-04-14 05:47 UTC, rt4914 requested changes
Tests are failing on circle CI because one import is missing in  `NavigationDrawerTestActivityTest`, once you fix that these test cases should pass. Also, do merge it with latest develop just to be on safe side.

2020-04-14 08:25 UTC, NullByte08 commented
@rt4914 Changes done. Please merge. Thank you.

2020-04-14 09:31 UTC, rt4914 approved these changes
LGTM, thanks.

2020-04-14 09:31 UTC, merged