Fix part of #5: Abstraction on top of Oppia GAE for ExplorationHandler (Part 2)
oppia/oppia-android pull request #99
Opened 2019-09-11 11:12 UTC by rt4914

## Explanation
This PR contains everything related to ExplorationHandler, i.e., ExplorationService, Moshi Models, Test cases.
Also, test-cases for ClassroomService have been created.
This PR was earlier on #66 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is **assigned** to an appropriate reviewer.

2019-09-11 12:07 UTC, veena14cs approved these changes
Looks good.

2019-09-12 06:04 UTC, nikitamarysolomanpvt approved these changes
LGTM

2019-09-12 06:26 UTC, rt4914 commented
@BenHenning Waiting for your review.

2019-09-13 04:35 UTC, BenHenning requested changes
Generally LGTM. If possible, I'd like to do another pass today before approving.

2019-09-13 04:35 UTC, BenHenning commented on data/src/main/java/org/oppia/data/backends/gae/model/GaeSubtitledHtml.kt
> +  @Json(name = "content_id") val contentId: String
Why not use nullable types for html & content_id per other GAE data classes?

2019-09-13 04:35 UTC, BenHenning commented on data/src/main/java/org/oppia/data/backends/gae/model/GaeVoiceover.kt
> +  @Json(name = "needs_update") val isUpdatedNeeded: Boolean,
Nit: ``isUpdateNeeded``

2019-09-13 04:35 UTC, BenHenning commented on data/src/main/java/org/oppia/data/backends/gae/model/GaeVoiceover.kt
> +  @Json(name = "file_size_bytes") val fileSizeBytes: Long,
Ditto here--why not use nullable types for these three?

2019-09-13 04:35 UTC, BenHenning commented on data/src/main/java/org/oppia/data/backends/gae/model/GaeRecordedVoiceovers.kt
> +  @Json(name = "voiceovers_mapping") val voiceoversMapping: Map<String, Map<String, GaeVoiceover>>
Ditto here--why not nullable?

2019-09-13 04:35 UTC, BenHenning commented on data/src/main/java/org/oppia/data/backends/gae/model/GaeWrittenTranslation.kt
> +  @Json(name = "html") val html: String,
Ditto for these two fields--why not nullable?

2019-09-13 04:35 UTC, BenHenning commented on data/src/main/java/org/oppia/data/backends/gae/model/GaeWrittenTranslations.kt
> +  @Json(name = "translations_mapping") val translationsMapping: Map<String, Map<String, GaeWrittenTranslation>>
And for this--should it be nullable?

2019-09-13 04:35 UTC, BenHenning commented on data/src/test/java/org/oppia/data/backends/FakeJsonResponse.kt
> +    "{\"exploration\":{\"param_changes\":[],\"title\":\"What is a Fraction? Part 1\",\"states\":{\"Q6 on N and D\":{\"param_changes\":[],\"interaction\":{\"solution\":null,\"answer_groups\":[{\"outco
At this point, it may be worth having a test data folder where we save these JSON files & retrieve them via a loader. It's hard to read this, and I suspect it'll be hard to update as the exploration structure changes.

2019-09-13 04:35 UTC, BenHenning commented on data/src/test/java/org/oppia/data/backends/test/MockClassroomTest.kt
> +    assertThat("Math").isEqualTo(classroomResponse.body()!!.topic_summary_dicts?.get(0)?.name)
I believe this truth line is backwards. It should be: ``assertThat(testResult).isEqualTo(expectedOutcome)``

2019-09-13 04:35 UTC, BenHenning commented on data/src/test/java/org/oppia/data/backends/FakeJsonResponse.kt
> +  const val EXPLORATION_SERVICE_RESPONSE: String =
We should use one of the demo explorations instead: https://github.com/oppia/oppia/tree/develop/data/explorations since these are already checked into the Oppia repository to be used for this purpose.

2019-09-13 04:49 UTC, rt4914 commented on data/src/main/java/org/oppia/data/backends/gae/model/GaeRecordedVoiceovers.kt
> +  @Json(name = "voiceovers_mapping") val voiceoversMapping: Map<String, Map<String, GaeVoiceover>>
Updated. Added nullable.

2019-09-13 04:50 UTC, rt4914 commented on data/src/main/java/org/oppia/data/backends/gae/model/GaeSubtitledHtml.kt
> +  @Json(name = "content_id") val contentId: String
Updated. Added nullable

2019-09-13 04:50 UTC, rt4914 commented on data/src/main/java/org/oppia/data/backends/gae/model/GaeVoiceover.kt
> +  @Json(name = "file_size_bytes") val fileSizeBytes: Long,
Updated. Added nullable

2019-09-13 04:50 UTC, rt4914 commented on data/src/main/java/org/oppia/data/backends/gae/model/GaeWrittenTranslation.kt
> +  @Json(name = "html") val html: String,
Updated. Added nullable

2019-09-13 04:51 UTC, rt4914 commented on data/src/main/java/org/oppia/data/backends/gae/model/GaeWrittenTranslations.kt
> +  @Json(name = "translations_mapping") val translationsMapping: Map<String, Map<String, GaeWrittenTranslation>>
Updated. Added nullable

2019-09-13 04:51 UTC, rt4914 commented on data/src/main/java/org/oppia/data/backends/gae/model/GaeVoiceover.kt
> +  @Json(name = "needs_update") val isUpdatedNeeded: Boolean,
Updated. `isUpdateNeeded`

2019-09-13 04:58 UTC, rt4914 commented on data/src/test/java/org/oppia/data/backends/test/MockClassroomTest.kt
> +    assertThat("Math").isEqualTo(classroomResponse.body()!!.topic_summary_dicts?.get(0)?.name)
Updated all test cases accordingly.

2019-09-13 04:59 UTC, rt4914 commented on data/src/test/java/org/oppia/data/backends/FakeJsonResponse.kt
> +  const val EXPLORATION_SERVICE_RESPONSE: String =
I tried converting these YAML files to JSON, but online converters are giving error that the YAML is invalid.

2019-09-13 05:29 UTC, seanlip commented on data/src/test/java/org/oppia/data/backends/FakeJsonResponse.kt
> +  const val EXPLORATION_SERVICE_RESPONSE: String =
Hi @rt4914 -- in general, when reporting an error / invalidity, please could you also explain _why_ it's invalid? That will help with debugging/resolving the issue, otherwise the discussion stalls. (This is important to do in future discussions, too.)

Thanks!

2019-09-13 06:24 UTC, rt4914 commented
@BenHenning PTAL. I have introduced json files in `test` folders. Removed `FakeJsonResponse` and created an `ApiUtils` file which will load data from json

2019-09-13 06:28 UTC, rt4914 commented
https://github.com/oppia/oppia-android/pull/99#discussion_r324040078

@seanlip Hi sean, actually the discussion shifted to hangout chats (between me, veena, nikita and Ben) with details and because of which it missed on here. 

For reference: Online converters (like http://convertjson.com/yaml-to-json.htm) cannot convert the examples provided in Oppia-Web (https://github.com/oppia/oppia/tree/develop/data/explorations) because of rich-text. Rich-text contains HTML tags which makes the YAML response invalid for the online converters.

Solution: Run local development server -> load explorations -> `http://localhost:8181/explorehandler/init/<exploration_id>` this will provide the json (with XSSI prefix).

2019-09-13 06:58 UTC, rt4914 commented
@BenHenning project structure for your reference:

<img width="427" alt="Screenshot 2019-09-13 at 12 27 03 PM" src="https://user-images.githubusercontent.com/9396084/64843132-e540ba00-d621-11e9-83af-8471a54b9428.png">

2019-09-13 07:06 UTC, BenHenning approved these changes
Thanks @rt4914! LGTM.

2019-09-13 07:16 UTC, merged